### PR TITLE
build: release v5.23.0

### PR DESCRIPTION
**Pull request by karrui**
~~Pre-release for now and not updated the version due to having one last copy change before this release is pushed.~~ Copywriting changes next week

# Release v5.23.0

New week, new features. 
This week's release includes:
- automatically removing verification on verified mobile fields if free sms quota has been hit (10k per user)
- moving `shared` folder to root

## Features
- feat: remove frontend code to delete   spcp cookie [`#2551`](https://github.com/opengovsg/FormSG/pull/2551)
- feat: sms limiting   [`#2504`](https://github.com/opengovsg/FormSG/pull/2504)

## Improvements
- ref: migrate public-facing submission   types to shared folder   [`#2509`](https://github.com/opengovsg/FormSG/pull/2509)
- refactor: move src/types/api/auth to   shared/types/form/form_auth   [`#2510`](https://github.com/opengovsg/FormSG/pull/2510)
- feat: loosen esrvcId validation to only   restrict whitespace [`#2521`](https://github.com/opengovsg/FormSG/pull/2521)
- feat: move most of src/shared to root   shared folder [`#2519`](https://github.com/opengovsg/FormSG/pull/2519)

## Fixes
- fix: update response limit error   message for storage mode submissions   [`#2448`](https://github.com/opengovsg/FormSG/pull/2448)

## Dependency updates
- chore: update bcrypt dependencies in   package-lock [`#2530`](https://github.com/opengovsg/FormSG/pull/2530)
- fix(deps): bump   @opengovsg/spcp-auth-client from 1.4.8 to 1.4.9   [`#2544`](https://github.com/opengovsg/FormSG/pull/2544)
- fix(deps): bump @sentry/browser from   6.10.0 to 6.11.0 [`#2546`](https://github.com/opengovsg/FormSG/pull/2546)
- fix(deps): bump @sentry/integrations   from 6.10.0 to 6.11.0   [`#2550`](https://github.com/opengovsg/FormSG/pull/2550)
- fix(deps): bump aws-sdk from 2.958.0 to   2.959.0 [`#2523`](https://github.com/opengovsg/FormSG/pull/2523)
- fix(deps): bump aws-sdk from 2.959.0 to   2.960.0 [`#2528`](https://github.com/opengovsg/FormSG/pull/2528)
- fix(deps): bump aws-sdk from 2.960.0 to   2.961.0 [`#2535`](https://github.com/opengovsg/FormSG/pull/2535)
- fix(deps): bump aws-sdk from 2.961.0 to   2.963.0 [`#2547`](https://github.com/opengovsg/FormSG/pull/2547)
- fix(deps): bump aws-sdk from 2.963.0 to   2.964.0 [`#2563`](https://github.com/opengovsg/FormSG/pull/2563)
- fix(deps): bump jszip from 3.7.0 to   3.7.1 [`#2549`](https://github.com/opengovsg/FormSG/pull/2549)
- fix: upgrade mongoose from 5.13.2 to   5.13.3 [`#2542`](https://github.com/opengovsg/FormSG/pull/2542)

### Dev dependencies
- chore: Move file-loader to   dev-dependencies [`#2556`](https://github.com/opengovsg/FormSG/pull/2556)
- chore(deps-dev): bump @babel/core from   7.14.8 to 7.15.0 [`#2536`](https://github.com/opengovsg/FormSG/pull/2536)
- chore(deps-dev): bump   @babel/plugin-transform-runtime   [`#2534`](https://github.com/opengovsg/FormSG/pull/2534)
- chore(deps-dev): bump @babel/preset-env   from 7.14.9 to 7.15.0   [`#2537`](https://github.com/opengovsg/FormSG/pull/2537)
- chore(deps-dev): bump @types/node from   14.17.7 to 14.17.9 [`#2529`](https://github.com/opengovsg/FormSG/pull/2529)
- chore(deps-dev): bump   @typescript-eslint/eslint-plugin   [`#2562`](https://github.com/opengovsg/FormSG/pull/2562)
- chore(deps-dev): bump   @typescript-eslint/parser from 4.28.5 to 4.29.0   [`#2524`](https://github.com/opengovsg/FormSG/pull/2524)
- chore(deps-dev): bump   @typescript-eslint/parser from 4.29.0 to 4.29.1   [`#2555`](https://github.com/opengovsg/FormSG/pull/2555)
- chore(deps-dev): bump concurrently from   6.2.0 to 6.2.1 [`#2548`](https://github.com/opengovsg/FormSG/pull/2548)
- chore(deps-dev): bump core-js from   3.16.0 to 3.16.1 [`#2554`](https://github.com/opengovsg/FormSG/pull/2554)
- chore(deps-dev): bump   eslint-plugin-import from 2.23.4 to 2.24.0   [`#2553`](https://github.com/opengovsg/FormSG/pull/2553)
- chore(deps-dev): bump lint-staged from   11.1.1 to 11.1.2 [`#2545`](https://github.com/opengovsg/FormSG/pull/2545)
- chore(deps-dev): bump ts-node from   10.1.0 to 10.2.0 [`#2552`](https://github.com/opengovsg/FormSG/pull/2552)
- chore(deps-dev): bump type-fest from   1.3.0 to 1.4.0 [`#2538`](https://github.com/opengovsg/FormSG/pull/2538)
- chore(deps-dev): bump type-fest from   1.4.0 to 2.0.0 [`#2543`](https://github.com/opengovsg/FormSG/pull/2543)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
### Deleting old SPCP cookie name in the frontend
- [ ] Create sp form and log in
  - [ ] Check that form can be submitted
  - [ ] Check that user can log out and jwt cookie is deleted thereafter
  - [ ] Log in again. Check that submission and log out works
- [ ] Repeat above with 'remember me' enabled
- [ ] Repeat above with CP form
- [ ] Repeat above with MyInfo form
- [ ] Repeat above with SGID form

**Comment by karrui** [comment]
## Tests
### Loosening esrvcId validation
### Manual tests
- [ ] Go to form, add esrvcId with whitespace. Should reject.
- [ ] Go to form, add esrvcId with any characters except whitespace. Should accept.

### Prod tests
- [ ] Go to form, add INVALID esrvcId with any characters except whitespace. Should accept. Activate form. Modal should reject and prevent form from being activated.

**Comment by karrui** [comment]
## Tests
### Correct error message on private mode form
Steps:
1. Activate a storage mode form
2. Open the form in a separate tab
3. In the admin panel, make the form private
4. Try to submit the form in the separate tab

- [ ] Should show error toast "This form has been taken down. For assistance, please contact the person who asked you to fill in this form."

**Comment by karrui** [comment]
## Tests
### verified sms limiting
**Happy path without db access**
- [ ] Create 2 new forms with a mobile field and sms verifications enabled 
- [ ] On 1 form, request to verify your phone number. 
- [ ] Return to the form and attempt to add a new mobile number field. The count should be updated
- [ ] Attempt to edit the other mobile number field. The count should also be updated. 
- [ ] Go to the other form, and repeat the above 2 tests.

**Comment by karrui** [comment]
## Tests
### verified sms limiting

**Warning email tests - requires db population in staging**
- [ ] Create 2 forms with verifiable mobile fields. ensure that 1 of them has the `msgSrvcName` property set.
- [ ] Create a form with a verifiable mobile field.  Insert 2499 smses into the db (see the misc section down below).
- [ ] Open the form and subsequently, the mobile field. Verify that the counts has been updated.
- [ ] request for otp verification. Should receive an email warning form admin about the limit. Attempt to toggle the mobile field on again - this should succeed and show the updated count.
- [ ] Verify that there is a warning email receieved.
- [ ] Ensure that the email received has **2** form titles. (the 2 forms w/o `msgSrvcName`)  
- [ ] Ensure that the form with `msgSrvcName` is not shown in the email
- [ ]  Repeat the above steps for 4999/7499 smses and verify the result

**Comment by karrui** [comment]
## Tests
### verified sms limiting

**Disabled email tests - requires db access**

**Have the edit mobile field window open before proceeeding**. Toggle **on** the sms verification feature and **do not save**. Remain on the modal.  Create another form in the staging db and set a `msgSrvcName` so that it acts as an onboarded form

- [ ] Have a window/tab with the form open prior to inserting smses. 
- [ ] Insert 10k smses. attempt to verify with the tab/window from previously. this should succeed. next, refresh the public forms page/navigate back (now the form has >10k smses). the `verify` option should not be there. 
- [ ] Now attempt to save the edit mobile field modal as an admin (with otp verification toggled on). There should be a toast informing you that the update is invalid.  
- [ ] Attempt to duplicate the mobile field. This should work. Click on the mobile field. It should be disabled. 
- [ ] Attempt to duplicate this form. This should work. Verify that the duplicated form also has sms verification disabled.
- [ ] Attempt to use the form as a template. This should work. Verify that the duplicated form also has sms verification disabled.
- [ ] Close the edit mobile field modal and reopen it. Verify that the toggle is greyed out. 
- [ ] Verify that you have received an email warning you that your forms have sms verifications disabled. 
- [ ] Transfer the form to `${name}+1@${domain here}` and make them the owner. Open the form and verify that sms counts have been reset.  
- [ ] Ensure that the other form with `msgSrvcName` is not affected and mobile number field can still be toggled

**Comment by karrui** [comment]
@karrui 

## Tests
### Check copywriting of emails, modals
- [ ] Email correct copywriting
- [ ] Modal correct copywriting

**Review by mantariksh — APPROVED** [review]

**Review by mantariksh — APPROVED** [review]

**Review by tshuli — APPROVED** [review]

**Pull request merged**
