### PR TITLE
build: release v5.18.0

### PR DESCRIPTION
**Pull request by karrui**
# Release v5.18.0

## New
- feat: rename "Reference   Number" to "Response ID"   [`#2277`](https://github.com/opengovsg/FormSG/pull/2277)
- feat: Admin form UI changes to   "Edit Welcome" fields   [`#2258`](https://github.com/opengovsg/FormSG/pull/2258)

## Fixes
- fix: allow creation of storage form   when emails are invalid   [`#2263`](https://github.com/opengovsg/FormSG/pull/2263)
- fix: correctly retrieve targetFormId   for redirect state [`#2261`](https://github.com/opengovsg/FormSG/pull/2261)

## Improvements
- refactor: ensure consistent filesize   const [`#2079`](https://github.com/opengovsg/FormSG/pull/2079)

## Dependency changes
- fix: upgrade mongoose from 5.12.12 to   5.12.13 [`#2257`](https://github.com/opengovsg/FormSG/pull/2257)
- fix(deps): bump @sentry/browser from   6.7.2 to 6.8.0 [`#2269`](https://github.com/opengovsg/FormSG/pull/2269)
- fix(deps): bump @sentry/integrations   from 6.7.2 to 6.8.0 [`#2268`](https://github.com/opengovsg/FormSG/pull/2268)
- fix(deps): bump aws-sdk from 2.932.0 to   2.933.0 [`#2252`](https://github.com/opengovsg/FormSG/pull/2252)
- fix(deps): bump aws-sdk from 2.933.0 to   2.935.0 [`#2259`](https://github.com/opengovsg/FormSG/pull/2259)
- fix(deps): bump aws-sdk from 2.935.0 to   2.936.0 [`#2273`](https://github.com/opengovsg/FormSG/pull/2273)

### Dev dependencies
- chore(deps-dev): bump   @typescript-eslint/eslint-plugin   [`#2271`](https://github.com/opengovsg/FormSG/pull/2271)
- chore(deps-dev): bump   @typescript-eslint/parser from 4.28.0 to 4.28.1   [`#2270`](https://github.com/opengovsg/FormSG/pull/2270)
- chore(deps-dev): bump core-js from   3.15.1 to 3.15.2 [`#2272`](https://github.com/opengovsg/FormSG/pull/2272)
- chore(deps-dev): bump coveralls from   3.1.0 to 3.1.1 [`#2274`](https://github.com/opengovsg/FormSG/pull/2274)
- chore(deps-dev): bump   optimize-css-assets-webpack-plugin   [`#2251`](https://github.com/opengovsg/FormSG/pull/2251)
- chore(deps-dev): bump prettier from   2.3.1 to 2.3.2 [`#2260`](https://github.com/opengovsg/FormSG/pull/2260)
- chore(deps-dev): bump ts-node-dev from   1.1.6 to 1.1.7 [`#2275`](https://github.com/opengovsg/FormSG/pull/2275)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
- [ ] Submit an email form. The email response email subject should look like `formsg-auto: <formtitle> (#<submissionId>)`(note the pound sign)
- [ ] the email body should refer to "Response ID" instead of reference number
- [ ] Submit a storage mode form. The data tab header when viewing the response should be "Response ID"
- [ ] Download the story mode CSV. The relevant header should be "Response ID"
- [ ] The update email confirmation PDF to form filler should use "Response ID"

**Comment by karrui** [comment]
## Tests
### Admin form edit start page UI change
Should look like screenshots in https://github.com/opengovsg/FormSG/pull/2258

**Comment by karrui** [comment]
## Tests
### Fix login redirect URL
Pre:
- [ ] Grab an URL of a form you own, and another URL for a form you don't own (probably can be rubbish formId)
Test:
- [ ] Clear cookies. Go to the URL of the form you own again. Should be kicked out to the login page. Sign in should redirect you correctly back into the view admin form page of that form.
- [ ] Clear cookies. Go to the URL of the form you don't own. Should be kicked out to an 404 error page, with a correct target form ID this time, e.g.

**Comment by karrui** [comment]
## Tests
### Allow creation of storage mode form when emails are invalid (when toggling to email mode and toggling back)
- [ ] Go to the create form modal and select "Email mode". Make the email list input invalid, e.g. by deleting all content in the input. Switch back to "Storage mode". You should still be able to create the form as long as the form title is valid. Make sure to go all the way through and create the form.
- [ ] Select "Storage mode" and type an invalid form title. You should be prevented from creating the form.
- [ ] Select "Email mode" and ensure that you are prevented from creating the form with the following types of inputs for the email list, with the correct error message in each case:
    - No input
    - Any invalid email present
    - Duplicate emails present
    - More than 30 non-duplicate emails present
- [ ] Repeat previous test for email list in the Settings tab for an email mode form. If the input is invalid, it should revert to its previous value on blur.

**Review by mantariksh — APPROVED** [review]

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
