### PR TITLE
build: Release 4.42.0

### PR DESCRIPTION
**Pull request by shuli-ogp**
**New**
- feat: require non-empty domains if restrict domain is toggled on [`#507`](https://github.com/opengovsg/FormSG/pull/507)
- feat: log create form failure on GA [`#505`](https://github.com/opengovsg/FormSG/pull/505)

**Improvements**
- docs(readme): acknowledge TellForm, others [`#495`](https://github.com/opengovsg/FormSG/pull/495)

**Fixes**
- fix: disable restrict email domains toggle if no otp verification [`#519`](https://github.com/opengovsg/FormSG/pull/519)

**Dependency Updates**
- chore: fix node version used to 12.18.4 to be consistent [`#516`](https://github.com/opengovsg/FormSG/pull/516)
- chore(deps-dev): bump @typescript-eslint/parser from 4.0.1 to 4.5.0 [`#501`](https://github.com/opengovsg/FormSG/pull/501)
- chore(deps-dev): bump jasmine from 3.6.1 to 3.6.2 [`#508`](https://github.com/opengovsg/FormSG/pull/508)
- chore(deps-dev): bump ts-jest from 26.3.0 to 26.4.1 [`#496`](https://github.com/opengovsg/FormSG/pull/496)
- chore(deps-dev): bump ts-node-dev from 1.0.0-pre.49 to 1.0.0 [`#510`](https://github.com/opengovsg/FormSG/pull/510)
- fix(deps): bump angular-sanitize from 1.8.0 to 1.8.1 [`#494`](https://github.com/opengovsg/FormSG/pull/494)
- fix(deps): bump mongoose from 5.10.0 to 5.10.9 [`#449`](https://github.com/opengovsg/FormSG/pull/449)
- fix(deps): bump selectize from 0.12.4 to 0.12.6 [`#500`](https://github.com/opengovsg/FormSG/pull/500)
- fix(deps): bump twilio from 3.49.3 to 3.50.0 [`#479`](https://github.com/opengovsg/FormSG/pull/479)
- fix(deps): unpin and bump mongoose from 5.10.0 to 5.10.10 [`#513`](https://github.com/opengovsg/FormSG/pull/513)

### CODE REVIEW

**Comment by shuli-ogp** [comment]
**feat: require non-empty domains if restrict domain is toggled on**
@shuli-ogp 

- [ ] Create a form with email field. Turn on restrict domain toggle. Check that it is not possible to save the form with an empty domain list and an error message shows "allowed domains cannot be empty"
- [ ] Fill in a valid restricted domain. Check that the form can now be saved.

**Comment by shuli-ogp** [comment]
**Run through on IE / Intranet**
_General run through_
- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your GSIB inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.
- [ ] Flag out any styling errors which you see

**Comment by shuli-ogp** [comment]
**Run through on IE / Intranet**
_feat: require non-empty domains if restrict domain is toggled on_

- [ ] Create a form with email field. Turn on restrict domain toggle. Check that it is not possible to save the form with an empty domain list and an error message shows "allowed domains cannot be empty"
- [ ] Fill in a valid restricted domain. Check that the form can now be saved.

**Review by karrui — APPROVED** [review]
elgeeteeem

**Pull request merged**
