### PR TITLE
build: release v6.56.0

### PR DESCRIPTION
**Pull request by timotheeg**
## New

- feat: Inject response time to DD v2 [`#6406`](https://github.com/opengovsg/FormSG/pull/6406)
- feat: payment manual sync [`#6102`](https://github.com/opengovsg/FormSG/pull/6102)
- feat: copy changes before payments is released to prod [`#6407`](https://github.com/opengovsg/FormSG/pull/6407)
- feat: capture paths with (accidental) trailing slashes [`#6405`](https://github.com/opengovsg/FormSG/pull/6405)
- feat: download payment guide from AWS [`#6403`](https://github.com/opengovsg/FormSG/pull/6403)
- fix: use balance transaction fees from stripe [`#6404`](https://github.com/opengovsg/FormSG/pull/6404)
- ci: remove staging-al2 branch [`#6397`](https://github.com/opengovsg/FormSG/pull/6397)
- revert: "feat: inject normalised response time to DD" [`#6402`](https://github.com/opengovsg/FormSG/pull/6402)
- feat: inject normalised response time to DD [`#6387`](https://github.com/opengovsg/FormSG/pull/6387)
- fix: payment settings copy - business details, icon and rendering [`#6390`](https://github.com/opengovsg/FormSG/pull/6390)
- build: merge v6.55.0 into develop [`#6394`](https://github.com/opengovsg/FormSG/pull/6394)
- build: release v6.55.0 [`#6393`](https://github.com/opengovsg/FormSG/pull/6393)

## Dependencies

- fix(deps): bump type-fest from 3.11.0 to 3.11.1 in /shared [`#6408`](https://github.com/opengovsg/FormSG/pull/6408)
- fix(deps): bump libphonenumber-js from 1.10.30 to 1.10.31 in /shared [`#6399`](https://github.com/opengovsg/FormSG/pull/6399)

## Dev-Dependencies

- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.59.7 to 5.59.8 in /shared [`#6401`](https://github.com/opengovsg/FormSG/pull/6401)
- chore(deps-dev): bump @typescript-eslint/parser from 5.59.7 to 5.59.8 in /shared [`#6400`](https://github.com/opengovsg/FormSG/pull/6400)
- chore(deps-dev): bump @types/lodash from 4.14.194 to 4.14.195 in /shared [`#6396`](https://github.com/opengovsg/FormSG/pull/6396)

### feat: Inject response time to DD v2 [`#6406`](https://github.com/opengovsg/FormSG/pull/6406)

@LinHuiqing 

- [x] Make a couple of submissions
- [x] go to dd metrics explorer
- [x] look for `formsg.submissions.responseTime.normalised` 
- [x] look for `formsg.submissions.responseTime` 
- [x] your submissions' response time data should be visible

### feat: payment manual sync [`#6102`](https://github.com/opengovsg/FormSG/pull/6102)

@LinHuiqing 

To test that failed events are resent:
- [x] Fill a payment form and proceed to pay (preferably on your phone).
    - [x] Then, revert staging to v6.41.0 (this is the release just before payments, without webhook handler). **While this deploys, keep your payment tab active!**
    - [x] When the deployment is complete, fill the card details on the payment page and click "Submit payment". This should lead you to a blank screen.
    - [x] Check that on the Stripe dashboard, two events have been sent out `charge.succeeded` and `payment_intent.succeeded`. Each should have been tried twice, with the next retry "in an hour".
    - [x] Now, restore the latest version onto staging.
    - [x] Refresh the payment page. This should show "we are waiting for your proof of payment" screen.
    - [x] Run the lambda, and refresh the payment page. This should show the success screen.
    - [x] Check the slack reconciliation report, that two events were successfully handled.

To test the payment cancellation flow:
- [x] Fill a payment form and proceed to pay. DO NOT make payment.
    - [x] Wait half an hour. Retrigger the lambda.
    - [x] Go back to the payment page. It should show "Payment request was cancelled".

#### Deploy Notes

New lambda scripts
- `form-payment-reconciliation`

Lambda environment configuration
- `SSM_ENV_SITE_NAME`: one of `prod`, `staging`, `staging-alt`, `staging-alt2` or `uat`.

New SSM configs
- `{ENV_NAME}-cron-payment parameter`
  - `CRON_PAYMENT_API_SECRET={secret-key}`
  - `SLACK_API_SECRET={slack-secret-key}`

### feat: copy changes before payments is released to prod [`#6407`](https://github.com/opengovsg/FormSG/pull/6407)

- [x] On a new login (or `has-seen-accouncement-rollout-...` cleared on localstorage), ensure that the announcement rollout modal shows with the payment feature.
- [x] On a new login (or `users.flags.lastSeenFeatureUpdateVersion` < 2), ensure that:
   - [x] There is a red badge beside "What's new".
   - [x] "What's new" drawer shows with the payment feature.
- [x] When creating a form, the Storage mode option should have "Supports payments" as one of the pointers.
- [x] In the production env's payment settings page, check that the Stripe onboarding form link is added to the infobox.
- [ ] For the Thank You page,
   - [x] Storage-mode form with payments
      - [x] All customising fields are disabled .
      - [ ] Preview reflects the wording for thank you page for payments.
   - [x] Storage-mode form without payments - has normal Thank You page as before.
   - [x] Email-mode form - has normal Thank You page as before.
- [x] Check that there is an infobox in the payment input panel for payment amounts of > $1000

### feat: capture paths with (accidental) trailing slashes [`#6405`](https://github.com/opengovsg/FormSG/pull/6405)

@timotheeg 

- [x] Verify the following hash-bang urls redirect to the correct react urls:
    - https://form.gov.sg/#!/5b88b36bdcac67000fec0403
    - https://form.gov.sg/#!/5b88b36bdcac67000fec0403/
    - https://form.gov.sg/#!/5b88b36bdcac67000fec0403/admin
    - https://form.gov.sg/#!/5b88b36bdcac67000fec0403/admin/
    - https://form.gov.sg/#!/5b88b36bdcac67000fec0403/preview
    - https://form.gov.sg/#!/5b88b36bdcac67000fec0403/preview/
    - https://form.gov.sg/#!/5b88b36bdcac67000fec0403/use-template
    - https://form.gov.sg/#!/5b88b36bdcac67000fec0403/use-template/
    - https://form.gov.sg/#!/forms
    - https://form.gov.sg/#!/forms/
    - https://form.gov.sg/#!/examples
    - https://form.gov.sg/#!/examples/

### fix: use balance transaction fees from stripe [`#6404`](https://github.com/opengovsg/FormSG/pull/6404)

@foochifa 

- [x] Enable both Card and Paynow as payment methods on a Stripe account.
- [x] Create a storage-mode form on a payment-enabled admin account. Connect the form to the Stripe account above.
- [x] Perform a form submission and payment with the Card payment method.
   - [x] Check that the transaction fees on FormSG matches the one on Stripe.
- [x] Perform a form submission and payment with the Paynow payment method.
   - [x] Check that the transaction fees on FormSG matches the one on Stripe.

### fix: payment settings copy - business details, icon and rendering [`#6390`](https://github.com/opengovsg/FormSG/pull/6390)

@foochifa 

Check that the payment settings page has the right copy under the following conditions (on a **staging** environment):
- [x] Production env (set `SECRET_ENV=production`)
   - [x] Before Stripe account is connected ([design](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17472-182345&t=zFqLebTBv4x4zIfc-0))
   - [x] After Stripe account is connected ([design](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17472-182590&t=zFqLebTBv4x4zIfc-0))
- [ ] Non-production env (set `SECRET_ENV=staging` or `development` or `test`)
   - [x] Before Stripe account is connected ([design](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17202-179867&t=zFqLebTBv4x4zIfc-0))
   - [x] After Stripe account is connected ([design](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17213-180740&t=zFqLebTBv4x4zIfc-0))
   - [ ] After Stripe account connection is skipped ([design](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17226-180896&t=zFqLebTBv4x4zIfc-0))

### CODE REVIEW

**Comment by foochifa** [comment]
Heads-up for #6390 there is an inconsistency of the settings page for test account on test env (GST, address not shown)

| On staging | Figma |
| --- | --- |
| image | image |

But shouldn't be blocking

**Comment by foochifa** [comment]
Another note for #6407

The link for the 'fake' `save payment invoice` will redirect to a 404 see below

Link (Bottom left)
image

Resulting page
image

**Review by LinHuiqing — APPROVED** [review]
only non-blocking issues! let's goooo

**Comment by LinHuiqing** [comment]
btw this is missing some deploy notes from https://github.com/opengovsg/FormSG/pull/6407

**Pull request merged**
