### PR TITLE
build: release v6.139.0

### PR DESCRIPTION
**Pull request by kevin9foong**
## New

- fix: forbid stripe acc connection with pdf summary enabled [`#7570`](https://github.com/opengovsg/FormSG/pull/7570)
- fix: enable pdf attachment for encrypt mode forms [`#7523`](https://github.com/opengovsg/FormSG/pull/7523)
- chore: remove unused sgid toggle [`#7563`](https://github.com/opengovsg/FormSG/pull/7563)

### fix: enable pdf attachment for encrypt mode forms [`#7523`](https://github.com/opengovsg/FormSG/pull/7523)
**DB Test to ensure formsg.unencryptedAttachments is not saved in DB**
- [x] 1. Create a storage mode form
- [x] 2. Add an attachment field and an email field
- [x] 3. Ensure that the email field has email confirmations enabled and PDF responses also enabled
- [x] 4. and and open the form to public
- [x] 5. Make a submission with an attachment
- [x] 6. Obtain the form ID and make a query on the appropriate DB: `{form: ObjectId('669735b40479eaf8b6627e48')}`
- [x] 7. Ensure that the DB doesn't contain the unencrypted attachments

**Duplicate Test form**
- [x] 1. Create a storage mode form
- [x] 2. Add an email field and enable email confirmations
- [x] 3. Enable PDF response as well
- [x] 4. Duplicate the Form to an MRF form
- [x] 5. Ensure that the email field still exists
- [x] 6. Ensure that the PDF response toggle is turned off and observe that the toggle is also locked.
- [x] 7. Turn off the email confirmations toggle
- [x] 8. Open the form to public
- [x] 9. Create a submission
- [x] 10. Observe that the submitter email doesn't receive any email at all
- [x] 11. Repeat for email mode forms

**Regression Tests to ensure that PDF responses works for Email mode**
- [x] 1. Create an email mode form
- [x] 2. Add an email field and an attachment field. Add other fields as well
- [x] 3. Enable the email confirmation for the email field and PDF responses as well.
- [x] 4. Make form public
- [x] 5. Make a submission with an attachment
- [x] 6. Observe that the submitter email receives an email confirmation 
- [x] 7. Observe that the email contains both the PDF responses + the attachments
- [x] 8. Observe that the attachments is equivalent to the submitted attachment
- [x] 9. Observe that the PDF response  contains all the fields in the form, and correspond to your inputs

**Ensure that payment form with NO active payment field CAN enable PDF responses**
- [x] 1. Create encrypt mode form
- [x] 2. Connect a stripe account
- [x] 3. Add an email field
- [x] 4. Enable email confirmations
- [x] 5. Observe that the toggle for pdf responses is not locked and can be toggled on

**Unusual path: Ensure form with active payment field AND includeFormSummary enabled doesn't get response.pdf**
- [x] 1. Create an encrypt form
- [x] 2. Add an email field and an attachment field
- [x] 3. For the email field, Enable email confirmations and also enable pdf response toggle
- [x] 4. Connect a stripe account
- [x] 5. Should not be allowed to add stripe account.  

**Ensure that payment form with active payment field CANNOT enable PDF responses**
- [x] 1. Create encrypt mode form
- [x] 2. Connect a stripe account
- [x] 3. Add an email field
- [x] 4. Enable email confirmations
- [x] 5. Observe that the toggle for the pdf response is locked and not toggled on.

**Regression test to ensure that MRF forms cannot enable email confirmations**
- [x] 1. Create an MRF form
- [x] 2. Add an email field
- [x] 3. Observe that the email confirmation toggle is locked

**Regression tests to ensure that email confirmation works for Email mode**
- [x] 1. Create an email mode form
- [x] 2. Add an email field and enable email confirmations. Add an attachment field as well
- [x] 3. Observe that the toggle for pdf response is not locked
- [x] 4. Enable pdf response
- [x] 5. Make form visible to public
- [x] 6. Make a submission
- [x] 7. Observe that the submitter email received the submission confirmation
- [x] 8. Observe that the email has PDF attachment and the other attachments as well.

**Regression tests to ensure that admin email notification still works for storage mode forms**
- [x] 1. Create a storage mode form
- [x] 2. Create a few input fields
- [x] 3. Add admin emails
- [x] 4. Make the form public and make a submission
- [x] 5. Observe that the admin email receives the email notification.
- [x] 6. Observe that the table contains all the visible fields
- [x] 7. Observe that the response ID, time of  submission are the same as the formsg submission page
- [x] 8. Observe that the json payload doesn't exist at the end of the email

### chore: remove unused sgid toggle [`#7563`](https://github.com/opengovsg/FormSG/pull/7563)

**Regression**
##### Check that sgID MyInfo fields are available.
- [x] Create a new form
- [x] Enable "Singpass-App only Myinfo (Free)"
- [x] Go to form builder
- [x] Observe that all fields are enabled

### [fix: forbid stripe acc connection with pdf summary enabled](https://github.com/opengovsg/FormSG/pull/7564/commits/da9e274afc674917918be99a1b94075b95855ab6)
**Ensure that payment forms cannot toggle on pdf response**
- [x] 1. Create an encrypt mode form
- [x] 2. Connect stripe account
- [x] 3. Add email field
- [x] 4. Toggle on email confirmation
- [x] 5. Try to toggle on pdf response, should not allow, it should be locked
- [x] 6. Observe that there's description text saying "PDF resposnse not available for payment forms"

**Ensure that forms with pdf response toggled cannot connect stripe**
- [x] 1. Create an encrypt mode form
- [x] 2. Add an email field
- [x] 3. Toggle on email confirmation and also toggle pdf response.
- [x] 4. Try to connect stripe account, it should not allow you to. 
- [x] 5. Observe that there's a info box to remind users to disable pdf response

**Ensure that forms with pdf response disabled can connect stripe**
- [x] 1. Create an encrypt mode form
- [x] 2. Add an email field
- [x] 3. Toggle on email confirmation and also DO NOT toggle pdf response.
- [x] 4. Try to connect stripe account, it should allow you to.

**Ensure that error message is unordered list for all 6 permutations of payment exclusions**
- [x] 1. Create an encrypt mode form
- [x] 2. Add an admin email in the settings page
- [x] 3. Add an email field, and enable Email confirmations + Enable pdf response
- [x] 4. Enable singpass toggle and enable single submission toggle as well.
- [x] 5. Navigate to payments page
- [x] 6. Observe that the info box is in unordered list format
- [x] 7. Repeat for 5 of the remaining permutations, ensure that if > 1 error is present, it should be an unordered list. Otherwise its just a sentence

### CODE REVIEW

**Comment by kevin9foong** [comment]
image
Storage mode form duplication bug encountered 

Email confirmation is not locked and disabled, but is once it is disabled.

Same behaviour as email mode form, so it is ok

**Comment by kevin9foong** [comment]
payment enabled storage forms have the `include pdf response` option disabled 
image

**Comment by kevin9foong** [comment]
image
stripe enabled after include pdf responses toggled on -> the toggle is locked

**Review by g-tejas — APPROVED** [review]
LGTM!

**Pull request merged**
