### PR TITLE
chore: improve webpack bundling

### PR DESCRIPTION
**Pull request by darrelhong**
## Overview
this PR covers some low-hanging fruits to improve the bundling of the v2 react frontend. while it might not be that important as you can get away with a lot these days (especially for a country [pretty fast](https://www.speedtest.net/global-index) broadband and mobile speeds), its at least good to take note. for example, i think the landing page bundles almost all the dependencies

## Problem
current bundle for react frontend has duplicate dependencies and lots of modules in main/vendor bundle

## Solution
add bundle analyzer plugin
update webpack alias to bundle from frontend/node_modules instead of shared
lazy import some of the bigger modules/pages

**Breaking Changes** 
probably the latest commit on this branch needs a bit more checking/testing. Not sure why some pages are lazily imported and others are not, maybe there are some considerations i am unaware of. Also didn't run the full docker workflow and just ran the frontend project on native host, so I can't be sure that nothing has broken
- [x] this PR contains breaking changes - Maybe
   
## Before & After Screenshots

**BEFORE**:
Screenshot 2022-07-29 at 12 14 15 AM

**AFTER**:
Screenshot 2022-07-29 at 12 17 52 AM

definitely more opportunities for improvement with splitting the vendor bundle and it also looks like lodash is not tree-shaken

**New dev dependencies**:

- `dependency` : :[webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer)

Other things that might be considered could be updating to [CRA v5](https://github.com/dilanx/craco/issues/378) to see if there's any improvements, or maybe even ejecting from CRA.

### CODE REVIEW

**Comment by timotheeg** [comment]
Thanks for the PR @darrelhong 🙏 . `webpack-bundle-analyzer` is really neat!

We are working on functional completion atm, so we might not get to this PR right away, but we will relook at our bundle strategy and optimizations as soon as we can. Thanks for bringing it to our attention!

**Comment by darrelhong** [comment]
since form-v2 is in "beta", it might be a good idea to merge some of these changes in so that any issues would be caught early. The changes should not affect the functional side of things and I believe the unit tests still pass. not too sure if it breaks any pipelines on your side

**Comment by darrelhong** [comment]
@timotheeg still looking into this? if not i will close the PR

**Comment by darrelhong** [comment]
@timotheeg @justynoh any update on this? I could take another look at this and it probably needs some rework

**Comment by timotheeg** [comment]
We are getting close to finally getting rid of angular in the codebase, and we'll be looking at upgrading react and the webpack bundling after thyat. 

Since the PR is outdated with conflicts now, I'm going to close it first. It's still a good problem to solve, so I recommend opening an issue first, and then opening the PR again when the code base has stabilized (another 2-3 weeks I reckon 🤞)

**Pull request closed without merging**
