### PR TITLE
build: Release v4.37.0

### PR DESCRIPTION
**Pull request by karrui**
### New
- feat: add `lastAccessed` key to track user login [`#364`](https://github.com/opengovsg/formsg/pull/364)
- feat: move notification banner back to top and add banner type capabilities [`#359`](https://github.com/opengovsg/formsg/pull/359)
- feat: filter storage mode responses by submission id [`#362`](https://github.com/opengovsg/formsg/pull/362)
- feat: implement email domain validation with unit tests [`#143`](https://github.com/opengovsg/formsg/pull/143)

### Improvements
- refactor: make bounceType required [`#360`](https://github.com/opengovsg/formsg/pull/360)

### Dependency upgrades
- fix(deps): upgrade node, alpine and chromium [`#363`](https://github.com/opengovsg/formsg/pull/363)
- fix(deps): bump @sentry/integrations from 5.22.3 to 5.24.2 [`#373`](https://github.com/opengovsg/formsg/pull/373)
- fix(deps): bump http-status-codes from 2.1.2 to 2.1.4 [`#354`](https://github.com/opengovsg/formsg/pull/354)
- chore(deps-dev): bump auto-changelog from 2.2.0 to 2.2.1 [`#365`](https://github.com/opengovsg/formsg/pull/365)
- chore(deps-dev): bump @types/validator from 13.0.0 to 13.1.0 [`#366`](https://github.com/opengovsg/formsg/pull/366)
- chore(deps-dev): bump prettier from 2.1.1 to 2.1.2 [`#356`](https://github.com/opengovsg/formsg/pull/356)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
### User document date key changes
- Checking whether `lastAccessed` key updates
  - Check your current user document in MongoDB. Take note of the `lastAccessed` value (if available, might not be there if you have no logged in prior to this feature). Take note of the `updatedAt` key value (if available, might not be there too)
  - Log out of FormSG if you are currently logged in
  - Log into FormSG
  - [ ] `lastAccessed` key value changes to your login datetime.
  - [ ] `updatedAt` key value does not change.

- Checking whether `updatedAt` key updates
  - Check your current user document in MongoDB. Take note of the `updatedAt` key value (if available, might not be there)
  - Update your emergency contact number (if you don't have a second number to verify with, Slack me and test against my phone)
  - [ ] `updatedAt` key value changes to your update datetime.

**Comment by karrui** [comment]
## Tests
### Banner changes
(Staging environment already has 2 environment variables set up: `ADMIN_BANNER_CONTENT=This is just a generic banner on secured routes to check banner content` and `IS_GENERAL_MAINTENANCE=warn:MockPass is currently undergoing maintenance, from 12am-4am.`)

- [ ] Info banner displays on private routes properly (list form and form builder routes)
- [ ] public forms displays correct warn banner
- [ ] General UI looks like they were before

**Comment by karrui** [comment]
## Tests
### Email field domain validation

**Create a new email field**
- [ ] There should be a new "Restrict email domains" toggle
- [ ]  If 'OTP Verification' is off, 'Restrict email domains' toggle should be disabled
- [ ] Toggle OTP Verification and Restrict email domains to both be toggled on. Toggle OTP Verification off. Restrict email domains should now be also disabled, and an error toast to appear to prompt the user about it.
- [ ] First line of placeholder text of unfilled allowed domains should be the user's own agency domain
- [ ] Should not allow duplicate email domains in Domains allowed textarea
- [ ] Should not allow invalid domains (i.e. must be prefixed with `@` and have a `.` somewhere)

Next, go to the public form with the above created domain restricted email field
**Public form**
- [ ]  Should prevent verification (with error text) if the domain of email entered is not an allowed domain
- [ ] Should allow verification if the email domain is allowed.

**Comment by karrui** [comment]
## Tests
@arshadali172 
- [ ] General run through ie11 and gsib

**Comment by mantariksh** [comment]
@mantariksh 
### Submission ID filtering
- [ ] Filter a storage mode form's results by submission ID. Ensure that the correct submission shows up.
- [ ] Clear the text box. The submissions should still be filtered. The full list of submissions should only be shown upon clicking "View all".
- [ ] Go to the database metrics and ensure that Disk IOPS and utilisation have not spiked.

**Review by mantariksh — APPROVED** [review]

**Review by arshadali172 — APPROVED** [review]

**Pull request merged**
