### PR TITLE
feat: mailto link for secret key

### PR DESCRIPTION
**Pull request by mantariksh**
## Problem

People lose their secret keys, thus losing all responses.

Addresses #9, but not fully as design is not finalised.

## Solution

Update the warning in the secret key modal to include guidelines for safekeeping secret keys, and add a convenient mailto URL to encourage users to share their secret keys.

### Before
Screenshot 2020-08-18 at 12 10 52 PM

### After
image

image

## Tests
- [ ] Clicking on "Email" link in secret key modal opens email with correct subject, form title and secret key

### CODE REVIEW

**Review by karrui — APPROVED** [review]
lgtm, just need to update some padding -- the email link seems to have some extra left padding
Screenshot 2020-08-19 at 11 37 22 AM

**Comment by mantariksh** [comment]
> lgtm, just need to update some padding -- the email link seems to have some extra left padding

@karrui yeah I actually was going to ask you about that - the padding is very mysterious, if you use your browser tools to check and uncheck `list-style-type: none` from the `ul`, it disappears. Any idea how to fix?

**Comment by karrui** [comment]
Ya just use padding-left: 0 on the list item

**Comment by mantariksh** [comment]
@karrui sorry sir that doesn't work, let me try and experiment

**Comment by mantariksh** [comment]
@karrui ok fixed by adding a space after the `-` in `content`

**Pull request merged**
