### PR TITLE
build: release 4.47.0

### PR DESCRIPTION
**Pull request by mantariksh**
# v4.47.0

## New
- feat: update TOU + PP, update public form footer [`#682`](https://github.com/opengovsg/FormSG/pull/682)
- feat: add feature request link in admin navbar [`#676`](https://github.com/opengovsg/FormSG/pull/676)
- feat: Increase attachment size options [`#668`](https://github.com/opengovsg/FormSG/pull/668)

## Improvements
- feat: change 'Verified?' on SMS config to 'OTP verification' [`#678`](https://github.com/opengovsg/FormSG/pull/678)
- ref: migrate feedback/count endpoint handler flow to TypeScript [`#706`](https://github.com/opengovsg/FormSG/pull/706)
- ref: extract assert permission levels helper functions [`#703`](https://github.com/opengovsg/FormSG/pull/703)
- refactor: migrate Singpass and Corppass code to TypeScript [`#701`](https://github.com/opengovsg/FormSG/pull/701)
- refactor: migrate home phone number validator to ts [`#704`](https://github.com/opengovsg/FormSG/pull/704)
- refactor: use neverthrow for exceptions [`#634`](https://github.com/opengovsg/FormSG/pull/634)
- refactor: migrate utils/permission-levels to admin-form.types [`#694`](https://github.com/opengovsg/FormSG/pull/694)
- ref: migrate get single encrypt submission flow to TypeScript [`#670`](https://github.com/opengovsg/FormSG/pull/670)
- feat: introduce CodeQL static analyzer [`#655`](https://github.com/opengovsg/FormSG/pull/655)
- refactor: extract temporary types into express.locals [`#683`](https://github.com/opengovsg/FormSG/pull/683)
- build: add lockfile-lint to CI [`#651`](https://github.com/opengovsg/FormSG/pull/651)

## Fixes
- fix: check duplicate MyInfo fields [`#702`](https://github.com/opengovsg/FormSG/pull/702)
- fix: early return on undefined verification signature [`e67bb8b`](https://github.com/opengovsg/FormSG/commit/e67bb8b1fc12e41c7c9cf1347a52ed7e30f2fbf5)

## Dependency updates
- chore(deps-dev): bump sinon from 9.2.0 to 9.2.1 [`#710`](https://github.com/opengovsg/FormSG/pull/710)
- chore(deps-dev): bump @opengovsg/mockpass from 2.5.5 to 2.5.6 [`#708`](https://github.com/opengovsg/FormSG/pull/708)
- chore(deps-dev): bump @types/mongodb from 3.5.33 to 3.5.34 [`#700`](https://github.com/opengovsg/FormSG/pull/700)
- fix(deps): bump twilio from 3.50.0 to 3.51.0 [`#699`](https://github.com/opengovsg/FormSG/pull/699)
- chore(deps-dev): bump jasmine-core from 3.5.0 to 3.6.0 [`#698`](https://github.com/opengovsg/FormSG/pull/698)
- fix(deps): bump angular-resource from 1.8.1 to 1.8.2 [`#689`](https://github.com/opengovsg/FormSG/pull/689)
- fix(deps): bump @sentry/integrations from 5.27.3 to 5.27.4 [`#688`](https://github.com/opengovsg/FormSG/pull/688)
- chore(deps-dev): bump htmlhint from 0.14.1 to 0.14.2 [`#687`](https://github.com/opengovsg/FormSG/pull/687)
- chore(deps-dev): bump eslint-plugin-jest from 24.0.2 to 24.1.3 [`#685`](https://github.com/opengovsg/FormSG/pull/685)
- fix(deps): bump jwt-decode from 3.1.1 to 3.1.2 [`#674`](https://github.com/opengovsg/FormSG/pull/674)
- fix(deps): bump mongoose from 5.10.14 to 5.10.15 [`#673`](https://github.com/opengovsg/FormSG/pull/673)
- fix(deps): bump fp-ts from 2.8.5 to 2.8.6 [`#672`](https://github.com/opengovsg/FormSG/pull/672)
- fix(deps): bump moment-timezone from 0.5.31 to 0.5.32 [`#675`](https://github.com/opengovsg/FormSG/pull/675)
- fix(deps): bump angular-sanitize from 1.8.1 to 1.8.2 [`#671`](https://github.com/opengovsg/FormSG/pull/671)
- chore(deps-dev): bump @types/mongodb from 3.5.27 to 3.5.33 [`#661`](https://github.com/opengovsg/FormSG/pull/661)
- chore(deps-dev): bump @types/ejs from 3.0.4 to 3.0.5 [`#660`](https://github.com/opengovsg/FormSG/pull/660)
- fix(deps): bump axios from 0.20.0 to 0.21.0 [`#658`](https://github.com/opengovsg/FormSG/pull/658)
- chore(deps-dev): bump lint-staged from 10.4.0 to 10.5.1 [`#657`](https://github.com/opengovsg/FormSG/pull/657)
- chore: bump version to v4.46.1 [`375df4f`](https://github.com/opengovsg/FormSG/commit/375df4f23a4a9253a50df6bdb1905cfcb40d83f2)

### CODE REVIEW

**Comment by mantariksh** [comment]
## Tests
**Intranet IE11**
- [ ] Feature request navbar item links to feature request form

**Comment by mantariksh** [comment]
## Tests
- [ ] Create a form with 2 MyInfo Name fields and a Vehicle Number field. Tamper with the first Name response by removing the HTML `disabled` attribute on the input and editing the field. Check that when you try to submit, you get a `MyInfo verification failed` error.
- [ ] Tamper with the 2nd field and check that you get the same error.
- [ ] Submit the form without tampering and check that you get the [MyInfo] prefix on the name fields and not the Vehicle Number field.
- [ ] Submit the form in preview mode and check that you get the [MyInfo] prefix on ALL fields (including Vehicle Number).

**Comment by mantariksh** [comment]
## Tests
- [ ] Create two home phone number fields. Hide one of them behind logic.
- [ ] Check that validation on both visible and hidden phone number fields work
 - Invalid phone number format is rejected
 - Valid phone number format is accepted
 - When international number are allowed, international phone number is accepted
 - When international number is not allowed, international phone number is rejected

**Comment by mantariksh** [comment]
## Tests
**Email Mode SingPass**
- [ ] Create a new form and add SingPass authentication with an invalid e-service ID. Attempt to activate the form. You should get an error message with a numeric error code (probably 138).
- [ ] Add a valid e-service ID. Check that you can activate the form.
- [ ] Add a mix of MyInfo fields which are verified (e.g. name) and non-verified (e.g. vehicle number).
- [ ] Preview the form. Check that the NRIC S1234567A is automatically populated. Submit the form in preview mode and ensure that you receive the response. The response should have the [MyInfo] prefix in front of all fields, regardless of whether they were verified.
- [ ] Go to the live form and log in. Check that your login has been added in the Login collection with the correct e-service ID, form ID, admin ID and agency ID.
- [ ] Check that you can submit the form and receive responses.
- [ ] Open your network tab and click "Log in to Singpass" on your form. Search for the "logininitial" network call, copy the URL, change the form ID in the "Target" query parameter to a non-existent form ID (or any random string), and visit the modified URL. Then log in to Singpass. You should see an empty "Not Found" page.
- [ ] Click "Log in to Singpass" on your form. In a separate tab, change the authentication type of the form to "Corppass" and reactivate the form. Continue logging in to Singpass. When you are redirected back to the form, you should see a Toastr saying "There was an unexpected error with your login". Check that the `jwtSp` cookie has not been set in your browser.

**Email Mode CorpPass**
- [ ] Create a new form and add CorpPass authentication with an invalid e-service ID. Check that you can activate the form (we don't do e-service ID validation for CorpPass).
- [ ] Add a valid e-service ID. Check that you can activate the form.
- [ ] Preview the form. Check that the UEN 123456789A is automatically populated. Submit the form in preview mode and ensure that you receive the response. You should have the UEN "123456789A" and the UID "ABC".
- [ ] Go to the live form and log in. Check that your login has been added in the Login collection with the correct e-service ID, form ID, admin ID and agency ID.
- [ ] Check that you can submit the form and receive responses.
- [ ] Open your network tab and click "Log in to Corppass" on your form. Search for the "logininitial" network call, copy the URL, change the form ID in the "Target" query parameter to a non-existent form ID (or any random string), and visit the modified URL. Then log in to Corppass. You should see an empty "Not Found" page.
- [ ] Click "Log in to Corppass" on your form. In a separate tab, change the authentication type of the form to "Singpass" and reactivate the form. Continue logging in to Corppass. When you are redirected back to the form, you should see a Toastr saying "There was an unexpected error with your login". Check that the `jwtCp` cookie has not been set in your browser.

**Storage Mode SingPass**
- [ ] Create a new form and add SingPass authentication with an invalid e-service ID. Attempt to activate the form. You should get an error message with a numeric error code (probably 138).
- [ ] Add a valid e-service ID. Check that you can activate the form.
- [ ] Preview the form. Check that the NRIC S1234567A is automatically populated. Submit the form in preview mode.
- [ ] Go to the live form and log in. Check that your login has been added in the Login collection with the correct e-service ID, form ID, admin ID and agency ID.
- [ ] Check that you can submit the form and view responses.
- [ ] Open your network tab and click "Log in to Singpass" on your form. Search for the "logininitial" network call, copy the URL, change the form ID in the "Target" query parameter to a non-existent form ID (or any random string), and visit the modified URL. Then log in to Singpass. You should see an empty "Not Found" page.
- [ ] Click "Log in to Singpass" on your form. In a separate tab, change the authentication type of the form to "Corppass" and reactivate the form. Continue logging in to Singpass. When you are redirected back to the form, you should see a Toastr saying "There was an unexpected error with your login". Check that the `jwtSp` cookie has not been set in your browser.

**Storage Mode CorpPass**
- [ ] Create a new form and add CorpPass authentication with an invalid e-service ID. Check that you can activate the form (we don't do e-service ID validation for CorpPass).
- [ ] Preview the form. Check that the UEN 123456789A is automatically populated. Submit the form in preview mode.
- [ ] Go to the live form and log in. Check that your login has been added in the Login collection with the correct e-service ID, form ID, admin ID and agency ID.
- [ ] Check that you can submit the form and receive responses.
- [ ] Open your network tab and click "Log in to Corppass" on your form. Search for the "logininitial" network call, copy the URL, change the form ID in the "Target" query parameter to a non-existent form ID (or any random string), and visit the modified URL. Then log in to Corppass. You should see an empty "Not Found" page.
- [ ] Click "Log in to Corppass" on your form. In a separate tab, change the authentication type of the form to "Singpass" and reactivate the form. Continue logging in to Corppass. When you are redirected back to the form, you should see a Toastr saying "There was an unexpected error with your login". Check that the `jwtCp` cookie has not been set in your browser.

**Comment by mantariksh** [comment]
**Email Mode CorpPass**
- [ ] Create a new form and add CorpPass authentication with an invalid e-service ID. Check that you can activate the form (we don't do e-service ID validation for CorpPass).
- [ ] Add a valid e-service ID. Check that you can activate the form.
- [ ] Preview the form. Check that the UEN 123456789A is automatically populated. Submit the form in preview mode and ensure that you receive the response. You should have the UEN "123456789A" and the UID "ABC".
- [ ] Go to the live form and log in. Check that your login has been added in the Login collection with the correct e-service ID, form ID, admin ID and agency ID.
- [ ] Check that you can submit the form and receive responses.
- [ ] Open your network tab and click "Log in to Corppass" on your form. Search for the "logininitial" network call, copy the URL, change the form ID in the "Target" query parameter to a non-existent form ID (or any random string), and visit the modified URL. Then log in to Corppass. You should see an empty "Not Found" page.
- [ ] Click "Log in to Corppass" on your form. In a separate tab, change the authentication type of the form to "Singpass" and reactivate the form. Continue logging in to Corppass. When you are redirected back to the form, you should see a Toastr saying "There was an unexpected error with your login". Check that the `jwtCp` cookie has not been set in your browser.

**Comment by mantariksh** [comment]
**Storage Mode SingPass**
- [ ] Create a new form and add SingPass authentication with an invalid e-service ID. Attempt to activate the form. You should get an error message with a numeric error code (probably 138).
- [ ] Add a valid e-service ID. Check that you can activate the form.
- [ ] Preview the form. Check that the NRIC S1234567A is automatically populated. Submit the form in preview mode.
- [ ] Go to the live form and log in. Check that your login has been added in the Login collection with the correct e-service ID, form ID, admin ID and agency ID.
- [ ] Check that you can submit the form and view responses.
- [ ] Open your network tab and click "Log in to Singpass" on your form. Search for the "logininitial" network call, copy the URL, change the form ID in the "Target" query parameter to a non-existent form ID (or any random string), and visit the modified URL. Then log in to Singpass. You should see an empty "Not Found" page.
- [ ] Click "Log in to Singpass" on your form. In a separate tab, change the authentication type of the form to "Corppass" and reactivate the form. Continue logging in to Singpass. When you are redirected back to the form, you should see a Toastr saying "There was an unexpected error with your login". Check that the `jwtSp` cookie has not been set in your browser.

**Comment by mantariksh** [comment]
## Tests

**Storage Mode CorpPass**
- [ ] Create a new form and add CorpPass authentication with an invalid e-service ID. Check that you can activate the form (we don't do e-service ID validation for CorpPass).
- [ ] Preview the form. Check that the UEN 123456789A is automatically populated. Submit the form in preview mode.
- [ ] Go to the live form and log in. Check that your login has been added in the Login collection with the correct e-service ID, form ID, admin ID and agency ID.
- [ ] Check that you can submit the form and receive responses.
- [ ] Open your network tab and click "Log in to Corppass" on your form. Search for the "logininitial" network call, copy the URL, change the form ID in the "Target" query parameter to a non-existent form ID (or any random string), and visit the modified URL. Then log in to Corppass. You should see an empty "Not Found" page.
- [ ] Click "Log in to Corppass" on your form. In a separate tab, change the authentication type of the form to "Singpass" and reactivate the form. Continue logging in to Corppass. When you are redirected back to the form, you should see a Toastr saying "There was an unexpected error with your login". Check that the `jwtCp` cookie has not been set in your browser.

**Comment by mantariksh** [comment]
## Tests
**General intranet run-through**
- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your GSIB inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.
- [ ] Create form with MyInfo fields. Submit successfully

**Review by karrui — APPROVED** [review]

**Pull request merged**
