### PR TITLE
build: release 4.57.0

### PR DESCRIPTION
**Pull request by tshuli**
### New

- feat: add db migration   scripts [`#1072`](https://github.com/opengovsg/FormSG/pull/1072)
- feat: mask cp uid in   autoreply to respondent   [`#1109`](https://github.com/opengovsg/FormSG/pull/1109)

### Improved

- fix: interrupt submission   if field is blank [`#1096`](https://github.com/opengovsg/FormSG/pull/1096)
- refactor: combine email   submission middleware into controller   [`#935`](https://github.com/opengovsg/FormSG/pull/935)
- refactor: migrate dropdown   validator to ts [`#861`](https://github.com/opengovsg/FormSG/pull/861)
- test: mock DNS in webhooks   tests [`#1056`](https://github.com/opengovsg/FormSG/pull/1056)

### Fixes

- fix/travis: wean off   Travis workspaces [`#1067`](https://github.com/opengovsg/FormSG/pull/1067)
- fix/updates: bugs and   refactors after building payments demo [`#1061`](https://github.com/opengovsg/FormSG/pull/1061)

### Dependency updates

- fix: upgrade   angular-translate from 2.18.3 to 2.18.4   [`#1086`](https://github.com/opengovsg/FormSG/pull/1086)
- fix: upgrade sortablejs   from 1.12.0 to 1.13.0   [`#1054`](https://github.com/opengovsg/FormSG/pull/1054)
- fix(deps): bump   @babel/runtime from 7.12.5 to 7.12.13   [`#1098`](https://github.com/opengovsg/FormSG/pull/1098)
- fix(deps): bump   @opengovsg/formsg-sdk from 0.8.2 to 0.8.3   [`#1095`](https://github.com/opengovsg/FormSG/pull/1095)
- fix(deps): bump   @sentry/browser from 5.30.0 to 6.1.0   [`#1094`](https://github.com/opengovsg/FormSG/pull/1094)
- fix(deps): bump aws-sdk   from 2.828.0 to 2.834.0   [`#1059`](https://github.com/opengovsg/FormSG/pull/1059)
- fix(deps): bump aws-sdk   from 2.834.0 to 2.838.0   [`#1092`](https://github.com/opengovsg/FormSG/pull/1092)
- fix(deps): bump ejs from   3.1.5 to 3.1.6 [`#1100`](https://github.com/opengovsg/FormSG/pull/1100)
- fix(deps): bump fp-ts from   2.9.3 to 2.9.4 [`#1075`](https://github.com/opengovsg/FormSG/pull/1075)
- fix(deps): bump helmet   from 4.3.1 to 4.4.1 [`#1042`](https://github.com/opengovsg/FormSG/pull/1042)
- fix(deps): bump neverthrow   from 3.2.0 to 4.0.1 [`#1041`](https://github.com/opengovsg/FormSG/pull/1041)
- fix(deps): bump opossum   from 5.1.2 to 5.1.3 [`#1069`](https://github.com/opengovsg/FormSG/pull/1069)
- chore(deps-dev): bump   @babel/core from 7.12.10 to 7.12.13   [`#1080`](https://github.com/opengovsg/FormSG/pull/1080)
- chore(deps-dev): bump   @babel/plugin-transform-runtime   [`#1089`](https://github.com/opengovsg/FormSG/pull/1089)
- chore(deps-dev): bump   @babel/preset-env from 7.12.11 to 7.12.13   [`#1091`](https://github.com/opengovsg/FormSG/pull/1091)
- chore(deps-dev): bump   @opengovsg/mockpass from 2.6.1 to 2.6.2   [`#1101`](https://github.com/opengovsg/FormSG/pull/1101)
- chore(deps-dev): bump   @types/express from 4.17.9 to 4.17.11   [`#1058`](https://github.com/opengovsg/FormSG/pull/1058)
- chore(deps-dev): bump   @types/mongodb from 3.6.3 to 3.6.5   [`#1093`](https://github.com/opengovsg/FormSG/pull/1093)
- chore(deps-dev): bump   @types/node from 14.14.20 to 14.14.22   [`#1043`](https://github.com/opengovsg/FormSG/pull/1043)
- chore(deps-dev): bump   @typescript-eslint/eslint-plugin   [`#1090`](https://github.com/opengovsg/FormSG/pull/1090)
- chore(deps-dev): bump   core-js from 3.8.2 to 3.8.3   [`#1076`](https://github.com/opengovsg/FormSG/pull/1076)
- chore(deps-dev): bump   csv-parse from 4.15.0 to 4.15.1   [`#1064`](https://github.com/opengovsg/FormSG/pull/1064)
- chore(deps-dev): bump   eslint-config-prettier from 7.1.0 to 7.2.0   [`#1081`](https://github.com/opengovsg/FormSG/pull/1081)
- chore(deps-dev): bump   eslint-plugin-typesafe from 0.4.0 to 0.5.2   [`#1060`](https://github.com/opengovsg/FormSG/pull/1060)
- chore(deps-dev): bump   husky from 4.3.7 to 4.3.8   [`#1033`](https://github.com/opengovsg/FormSG/pull/1033)
- chore(deps-dev): bump   jasmine from 3.6.3 to 3.6.4   [`#1065`](https://github.com/opengovsg/FormSG/pull/1065)
- chore(deps-dev): bump   mongodb-memory-server-core from 6.9.2 to 6.9.3   [`#1063`](https://github.com/opengovsg/FormSG/pull/1063)
- chore(deps-dev): bump   sinon from 9.2.3 to 9.2.4   [`#1057`](https://github.com/opengovsg/FormSG/pull/1057)
- chore(deps-dev): bump   supertest from 6.0.1 to 6.1.3   [`#1062`](https://github.com/opengovsg/FormSG/pull/1062)
- chore(deps-dev): bump   ts-jest from 26.4.4 to 26.5.0   [`#1099`](https://github.com/opengovsg/FormSG/pull/1099)

### CODE REVIEW

**Comment by tshuli** [comment]
### Tests

**Deprecate myinfo fields**

- [ ] Home number, mailing address, billing address, education level, school name and graduation year are missing from MyInfo options in Build tab
- [ ] Existing forms with these fields can still be submitted
- [ ] Existing forms with these fields can still be edited. The deprecated fields can be edited, reordered and deleted.

**Comment by tshuli** [comment]
**Interrupt submission if field is blank**

- [ ] Submit a form with image field, statement field and table field with optional dropdown column and optional text field column
- [ ] Submit a form with the above fields hidden by logic

**Comment by tshuli** [comment]
**combine email submission middleware into controller**


- [ ] Submitting email mode form in preview mode works
- [ ] Submitting storage mode form in preview mode works
- [ ] Attempt to access a form which has been made private and check that you see the correct inactive form message
- [ ] Attempt to access a form which has been archived and check that you see the correct "Oops! We can't find the page you're looking for." page.
- [ ] Attempt to submit a form with captcha via API and ensure that you get a HTTP 400 response.
- [ ] Attempt to submit a MyInfo form where you have changed one of the prefilled fields and check that you get a 401
- [ ] Attempt to submit a SingPass form (with Captcha disabled) via API without logging into SingPass and check that you get a 401
- [ ] Submit a form with all MyInfo fields
- [ ] Submit a form with two email fields, one with email confirmation and one without, and ensure that you receive the email confirmation at the correct email

**Comment by tshuli** [comment]
**Migrate dropdown validator to typescript**

- [ ] Create two dropdown fields. Hide one of them behind logic.
- [ ] Check that validation on both visible and hidden dropdown fields work when submitting programatically
- Response is rejected if it is not one of the dropdown options
- [ ] Create Myinfo field with dropdown (e.g. nationality). Check that form can be submitted normally.

**Comment by tshuli** [comment]
**IE11 intranet general run-through**
- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your intranet inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments for individual fields can be downloaded from Data tab in storage mode.
- [ ] Attachment ZIP for submission can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
