### PR TITLE
build: release v5.3.0

### PR DESCRIPTION
**Pull request by karrui**
# Release v5.3.0

## Features
- feat: create new PATCH endpoint for updating form settings [`#1383`](https://github.com/opengovsg/FormSG/pull/1383)
- feat: rename /admin/form endpoint to /admin/forms, correct dir structure of /api/v3 routes [`#1425`](https://github.com/opengovsg/FormSG/pull/1425)
- feat: show error Toastr for intranet users on SPCP forms [`#1397`](https://github.com/opengovsg/FormSG/pull/1397)
- feat: switch to CorpPass Cloud for test form [`#1392`](https://github.com/opengovsg/FormSG/pull/1392)

## Improvements
- fix: add rows attr to email confirmation email body textarea [`941b6bf`](https://github.com/opengovsg/FormSG/commit/941b6bfb1f847fa8a0fb532977acb09aef87bbe2)
- refactor: convert mail and sms services into neverthrown variants [`#1344`](https://github.com/opengovsg/FormSG/pull/1344)
- refactor: Add handler for encrypted submissions controller [`#1362`](https://github.com/opengovsg/FormSG/pull/1362)
- refactor: convert analytics module to TypeScript/fp-ts, remove statistics animation on landing page [`#1361`](https://github.com/opengovsg/FormSG/pull/1361)
- refactor: migrate yesno validator to typescript, with tests [`#1372`](https://github.com/opengovsg/FormSG/pull/1372)
- refactor: rename type to AnalyticStatsDto [`#1393`](https://github.com/opengovsg/FormSG/pull/1393)
- refactor: return custom HashingError from utils when bcrypt fails [`#1426`](https://github.com/opengovsg/FormSG/pull/1426)
- build: automate dependency upgrades using mergify [`#1424`](https://github.com/opengovsg/FormSG/pull/1424)
- chore: change verified sms modal copy [`#1403`](https://github.com/opengovsg/FormSG/pull/1403)

## Dependency upgrades
- fix(deps): bump @sentry/integrations from 6.2.2 to 6.2.3 [`#1419`](https://github.com/opengovsg/FormSG/pull/1419)
- fix(deps): bump aws-sdk from 2.863.0 to 2.864.0 [`#1388`](https://github.com/opengovsg/FormSG/pull/1388)
- fix(deps): bump aws-sdk from 2.864.0 to 2.866.0 [`#1404`](https://github.com/opengovsg/FormSG/pull/1404)
- fix(deps): bump celebrate from 13.0.4 to 14.0.0 [`#1423`](https://github.com/opengovsg/FormSG/pull/1423)
- fix(deps): bump convict from 6.0.0 to 6.0.1 [`#1395`](https://github.com/opengovsg/FormSG/pull/1395)
- fix(deps): bump libphonenumber-js from 1.9.13 to 1.9.14 [`#1417`](https://github.com/opengovsg/FormSG/pull/1417)
- fix(deps): bump neverthrow from 4.1.1 to 4.2.0 [`#1379`](https://github.com/opengovsg/FormSG/pull/1379)
- fix(deps): bump neverthrow from 4.2.0 to 4.2.1 [`#1416`](https://github.com/opengovsg/FormSG/pull/1416)
- fix(deps): bump opossum from 5.1.3 to 6.0.0 [`#1412`](https://github.com/opengovsg/FormSG/pull/1412)
- fix(deps): bump twilio from 3.57.0 to 3.58.0 [`#1394`](https://github.com/opengovsg/FormSG/pull/1394)
- chore(deps-dev): bump @opengovsg/mockpass from 2.6.6 to 2.6.7 [`#1387`](https://github.com/opengovsg/FormSG/pull/1387)
- chore(deps-dev): bump @types/express-serve-static-core [`#1390`](https://github.com/opengovsg/FormSG/pull/1390)
- chore(deps-dev): bump @types/jest from 26.0.20 to 26.0.21 [`#1402`](https://github.com/opengovsg/FormSG/pull/1402)
- chore(deps-dev): bump @types/mongodb from 3.6.9 to 3.6.10 [`#1377`](https://github.com/opengovsg/FormSG/pull/1377)
- chore(deps-dev): bump @types/node from 14.14.34 to 14.14.35 [`#1378`](https://github.com/opengovsg/FormSG/pull/1378)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#1380`](https://github.com/opengovsg/FormSG/pull/1380)
- chore(deps-dev): bump @typescript-eslint/parser from 4.17.0 to 4.18.0 [`#1386`](https://github.com/opengovsg/FormSG/pull/1386)
- chore(deps-dev): bump eslint-plugin-jest from 24.3.1 to 24.3.2 [`#1400`](https://github.com/opengovsg/FormSG/pull/1400)
- chore(deps-dev): bump jasmine from 3.6.4 to 3.7.0 [`#1413`](https://github.com/opengovsg/FormSG/pull/1413)
- chore(deps-dev): bump jasmine-core from 3.6.0 to 3.7.1 [`#1415`](https://github.com/opengovsg/FormSG/pull/1415)
- chore(deps-dev): bump ts-jest from 26.5.3 to 26.5.4 [`#1399`](https://github.com/opengovsg/FormSG/pull/1399)
- chore(deps): update spcp-auth-client, mockpass [`#1406`](https://github.com/opengovsg/FormSG/pull/1406)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests

### PATCH Settings
- [ ] Update form settings for an **email** mode form. All possible updates should work:
  - [ ] Activate/deactivate form
  - [ ] Toggle submission limit, change limit number
  - [ ] Set inactive form message
  - [ ] Authentication types,  esrvcId, etc.
  - [ ] Toggle on/off captcha
  - [ ] Update form name
  - [ ] Update emails
- [ ] Update form settings for a **storage** mode form. All possible updates should work:
  - [ ] Activate/deactivate form
  - [ ] Toggle submission limit, change limit number
  - [ ] Set inactive form message
  - [ ] Authentication types,  esrvcId, etc.
  - [ ] Toggle on/off captcha
  - [ ] Update form name
  - [ ] Update webhook URL
- [ ] For any mode form, try with random keys to update settings. Should return 400 error

**Comment by karrui** [comment]
## GSIB/Intranet/IE11 Tests

### Intranet IPs Toast
- [x] List of intranet IPs has been SFTPed into production, and `INTRANET_IP_LIST_PATH` env var has been added in production
- [ ] SingPass, CorpPass and MyInfo forms on intranet show the error Toastr
- [ ] Non-authenticated forms on intranet do not show the error Toastr
- [ ] SingPass, CorpPass, MyInfo and non-authenticated forms on internet do not show the error Toastr

## General runthrough
- [ ] Create email mode form with all fields and custom start/end page. Activate and submit form. Check that you can receive responses in your intranet inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields and custom start/end page. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments for individual fields can be downloaded from Data tab in storage mode.
- [ ] Attachment ZIP for submission can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Comment by karrui** [comment]
## Tests
### Corppass cert change
- [ ] Create, activate and submit a new CorpPass form. Should be able to log in and submit successfully.
- [ ] Log out of this new CorpPass form and deactivate it. Change the `CP_CLOUD_FORM_ID` env var to the ID of the new CorpPass form. Should still be able to activate the form, but should see "There was an unexpected error with your log in" after attempting to log in using CorpPass.
- [ ] Delete the `CP_CLOUD_CERT_PATH`, `CP_CLOUD_ENDPOINT` and `CP_CLOUD_FORM_ID` env vars from staging. You should now be able to log in and submit the new CorpPass form again.

**Comment by karrui** [comment]
## Tests
### UI/Copy changes
- [ ] In admin build tab, go to email field > email confirmation > email body text area. The textarea should be larger than 2 rows:

**Comment by karrui** [comment]
## Tests
### neverthrown mail and sms services

**For mail service**
- [ ] Create an email form, and add an email field with email verification and confirmation.
  1. Enter your email into the email form and verify your email. The email should be sent to the given email and the OTP should validate successfully.
  2. Submit the form. You (as form admin) should receive the usual form submission email with the correct answers. You (as the form filler) should also receive an acknowledgement email. 

**For sms service**
- [ ] Create verified sms field. Go to form and check if sms is received
  - [ ] Give invalid OTP. Correct invalid otp error should be shown.
  - [ ] Turn off data in Chrome console and submit OTP. Correct unknown error should be shown.
  - [ ] Enter correct OTP. Should be verified correctly.
- [ ] Update emergency contact number
  - [ ] Give invalid OTP. Correct invalid otp error should be shown.
  - [ ] Turn off data in Chrome console and submit OTP. Correct unknown error should be shown.
  - [ ] Enter correct OTP. Should be verified correctly.

**Comment by karrui** [comment]
## Tests
### encrypt submission middleware merge
- [ ] Submit an storage mode form submission. Should submit with no errors. 
- [ ] Should also be able to successfully retrieve the response of the above submission

**Comment by karrui** [comment]
## Tests
### Analytics endpoint refactor
- [ ] On the landing page, all statistics should show correctly.

**Comment by karrui** [comment]
## Tests
### YesNo field refactor
- [ ] Create two required yesno fields. Hide one of them behind logic. Check that normal submission using frontend succeeds for both visible and hidden field.
- [ ] Check that following validation works when submitting programatically
- Answer cannot be empty for required field
- Invalid answer (e.g. 'abc') is rejected

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
