### PR TITLE
build: Release 5.63.0

### PR DESCRIPTION
**Pull request by tshuli**
## Changelog

**New**

- chore: expose public jwks endpoint [`#4071`](https://github.com/opengovsg/FormSG/pull/4071)
- feat: store prefill in frontend for spcp/myinfo forms, enable prefill for SGID forms [`#3920`](https://github.com/opengovsg/FormSG/pull/3920)
- feat: add end-page uri scheme validation [`#3991`](https://github.com/opengovsg/FormSG/pull/3991)
- feat: enable datadog APM  [`#3908`](https://github.com/opengovsg/FormSG/pull/3908)
- dev: enable eb deploy for staging-alt2 branch [`#4012`](https://github.com/opengovsg/FormSG/pull/4012)

**Dependency Updates**

- chore(deps-dev): bump eslint-plugin-jest from 26.2.2 to 26.5.3 [`#4058`](https://github.com/opengovsg/FormSG/pull/4058)
- chore(deps-dev): bump @babel/plugin-transform-runtime [`#4060`](https://github.com/opengovsg/FormSG/pull/4060)
- fix(deps): bump hot-shots from 9.0.0 to 9.1.0 [`#4066`](https://github.com/opengovsg/FormSG/pull/4066)
- chore(deps-dev): bump eslint-plugin-prettier in /shared [`#4067`](https://github.com/opengovsg/FormSG/pull/4067)
- fix(deps): bump type-fest from 2.14.0 to 2.15.1 in /shared [`#4068`](https://github.com/opengovsg/FormSG/pull/4068)
- fix(deps): bump nocache from 3.0.3 to 3.0.4 [`#4059`](https://github.com/opengovsg/FormSG/pull/4059)
- chore(deps-dev): bump @babel/core from 7.17.12 to 7.18.5 [`#4052`](https://github.com/opengovsg/FormSG/pull/4052)
- chore(deps-dev): bump core-js from 3.22.5 to 3.23.3 [`#4053`](https://github.com/opengovsg/FormSG/pull/4053)
- chore(deps-dev): bump eslint-plugin-prettier in /shared [`#4054`](https://github.com/opengovsg/FormSG/pull/4054)
- fix(deps): bump helmet from 5.0.2 to 5.1.0 [`#4048`](https://github.com/opengovsg/FormSG/pull/4048)
- chore(deps-dev): bump @types/validator from 13.7.2 to 13.7.3 [`#4049`](https://github.com/opengovsg/FormSG/pull/4049)
- fix(deps): bump type-fest from 2.13.1 to 2.14.0 in /shared [`#4050`](https://github.com/opengovsg/FormSG/pull/4050)
- fix(deps): bump @sentry/browser from 6.19.7 to 7.2.0 [`#4017`](https://github.com/opengovsg/FormSG/pull/4017)
- fix(deps): bump got from 11.8.3 to 11.8.5 [`#4026`](https://github.com/opengovsg/FormSG/pull/4026)
- fix(deps): bump libphonenumber-js from 1.10.6 to 1.10.7 in /shared [`#4023`](https://github.com/opengovsg/FormSG/pull/4023)
- chore(deps-dev): bump @types/node from 17.0.33 to 18.0.0 [`#4015`](https://github.com/opengovsg/FormSG/pull/4015)
- chore(deps-dev): bump @babel/plugin-transform-runtime [`#4013`](https://github.com/opengovsg/FormSG/pull/4013)

**Deployment Steps**
- SSH into prod and load the public jwks in `/certs/singpass/prod_spoidc_jwks_public.json`
- Add the `SP_OIDC_RP_JWKS_PUBLIC_PATH` env var

## Post-release check
- [ ] Check that `/singpass/.well-known/jwks.json` endpoint should return the public jwks

## Notes
- fix(deps): bump @opengovsg/sgid-client from 0.0.12 to 1.0.3 [`#3905`](https://github.com/opengovsg/FormSG/pull/3905) has been reverted as it broke SGID integration

```


error.at.0 | stack 0 RPError: nonce mismatch, expected undefined, got: w2xNz1f9QQhTatWCu8fzeTdjCTJLLf45gPbsTLyXMA0
-- | --
error.at.1 | stack 1 at Client.validateIdToken (/opt/formsg/node_modules/@opengovsg/sgid-client/node_modules/openid-client/lib/client.js:805:13)
error.at.2 | stack 2 at processTicksAndRejections (internal/process/task_queues.js:95:5)
error.at.3 | stack 3 at async Client.callback (/opt/formsg/node_modules/@opengovsg/sgid-client/node_modules/openid-client/lib/client.js:486:7)
error.jwt | eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2FwaS5pZC5nb3Yuc2ciLCJzdWIiOiJ2NDl2ZXZtMDJjMHEzdGFhYTJobiIsImF1ZCI6IjE2MzY3YjRkN2ViZGRkOGU3ZjhlZWE5OTlmMGVkZWJlIiwibm9uY2UiOiJ3MnhOejFmOVFRaFRhdFdDdThmemVUZGpDVEpMTGY0NWdQYnNUTHlYTUEwIiwiZXhwIjoxNjU2NzUyNjAwLCJpYXQiOjE2NTY3NTIzMDB9.rOQJ64-sIg1AFKKF_1lq5BOyNAJ-SxJAcqQyLKmZVoj2l2A0TIPIQ9VFk0-gu1CncD-SFTKiOO8m3WqxnLRxREs91F_ATrikhGh-JDx6xvM_j50ZsQhkz1ZSIg1-SvbreoZ4_TkKcTI4dpfjCHPpqhrOX53CkBmDeNJAnq7l3neM81WliLjRmgDpDeGDUSb6vVzuGL_gFPW4UhuVvIvc-EqgQ-SCLxleKYB70efakkxOh1hu2KljcUZM2CiMq12mH104-no4-1hs2nHhaxHz2f00ugphfCkH7whWPnrMJSOKAnHcxyHp_wePs8lQhWKEJ9-LrTgNvMPTBxFjrxxTcw
error.message | nonce mismatch, expected undefined, got: w2xNz1f9QQhTatWCu8fzeTdjCTJLLf45gPbsTLyXMA0
error.name | RPError
label | sgid/sgid.service
level | error
message | Failed to retrieve access token from sgID
meta.action | token
meta.code | HUVLKzb4NwvpQn9wfDnVFLPioB3LJP
timestamp | 2022-07-02T08:58:20.941Z

```
-

### CODE REVIEW

**Comment by tshuli** [comment]
## Tests ##

**expose public jwks endpoint**
@wanlingt 
- [x] `/singpass/.well-known/jwks.json` endpoint should return the public jwks

**Comment by tshuli** [comment]
**store prefill in frontend for spcp/myinfo forms, enable prefill for SGID forms**
@tshuli 

- [x] Create Singpass form. Open in public view with prefilled query parameters. Login to Singpass. On redirect back to the form, check that the prefill displays correctly. Check that `storedQuery` has been deleted from `sessionStorage`
- [x] Logout. With the prefilled query parameters still in the url, click login again. Do not complete the Singpass authentication flow. Return to the form and enter a new set of prefilled query parameters. Login using this new set of query parameters and complete the authentication flow. Check that on redirect back to the form, the correct prefill is displayed and `storedQuery` has been deleted from `sessionStorage`
- [x] Repeat above for CP, MyInfo and SGID forms
- [x] Create normal prefill form and check that it works normally

**Comment by tshuli** [comment]
**add end-page uri scheme validation**
@karrui 

- [x] Change the end-page's thank you button link to a scheme that's not http or https. Submit the HTTP request. Validation should fail.
- [x] Change the end-page's thank you button link to a scheme that's http or https. Submit the HTTP request. Request should succeed.

side note @wanlingt: it just returns 400 (without error message) when requesting through Insomnia directly, is that expected?

**Review by timotheeg — APPROVED** [review]

**Comment by wanlingt** [comment]
> **add end-page uri scheme validation** @karrui
> 
> * [x]  Change the end-page's thank you button link to a scheme that's not http or https. Submit the HTTP request. Validation should fail.
> * [x]  Change the end-page's thank you button link to a scheme that's http or https. Submit the HTTP request. Request should succeed.
> 
> side note @wanlingt: it just returns 400 (without error message) when requesting through Insomnia directly, is that expected?

I'm not sure about Insomnia but I tested this using Terminal. Should get the following for the failed-validation test:
(will update the PR with a more descriptive test)
Screenshot 2022-07-04 at 10 11 01 AM

**Pull request merged**
