### PR TITLE
feat: Release 4.33.0

### PR DESCRIPTION
**Pull request by mantariksh**
## New
- Emergency contact for admins
- Bulk download of storage mode attachments
- Share form secret keys across browser tabs
- Mailto link to share secret key with colleagues after form activation

## Improved
- Retries for email failures
- Various backend modules migrated to TypeScript
    - Webhooks service
    - All utils
- Standardised logging format
- Use of Express Router for modules
- Better logging for critical bounces

## Misc
- Introduce test coverage thresholds
- Various dependency version bumps
    - `axios 0.19.2 => 0.20.0`
    - `eslint 6.8.0 => 7.7.0`
    - `http-status-codes 1.4.0 => 2.1.2`
    - `opossum 5.0.0 => 5.0.1`
    - `sinon 6.3.5 => 9.0.3`
    - `validator 11.1.0 => 13.1.1`
    - `@types/helmet 0.0.47 => 0.0.48`
    - `@types/mongoose 5.7.25 => 5.7.36`

### CODE REVIEW

**Comment by mantariksh** [comment]
@mantariksh
### Secret key broadcast
- [ ] Open two tabs and navigate to the View Responses page of a storage mode form. Upload a secret key to one form to unlock. The other tab should be unlocked automatically.
- [ ] Unlock responses on one form. Open a second tab and go to view responses. The tab should already be unlocked.

### Attachment bulk download
- [ ] Downloading zip works correctly for submission with multiple attachments up to 20MB.
- [ ] Can download attachments for multiple consecutive submissions.

### Logging
- [ ] Add CloudWatch filter and alarm for `sendNodeMail` errors.

**Comment by mantariksh** [comment]
@shuli-ogp
### Emergency contact
- [ ] Emergency contact can be entered and verified.
- [ ] Emergency contact is correctly saved when user logs out and in again.
- [ ] Emergency contact can be updated.
- [ ] Play around with the UI for the avatar and dropdown, make sure there are no issues.

**Comment by mantariksh** [comment]
@karrui
### Secret key mailto
- [ ] Activating storage mode form shows the Toastr as per the screenshot. Toastr lasts for 10 seconds. Clicking on the link opens an email with the form title, URL and secret key, also as per the screenshot.

### Critical bounces
- [ ] Create a critical bounce by submitting a form where all email recipients are invalid. In CloudWatch, filter for `message.type = 'CRITICAL BOUNCE'`. Under `message.bounceInfo` in the log message, you should see the bounce type, subtype and some information regarding each bounced recipient, including a `diagnosticCode`.

**Comment by mantariksh** [comment]
@arshadali172
- [ ] General run through on intranet and IE11.
- [ ] Bulk download for storage mode attachments works on IE11.
- [ ] Emergency contact works on IE11.

**Comment by karrui** [comment]
Remember to add indices on Mongo Atlas for the new `adminverification` collection prior to release:

```
AdminVerificationSchema.index({ expireAt: 1 }, { expireAfterSeconds: 0 })
```

**Review by karrui — APPROVED** [review]

**Pull request merged**
