### PR TITLE
refactor(frontend-api): duplicate frontend client endpoints to new /api/v3 router

### LINKED ISSUE #1564: [API] Duplicate /frontend related endpoints to their new /api counterparts
This issue tracks the straight duplication of `/frontend` related endpoints to their `/api` rooted endpoints to follow a RESTful hierarchy.

The old endpoint should not be deleted for backwards compatibility (at least for a few weeks after the new endpoint has been released).

The current to new mapping is shown below:

\# | Existing endpoints | New endpoints<br>(note that all routes are prefixed with /api/v3) | Description
-- | -- | --|--
1 | GET /frontend/datalayer | GET /client/analytics/google | provide google analytics related variables to client
2 | GET /frontend/environment | GET /client/environment | provide environment variables to client
3 | GET /frontend/features | GET /client/features | provide enabled features to client
4 | GET /frontend/redirect | GET /client/redirect | redirect endpoint

### PR DESCRIPTION
**Pull request by orbitalsqwib**
## Problem

Update current miscellaneous endpoints to their /api rooted endpoints to follow a RESTful hierarchy.

Closes #1564

## Solution

**Features**:

- duplicate frontend client endpoints functionality and update them to use the new api v3 routes
- update v3 router to use new endpoints
- update frontend api calls to use new endpoints

## Tests

- [ ] Check that feature requests return 200 on the /api/v3/client/features on landing page
- [ ] Check that form redirects work by accessing a form from a form share link (/api/v3/client/redirect)
- [ ] Test `/api/v3/client/analytics/google`
- [ ] Test `/api/v3/client/environment`

### CODE REVIEW

**Comment by karrui** [comment]
this may conflict with https://github.com/opengovsg/FormSG/pull/1405, coordinate accordingly :P

**Comment by karrui** [comment]
I'll let @tshuli review this one first

**Comment by tshuli** [comment]
As `modules/frontend/frontend.server.routes.ts` has been updated, could I trouble you to duplicate using the updated version instead? Including `google-analytics.factory.ts` and the controller as well

No issue if you want to rename it to `ClientRouter` instead

**Review by tshuli — APPROVED** [review]
lgtm, unless @karrui has other comments

**Review by karrui — APPROVED** [review]
lgtm, remember to check that all the calls to the new endpoints work

**Pull request merged**
