### PR TITLE
fix: dropdown truncation in table

### PR DESCRIPTION
**Pull request by kevin9foong**
## Problem
table fields don’t show full response especially if there are many columns which prevents mrf respondents from using table fields effectively in MRF forms

Closes FRM-1843

## Solution
Fix: remove truncation behavior of the dropdown fields

**Breaking Changes** 

- No - this PR is backwards compatible  

## Before & After Screenshots
See linear issue.

### CODE REVIEW

**Comment by kevin9foong** [comment]
Done some preliminary testing to ensure everything works well, does not disrupt existing ui. Will double check with chromatic stories.

**Review by KenLSM — APPROVED** [review]
Mainly CSS, no issue with proposed change. Double check on the chromatic visuals!

**Comment by kevin9foong** [comment]
some single select dropdowns are now becoming >1 line when they should still be. will look into this later on

**Comment by kevin9foong** [comment]
Closing due to [discussion](https://opengovproducts.slack.com/archives/CKHLS3W3X/p1726471447165619?thread_ts=1725939939.696009&cid=CKHLS3W3X)

**Pull request closed without merging**
