### PR TITLE
build: release v5.14.0

### PR DESCRIPTION
**Pull request by mantariksh**
## New
- feat(feature-manager): remove GoogleAnalytics feature [`#2127`](https://github.com/opengovsg/FormSG/pull/2127)
- feat(feature-manager): remove Sentry from feature manager [`#2130`](https://github.com/opengovsg/FormSG/pull/2130)
- feat(feature-manager): remove feature toggles from frontend [`#2118`](https://github.com/opengovsg/FormSG/pull/2118)
- feat(feature-manager): tear out AggregateStats feature [`#2120`](https://github.com/opengovsg/FormSG/pull/2120)
- feat: store only user ID in session [`#1849`](https://github.com/opengovsg/FormSG/pull/1849)

## Improved
- refactor(encrypt-submission): introduce IncomingEncryptSubmission [`#1987`](https://github.com/opengovsg/FormSG/pull/1987)
- refactor(angularjs): remove angular-moment [`#2154`](https://github.com/opengovsg/FormSG/pull/2154)
- build: mute Localstack logs [`#2146`](https://github.com/opengovsg/FormSG/pull/2146)
- feat(feature-manager): hardcode /features API response [`#2149`](https://github.com/opengovsg/FormSG/pull/2149)
- docs(feature-manager): update docs to reflect FeatureManager removal [`#2145`](https://github.com/opengovsg/FormSG/pull/2145)
- fix(submissions): remove captcha dependence on feature toggle [`#2143`](https://github.com/opengovsg/FormSG/pull/2143)
- test(adminsubmissionservice): unit tests for download methods [`#2129`](https://github.com/opengovsg/FormSG/pull/2129)
- feat(feature-manager): remove Intranet from feature manager [`#2131`](https://github.com/opengovsg/FormSG/pull/2131)
- refactor(submissions.client.factory): refactored download methods [`#2054`](https://github.com/opengovsg/FormSG/pull/2054)
- refactor(auth.client.service): refactor to Typescript [`#2132`](https://github.com/opengovsg/FormSG/pull/2132)
- test: remove basic and full e2e test separation [`#2128`](https://github.com/opengovsg/FormSG/pull/2128)
- fix(auth): make login emails case-insensitive [`#2125`](https://github.com/opengovsg/FormSG/pull/2125)
- refactor: formFactoryClientService [`#2117`](https://github.com/opengovsg/FormSG/pull/2117)
- test: loosen URL check in e2e test [`#2119`](https://github.com/opengovsg/FormSG/pull/2119)
- chore: remove blocking of SP and RP admin updates [`#2114`](https://github.com/opengovsg/FormSG/pull/2114)
- refactor(auth.client): (1) extract email validation and send login otp flow to Typescript [`#2084`](https://github.com/opengovsg/FormSG/pull/2084)
- fix: return storage mode submission version when when retrieving from server [`#2112`](https://github.com/opengovsg/FormSG/pull/2112)
- refactor: replace $resource in angularjs form-api.client.factory.js with typescript FormService  [`#1947`](https://github.com/opengovsg/FormSG/pull/1947)
- refactor(ts-migration): ndjsonstream and process-decrypted-content [`#2111`](https://github.com/opengovsg/FormSG/pull/2111)
- refactor(auth.client.service): refactor to Typescript [`#2132`](https://github.com/opengovsg/FormSG/pull/2132)

### App dependencies
- fix(deps): bump @opengovsg/spcp-auth-client from 1.4.7 to 1.4.8 [`#2164`](https://github.com/opengovsg/FormSG/pull/2164)
- fix(deps): bump @sentry/integrations from 6.6.0 to 6.7.0 [`#2163`](https://github.com/opengovsg/FormSG/pull/2163)
- fix(deps): bump @sentry/browser from 6.6.0 to 6.7.0 [`#2160`](https://github.com/opengovsg/FormSG/pull/2160)
- fix(deps): bump zod from 3.1.0 to 3.2.0 [`#2151`](https://github.com/opengovsg/FormSG/pull/2151)
- fix(deps): bump aws-sdk from 2.925.0 to 2.927.0 [`#2153`](https://github.com/opengovsg/FormSG/pull/2153)
- fix(deps): bump aws-sdk from 2.924.0 to 2.925.0 [`#2136`](https://github.com/opengovsg/FormSG/pull/2136)
- fix(deps): bump @sentry/browser from 6.5.1 to 6.6.0 [`#2135`](https://github.com/opengovsg/FormSG/pull/2135)
- fix(deps): bump @babel/runtime from 7.14.0 to 7.14.5 [`#2139`](https://github.com/opengovsg/FormSG/pull/2139)
- fix(deps): bump @sentry/integrations from 6.5.1 to 6.6.0 [`#2137`](https://github.com/opengovsg/FormSG/pull/2137)
- fix(deps): bump aws-sdk from 2.923.0 to 2.924.0 [`#2123`](https://github.com/opengovsg/FormSG/pull/2123)
- fix(deps): bump zod from 3.0.0 to 3.1.0 [`#2107`](https://github.com/opengovsg/FormSG/pull/2107)
- fix(deps): bump aws-sdk from 2.922.0 to 2.923.0 [`#2105`](https://github.com/opengovsg/FormSG/pull/2105)

### Dev dependencies
- chore(deps-dev): bump @typescript-eslint/parser from 4.26.1 to 4.27.0 [`#2162`](https://github.com/opengovsg/FormSG/pull/2162)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#2161`](https://github.com/opengovsg/FormSG/pull/2161)
- chore(deps-dev): bump @types/mongodb from 3.6.17 to 3.6.18 [`#2152`](https://github.com/opengovsg/FormSG/pull/2152)
- chore(deps-dev): bump htmlhint from 0.14.2 to 0.15.1 [`#2150`](https://github.com/opengovsg/FormSG/pull/2150)
- chore(deps-dev): bump @babel/plugin-transform-runtime [`#2141`](https://github.com/opengovsg/FormSG/pull/2141)
- chore(deps-dev): bump @babel/preset-env from 7.14.4 to 7.14.5 [`#2140`](https://github.com/opengovsg/FormSG/pull/2140)
- chore(deps-dev): bump @babel/core from 7.14.3 to 7.14.5 [`#2138`](https://github.com/opengovsg/FormSG/pull/2138)
- chore(deps-dev): bump csv-parse from 4.15.4 to 4.16.0 [`#2124`](https://github.com/opengovsg/FormSG/pull/2124)
- chore(deps-dev): bump @types/validator from 13.1.3 to 13.1.4 [`#2122`](https://github.com/opengovsg/FormSG/pull/2122)
- chore(deps-dev): bump @types/node from 14.17.2 to 14.17.3 [`#2108`](https://github.com/opengovsg/FormSG/pull/2108)
- chore(deps-dev): bump ts-essentials from 7.0.1 to 7.0.2 [`#2110`](https://github.com/opengovsg/FormSG/pull/2110)
- chore(deps-dev): bump @types/express-rate-limit from 5.1.1 to 5.1.2 [`#2109`](https://github.com/opengovsg/FormSG/pull/2109)

### CODE REVIEW

**Comment by mantariksh** [comment]
## Tests
**Webhook attachments**
- [ ] Create a webhook server which decrypts and prints the content of attachments. Set the responses such that it returns a non-200 status code for the first request, and subsequently returns 200. Create a storage mode form with attachments and enable retries. Submit a form with a text file for an attachment, and check that the attachment is received and decrypted correctly for both the initial attempt and the retry.

**Comment by mantariksh** [comment]
## Tests
**UEN field**
Create a UEN field and check that the following UENs are **valid**:
- [ ] 01234567A
- [ ] 012345678A
- [ ] T01LP1234Z
- [ ] S01LP1234Z
- [ ] R01LP1234Z

Check that the following UENs are **invalid**:
- [ ] B1234567A
- [ ] 012345678
- [ ] 0123456789
- [ ] A01LP1234Z
- [ ] S01AA1234Z
- [ ] RS1LP1234Z
- [ ] R010P1234Z
- [ ] R01LPL234Z
- [ ] R01LP12345

Submit the following UEN **by API** and check that the backend invalidates it:
- [ ] R01LP12345

**Comment by mantariksh** [comment]
## Tests
**Admin form endpoint**
- [ ] Access admin form. In chrome network tab, should call new /api/v3 endpoint.

**Comment by mantariksh** [comment]
## Tests
**IncomingEncryptSubmission**
Do the following tests **with the network tab open** so you can copy the request body for testing.

- [ ] Duplicate [this form](https://staging.form.gov.sg/60bda996c76a3c0011a314ba/use-template). Submit with all optional fields left empty. No errors should occur.
- [ ] Use the same form and fill everything up. No errors should occur. You should get an auto-reply email.
- [ ] Go to the network tab and copy the request as cURL. paste in terminal, modify the responses field by setting the email field to be a non-email. Should fail and tell you that there's something wrong with the submission
- [ ] Paste the same request you copied earlier into the terminal, modify the responses array by deleting one element. Should fail and tell you that the form has been updated.
- [ ] I'm sorry but you'll have to repeat the above 4 again, but this time in the preview page.
- [ ] Decrypt responses and ensure that none were lost.

**Comment by mantariksh** [comment]
## Tests
**Remove angular-moment**
## Manual tests
- [ ] Modify a form and check that the "last modified" under the form title in the admin dashboard is formatted the same way as in production
- [ ] Check that the "last modified" date for forms in the form dashboard is formatted the same way as in production
- [ ] Storage mode CSV download works correctly
- [ ] Formatting of submission date in end page (page after submitting form) works correctly

**Comment by mantariksh** [comment]
## Tests
**Frontend submissions factory**
First create a storage mode form with an attachment field and publish it. Go to the form and submit it >1 times with attachment and a few times without.
- [ ] Go to the admin panel and unlock the form. Click on export and attempt both actions. This should succeed and the csv should contain the correct # of responses. 
- [ ] Click into a single response (with data) then select download as zip. The download should succeed. 
- [ ] Click into a single response (with data) and click on the attachment. The download should succeed

**Comment by mantariksh** [comment]
## Tests
**Frontend auth service**
- [ ] Reach verify OTP flow. Invalid OTP should be rejected. Valid OTP should succeed
- [ ] On successful log in, the user object should be stored in localStorage
- [ ] Chrome network tab. Open dropdown avatar. The call should succeed and return the current user. Localstorage should also be replaced (or unchanged)
- [ ] Logout from the app. The user item from localStorage should be cleared and you should be kicked out to the login page.
- [ ] Open avatar dropdown. Should load current user successfully.
- [ ] Open edit contact number modal. Should load current user successfully.
- [ ] Look at Google Analytics when you have downloaded a storage mode form responses. The label should be `${params.formTitle} (${params.formId}), ${<your email>}`
- [ ] In your admin form, go to the share form page. There should be a "use go link" lightbulb tooltip thingy
- [ ] Should be able to successfully view admin form page (of your form) when logged in
- [ ] Should be able to successfully view the edit form field modal successfully when logged in
- [ ] Should be able to view form dashboard successfully when logged in
- [ ] Should be able to view form settings successfully when logged in
- [ ] Should be able to view examples page successfully when logged in
- [ ] Should be able to view billing page successfully when logged in
- [ ] In an admin form page, delete the user object from localStorage. 
  - [ ] Should be logged out and redirected to the login page
  - [ ] After login, should be redirected back to the admin form page where you deleted the localStorage user.

**Comment by mantariksh** [comment]
## Tests
**Frontend form factory service**
- [ ] Duplicate any form. Ensure duplicate form modal appears and duplicated form appears on the dashboard upon completion.
- [ ] Create a form from scratch in storage mode and email mode. Should be redirected to edit page with no existing fields. Check that form appears on dashboard. 
- [ ] Select create new form and select any covid template. Modal with template form in public view should be displayed. Select "Use Template", and follow steps to create form. Ensure relevant form fields are present on edit page.
- [ ] Select any template under **examples**.  Select "Use Template", and follow steps to create form. Ensure relevant form fields are present on edit page.

**Comment by mantariksh** [comment]
## Tests
**Email validation**
- [ ] Login with invalid email. Should return and display not-whitelisted error message below the input
- [ ] Login with disconnected internet (chrome console > network > offline). Should display error message below the input
- [ ] Login with valid email. Should proceed to verify OTP page
- [ ] Enter invalid OTP. Should reject.
- [ ] Click resend OTP, then use previous valid OTP. Should reject. Should receive new OTP.

**Comment by mantariksh** [comment]
## Tests
**Storage mode submission version**
- [ ] View individual storage mode response.  Should decrypt and display correctly
- [ ] Download storage mode response (without attachment). Should download correctly and correct responses decrypted.
- [ ] Download storage mode response. same as above.

**Comment by mantariksh** [comment]
## Tests
**Frontend form API factory**
- [ ] Load forms dashboard page. Check that all available forms are present. (query)
- [ ] Click on any form. Should be redirected to edit page. Check that previous fields (if any) are present. (getAdmin)
- [ ] Click on `open in new window` in share tab **without** activating form. Should be redirected to error page. (getPublic)
- [ ] Click on `open in new window` in share tab after activating form. Should be redirected to public view of form. (getPublic)
- [ ] Duplicate a field in a form. Check that the field is duplicated correctly i.e. contents of the field are correct (update)
- [ ] Duplicate any form. Ensure duplicate form modal appears and duplicated form appears on the dashboard upon completion (save) 
- [ ] Delete a form. Ensure that the form is no longer visible on the dashboard (delete)
- [ ] Create a form from scratch in storage mode and email mode. Should be redirected to edit page with no existing fields. Check that form appears on dashboard. (create)
- [ ] Select create new form and select any template. Modal with template form in public view should be displayed. (template)
- [ ] Select use template (following from previous check). Perform same checks done for create form.
- [ ] Select preview mode of any existing form. Should be redirected to preview page. (preview)
- [ ] Add a collaborator and change role to owner. Ownership should have changed. (transferOwner)
- [ ] Create myinfo fields. Check that myinfo fields are correctly stripped and injected. 
- [ ] Duplicate myinfo fields. Check that myinfo fields are correctly stripped and injected.
- [ ] Duplicate a form with myinfo fields. Check that myinfo fields are correctly stripped and injected.
- [ ] Check that myinfo fields are correctly injected into public form view
- [ ] Check that forms can be createdfrom the examples page
- [ ] Check that forms can be created from the "Share Template" link under the "Share" tab

**Comment by mantariksh** [comment]
@mantariksh 

## Tests
**ValidationOptions schema change**
- [ ] Create a form with the following fields
  - Short text, with minimum 3 chars
  - Short text, with exactly 3 chars
  - Long text, with minimum 3 chars
  - Long text, with exactly 3 chars
  - Number, with minimum 3 chars
  - Number, with exactly 3 chars
- [ ] Test that the validation works correctly and the form can be submitted
- [ ] Edit the validation by replacing minimum with maximum. Check that the validation works correctly and form can be submitted.

**Backward compatibility checks**
- [ ] Repeat the above tests but using an old client for the public form user. Check that the validation works correctly and form can be submitted.
- [ ] Repeat the above tests but using an old client for the admin. Check that the form can be modified correctly and that the modified changes persist.

**Comment by mantariksh** [comment]
@mantariksh 
## Tests
**Prerequisites**
- Create email form with email field that has autoreply toggled
- Create storage mode form with email field that has autoreply toggled

### IE 11 public facing submission
- [ ] Can access email form
- [ ] Can submit email form
- [ ] For email forms, should receive autoreply email (with pdf if toggled)
  - [ ] As admin, should receive submission email
- [ ] For storage forms, should receive autoreply email
  - [ ] As admin, check responses tab and a new submission should have been made. (no need to be on IE11)
  - [ ] As admin, response should be decrypt-able (no need to be on IE11)
- [ ] Should be able to submit feedback (check on admin side)

**Comment by seaerchin** [comment]
## Tests

First create a storage mode form with an attachment field and publish it. Go to the form and submit it >1 times with attachment and a few times without.
- [ ] Go to the admin panel and unlock the form. Click on export and attempt both actions. This should succeed and the csv should contain the correct # of responses. 
- [ ] Click into a single response (with data) then select download as zip. The download should succeed. 
- [ ] Click into a single response (with data) and click on the attachment. The download should succeed

**Review by yong-jie — APPROVED** [review]

**Review by LoneRifle — APPROVED** [review]

**Review by karrui — APPROVED** [review]

**Pull request merged**
