### PR TITLE
build: release v4.40.0

### PR DESCRIPTION
**Pull request by karrui**
We're hitting the big four-ohs!

**New:**
- feat: using `neverthrow` to explicitly handle errors in UserController [`#371`](https://github.com/opengovsg/formsg/pull/371)

**Improvements:**
- chore: ui/copy changes [`#446`](https://github.com/opengovsg/formsg/pull/446)
- refactor(field-validators): introduce scaffolding & reference implementations for section, short text & long text fields [`#409`](https://github.com/opengovsg/formsg/pull/409)
- refactor(mail): group files into service [`#432`](https://github.com/opengovsg/formsg/pull/432)

**Fixes:**
- fix: prevent undefined split errors when vm.user does not exist [`#454`](https://github.com/opengovsg/formsg/pull/454)

**Dependency updates:**
- chore(deps-dev): bump mongodb-memory-server-core from 6.7.5 to 6.9.2 [`#450`](https://github.com/opengovsg/formsg/pull/450)
- chore: clean up dependencies [`#448`](https://github.com/opengovsg/formsg/pull/448)
- fix(deps): bump @sentry/integrations from 5.24.2 to 5.25.0 [`#442`](https://github.com/opengovsg/formsg/pull/442)
- fix(deps): bump aws-sdk from 2.763.0 to 2.770.0 [`#443`](https://github.com/opengovsg/formsg/pull/443)
- chore(deps-dev): bump @types/jest from 26.0.9 to 26.0.14 [`#444`](https://github.com/opengovsg/formsg/pull/444)
- chore(deps-dev): bump sinon from 9.0.3 to 9.2.0 [`#441`](https://github.com/opengovsg/formsg/pull/441)
- chore(deps-dev): bump eslint-config-prettier from 6.11.0 to 6.12.0 [`#435`](https://github.com/opengovsg/formsg/pull/435)
- fix(deps-dev): run npm audit fix [`#428`](https://github.com/opengovsg/formsg/pull/428)

**Misc:**
- chore: update test threshold to 25% [`#457`](https://github.com/opengovsg/formsg/pull/457)
- chore: extend namespace globally for request properties and log info utility function [`#429`]
(https://github.com/opengovsg/formsg/pull/429)
- chore: add lint error for unused variables [`#437`](https://github.com/opengovsg/formsg/pull/437)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
### User route refactor to neverthrow
**Emergency contact flow**
- [ ] Emergency contact can be entered and verified.
- [ ] Emergency contact is correctly saved when user logs out and in again.
- [ ] Emergency contact can be updated.

**/user endpoint flow**
- [ ] Open Chrome devtools. Log into FormSG. When in list form route, `/user` is correctly called and the current user is correctly returned.
- [ ] Staying in list form route; delete session cookie. Refresh the page. `/user` endpoint should return 401 and you should be kicked out to the login page.

**Comment by karrui** [comment]
## Tests
### Copy/UI changes
- [ ] In admin form share tab, verify the following copy changes:
  - [ ] 'Enable Captcha' --> 'Enable reCaptcha'
  - [ ] infotip on captcha 'Picture selection' --> 'Image selection'

**Comment by karrui** [comment]
## Tests
### Mail refactor
- [ ] General mail run through; verified email field, update email subject/body/etc, update recipients. All expected functions of mail should continue to work.

**Comment by karrui** [comment]
## Tests
### Undefined string split
- [ ] Log into the list form admin route. Delete user object in localstorage and refresh. You should be kicked out to the login screen and no console errors should appear.

**Comment by karrui** [comment]
## Tests
- [ ] General run through on IE11/Intranet

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
