### PR TITLE
build: release v5.26.0

### PR DESCRIPTION
**Pull request by karrui**
## Release v5.26.0
This week's release sees a couple of bug fixes, in addition to the usual dependency updates.

There is also a notable refactor in which shared types in the backend and frontend are now imported from the (root) `/shared` folder's exports instead of the re-exports from backend types.

### Fixes
- fix: Email domain validation should be case-insensitive [`#2682`](https://github.com/opengovsg/FormSG/pull/2682)
- fix: only check for sms quota on verified mobile field OTP verifications instead of all verified fields [`#2710`](https://github.com/opengovsg/FormSG/pull/2710)

### Improvements
- feat: clean up all naming discrepancies between shared and backend types [`#2527`](https://github.com/opengovsg/FormSG/pull/2527)
- fix: Add 10 MB max length checks to form field editor [`#2584`](https://github.com/opengovsg/FormSG/pull/2584)

### Dependency updates
- fix: upgrade jszip from 3.7.0 to 3.7.1 [`#2692`](https://github.com/opengovsg/FormSG/pull/2692)
- fix: upgrade mongoose from 5.13.4 to 5.13.5 [`#2664`](https://github.com/opengovsg/FormSG/pull/2664)
- fix: upgrade type-fest from 1.2.3 to 1.3.0 [`#2663`](https://github.com/opengovsg/FormSG/pull/2663)
- fix: upgrade type-fest from 1.3.0 to 1.4.0 [`#2691`](https://github.com/opengovsg/FormSG/pull/2691)
- fix: upgrade zod from 3.6.1 to 3.7.1 [`#2662`](https://github.com/opengovsg/FormSG/pull/2662)
- fix(deps): bump @opengovsg/spcp-auth-client from 1.4.9 to 1.4.10 [`#2694`](https://github.com/opengovsg/FormSG/pull/2694)
- fix(deps): bump aws-sdk from 2.973.0 to 2.974.0 [`#2671`](https://github.com/opengovsg/FormSG/pull/2671)
- fix(deps): bump aws-sdk from 2.974.0 to 2.976.0 [`#2688`](https://github.com/opengovsg/FormSG/pull/2688)
- fix(deps): bump aws-sdk from 2.976.0 to 2.978.0 [`#2699`](https://github.com/opengovsg/FormSG/pull/2699)
- fix(deps): bump express-winston from 4.1.0 to 4.2.0 [`#2702`](https://github.com/opengovsg/FormSG/pull/2702)
- fix(deps): bump libphonenumber-js from 1.9.24 to 1.9.25 [`#2689`](https://github.com/opengovsg/FormSG/pull/2689)
- fix(deps): bump opossum from 6.2.0 to 6.2.1 [`#2674`](https://github.com/opengovsg/FormSG/pull/2674)
- fix(deps): bump spark-md5 from 3.0.1 to 3.0.2 [`#2678`](https://github.com/opengovsg/FormSG/pull/2678)
- fix(deps): bump sqs-consumer from 5.5.0 to 5.6.0 [`#2686`](https://github.com/opengovsg/FormSG/pull/2686)
- fix(deps): bump twilio from 3.67.0 to 3.67.1 [`#2690`](https://github.com/opengovsg/FormSG/pull/2690)
#### Dev dependency updates
- chore(deps-dev): bump @opengovsg/mockpass from 2.7.7 to 2.7.8 [`#2697`](https://github.com/opengovsg/FormSG/pull/2697)
- chore(deps-dev): bump @types/node from 14.17.11 to 14.17.12 [`#2685`](https://github.com/opengovsg/FormSG/pull/2685)
- chore(deps-dev): bump @types/opossum from 4.1.2 to 6.2.0 [`#2670`](https://github.com/opengovsg/FormSG/pull/2670)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#2706`](https://github.com/opengovsg/FormSG/pull/2706)
- chore(deps-dev): bump @typescript-eslint/parser from 4.29.2 to 4.29.3 [`#2673`](https://github.com/opengovsg/FormSG/pull/2673)
- chore(deps-dev): bump @typescript-eslint/parser from 4.29.3 to 4.30.0 [`#2707`](https://github.com/opengovsg/FormSG/pull/2707)
- chore(deps-dev): bump core-js from 3.16.2 to 3.16.3 [`#2681`](https://github.com/opengovsg/FormSG/pull/2681)
- chore(deps-dev): bump core-js from 3.16.3 to 3.16.4 [`#2700`](https://github.com/opengovsg/FormSG/pull/2700)
- chore(deps-dev): bump csv-parse from 4.16.0 to 4.16.2 [`#2696`](https://github.com/opengovsg/FormSG/pull/2696)
- chore(deps-dev): bump eslint-plugin-import from 2.24.1 to 2.24.2 [`#2676`](https://github.com/opengovsg/FormSG/pull/2676)
- chore(deps-dev): bump husky from 7.0.1 to 7.0.2 [`#2679`](https://github.com/opengovsg/FormSG/pull/2679)
- chore(deps-dev): bump jest-localstorage-mock from 2.4.16 to 2.4.17 [`#2672`](https://github.com/opengovsg/FormSG/pull/2672)
- chore(deps-dev): bump ts-essentials from 8.0.0 to 8.1.0 [`#2698`](https://github.com/opengovsg/FormSG/pull/2698)
- chore(deps-dev): bump typescript from 4.3.5 to 4.4.2 [`#2701`](https://github.com/opengovsg/FormSG/pull/2701)

### CODE REVIEW

**Comment by karrui** [comment]
### Tests
#### Email domain casing
- [ ] Create a form with a verifiable email field and supply 2 allowed domains `oPeN.GoV.sG` and `gmail.COM`
- [ ] Open form, and verify that
    - [ ] invalid domain is rejected: `me<AT>ogp<DOT>sg` should show error message: `Not an allowed email domain`
    - [ ] Test with the following emails (with an email that you own) and check if the verification email is sent:
         - `<your email AT>gmail.com`
         - `<your email AT>GMAIL.com`
         - `<your email AT>gmAIL.CoM`
         - `<your email AT>OPEN.GOV.SG`
         - `<your email AT>open.gov.sg`
         - `<your email AT>oPeN.GoV.sG`

**Comment by karrui** [comment]
### Shared folder refactor/misc checklist
- [ ] Create email mode form with all fields and custom start/end page, with email to respondent also toggled on. Activate and submit form. Check that you received responses for both your admin/form filler portion
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields and custom start/end page. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments for individual fields can be downloaded from Data tab in storage mode.
- [ ] Attachment ZIP for submission can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Comment by karrui** [comment]
@karrui
(I realize I'm self testing, but someone else can feel free to do it too)

## Tests
### only check for sms quota on verified mobile field OTP verifications instead of all verified fields
- [x] On an admin account that has hit the free sms quota
  - [x] Create a form with a verified **EMAIL** field. Verify email on that field and should verify successfully. No emails about SMS quota should be sent.
  - [x] Create a form with a verified **MOBILE** field (toggle isVerifiable in the database). Verify mobile number on that field and submit form. Verification should go through and form submission should succeed. Should get deactivation email sent to admin and all collaborators.

**Comment by mantariksh** [comment]
## Tests
**10MB max field check**
- [ ] Copy and paste a large amount of text (>10MB) into a dropdown field and check that you see an error message saying that the field is too big

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
