### PR TITLE
feat: update RUM sampleRate to match increased rollout percentage

### PR DESCRIPTION
**Pull request by wanlingt**
The target % of RUM sessions is 5%.

Since we're increasing rollout % for email-mode respondents to 100% and admins to 65%, increase RUM sampleRate to 5%.

### CODE REVIEW

**Review by karrui — APPROVED** [review]

**Comment by karrui** [comment]
why you merge :P

**Comment by wanlingt** [comment]
> why you merge :P

oh was I supposed to merge w another branch instead?

**Comment by karrui** [comment]
Supposed to squash hehe

**Comment by wanlingt** [comment]
OHHH whoops i just clicked the button forgot to check, my bad!!!

**Pull request merged**
