### PR TITLE
build: Release v4.46.0

### PR DESCRIPTION
**Pull request by karrui**
# v4.46.0

## New
- feat: allow .oa files to be attached [`#650`](https://github.com/opengovsg/FormSG/pull/650)
- feat: Backend implementation for bulk attachment downloading [`#555`](https://github.com/opengovsg/FormSG/pull/555)
- feat(monitoring): add memory monitoring to EC2 instances [`#620`](https://github.com/opengovsg/FormSG/pull/620)
- style: make transfer ownership email more prominent [`#630`](https://github.com/opengovsg/FormSG/pull/630)

## Improvements
- chore: use travis_retry to retry flaky tests automatically [`#641`](https://github.com/opengovsg/FormSG/pull/641)
- ref: migrate createPresignedPost endpoint for images to   TypeScript [`#604`](https://github.com/opengovsg/FormSG/pull/604)
- ref: migrate createPresignedPost endpoint for logos to   TypeScript [`#607`](https://github.com/opengovsg/FormSG/pull/607)
- ref: migrate fetch form submission counts flow to Typescript [`#592`](https://github.com/opengovsg/FormSG/pull/592)
- ref: migrate inline queries for retrieval of submissions   metadata to model static methods [`#601`](https://github.com/opengovsg/FormSG/pull/601)
- ref: migrate streamEncryptedResponses flow to Typescript [`#615`](https://github.com/opengovsg/FormSG/pull/615)
- refactor: convert errors.server.controller to typescript   utility function [`#602`](https://github.com/opengovsg/FormSG/pull/602)
- refactor: convert req.hashedFields to Set [`#617`](https://github.com/opengovsg/FormSG/pull/617)
- refactor: migrate MyInfo functionality to TypeScript [`#560`](https://github.com/opengovsg/FormSG/pull/560)
- refactor: migrate NRIC validator to TypeScript [`#639`](https://github.com/opengovsg/FormSG/pull/639)
- feat: upgrade spcp-auth-client [`#649`](https://github.com/opengovsg/FormSG/pull/649)

## Fixes
- fix: add required env vars for MyInfo [`#612`](https://github.com/opengovsg/FormSG/pull/612)
- fix: package.json & package-lock.json to reduce   vulnerabilities [`#637`](https://github.com/opengovsg/FormSG/pull/637)
- fix: resolve &amp; in url upon redirect, shift prefill to textfield component [`#569`](https://github.com/opengovsg/FormSG/pull/569)
- fix: use maildev for dev environment emails [`#613`](https://github.com/opengovsg/FormSG/pull/613)
- test: enable local e2e tests [`#616`](https://github.com/opengovsg/FormSG/pull/616)

## Dependency updates
- chore(deps-dev): bump @types/mongoose from 5.7.36 to 5.7.37 [`#597`](https://github.com/opengovsg/FormSG/pull/597)
- chore(deps-dev): bump @types/mongoose from 5.7.37 to 5.10.0 [`#644`](https://github.com/opengovsg/FormSG/pull/644)
- chore(deps-dev): bump @types/node from 14.14.6 to 14.14.7 [`#611`](https://github.com/opengovsg/FormSG/pull/611)
- chore(deps-dev): bump @typescript-eslint/parser from 4.5.0 to   4.7.0 [`#610`](https://github.com/opengovsg/FormSG/pull/610)
- chore(deps-dev): bump babel-loader from 8.1.0 to 8.2.1 [`#625`](https://github.com/opengovsg/FormSG/pull/625)
- chore(deps-dev): bump eslint from 7.12.1 to 7.13.0 [`#643`](https://github.com/opengovsg/FormSG/pull/643)
- chore(deps-dev): bump eslint-plugin-simple-import-sort from   5.0.3 to 6.0.0 [`#646`](https://github.com/opengovsg/FormSG/pull/646)
- chore(deps-dev): bump supertest from 5.0.0 to 6.0.1 [`#622`](https://github.com/opengovsg/FormSG/pull/622)
- chore(deps-dev): bump testcafe from 1.8.6 to 1.9.4 [`#632`](https://github.com/opengovsg/FormSG/pull/632)
- fix(deps): bump @sentry/browser from 5.24.2 to 5.27.3 [`#631`](https://github.com/opengovsg/FormSG/pull/631)
- fix(deps): bump angular from 1.8.0 to 1.8.2 [`#633`](https://github.com/opengovsg/FormSG/pull/633)
- fix(deps): bump angular-aria from 1.8.0 to 1.8.2 [`#619`](https://github.com/opengovsg/FormSG/pull/619)
- fix(deps): bump helmet from 4.1.1 to 4.2.0 [`#624`](https://github.com/opengovsg/FormSG/pull/624)
- fix(deps): bump jwt-decode from 2.2.0 to 3.1.1 [`#594`](https://github.com/opengovsg/FormSG/pull/594)
- fix(deps): bump mongoose from 5.10.10 to 5.10.14 [`#645`](https://github.com/opengovsg/FormSG/pull/645)
- fix(deps): bump uuid from 8.3.0 to 8.3.1 [`#626`](https://github.com/opengovsg/FormSG/pull/626)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
### Allow `.oa` files to be uploaded in attachment fields
- [ ] In a storage mode form, create an attachment field and submit an `.oa` file. The submission should be successful. 
  - [ ] Go to the responses of the form, should be able to download all the attachments (including the .oa) as a zip
  - [ ] Go to the responses of the form, should be able to download the attachment by itself
- [ ] In email mode form, create an attachment field and submit an `.oa` file. The submission should be successful. 
  - [ ] Should successfully receive the attachment in your email.

**Comment by karrui** [comment]
## Tests
### Typescript route migrations
ref: migrate fetch form submission counts flow to Typescript #592
- [ ] Upload an image for image field. Upload should work successfully and the image is shown on the public form. 
- [ ] Upload a logo for any form. Upload should work successfully and the logo is shown on the public form start page component.
- [ ] Go to the data tab of any form with submissions. The submission count should be retrieved correctly.
- [ ] In a storage mode form, go to the response tab and view responses. The responses table should populate correctly with the correct metadata.
  - [ ] Click into any submission response. The response answers should be decrypted properly.
  - [ ] Download all encrypted responses. Should download successfully.
  - [ ] Download encrypted responses in a date range. Should download successfully.

**Comment by karrui** [comment]
## Tests
- NRIC field validation should work as per normal -- invalid NRICs should still be invalid, valid NRICs should still be valid

**Comment by karrui** [comment]
## Tests

### Run through on IE / Intranet
_General run through_
- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your GSIB inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.
- [ ] Create form with MyInfo fields. Submit successfully

**Comment by tshuli** [comment]
## Tests

## Prefill

- [ ] Create a form with short text field. Open in public view with the query params <shortTextFieldId>=<value1>, where <value1> comprises alphanumeric/hyphen/underscore characters. Check that the short text field is not prefilled with value1
- [ ] In the db, check that allowPrefill is set to false for the short text field. set allowPrefill = true. Check that prefill now works.
- [ ] Create myinfo field. Set allowPrefill = true for the myinfo field. Access form on public view and login to singpass. Check that prefill does not work on the myinfo field.
- [ ] Check that prefilling works even without the hashbang in the url
- [ ] Check that for non-hashbang url with two query params, upon redirection, the redirect path uses `&` to separate the query params instead of `&amp;`
- [ ] Add radio button to the form. Set form logic to hide the short text field conditional on the radio button. Check that the short text field is prefilled when it is unhidden
- [ ] Prefilled field value is cleared when field is hidden by logic at the point of submission

**Comment by mantariksh** [comment]
## Tests

### SP/CP
- [ ] Create an email mode form. Change the auth type to SingPass. Activate the form and submit it.
- [ ] Create an email mode form. Change the auth type to CorpPass. Activate the form and submit it.
- [ ] Create a storage mode form. Change the auth type to SingPass. Activate the form and submit it.
- [ ] Create a storage mode form. Change the auth type to CorpPass. Activate the form and submit it.

### MyInfo
- [ ] Create and submit a form with all MyInfo fields. Ensure that when you receive the email response, all the disabled fields (and no others) have the [MyInfo] prefix.

**Comment by karrui** [comment]
## Tests

### Specific IE11/ Intranet tests
- [ ] Should be able to upload .oa files in storage mode forms.
- [ ] Should be able to upload .oa files in email mode forms.
- [ ] Should be able to receive form submissions with .oa files in intranet email for email mode submissions
- [ ] Should be able to download form attachment of .oa files
- [ ] Should be able to download form attachments of entire response (including .oa file attachment)

- [ ] Transfer form ownership modal styling is correct like in #630

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
