### PR TITLE
build: release v6.65.0

### PR DESCRIPTION
**Pull request by tshuli**
## New

- fix: issue report icon for mobile [`#6527`](https://github.com/opengovsg/FormSG/pull/6527)
- feat: Create issue feedback UI on public form interface [`#6452`](https://github.com/opengovsg/FormSG/pull/6452)
- chore: variable payments UI review changes [`#6524`](https://github.com/opengovsg/FormSG/pull/6524)
- feat: issue feedback admin page [`#6517`](https://github.com/opengovsg/FormSG/pull/6517)
- feat: issue feedback post api service [`#6492`](https://github.com/opengovsg/FormSG/pull/6492)
- fix: disallow path traversal when proxying static assets [`#6513`](https://github.com/opengovsg/FormSG/pull/6513)
- fix: mishandling stripe callback when user clicks return to form [`#6522`](https://github.com/opengovsg/FormSG/pull/6522)
- feat: migrate payment enablement from toggle to delete button [`#6511`](https://github.com/opengovsg/FormSG/pull/6511)
- feat: create get api for listing and downloading issues [`#6516`](https://github.com/opengovsg/FormSG/pull/6516)
- feat: payment dashboard [`#6504`](https://github.com/opengovsg/FormSG/pull/6504)
- fix: set decompress to false [`#6515`](https://github.com/opengovsg/FormSG/pull/6515)
- refactor: Fix backwards compatibility issues with Turnstile integration [`#6502`](https://github.com/opengovsg/FormSG/pull/6502)
- feat: decouple otp validation and restrict email domain [`#6497`](https://github.com/opengovsg/FormSG/pull/6497)
- build: merge v6.64.0 into develop [`#6512`](https://github.com/opengovsg/FormSG/pull/6512)
- build: release v6.64.0 [`#6509`](https://github.com/opengovsg/FormSG/pull/6509)
- chore: fix typo maxmium -&gt; maximum [`#6510`](https://github.com/opengovsg/FormSG/pull/6510)
- feat: deep link myinfo settings message in builder [`#6503`](https://github.com/opengovsg/FormSG/pull/6503)

## Dependencies

- fix(deps): bump type-fest from 3.12.0 to 3.13.0 in /shared [`#6521`](https://github.com/opengovsg/FormSG/pull/6521)
- fix(deps): bump protobufjs from 7.1.2 to 7.2.4 [`#6519`](https://github.com/opengovsg/FormSG/pull/6519)
- chore(deps): bump tough-cookie from 4.1.2 to 4.1.3 in /frontend [`#6518`](https://github.com/opengovsg/FormSG/pull/6518)

### feat: Create issue feedback UI on public form interface [`#6452`](https://github.com/opengovsg/FormSG/pull/6452)
@tshuli 
- [x] In public form, respondent can always see the issue feedback button (message icon) in the bottom right corner of the screen to report an issue.
- [x] Create a long form and scroll through it, respondent should still be able to see the message button.
- [x] When hover over the button, a `Report an issue` tooltip is displayed.
- [x] Click on the button, a pop up modal should show up, allowing user to report any issue they wish.
- [x] Respondent cannot submit the form if the description box is empty, a validation error is shown below the text box, stating `This field is required`.
- [x] Respondent can submit the form if the contact box is empty.
- [x] Respondent must key in a valid email (in term of format), otherwise a validation error will be shown below the text box, stating `Please enter a valid email`
- [x] No email OTP verification is required for the email.
- [x] Check that it's the same flow as in the preview form, except that upon submission of the feedback, a toast showing `Thank you for submitting your feedback! Since you are in preview mode, the feedback is not stored.`
- [x] Validate all other pages (admin creation form, post submission form) do not have the issue feedback button.
- [x] Validate that form admin receives an email notification (at most 1 form per form per day) saying respondents are facing issues with their form
- [x] Validate that the form issues are correctly listed on the Response tab in admin page

### chore: variable payments UI review changes [`#6524`](https://github.com/opengovsg/FormSG/pull/6524)

@wanlingt 
- [x] Create a new storage mode form 
- [x] Go to Create Tab -> Payment, you should be able to toggle `Payment Type`
- [x] Connect to stripe account
- [x] Go to Create Tab -> Payment
- [x] Ensure that there isn't any placeholders for `Product/service name` and `Description`
- [x] Go to `Product/service name` and enter without adding any value, you should see an error that it is required
- [x] Go to `Description` and enter without adding any value, there should be no error
- [x] Select `Fixed Payment`, go to 'Payment Amount' and input >$1000, you should see the warning message for invoices and be able to click the link
- [x] Select `Variable payment` you should see the max and min placeholders. 
- [x] Upon entering empty values for both max and min -> you should see warning messages that tells you the max and min values expected
- [x] Go to an email mode form
- [x] Go to Create Tab -> Payment, you should not be able to select any fields in email mode 

### feat: issue feedback admin page [`#6517`](https://github.com/opengovsg/FormSG/pull/6517)
Listing Issues
@justynoh 
- [x] Create a new form and view the Results > Feedback tab, observe that `You don't have any feedback yet` is shown.
- [x] Make the form public and fill in the form as public users, and provide some review and rating after submitting the form.
- [x] Go to the Results > Feedback tab, see that there is `0 issues to date`.
- [x] Observe that Export button is greyed out as there're no issues to export.
- [x] Click onto the Review button, see that the reviews and ratings entered earlier is listed on the page.
- [x] Click onto the Export button, the reviews and ratings should be properly exported.

### feat: issue feedback post api service [`#6492`](https://github.com/opengovsg/FormSG/pull/6492)
Full E2E test can be done once https://github.com/opengovsg/FormSG/pull/6452 is merged.

### fix: disallow path traversal when proxying static assets [`#6513`](https://github.com/opengovsg/FormSG/pull/6513)
(update the domain based on he environment being tested)
@justynoh 
-  [x]  run the following curl command the the CLI:
```
curl 'https://form.gov.sg/static/..\../cureredirbucket/test.html'
```
It should **NOT** return
```
<!DOCTYPE html>
<body>
<h2>hello</h2>
<script>alert(123)</sript>
</body>
```
instead it should return the usual FormSG start page
```
<!doctype html><html lang="en"><head><meta charset="utf-8"/><base href="/"/><link rel="icon" href="./favicon.ico"/><link rel="icon" type="image/svg+xml" href="./favicon.svg"/><link rel="icon" type="image/png" sizes="32x32" href="./favicon-32x32.png"/><link rel="icon" type="image/png" sizes="16x16" href="./favicon-16x16.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#ffffff"/><meta name="description" content="Trusted form manager of the Singapore Government"/><link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png"/><link rel="manifest" href="./manifest.json"/><title>FormSG</title><meta property="og:site_name" content="FormSG"/><meta property="og:title" content="FormSG"/><meta property="og:description" content="Trusted form manager of the Singapore Government"/><meta property="og:image" content="./static/images/og-img-metatag-nonpublicform.png"/><meta property="og:type" content="website"/><meta name="twitter:card" content="summary"/><meta name="twitter:title" content="FormSG"/><meta name="twitter:description" content="Trusted form manager of the Singapore Government"/><meta name="twitter:image" content="./static/images/og-img-metatag-nonpublicform.png"/><script src="../static/js/datadog-chunk.6d7096ea607353a4280f.js"></script><link href="./static/css/6.7aaaf388.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script src="./static/js/runtime-main.e84c65d3.js"></script><script src="./static/js/6.cf2ed09b.chunk.js"></script><script src="./static/js/main.0e279f22.chunk.js"></script></body></html>
```

### fix: mishandling stripe callback when user clicks return to form [`#6522`](https://github.com/opengovsg/FormSG/pull/6522)
@sebastianwzq 
- [x] Go to any form that has yet to configured payment
- [x] Go to Settings > Payments, click `Connect with my stripe account`
- [x] Click Return to FormSG instead of continuing with connection
- [x] Observe that page is redirected back to Settings > Payments page

### feat: migrate payment enablement from toggle to delete button [`#6511`](https://github.com/opengovsg/FormSG/pull/6511)

**In desktop**
@sebastianwzq 
- [x] Go to a storage mode form (stripe unconnected)
- [x] Go to Create Tab -> Payments, you should see the preview but cannot save field
- [x] Go to settings -> connect stripe
- [x] Go to Create Tab -> Payments
- [x] Create a fixed payment
- [x] Open the form and make a payment
- [x] Delete the payment field
- [x] Open the form and submit the form (no payment)
- [x] Create a variable payment
- [x] Open the form and make a payment
- [x] Delete the payment field
- [x] Open the form and submit the form (no payment)

**In mobile**
@LinHuiqing 
- [x] Go to a storage mode form (stripe unconnected)
- [x] Go to Create Tab -> Payments, you should not be able to save field
- [x] Go to settings -> connect stripe
- [x] Go to Create Tab -> payments
- [x] Create a fixed payment
- [x] Edit the payment field by selecting the `gear` icon on the field
- [x] Open the form and make a payment
- [x] Delete the payment field
- [x] Open the form and submit the form (no payment)

### feat: payment dashboard [`#6504`](https://github.com/opengovsg/FormSG/pull/6504)

**Regression**
@LinHuiqing 
Viewing of results for non-payment forms
As an admin
- [x] enable to view form results response table without new fields (email, paid amount, net amount, fees, payout date)

**Features**
@LinHuiqing 
Viewing of results for payment forms
As an admin
- [x] enable to view form results response table with new fields (email, paid amount, net amount, fees, payout date)

### fix: set decompress to false [`#6515`](https://github.com/opengovsg/FormSG/pull/6515)
@mayying 
- [x] Send webhook to an endpoint on https://webhook.site/<your endpoint>. Check that webhook is received at endpoint, and that formsg logs indicate webhook response received successfully (200).

### refactor: Fix backwards compatibility issues with Turnstile integration [`#6502`](https://github.com/opengovsg/FormSG/pull/6502)
@mayying 
Conduct the following tests with and without VPN to trigger captchas
- [x]  Verify that Turnstile captcha works (i.e. able to submit forms) after switching on the enableTurnstileFeatureFlag
- [x] Verify that Google recaptcha works (i.e. able to submit forms) after switching off the enableTurnstileFeatureFlag

### feat: decouple otp validation and restrict email domain [`#6497`](https://github.com/opengovsg/FormSG/pull/6497)
@foochifa 
- [x] Can create email field without otp verification and without restrict email domain and submit form
- [x] Can create email field with otp verification and without restrict email domain and submit form
- [x] Can create email field without otp verification and with restrict email domain and submit form
  - [x] Whitelisted domains submit successfully
  - [x] Non-whitelisted domains blocked by frontend
  - [x] Non-whitelisted domains blocked by backend
- [x] (via network call) attempting to create email field with `hasAllowedEmailDomains` true and `allowedEmailDomains` nonEmpty will result in error with message `List of allowed email domains should be empty if restrict email domains is disabled`

#### Scripts

There are 23 documents with invalid state for `hasAllowedEmailDomains = true` but `allowedEmailDomains = []`. Will have to run a DB migration script [f437212](https://github.com/opengovsg/FormSG/pull/6497/commits/f437212bcfb9fdc46d593cbaa857ee18c6ebf41c)

### feat: deep link myinfo settings message in builder [`#6503`](https://github.com/opengovsg/FormSG/pull/6503)

@kenjin-work 
- [X] Create an email mode form
- [X] Go to `create` tab, and select `myinfo` tab, you should see the message as the screenshot above
- [X] Settings should be clickable
- [X] Click settings, enable myinfo
- [X] Add myinfo field
- [X] Open form
- [X] Fill and submit form

test payment settings redirect still works
@sebastianwzq 
- [x] Create a storage mode form
- [x] Go to `create` tab and select `payment` tab with stripe unconnected
- [x] You should be able to select 'Settings' in the info message
- [x] It should redirect you to `settings/payments`

### CODE REVIEW

**Comment by justynoh** [comment]
For #6513, I did the following:

```
curl 'https://staging.form.gov.sg/static/..\../cureredirbucket/test.html'

Not Found
```
 is this intended? the test says that the root page should be returned but this is not the case.

Tagging @timotheeg to double-check!

**Comment by foochifa** [comment]
@tshuli for #6497, shouldn't we have a FE error message below the 'Domains Allowed' instead of a toast here? 
image

**Comment by mayying** [comment]
I am not able to see captcha with VPN off and turnstile=true, please verify if that is expected. For all other cases, I can see captcha. @sebastianwzq

**Comment by tshuli** [comment]
> @tshuli for #6497, shouldn't we have a FE error message below the 'Domains Allowed' instead of a toast here? image

good catch, thanks @foochifa ! added in #6529 

Screenshot 2023-07-11 at 11 42 50 PM

**Review by foochifa — APPROVED** [review]

**Pull request merged**
