### PR TITLE
build: release v5.13.0

### PR DESCRIPTION
**Pull request by karrui**
# Release v5.13.0
New week, new release. This release enables webhook retries for the application. Big stuff. Get excited. 

## Features
- feat: enable retries for webhooks   [`#2093`](https://github.com/opengovsg/FormSG/pull/2093)

## Improvements
- feat: log form updates   [`#2063`](https://github.com/opengovsg/FormSG/pull/2063)
- feat: sort responses for csv download   according to creation date   [`#2028`](https://github.com/opengovsg/FormSG/pull/2028)
- fix: restore typings to some model   static methods [`#2067`](https://github.com/opengovsg/FormSG/pull/2067)
- refactor: replace set hook with   validator hook in emailField model   [`#1971`](https://github.com/opengovsg/FormSG/pull/1971)
- refactor(beta): migrate to TypeScript   [`#2058`](https://github.com/opengovsg/FormSG/pull/2058)
- refactor(formApiClientFactory):   rearrange types [`#2061`](https://github.com/opengovsg/FormSG/pull/2061)
- refactor(submissions.client.factory):   extract admin form features   [`#1983`](https://github.com/opengovsg/FormSG/pull/1983)
- test(betas): provide coverage   [`23f9a9f`](https://github.com/opengovsg/FormSG/commit/23f9a9fe9675eab1d25c1983a08a7c76e0139d52)

## Dependency updates
- fix(deps): bump @sentry/browser from   6.5.0 to 6.5.1 [`#2069`](https://github.com/opengovsg/FormSG/pull/2069)
- fix(deps): bump @sentry/integrations   from 6.5.0 to 6.5.1 [`#2071`](https://github.com/opengovsg/FormSG/pull/2071)
- fix(deps): bump aws-sdk from 2.918.0 to   2.919.0 [`#2060`](https://github.com/opengovsg/FormSG/pull/2060)
- fix(deps): bump aws-sdk from 2.919.0 to   2.920.0 [`#2070`](https://github.com/opengovsg/FormSG/pull/2070)
- fix(deps): bump aws-sdk from 2.920.0 to   2.922.0 [`#2078`](https://github.com/opengovsg/FormSG/pull/2078)
- fix(deps): bump nocache from 2.1.0 to   3.0.0 [`#2068`](https://github.com/opengovsg/FormSG/pull/2068)
- fix(deps): bump twilio from 3.63.0 to   3.63.1 [`#2072`](https://github.com/opengovsg/FormSG/pull/2072)
- fix(deps): downgrade typescript to   4.2.4 and pin [`#2097`](https://github.com/opengovsg/FormSG/pull/2097)
- fix(deps): update mongoose to 5.12.12,   update model types [`#2046`](https://github.com/opengovsg/FormSG/pull/2046)

### Dev dependencies
- chore(deps-dev): bump @types/node from   14.17.1 to 14.17.2 [`#2059`](https://github.com/opengovsg/FormSG/pull/2059)
- chore(deps-dev): bump   @typescript-eslint/eslint-plugin   [`#2095`](https://github.com/opengovsg/FormSG/pull/2095)
- chore(deps-dev): bump   @typescript-eslint/parser from 4.26.0 to 4.26.1   [`#2094`](https://github.com/opengovsg/FormSG/pull/2094)
- chore(deps-dev): bump core-js from   3.13.1 to 3.14.0 [`#2076`](https://github.com/opengovsg/FormSG/pull/2076)
- chore(deps-dev): bump eslint from   7.27.0 to 7.28.0 [`#2077`](https://github.com/opengovsg/FormSG/pull/2077)
- chore(deps-dev): bump prettier from   2.2.1 to 2.3.1 [`#2075`](https://github.com/opengovsg/FormSG/pull/2075)
- chore(deps-dev): bump type-fest from   0.20.2 to 1.2.0 [`#2049`](https://github.com/opengovsg/FormSG/pull/2049)

## Documentation
- chore: remove   endPage.buttons key from database&nbsp;   [`#2087`](https://github.com/opengovsg/FormSG/pull/2087)
- docs(readme): remove active   contributors [`#2064`](https://github.com/opengovsg/FormSG/pull/2064)
- docs(script): add scripts to privatize   all sp/rp student forms   [`#2073`](https://github.com/opengovsg/FormSG/pull/2073)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
**Don't do them yet, until staging VPC is up, @mantariksh will ping**
### Webhook retries
- [ ] `WEBHOOK_SQS_URL` env var should be added in production.
- [ ] [Guide PR](https://github.com/opendocsg/opendoc-formsg-faq/pull/82) should be merged and go.gov.sg/form-webhook-retries should be updated to point to the correct section
- [ ] Spin up a webhook server and set it up such that it returns a non-200 response for the first request, and subsequently returns 200. Enable retries on the form. Check in the logs that when the initial webhook fails, the webhook is added to the queue (message: "Pushed webhook to queue"). Check that the subsequent retry is received by your server, and the FormSG server logs "Webhook POST succeeded".
- [ ] Without deactivating the form, disable retries. Ensure that your server is returning only non-200 responses, and submit the form. Check in the logs that the webhook fails but the webhook is not added to the queue (there is no "Pushed webhook to queue" log message).

**Comment by karrui** [comment]
## Tests
### Submissions client partial refactor
Create a storage mode form with any field and activate it. Submit the form >= 11 times. Go to the data section and unlock responses. 

- [ ] There should be the correct number of responses displayed
- [ ] Click on any page that is not 1. The relevant responses should be displayed
- [ ] Select a time period without responses and attempt to download (both options). This should **not** work
- [ ] Select a time period with responses and attempt to download (both options). This should work
- [ ] Search for a response using a valid `referenceId`. this should work and clicking into the response should display all related data. 
- [ ] Search for a response using an invalid/partial `referenceId`. There should be no responses displayed.
- [ ] Clicking into a single response should work and display all data correctly.

**Comment by karrui** [comment]
## Tests
**Prerequisites**
- Create email form with email field that has autoreply toggled
- Create storage mode form with email field that has autoreply toggled
### IE 11 public facing submission
- [ ] Can access email form
- [ ] Can submit email form
- [ ] For email forms, should receive autoreply email (with pdf if toggled)
  - [ ] As admin, should receive submission email
- [ ] For storage forms, should receive autoreply email
  - [ ] As admin, check responses tab and a new submission should have been made. (no need to be on IE11)
  - [ ] As admin, response should be decrypt-able (no need to be on IE11)
- [ ] Should be able to submit feedback (check on admin side)

**Comment by tshuli** [comment]
## Tests

## Extra logging for form updates
- [ ] Create a form with short text field. Edit the field. Check that the edit action shows up in the logs with details of the edit under `body` meta.

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
