### PR TITLE
build: Release 4.45.0

### PR DESCRIPTION
**Pull request by tshuli**
**New**
- feat: deprecate MYINFO_APP_KEY [`#557`](https://github.com/opengovsg/FormSG/pull/557)
- feat: display a Toast when reCAPTCHA fails while users are filling up a form [`#582`](https://github.com/opengovsg/FormSG/pull/582)

**Improvements**
- chore:   set datepicker default view to minimum date [`#574`](https://github.com/opengovsg/FormSG/pull/574)
- chore: shift webhook field   to bottom of settings page, update copy [`#553`](https://github.com/opengovsg/FormSG/pull/553)
- feat: move public spcp login form messaging [`#589`](https://github.com/opengovsg/FormSG/pull/589)
- feat: remove exclamation when user updates contact [`#586`](https://github.com/opengovsg/FormSG/pull/586)
- feat: update landing page footer [`#584`](https://github.com/opengovsg/FormSG/pull/584)
- feat:   use auth middleware to protect routes [`#568`](https://github.com/opengovsg/FormSG/pull/568)
- refactor: convert MyInfo hash update to static domain method [`#562`](https://github.com/opengovsg/FormSG/pull/562)
- refactor: hash uinFin in domain layer [`#596`](https://github.com/opengovsg/FormSG/pull/596)
- refactor: migrate GET /adminform endpoint to Typescript [`#575`](https://github.com/opengovsg/FormSG/pull/575)
- refactor: validate MyInfo env vars using Convict [`#559`](https://github.com/opengovsg/FormSG/pull/559)

**Fixes**
- fix: overflow when printing responses [`#585`](https://github.com/opengovsg/FormSG/pull/585)

**Dependencies**
- feat: upgrade myinfo-gov-client [`#593`](https://github.com/opengovsg/FormSG/pull/593)
- fix(deps): bump @sentry/integrations from 5.25.0 to 5.27.3 [`#600`](https://github.com/opengovsg/FormSG/pull/600)
- fix(deps): bump angular-cookies from 1.8.1 to 1.8.2 [`#590`](https://github.com/opengovsg/FormSG/pull/590)
- chore(deps-dev): bump @babel/preset-env from 7.11.5 to 7.12.1 [`#599`](https://github.com/opengovsg/FormSG/pull/599)
- chore(deps-dev): bump @types/node from 14.11.2 to 14.14.6 [`#588`](https://github.com/opengovsg/FormSG/pull/588)
- chore(deps-dev): bump axios-mock-adapter from 1.18.2 to 1.19.0 [`#598`](https://github.com/opengovsg/FormSG/pull/598)
- chore(deps-dev): bump eslint-plugin-import from 2.22.0 to 2.22.1 [`#580`](https://github.com/opengovsg/FormSG/pull/580)
- chore(deps-dev): bump jasmine from 3.6.2 to 3.6.3 [`#587`](https://github.com/opengovsg/FormSG/pull/587)
- chore(deps-dev): bump jest from 26.5.3 to 26.6.2 [`#570`](https://github.com/opengovsg/FormSG/pull/570)
- chore(deps-dev): bump ngrok from 3.2.7 to 3.3.0 [`#578`](https://github.com/opengovsg/FormSG/pull/578)

### CODE REVIEW

**Comment by tshuli** [comment]
** deprecate MYINFO_APP_KEY**
- [ ] Create form with myinfo field. Check that form can be filled in and submitted successfully.

** set datepicker default view to minimum date**

- [ ] Create date field. Set custom date range with minimum date in the distant past (e.g. 2015). Open the form in public view. Check that the datepicker opens to the month of the minimum date by default. 
- [ ] Create date field with no date validation. Open in public view. Check that the datepicker opens to the current month by default.
- [ ] Check that date fields can be filled in and submitted successfully

**Comment by tshuli** [comment]
**shift webhook field to bottom of settings page**
- [ ] Create storage mode form. Add any webhook url. Submit form. Check in the logs that attempt was made to post the response to webhook url.

**move public spcp login form messaging**
- [ ] Create form with myinfo field. Test that the messaging shows up correctly in [public view](https://github.com/opengovsg/FormSG/pull/589) _Note: for Myinfo error message, can use the faulty accounts in 1pw_

**remove exclamation when user updates contact**
- [ ] Log in and add emergency contact. Check that the exclamation disappears once the emergency contact has been added without need for page refresh.

** update landing page footer**

- [ ] Check that landing page footer displays [correctly](https://github.com/opengovsg/FormSG/pull/584)

**Comment by tshuli** [comment]
**overflow when printing responses**
- [ ] Create storage mode form. Add 10 short text fields. Submit. Open submitted response in response tab. Check that all responses are captured in print preview.

**Comment by tshuli** [comment]
**Run through on IE / Intranet**
_General run through_
- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your GSIB inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.
- [ ] Create form with MyInfo fields. Submit successfully

**Comment by tshuli** [comment]
**Run through on IE / Intranet**
_Specific_

**overflow when printing responses**
- [ ] Create storage mode form. Add 10 short text fields. Submit. Open submitted response in response tab. Check that all responses are captured in print preview.


**deprecate MYINFO_APP_KEY**
- [ ] Create form with ALL myinfo fields. Check that form can be filled in and submitted successfully.

**set datepicker default view to minimum date**

- [ ] Create date field. Set custom date range with minimum date in the distant past (e.g. 2015). Open the form in public view. Check that the datepicker opens to the month of the minimum date by default. 
- [ ] Create date field with no date validation. Open in public view. Check that the datepicker opens to the current month by default.
- [ ] Check that date fields can be filled in and submitted successfully

**shift webhook field to bottom of settings page**
- [ ] Create storage mode form. Add any webhook url. Submit form. Check in the logs that attempt was made to post the response to webhook url.

**move public spcp login form messaging**
- [ ] Create form with myinfo field. Test that the messaging shows up correctly in [public view](https://github.com/opengovsg/FormSG/pull/589) _Note: for Myinfo error message, can use the faulty accounts in 1pw_

**remove exclamation when user updates contact**
- [ ] Log in and add emergency contact. Check that the exclamation disappears once the emergency contact has been added without need for page refresh.

**update landing page footer**

- [ ] Check that landing page footer displays [correctly](https://github.com/opengovsg/FormSG/pull/584)

**Review by karrui — APPROVED** [review]

**Pull request merged**
