### PR TITLE
feat(deps): update mongoose to v6.0.13, update mongoose dependencies likewise

### PR DESCRIPTION
**Pull request by karrui**
## Problem

Updating mongoose is a larger undertaking than the usual dependency updates, as it has a bunch of peer dependencies that needs to be updated in tandem. Below notes the upgrades of the dependencies:

**Deps**
- `mongoose`: from `5.13.5` to `6.0.13`
- `bson-ext`: from `2.0.5` to `4.0.2`
- `connect-mongo`:  from `4.4.1` to `4.6.0`
- `mongodb`:  from `null` to `4.1.4` (for types)

**Devdeps**
- `mongodb-memory-server-core`: from `6.9.6` to `8.0.2`
- `mockingoose` from `2.13.2` to `null` (underused and unneeded)

## Solution

**Breaking Changes** 

- [ ] Yes - this PR contains breaking changes
- [x] No - this PR is backwards compatible  
  - Should be backwards compatible, only changes are serverside (and mostly typing changes)

**Bug Fixes**:

- fix(FormModel): update schema validators to 6.x syntax
- fix(config): use ConnectOptions type declaration from mongoose@6
- fix(config): remove unsupported options (now default) 
- fix: misc type errors due to mongoose@6
- fix(UserModel): update schema to fit new syntax and MongoServerError
- fix(FormModel): move esrvcId schema prop to be above status 
- fix(MyInfoModel): use Mixed type instead of undocumented Object type
- fix(tests): update instantiation of test db
- fix(e2e): correctly return promise of mongoose.createConnection
- fix(tests): update mongoose toEqual matchers to toMatchObject matchers 
- fix(test): fix failing tests due to immutable create field 

## Tests

Tests have been updated.

### CODE REVIEW

**Comment by karrui** [comment]
I'm going to kill off testcafe; we are moving towards cypress soon anyways.

**Comment by karrui** [comment]
This PR causes an unhandled error when submitting a table field on email mode; investigating

**Comment by karrui** [comment]
Seems to be a bug with nested discriminators, Table column types are not being created properly

**Comment by karrui** [comment]
Ready for review. All functionality tested to be working on staging and locally.

**Review by tshuli — APPROVED** [review]

**Pull request merged**
