### PR TITLE
feat(form-v2): replace icon with BiHomeCircle

### PR DESCRIPTION
**Pull request by tohhengxing**
## Problem

"The icons for UEN and MyInfo registered address fields are identical under the Build tab. The icon for "Registered Address" should be changed to bx-home-circle as per @pearlyong's recommendation." as per issue #2166

Closes [#2166]

## Solution
update the icon to the correct one

**Breaking Changes** 

- [x] No - this PR is backwards compatible  

## Before & After Screenshots

**BEFORE**:
<details>
<summary>before</summary>

image
</details>

**AFTER**:
<details>
<summary>after</summary>

image
</details>

### CODE REVIEW

**Comment by karrui** [comment]
@tohhengxing thanks for the contribution!

@pearlyong looking at the screen shots the icon for MyInfo mobile number seems to also be wrong. Should it be changed to `BiMobile` for consistency?

**Comment by karrui** [comment]
Reopening and closing to hopefully trigger CI/CD

**Comment by pearlyong** [comment]
yes, can change to Mobile icon. thanks!

**Comment by tohhengxing** [comment]
hi, as requested

<details>
<summary>bimobile</summary>

image
</details>

**Review by timotheeg — APPROVED** [review]

**Pull request merged**
