### PR TITLE
build: release v6.43.0

### PR DESCRIPTION
**Pull request by LinHuiqing**
## New

- fix: normalize email field values to lowercase [`#6163`](https://github.com/opengovsg/FormSG/pull/6163)
- fix: lift mongoose sessions for copying submissions to Stripe webhook handler level [`#6157`](https://github.com/opengovsg/FormSG/pull/6157)
- build: merge release v6.42.2 to develop [`#6165`](https://github.com/opengovsg/FormSG/pull/6165)
- feat(admin): add invoice url on response page [`#6137`](https://github.com/opengovsg/FormSG/pull/6137)
- feat: add formId to payment document [`#6158`](https://github.com/opengovsg/FormSG/pull/6158)
- feat: send payment confirmation email with invoice receipt [`#6145`](https://github.com/opengovsg/FormSG/pull/6145)
- fix: add missing context provider on endpagedrawer and paymentdrawer [`#6160`](https://github.com/opengovsg/FormSG/pull/6160)
- refactor: scope drawer width change only to affected components [`#6076`](https://github.com/opengovsg/FormSG/pull/6076)
- build: merge release v6.42.0 to develop  [`#6150`](https://github.com/opengovsg/FormSG/pull/6150)
- feat: normalize payment contact email on backend [`9f1a2b5`](https://github.com/opengovsg/FormSG/commit/9f1a2b5ae47dc7276701b91f6444e153c9a95bf3)

## Dependencies

- fix(deps): bump vm2 from 3.9.16 to 3.9.17 [`#6162`](https://github.com/opengovsg/FormSG/pull/6162)

### fix: normalize email field values to lowercase [`#6163`](https://github.com/opengovsg/FormSG/pull/6163)
@KenLSM 

- [x] On an email field, type any email with a variety in terms of upper-/lower-case. Regardless of whether the entered input is upper or lower case, the output on the field should be lower-case.
- [x] On a payment contact field, type any email with a variety in terms of upper-/lower-case. Regardless of whether the entered input is upper or lower case, the output on the field should be lower-case.
- [x] Submit a form with at least 1 email field and the payment contact email field. After submission, the emails should be saved correctly in the DB.

### feat(admin): add invoice url on response page [`#6137`](https://github.com/opengovsg/FormSG/pull/6137)

@foochifa 
- [x] new feature tests
  - [x] payments with completed payments should see URL and can download a well-formed invoice
  - [x] download csv should contain a well-formed invoice url  on payment forms
- [x] regressive tests
  - [x] download csv should still work on non-payment forms 

### feat: add formId to payment document [`#6158`](https://github.com/opengovsg/FormSG/pull/6158)

@LinHuiqing 
- [x] Fill in a payment form, select proceed to pay
- [x] Go to DB and ensure the payment document has formId in it and that its the correct form
- [x] Complete the payment (make sure webhook listener is on)
- [x] Go to DB and check that payment document has been successfully updated with completedPayment. And that formId still exists

### feat: send payment confirmation email with invoice receipt [`#6145`](https://github.com/opengovsg/FormSG/pull/6145)

@KenLSM 
Submit a payment on a payment form. Then,
- [x] Upon successful payment, you should be able to save the payment invoice on the "Your payment has been made successfully" page.
- [x] Upon successful payment, you should also receive an email titled `Your payment on FormSG was successful`. The email contents should include the **form title**, **response ID** and a **link to the payment invoice**.
  - [x] Clicking the link to the payment invoice should download it to your device

### fix: add missing context provider on endpagedrawer and paymentdrawer [`#6160`](https://github.com/opengovsg/FormSG/pull/6160)

@foochifa 
- [x] Admin View storage forms
  - [x] with payments enabled, payment drawer should be able to open and close
  - [x] EndPageDrawer should be able to open and close
- [x] Admin View email forms
  - [x] EndPageDrawer should be able to open and close
- [x] Admin View general regression
  - [x] CreateAndBuildDrawer should be able to open and close
  - [x] Form Preview should render without errors

### CODE REVIEW

**Review by KenLSM — APPROVED** [review]

**Comment by KenLSM** [comment]
> On an email field, type any email with a variety in terms of upper-/lower-case. 

If I manually insert a capital letter in a non-ending position of the string, my input cursor will pop all the way at the back.
Non-blocking, issue as this is only for inserting a capital letter during an edit.

Introduced in #6163

**Comment by foochifa** [comment]
image
Shouldnt this say 'Invoice' instead of 'Receipt'? Can be quite confusing as the link leads to an Invoice download

Similarly for the CSV, the column name is still 'Receipt'

**Comment by KenLSM** [comment]
> image
> 
> Shouldnt this say 'Invoice' instead of 'Receipt'? Can be quite confusing as the link leads to an Invoice download
> Similarly for the CSV, the column name is still 'Receipt'

Mentioned here https://github.com/opengovsg/FormSG/pull/6137#issuecomment-1515874729
But now with two people giving feedback, I guess the copy should be changed...?

**Comment by LinHuiqing** [comment]
We'll leave the copy change ("Receipt" vs "Invoice") up to design / product and after Monday's release bah! (cc: @amitogp @staceytan1998)

**Comment by wanlingt** [comment]
> We'll leave the copy change ("Receipt" vs "Invoice") up to design / product and after Monday's release bah! (cc: @amitogp @staceytan1998)

sounds good to me, dont think it's a blocker for release

**Comment by LinHuiqing** [comment]
Oh btw I added a comment asking about the copy change on [figma](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti?node-id=16236:159983#426365144)!

**Comment by LinHuiqing** [comment]
Okays as [per replied](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti?node-id=16236:159983#426365144), let's change it to "Invoice" 👍

**Pull request merged**
