### PR TITLE
build: release v5.8.0

### PR DESCRIPTION
**Pull request by mantariksh**
## New
- feat(spcp): raise sp cookie max age to 3 hrs [`#1727`](https://github.com/opengovsg/FormSG/pull/1727)
- feat: Add a limit for the number of MyInfo fields that can be added [`#1664`](https://github.com/opengovsg/FormSG/pull/1664)
- feat: prefill mainstream launch [`#1702`](https://github.com/opengovsg/FormSG/pull/1702)

## Fixes
- fix: show correct error message for e-service ID validation [`#1722`](https://github.com/opengovsg/FormSG/pull/1722)
- fix: remove verified prefix on blank verified fields [`#1701`](https://github.com/opengovsg/FormSG/pull/1701)

## Improved
- feat(client): log client form reCAPTCHA failure to GA [`#1684`](https://github.com/opengovsg/FormSG/pull/1684)
- feat(api): collapse spcp/myinfo redirect endpoint to new endpoint [`#1672`](https://github.com/opengovsg/FormSG/pull/1672)
- chore(admin-forms-routes): remove duplicate logic route endpoint [`#1703`](https://github.com/opengovsg/FormSG/pull/1703)
- feat(api-refactor): implement specific reorder field api [`#1726`](https://github.com/opengovsg/FormSG/pull/1726)
- chore(admin-forms-routes): remove duplicate logic route endpoint [`#1703`](https://github.com/opengovsg/FormSG/pull/1703)
- fix(mongoose): use official discriminator definitions [`#1704`](https://github.com/opengovsg/FormSG/pull/1704)
- fix: sync email field state between hasAllowedEmailDomains and allowedEmailDomains [`#1697`](https://github.com/opengovsg/FormSG/pull/1697)
- refactor(preview-api): duplicate adminform presign endpoints for /api/v3 [`#1644`](https://github.com/opengovsg/FormSG/pull/1644)
- feat(webhooks): streamline webhook response data [`#1696`](https://github.com/opengovsg/FormSG/pull/1696)
- refactor: Extract delete logic endpoint [`#1586`](https://github.com/opengovsg/FormSG/pull/1586)
- refactor(preview-api): duplicate adminform preview endpoints for /api/v3 [`#1643`](https://github.com/opengovsg/FormSG/pull/1643)
- feat(api-refactor): implement specific create field api [`#1671`](https://github.com/opengovsg/FormSG/pull/1671)
- feat(api-refactor): add specific API for updating of single form field [`#1640`](https://github.com/opengovsg/FormSG/pull/1640)
- refactor: shard public forms router [`#1669`](https://github.com/opengovsg/FormSG/pull/1669)
- feat(admin-forms): implement retrieval of form settings [`#1633`](https://github.com/opengovsg/FormSG/pull/1633)
- refactor: migrate submissions metadata [`#1651`](https://github.com/opengovsg/FormSG/pull/1651)
- fix: convert form field responses to field class  [`#1739`](https://github.com/opengovsg/FormSG/pull/1739)
- refactor(test): integration and unit tests for redirect  [`#1728`](https://github.com/opengovsg/FormSG/pull/1728)
- fix: update MyInfo field count correctly, show correct error [`#1738`](https://github.com/opengovsg/FormSG/pull/1738)
- refactor: use shared DateSelectedValidation enum instead of DATE_VALIDATION_OPTIONS object [`#1724`](https://github.com/opengovsg/FormSG/pull/1724)

## Dependency upgrades
- chore(deps-dev): bump @types/jest from 26.0.22 to 26.0.23 [`#1735`](https://github.com/opengovsg/FormSG/pull/1735)
- chore(deps-dev): bump eslint-plugin-jest from 24.3.5 to 24.3.6 [`#1734`](https://github.com/opengovsg/FormSG/pull/1734)
- build(deps): bump mockpass and spcp-auth-client [`#1723`](https://github.com/opengovsg/FormSG/pull/1723)
- fix(deps): bump @sentry/browser from 6.3.0 to 6.3.1 [`#1719`](https://github.com/opengovsg/FormSG/pull/1719)
- chore(deps-dev): bump eslint-config-prettier from 8.2.0 to 8.3.0 [`#1716`](https://github.com/opengovsg/FormSG/pull/1716)
- chore(deps-dev): bump stylelint-config-standard from 21.0.0 to 22.0.0 [`#1720`](https://github.com/opengovsg/FormSG/pull/1720)
- fix(deps): bump @sentry/integrations from 6.3.0 to 6.3.1 [`#1718`](https://github.com/opengovsg/FormSG/pull/1718)
- chore(deps-dev): bump eslint from 7.24.0 to 7.25.0 [`#1717`](https://github.com/opengovsg/FormSG/pull/1717)
- chore(deps-dev): bump stylelint from 13.12.0 to 13.13.0 [`#1715`](https://github.com/opengovsg/FormSG/pull/1715)
- fix(deps): bump aws-sdk from 2.890.0 to 2.892.0 [`#1714`](https://github.com/opengovsg/FormSG/pull/1714)
- fix(deps): bump twilio from 3.60.0 to 3.61.0 [`#1711`](https://github.com/opengovsg/FormSG/pull/1711)
- fix(deps): bump aws-sdk from 2.889.0 to 2.890.0 [`#1710`](https://github.com/opengovsg/FormSG/pull/1710)
- chore(deps-dev): bump core-js from 3.10.2 to 3.11.0 [`#1709`](https://github.com/opengovsg/FormSG/pull/1709)
- fix(deps): bump @babel/runtime from 7.13.16 to 7.13.17 [`#1700`](https://github.com/opengovsg/FormSG/pull/1700)
- fix(deps): bump @sentry/integrations from 6.2.5 to 6.3.0 [`#1690`](https://github.com/opengovsg/FormSG/pull/1690)
- chore(deps-dev): bump @babel/core from 7.13.15 to 7.13.16 [`#1692`](https://github.com/opengovsg/FormSG/pull/1692)
- fix(deps): bump aws-sdk from 2.888.0 to 2.889.0 [`#1691`](https://github.com/opengovsg/FormSG/pull/1691)
- fix(deps): bump @babel/runtime from 7.13.10 to 7.13.16 [`#1689`](https://github.com/opengovsg/FormSG/pull/1689)
- fix(deps): bump validator from 13.5.2 to 13.6.0 [`#1688`](https://github.com/opengovsg/FormSG/pull/1688)
- fix(deps): bump @sentry/browser from 6.2.5 to 6.3.0 [`#1687`](https://github.com/opengovsg/FormSG/pull/1687)
- fix(deps): bump fp-ts from 2.10.3 to 2.10.4 [`#1686`](https://github.com/opengovsg/FormSG/pull/1686)

### CODE REVIEW

**Comment by mantariksh** [comment]
## Tests
**Singpass/MyInfo cookie expiry**
- [ ] Check that after logging into Singpass with "Keep me logged in" checked, the `jwtSp` cookie expiry is set to 1 month
- [ ] Check that after logging into Singpass without "Keep me logged in" checked, the `jwtSp` cookie expiry is set to 3 hours
- [ ] Check that after logging into Corppass, the `jwtCp` cookie expiry is set to 6 hours.
- [ ] Log in to a MyInfo form with a MyInfo name field. Search the `myinfohashes` collection for the hashes corresponding to your login. Check that the document's `expireAt` is 3 hours later.

**Comment by mantariksh** [comment]
## Tests
**MyInfo field limit**
- [ ] Add 30 MyInfo fields to a form.
- [ ] Check that under the build tab, MyInfo fields can no longer be added
- [ ] Check that MyInfo fields cannot be duplicated
- [ ] Delete a Myinfo field (such that the form now has <30) and check that you can now add and duplicate Myinfo fields
- [ ] Manually add an additional MyInfo field to the form by editing the database. Check that when you try to edit the form subsequently, you get an error message saying to check that the form has max 30 MyInfo fields.
- [ ] Run the following query to ensure that there are no existing forms with >30 MyInfo fields:
```
db.getMongo().setReadPref('secondary')
db.getCollection('forms').aggregate([
    { $match: { 'form_fields.myInfo': { $exists: true } } },
    { $unwind: '$form_fields' },
    { $match: { 'form_fields.myInfo': { $exists: true } } },
    { $group: { _id: '$_id', count: { $sum: 1 } } },
    { $match: { count: { $gt: 30 } } }
])
```
- [ ] **After release has been deployed**, run the above query again to check that there are still no forms with >30 MyInfo fields. If there are, the form admin must be contacted.

**Comment by mantariksh** [comment]
## Tests
**E-service ID validation**
- [ ] Attempt to activate a Singpass form with an invalid e-service ID. The error message should say that Singpass returned error code 138.
- [ ] Repeat above test for MyInfo form.

**Comment by mantariksh** [comment]
## Tests
**Blank verified fields**
- [ ] Create an email mode form with optional verified email and mobile fields. Submit the form without filling in both fields. The response email should not have the "[verified]" prefix for either field.
- [ ] Repeat with storage mode form. The data tab should not have the "[verified]" prefix for either field. (no need to check CSV as it has no prefixes anyway)
- [ ] Repeat email mode test but fill in both fields. The [verified] prefix should now be present for both fields.
- [ ] Repeat with storage mode form.

**Comment by mantariksh** [comment]
## Tests
**Reorder fields**
- [ ] Turn off network (from chrome devtools) and attempt to reorder a field. An error toast should occur and the form field ordering should revert to initial ordering
- [ ] Reorder a field. The returned form_fields shape should be the new ordering.
- [ ] Open two builder tabs in your browser for the same form (with at least 2 initial fields). Add a field on the second tab (should now have +1 fields). Go back to the first tab (with the initial field count) and reorder the fields. 3 fields should show up but correctly ordered.

**Comment by mantariksh** [comment]
## Tests
**hasAllowedEmailDomains**
### Manual Tests
- [ ] Create an email field with OTP verification toggled on, then toggle on Restrict email domains, then fill in the allowed domains. Save the field. The returned field from the network request should contain 
  - `isVerifiable=true`, 
  - `hasAllowedEmailDomains=true`, 
  - `allowedEmailDomains=[<whatever you filled in>]`
- [ ] For the same field, toggle off OTP verification. Restrict email domains should automatically be toggled off and a toast for restrict email domains should show up. Save the field. The returned field from the network request should contain
  - `isVerifiable=false`,
  - `hasAllowedEmailDomains=false`,
  - `allowedEmailDomains=[]` // empty array
- [ ] For the same field, toggle OTP verification back on and save the field. The returned field should contain
  - `isVerifiable=true`,
  - `hasAllowedEmailDomains=false`,
  - `allowedEmailDomains=[]`

### Manual Tests (Programmatic)
Programatically submit an field creation request to the OLD endpoint (or copy and paste the below body snippet changing the `formId` to a form that you control): 

`POST <baseUrl>/<formId>/adminform`

```
{
  "form": {
    "editFormField": {
      "action": {
        "name": "CREATE"
      },
      "field": {
        "required": true,
        "disabled": false,
        "autoReplyOptions": {
          "hasAutoReply": false,
          "autoReplyMessage": "",
          "includeFormSummary": false
        },
        "isVerifiable": false,
        "hasAllowedEmailDomains": true,
        "allowedEmailDomains": [],
        "fieldName": "Email",
        "title": "Email",
        "fieldType": "email",
      }
    }
  }
}
```

Note the body is mimicking state 1 in the table above, where hasAllowedEmailDomains is true, but the array is empty. 
- [ ] The returned form field should manipulate the created field into state 4, a valid state
- [ ] Change the above body snippet to `hasAllowedEmailDomains=false` with a non-empty `allowedEmailDomains` array value. The returned form field should manipulate the created field also into state 4, since hasAllowedEmailDomains is false.

**Comment by mantariksh** [comment]
## Tests
**Image/logo API refactor**
- [ ] Check that logos can be uploaded to a form's header (POST /api/v3/admin/forms/:formId/logos/presign)
- [ ] Check that images can be uploaded to a form image component (POST /api/v3/admin/forms/:formId/images/presign)

**Comment by mantariksh** [comment]
## Tests
**Streamline webhook response data**
- [ ] Set up a server to receive webhooks which only returns 4xx. Submit a webhooked form and check that the response status code, data, headers, webhook URL and signature are reflected in the submission document.
- [ ] Repeat with a server which returns 2xx.

**Comment by mantariksh** [comment]
## Tests
**Logic API refactor**
- Create a form with single logic. 
  - [ ] Check that delete logic works on admin view Logic Tab. The network call should return 200.
  - [ ] Repeat the above with multiple logic. Check that only one logic is deleted.
- Test using manual API calls
  - [ ] Check that new delete endpoint `DELETE /forms/:formId/logic/:logicId` returns 200 when formId and logicId are correct and that the specific logicId is deleted from db
  - [ ] Check that endpoint returns 404 when formId or logicId are incorrect

**Comment by mantariksh** [comment]
## Tests
**Preview endpoint API refactor**
- [ ] Check that forms can be previewed as admin (GET /api/v3/admin/forms/:formId/preview)
- [ ] Check that previewed forms in email mode can be submitted and an email response is received (POST /api/v3/admin/forms/:formId/preview/submissions/email)
- [ ] Check that previewed forms in encrypt mode can be submitted (POST /api/v3/admin/forms/:formId/preview/submissions/encrypt)

**Comment by mantariksh** [comment]
## Tests
**Create field API refactor**
- [ ] Create a new field. Should be created successfully. Network tab should show a call to the new endpoint.
- [ ] Create a new MyInfo field. Should be created successfully. Network tab should show a call to the new endpoint.

**Comment by mantariksh** [comment]
## Tests
**Update field API refactor**
- [ ] Create a new field and then edit and save it. The field should successfully be updated (go into the field and check again)
  - [ ] Update image fields (change image). Should update correctly.
  - [ ] Update attachment fields (size, description, etc). Should update correctly.
  - [ ] Try a sample various variants of other fields. All should be successfully saved.
- [ ] Create a new myinfo field and then edit and save it. The field should be "updated" without changes

**Comment by mantariksh** [comment]
## Tests
**Submissions metadata API refactor**
- [ ] Create a storage mode form and activate it. Submit **>10** responses to the form. Go to the admin panel and click on data
    - Verify that clicking on any page returns a list of responses  
    - Verify that searching on any single response id returns exactly that response   
    - Verify that searching on any substring of a response id returns nothing

**Comment by mantariksh** [comment]
@mantariksh
## Tests

**Intranet IE11 runthrough**
- [ ] Create email mode form with all fields and custom start/end page. Activate and submit form. Check that you can receive responses in your intranet inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields and custom start/end page. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments for individual fields can be downloaded from Data tab in storage mode.
- [ ] Attachment ZIP for submission can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Comment by mantariksh** [comment]
@mantariksh 
## Tests
**Prefill feature**
- [ ] Create two short text fields and set prefill toggle to true. Open form in public view. Check that the fields are prefillable by adding the query params to URL
- [ ] Check that prefill fields are highlighted in yellow
- [ ] Check that warning label appears if there are prefillable fields on form, and does not appear if there are no prefillable fields on form
- [ ] Hide prefill field with logic. Check that warning label only appears when field is visible.

**Comment by mantariksh** [comment]
## Tests
**Form/field interceptor migration**
- [ ] Create a table field and save it. Without refreshing, edit the table field again. The table should be rendered properly and changes should be saved successfully.
- [ ] Create a Race MyInfo field. When saving it, check the network request. The body should contain the following empty key-values: 
```
fieldName: ""
fieldOptions: []
fieldType: "dropdown"
fieldValue: ""
```
- [ ] Update the same MyInfo field. The network request body should look the same.

**Review by karrui — APPROVED** [review]

**Review by karrui — APPROVED** [review]

**Pull request merged**
