### PR TITLE
build: release v4.59.0

### PR DESCRIPTION
**Pull request by karrui**
## Features
-   feat: use textarea for providing checkbox options   [`#962`](https://github.com/opengovsg/FormSG/pull/962)

## Refactors
-   ref: migrate update form flow to TypeScript   [`#883`](https://github.com/opengovsg/FormSG/pull/883)
-   refactor: migrate email validator to ts   [`#1126`](https://github.com/opengovsg/FormSG/pull/1126)
-   refactor: migrate number validator to typescript   [`#1145`](https://github.com/opengovsg/FormSG/pull/1145)
-   refactor: migrate preview admin form endpoint to Typescript   [`#864`](https://github.com/opengovsg/FormSG/pull/864)
-   refactor: move addLogin method to Billing module   [`#1195`](https://github.com/opengovsg/FormSG/pull/1195)

## Improvements
-   fix: agency logo on development environment   [`#1182`](https://github.com/opengovsg/FormSG/pull/1182)

## Dependency updates
-   fix(deps): bump @babel/runtime from 7.12.13 to 7.12.18   [`#1194`](https://github.com/opengovsg/FormSG/pull/1194)
-   fix(deps): bump @sentry/browser from 6.1.0 to 6.2.0   [`#1188`](https://github.com/opengovsg/FormSG/pull/1188)
-   fix(deps): bump @sentry/integrations from 5.30.0 to 6.2.0   [`#1142`](https://github.com/opengovsg/FormSG/pull/1142) [`#1198`](https://github.com/opengovsg/FormSG/pull/1198)
-   fix(deps): bump aws-sdk from 2.844.0 to 2.848.0   [`#1179`](https://github.com/opengovsg/FormSG/pull/1179)[`#1192`](https://github.com/opengovsg/FormSG/pull/1192)[`#1203`](https://github.com/opengovsg/FormSG/pull/1203)
-   fix(deps): bump express-rate-limit from 5.2.3 to 5.2.6   [`#1166`](https://github.com/opengovsg/FormSG/pull/1166)[`#1178`](https://github.com/opengovsg/FormSG/pull/1178)
-   fix(deps): bump express-winston from 4.0.5 to 4.1.0   [`#1197`](https://github.com/opengovsg/FormSG/pull/1197)
-   fix(deps): bump libphonenumber-js from 1.9.8 to 1.9.11   [`#1138`](https://github.com/opengovsg/FormSG/pull/1138)
-   fix(deps): bump lodash from 4.17.20 to 4.17.21   [`#1205`](https://github.com/opengovsg/FormSG/pull/1205)
-   fix(deps): bump neverthrow from 4.0.1 to 4.1.0   [`#1170`](https://github.com/opengovsg/FormSG/pull/1170)
-   fix(deps): bump nodemailer from 6.4.17 to 6.4.18   [`#1143`](https://github.com/opengovsg/FormSG/pull/1143)
-   fix(deps): bump twilio from 3.55.0 to 3.56.0   [`#1164`](https://github.com/opengovsg/FormSG/pull/1164)
-   fix(deps): bump whatwg-fetch from 3.5.0 to 3.6.1   [`#1187`](https://github.com/opengovsg/FormSG/pull/1187)
-   chore: use formsg-sdk beta release   [`#1219`](https://github.com/opengovsg/FormSG/pull/1219)
-   chore(deps-dev): bump @babel/core from 7.12.16 to 7.12.17   [`#1185`](https://github.com/opengovsg/FormSG/pull/1185)
-   chore(deps-dev): bump @babel/plugin-transform-runtime   [`#1190`](https://github.com/opengovsg/FormSG/pull/1190)
-   chore(deps-dev): bump @babel/preset-env from 7.12.13 to 7.12.17   [`#1155`](https://github.com/opengovsg/FormSG/pull/1155)[`#1196`](https://github.com/opengovsg/FormSG/pull/1196)
-   chore(deps-dev): bump @opengovsg/mockpass from 2.6.2 to 2.6.3   [`#1184`](https://github.com/opengovsg/FormSG/pull/1184)
-   chore(deps-dev): bump @types/ejs from 3.0.5 to 3.0.6   [`#1150`](https://github.com/opengovsg/FormSG/pull/1150)
-   chore(deps-dev): bump @types/mongodb from 3.6.5 to 3.6.8   [`#1162`](https://github.com/opengovsg/FormSG/pull/1162)[`#1189`](https://github.com/opengovsg/FormSG/pull/1189)
-   chore(deps-dev): bump @types/node from 14.14.22 to 14.14.31   [`#1154`](https://github.com/opengovsg/FormSG/pull/1154)[`#1191`](https://github.com/opengovsg/FormSG/pull/1191)[`#1207`](https://github.com/opengovsg/FormSG/pull/1207)
-   chore(deps-dev): bump @typescript-eslint/eslint-plugin   [`#1163`](https://github.com/opengovsg/FormSG/pull/1163)
-   chore(deps-dev): bump @typescript-eslint/parser from 4.15.0 to 4.15.1   [`#1148`](https://github.com/opengovsg/FormSG/pull/1148)
-   chore(deps-dev): bump concurrently from 5.3.0 to 6.0.0   [`#1202`](https://github.com/opengovsg/FormSG/pull/1202)
-   chore(deps-dev): bump core-js from 3.8.3 to 3.9.0   [`#1193`](https://github.com/opengovsg/FormSG/pull/1193)
-   chore(deps-dev): bump csv-parse from 4.15.1 to 4.15.3   [`#1213`](https://github.com/opengovsg/FormSG/pull/1213)
-   chore(deps-dev): bump eslint from 7.19.0 to 7.20.0   [`#1168`](https://github.com/opengovsg/FormSG/pull/1168)
-   chore(deps-dev): bump eslint-config-prettier from 7.2.0 to 8.0.0   [`#1204`](https://github.com/opengovsg/FormSG/pull/1204)
-   chore(deps-dev): bump eslint-plugin-jest from 24.1.3 to 24.1.5   [`#1180`](https://github.com/opengovsg/FormSG/pull/1180)
-   chore(deps-dev): bump form-data from 3.0.0 to 4.0.0   [`#1167`](https://github.com/opengovsg/FormSG/pull/1167)
-   chore(deps-dev): bump stylelint from 13.10.0 to 13.11.0   [`#1206`](https://github.com/opengovsg/FormSG/pull/1206)
-   chore(deps-dev): bump testcafe from 1.10.1 to 1.11.0   [`#1165`](https://github.com/opengovsg/FormSG/pull/1165)
-   chore(deps-dev): bump ts-jest from 26.5.0 to 26.5.1   [`#1161`](https://github.com/opengovsg/FormSG/pull/1161)

## Misc
-   build(mongodb): tests should run on mongo v4.0.22   [`#1173`](https://github.com/opengovsg/FormSG/pull/1173)
-   build: Revert "fix/travis: wean off Travis workspaces (#1067)"   [`#1147`](https://github.com/opengovsg/FormSG/pull/1147)
-   chore: set dependabot to run at 1am singapore time   [`#1158`](https://github.com/opengovsg/FormSG/pull/1158)
-   test: add missing modules/verified-content tests   [`#1172`](https://github.com/opengovsg/FormSG/pull/1172)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
### use textarea for providing checkbox options
- [ ] Create a checkbox field. Should be able to create new options like in a dropdown field. Add validation like max selection limit of 1. Should save successfully.
- [ ] Go to form with above checkbox field. Selection limit validation should work. Should be able to submit properly.

**Comment by karrui** [comment]
## Tests
### Backend endpoint refactors

**Comment by karrui** [comment]
## Tests
### Field validator refactors
#### Email
- [ ] Create two email fields. Hide one of them behind logic. Check that normal submission using frontend succeeds for both visible and hidden field when using a valid email domain.
- [ ] Check that domain validation on visible email field works when submitting programatically
  - First, fill in field with valid domain, verify, and then submit using the frontend. Capture the network requests for otp, verify and submission
  - Programatically resubmit for otp and verify using an invalid email domain. After the signature is generated for the invalid domain from the verify endpoint, programatically submit the form using the invalid domain but with the valid signature
  - Submission should fail
- [ ] Check that signature validation on visible email field works when submitting programatically
  - Submit and capture submissions network request. Now modify the signature network request and resubmit programatically
  - Submission should fail
- [ ] Attempt to submit programatically for hidden field using valid domain and signature. Submission should fail.

#### Number
- [ ] Create two number fields. Hide one of them behind logic.
- [ ] Check that validation on both visible and hidden number fields work when submitting programatically
  - [ ] Response is rejected if it contains non numeric characters
  - [ ] Response is rejected if not within the specified length

**Comment by karrui** [comment]
## Tests
### Billing module
- [ ] Create a new SingPass form and log in. Check that a record for the form is added to the Login collection.
- [ ] Repeat above for CorpPass.

**Comment by karrui** [comment]
## Tests
@mantariksh 
**IE11 intranet general run-through**

- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your intranet inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments for individual fields can be downloaded from Data tab in storage mode.
- [ ] Attachment ZIP for submission can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Slightly more specific**
- [ ] Checkbox field options can be added successfully
- [ ] Preview form works properly

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
