### PR TITLE
feat: add range validation to number field

### LINKED ISSUE #378: Add range validation to number field

### PR DESCRIPTION
**Pull request by aniruddha-adhikary**
## Problem
Add range validation to the number field

Closes #378

## Solution

**Breaking Changes** 
- [x] Yes - this PR contains breaking changes
  - New field validation type for number fields in the database, will break application due to unknown field type if rolling back
- [ ] No - this PR is backwards compatible  

**Features**:

- Number field supports Range Validation

## Before & After Screenshots

**BEFORE**:
Screenshot 2021-06-08 at 11 33 56 AM

**AFTER**:
Screenshot 2021-06-08 at 11 31 49 AM

Screenshot 2021-06-08 at 11 37 31 AM

## Tests

There are no unit / e2e tests for this. However, to manually test, follow the steps:

1. Create a new form.
2. Add a Number Field.
3. Choose Range Validation, enter a custom range.
4. Preview Form
5. Any values not between the boundaries would trigger an error message in the frontend.

## Edge cases considered and tested
- Only max no Min
- Only min no Max
- Both min and max
- Neither min or max

### CODE REVIEW

**Comment by karrui** [comment]
@aniruddha-adhikary Thank you so much for your contribution! 

@tshuli, can you check if this change conflicts with #408 (and by extension #2040)?

**Comment by karrui** [comment]
@aniruddha-adhikary #2040 is merged in! Will review after merge conflicts are fixed. Thank you again! :D

**Comment by aniruddha-adhikary** [comment]
@karrui @tshuli I do not have the permissions to request a review through the GitHub UI. Thus requesting a review with a comment :D

**Comment by mantariksh** [comment]
heya @aniruddha-adhikary thanks for the contribution! give us a while to consult the design team on this. I'm worried that putting length validation and range validation in the same dropdown menu might be confusing for users.

**Comment by mantariksh** [comment]
yo @aniruddha-adhikary the [issue](https://github.com/opengovsg/FormSG/issues/378) has been updated with the new design mocks. would you be okay with implementing the new design?

**Comment by aniruddha-adhikary** [comment]
@mantariksh Thanks for the update! Yes, I'll continue on it 👍🏽

**Comment by aniruddha-adhikary** [comment]
@mantariksh looks to be ready for review at this point based on @pearlyong 's design.

**Review by mantariksh — COMMENTED** [review]
some preliminary comments on the schema design, lmk what you think!

**Pull request closed without merging**
