### PR TITLE
build: release v6.59.0

### PR DESCRIPTION
**Pull request by LinHuiqing**
## New

- feat: placeholder landing page for payments [`#6440`](https://github.com/opengovsg/FormSG/pull/6440)
- feat: MyInfo over sgID backend [`#6337`](https://github.com/opengovsg/FormSG/pull/6337)
- feat: migrate banners on React to non-'React'-suffixed env vars [`#6441`](https://github.com/opengovsg/FormSG/pull/6441)
- feat: payment banners on landing and login pages [`#6431`](https://github.com/opengovsg/FormSG/pull/6431)
- chore: remove unused angular deps [`#6438`](https://github.com/opengovsg/FormSG/pull/6438)
- fix: legacy frontend routing [`#6430`](https://github.com/opengovsg/FormSG/pull/6430)
- fix: use payment intent data for preview [`#6432`](https://github.com/opengovsg/FormSG/pull/6432)
- feat: bearer token authentication for public APIs [`#6376`](https://github.com/opengovsg/FormSG/pull/6376)
- build: merge v6.58.0 into develop [`#6429`](https://github.com/opengovsg/FormSG/pull/6429)
- build: release v6.58.0 [`#6423`](https://github.com/opengovsg/FormSG/pull/6423)

## Dependencies

- chore(deps): bump fast-xml-parser, @aws-sdk/client-secrets-manager and @aws-sdk/client-ssm in /functions/form-payment-reconciliation [`#6434`](https://github.com/opengovsg/FormSG/pull/6434)
- fix(deps): bump date-fns from 2.29.3 to 2.30.0 [`#6443`](https://github.com/opengovsg/FormSG/pull/6443)
- build(deps): [Snyk] Security upgrade @aws-sdk/client-cloudwatch-logs from 3.342.0 to 3.347.1 [`#6437`](https://github.com/opengovsg/FormSG/pull/6437)
- chore(deps): bump fast-xml-parser and @aws-sdk/credential-providers in /scripts/20230317_whitespace_issue [`#6433`](https://github.com/opengovsg/FormSG/pull/6433)
- fix(deps): bump libphonenumber-js from 1.10.33 to 1.10.34 in /shared [`#6427`](https://github.com/opengovsg/FormSG/pull/6427)

## Dev-Dependencies

- chore(deps-dev): bump @babel/preset-env from 7.20.2 to 7.22.5 [`#6446`](https://github.com/opengovsg/FormSG/pull/6446)
- chore(deps-dev): bump @playwright/test from 1.29.1 to 1.34.3 [`#6391`](https://github.com/opengovsg/FormSG/pull/6391)
- chore(deps-dev): bump @typescript-eslint/parser from 5.59.8 to 5.59.9 in /shared [`#6428`](https://github.com/opengovsg/FormSG/pull/6428)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.59.8 to 5.59.9 in /shared [`#6426`](https://github.com/opengovsg/FormSG/pull/6426)

### feat: placeholder landing page for payments [`#6440`](https://github.com/opengovsg/FormSG/pull/6440)

@justynoh 

- [x] Check that landing page is as expected on desktop ([design](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17464-183101&t=dHH857IVxtAbRsYj-0)).
- [x] Check that landing page is as expected on mobile.

To check button theme works on banner buttons as well:
- [x] Check that the "Learn more" button in the payments banner on main landing page is okay.
- [x] Check that the "Learn more" button in the payments banner on login page is okay.

### feat: MyInfo over sgID backend [`#6337`](https://github.com/opengovsg/FormSG/pull/6337)
@justynoh 

I've added tests to the sgID adapter to make sure it works. It should automatically be run as part of the existing test suite.

Regression tests:
- [X] myInfo forms (both admin setup/edits + submissions); and
- [X] the “regular” sgid auth (also both admin setup/edits + submissions)

### feat: payment banners on landing and login pages [`#6431`](https://github.com/opengovsg/FormSG/pull/6431)

@justynoh 

Check that new banners work:
- [x] Landing page
   - [x] Check that banner has the right copy
   - [x] Check that the "Learn more" button opens the public FormSG payment guide in a new tab
- [x] Login page
   - [x] Check that banner has the right copy
   - [x] Check that the "Learn more" button opens the public FormSG payment guide in a new tab

Check that the refactor that takes out the links as constants works with the existing payments copy things:
- [x] Announcement Rollout Modal
   - [x] If you've seen the announcement modal before, right click > Inspect > Applications. Delete local storage items prefixed with "has-seen-rollout-announcement-"
   - [x] Check that the content in the announcement modal that pops up has the link to the payment directory slides
- [x] What's New drawer
   - [x] Check that the content in the What's New drawer has the link to the payment directory slides

### chore: remove unused angular deps [`#6438`](https://github.com/opengovsg/FormSG/pull/6438)
@LinHuiqing 

React bundling should be unaffected
- [x] can view FormSG React homepage 

#### Deploy Notes

**Removed dev dependencies**:
- `copy-webpack-plugin` : used in angular to copy static assets for the file server to serve
- `google-fonts-plugin` : used in angular only
- `mini-css-extract-plugin` : used in angular's webpack to chunk css, from our angular code, by page
- `optimize-css-assets-webpack-plugin` : used in angular's webpack to run various css optimization
- `terser-webpack-plugin` : used in angular's webpack to 
- `webpack-merge` : used in angular's webpack

### fix: legacy frontend routing [`#6430`](https://github.com/opengovsg/FormSG/pull/6430)
@LinHuiqing 

The following frontend routes should redirect appropriately:

- [x] `/:formId/preview` --> `/admin/form/:formId/preview`
- [x] `/:formId/template` --> `/admin/form/:formId/use-template`
- [x] `/:formId/use-template` --> `/admin/form/:formId/use-template`
- [x] `/:formId/embed` --> `/:formId`
- [x] `/forms/:agency/:formId` --> `/:formId`
- [x] `/forms/:agency/:formId/preview` --> `/admin/form/:formId/preview`
- [x] `/forms/:agency/:formId/template` --> `/admin/form/:formId/use-template`
- [x] `/forms/:agency/:formId/use-template` --> `/admin/form/:formId/use-template`
- [x] `/forms/:agency/:formId/embed` --> `/:formId`

#### Deploy Notes

When this PR is deployed on production, the Cloudflare rules on these routes should be disabled prior to testing. Otherwise, we will have false positives.

### fix: use payment intent data for preview [`#6432`](https://github.com/opengovsg/FormSG/pull/6432)
@LinHuiqing 

Make sure the respondents will see the correct payment amount on the payment page:
- [x] go to a payment public form
- [x] complete the form and proceed until the proceed to pay modal is shown
- [x] on admin side, change the payment field amount and description 
- [x] click proceed to pay
- [x] the payment preview amount and description should be updated based on the admin's update
- [x] pay - the amount paid should be the amount shown on the payment page

Make sure that respondents will be paying for the amount they see on the payment element even when admins change the value when respondents are already on the payment page:
- [x] go to a payment public form
- [x] make a submission + payment intent (make sure to keep track of the current field price)
- [x] (at this point you should be at the payment page)
- [x] on admin side, change the payment field amount and description 
- [x] the payment preview amount and description should be the same as when you have made the submission (not the updated version)
- [x] complete the payment

###### Test API
@KenLSM 
**Test 1: API works**
  - [x] a. Generate a random string using `crypto.randomBytes(32).toString("base64")`
  - [x] b. find your user id, and format an API key as **`test_v1_${userId}_${randomString}`**
  - [x] c. Store a hash of that key (using 1 salt round) in the user collection, adding it a structure 
```
  "apiToken" :{
      "keyHash": "${hashedApiKey}",
      "createdAt": ISODate("2023-06-01T00:00:00.000Z"),
      "lastUsedAtAt": ISODate("2023-06-01T00:00:00.000Z"),
      }
```
 (instructions on how to generate the api key and hash are also [here](https://www.notion.so/opengov/API-d3b711dbd53f4b8e96c52ce2d8e0a171))
  - [x] d. Send an API request as such:
```
curl --request GET \
  --url http://form.gov.sg/api/public/v1/admin/forms \
  --header 'Authorization: Bearer ${apiKey}' \
```
  You should receive a `200 OK` response, with the full list of forms associated with your user.

**Test 2: Without authorisation header**
  - [x] Repeat the same steps as above. 
  - [x] In Step 2c, send a curl request without an authorisation header
```
curl --request GET \
  --url http://form.gov.sg/api/public/v1/admin/forms \
```
  - [x] You should receive a `401 Unauthorized` response, with the message "Authorisation header is missing"

**Test 3: With wrong credentials**
  - [ ] Repeat the same steps as above. 
  - [ ] In Step 2c, send a curl request with a different API token
```
curl --request GET \
  --url http://form.gov.sg/api/public/v1/admin/forms \
  --header 'Authorization: Bearer test_v1_${userId}_${WRONG_API_TOKEN}' \
```
  - [ ] You should receive a `401 Unauthorized` response

###### Regression Test
**Test 4: Regression test for `handleListDashboardForms`**
- [x] Log in. You should see the full list of forms in your dashboard, i.e. the GET request to http://form.gov.sg/api/v3/admin/forms should return with a `200 OK`
- [x] Happy path tests of admin login + a few form creation and edits

#### Deploy Notes

**New environment variables**:

- `API_KEY_VERSION`: current API version
- `PUBLIC_API_RATE_LIMIT`: Per-minute, per-IP, per-instance request limit for public APIs

### CODE REVIEW

**Comment by LinHuiqing** [comment]
Additional regression tests:
- https://github.com/opengovsg/FormSG/pull/6376:
   - happy path tests of admin login + a few form creation and edits
- https://github.com/opengovsg/FormSG/pull/6337
   1. myInfo forms (both admin setup/edits + submissions); and 
   2. the “regular” sgid auth (also both admin setup/edits + submissions)

Edit: added to PR description

**Comment by LinHuiqing** [comment]
@justynoh, the first 2 tests for `fix: legacy frontend routing` (https://github.com/opengovsg/FormSG/pull/6430) don't seem to be the behaviour I observe? The routes just redirect to `/:formId`

**Comment by LinHuiqing** [comment]
Modified tests for `fix: use payment intent data for preview` https://github.com/opengovsg/FormSG/pull/6432 (typing here first to decrease the chances of multiple people editing the description at the same time)

Make sure the respondents will see the correct payment amount on the payment page:
- [ ] go to a payment public form
- [ ] complete the form and proceed until the proceed to pay modal is shown
- [ ] on admin side, change the payment field amount and description 
- [ ] click proceed to pay
- [ ] the payment preview amount and description should be updated based on the admin's update
- [ ] pay - the amount paid should be the amount shown on the payment page

Make sure that respondents will be paying for the amount they see on the payment element even when admins change the value when respondents are already on the payment page:
- [ ] go to a payment public form
- [ ] make a submission + payment intent (make sure to keep track of the current field price)
- [ ] (at this point you should be at the payment page)
- [ ] on admin side, change the payment field amount and description 
- [ ] the payment preview amount and description should be the same as when you have made the submission (not the updated version)

Edit: added to PR description

**Review by KenLSM — APPROVED** [review]

**Comment by KenLSM** [comment]
Hey @wanlingt FYI, during the manual release test, these were not successful. But we've continued with the release as this test failure is non-blocking.

```
Test 3: With wrong credentials

- Repeat the same steps as above.
- In Step 2c, send a curl request with a different API token
curl --request GET \
  --url http://form.gov.sg/api/public/v1/admin/forms \
  --header 'Authorization: Bearer test_v1_${userId}_${WRONG_API_TOKEN}' \
 You should receive a 401 Unauthorized response
```

**Pull request merged**
