### PR TITLE
build: release v5.11.0

### PR DESCRIPTION
**Pull request by mantariksh**
## New
- feat: add enable captcha infobox [`#1908`](https://github.com/opengovsg/FormSG/pull/1908)
- feat: add response ID to thank you page [`#1855`](https://github.com/opengovsg/FormSG/pull/1855)

## Bug fixes
- fix: set form logo default value when creating form document [`#1966`](https://github.com/opengovsg/FormSG/pull/1966)

## Improved
- feat: extract public form submission flow (and preview) to specific Typescript services [`#1917`](https://github.com/opengovsg/FormSG/pull/1917)
- refactor: convert rating.client.service.js to typescript enum [`#1955`](https://github.com/opengovsg/FormSG/pull/1955)
- feat: implement specific API for duplicating form fields [`#1907`](https://github.com/opengovsg/FormSG/pull/1907)
- fix(encrypt-submission): shift encrypt mode form guard higher up the pipeline [`#1929`](https://github.com/opengovsg/FormSG/pull/1929)
- refactor(admin-form): extract update form startpage [`#1833`](https://github.com/opengovsg/FormSG/pull/1833)
- refactor: convert color-themes.client.service.js to TypeScript enum [`#1846`](https://github.com/opengovsg/FormSG/pull/1846)
- refactor(verification): migrate verified field [`#1866`](https://github.com/opengovsg/FormSG/pull/1866)
- refactor: extract create logic endpoint / refactor $watchCollection [`#1796`](https://github.com/opengovsg/FormSG/pull/1796)
- refactor(verification): reset field verification state when field changes [`#1900`](https://github.com/opengovsg/FormSG/pull/1900)

## Dev changes
- build: mute database container logs [`#1927`](https://github.com/opengovsg/FormSG/pull/1927)
- build: migrate unit tests to GitHub Actions [`#1870`](https://github.com/opengovsg/FormSG/pull/1870)
- chore(pull_request_template): adds breaking changes section to github template [`#1915`](https://github.com/opengovsg/FormSG/pull/1915)

## Dependency upgrades
- fix(deps): bump libphonenumber-js from 1.9.17 to 1.9.18 [`#1954`](https://github.com/opengovsg/FormSG/pull/1954)
- fix(deps): bump nodemailer from 6.6.0 to 6.6.1 [`#1951`](https://github.com/opengovsg/FormSG/pull/1951)
- fix(deps): bump aws-sdk from 2.910.0 to 2.912.0 [`#1950`](https://github.com/opengovsg/FormSG/pull/1950)
- fix(deps): bump @stablelib/base64 from 1.0.0 to 1.0.1 [`#1949`](https://github.com/opengovsg/FormSG/pull/1949)
- fix(deps): bump express-session from 1.17.1 to 1.17.2 [`#1946`](https://github.com/opengovsg/FormSG/pull/1946)
- fix(deps): bump twilio from 3.62.0 to 3.63.0 [`#1945`](https://github.com/opengovsg/FormSG/pull/1945)
- fix(deps): bump aws-sdk from 2.909.0 to 2.910.0 [`#1944`](https://github.com/opengovsg/FormSG/pull/1944)
- fix(deps): bump @sentry/integrations from 6.4.0 to 6.4.1 [`#1931`](https://github.com/opengovsg/FormSG/pull/1931)
- fix(deps): bump aws-sdk from 2.908.0 to 2.909.0 [`#1934`](https://github.com/opengovsg/FormSG/pull/1934)
- fix(deps): bump @sentry/browser from 6.4.0 to 6.4.1 [`#1933`](https://github.com/opengovsg/FormSG/pull/1933)
- feat: upgrade myinfo-gov-client to 4.0.0 [`#1925`](https://github.com/opengovsg/FormSG/pull/1925)
- fix(deps): bump @sentry/integrations from 6.3.6 to 6.4.0 [`#1912`](https://github.com/opengovsg/FormSG/pull/1912)
- fix(deps): bump @sentry/browser from 6.3.6 to 6.4.0 [`#1913`](https://github.com/opengovsg/FormSG/pull/1913)
- fix(deps): bump aws-sdk from 2.906.0 to 2.907.0 [`#1894`](https://github.com/opengovsg/FormSG/pull/1894)
- fix(deps): bump aws-sdk from 2.907.0 to 2.908.0 [`#1922`](https://github.com/opengovsg/FormSG/pull/1922)
- fix(deps): bump aws-sdk from 2.905.0 to 2.906.0 [`#1883`](https://github.com/opengovsg/FormSG/pull/1883)
- fix(deps): bump aws-sdk from 2.904.0 to 2.905.0 [`#1877`](https://github.com/opengovsg/FormSG/pull/1877)
- fix(deps): bump aws-sdk from 2.903.0 to 2.904.0 [`#1869`](https://github.com/opengovsg/FormSG/pull/1869)
- fix(deps): bump @sentry/integrations from 6.3.5 to 6.3.6 [`#1850`](https://github.com/opengovsg/FormSG/pull/1850)

### Dev dependencies
- chore(deps-dev): bump @typescript-eslint/parser from 4.24.0 to 4.25.0 [`#1959`](https://github.com/opengovsg/FormSG/pull/1959)
- chore(deps-dev): bump concurrently from 6.1.0 to 6.2.0 [`#1961`](https://github.com/opengovsg/FormSG/pull/1961)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#1963`](https://github.com/opengovsg/FormSG/pull/1963)
- chore(deps-dev): bump @opengovsg/mockpass from 2.6.10 to 2.7.0 [`#1962`](https://github.com/opengovsg/FormSG/pull/1962)
- chore(deps-dev): bump @types/nodemailer from 6.4.1 to 6.4.2 [`#1960`](https://github.com/opengovsg/FormSG/pull/1960)
- chore(deps-dev): bump auto-changelog from 2.2.1 to 2.3.0 [`#1958`](https://github.com/opengovsg/FormSG/pull/1958)
- chore(deps-dev): bump @types/mongodb from 3.6.14 to 3.6.16 [`#1953`](https://github.com/opengovsg/FormSG/pull/1953)
- chore(deps-dev): bump eslint-plugin-import from 2.23.2 to 2.23.3 [`#1952`](https://github.com/opengovsg/FormSG/pull/1952)
- chore(deps-dev): bump eslint from 7.26.0 to 7.27.0 [`#1948`](https://github.com/opengovsg/FormSG/pull/1948)
- chore(deps-dev): bump @types/mongodb from 3.6.12 to 3.6.14 [`#1932`](https://github.com/opengovsg/FormSG/pull/1932)
- chore(deps-dev): bump @babel/core from 7.14.2 to 7.14.3 [`#1920`](https://github.com/opengovsg/FormSG/pull/1920)
- chore(deps-dev): bump @types/node from 14.14.45 to 14.17.0 [`#1921`](https://github.com/opengovsg/FormSG/pull/1921)
- chore(deps-dev): bump @babel/plugin-transform-runtime [`#1919`](https://github.com/opengovsg/FormSG/pull/1919)
- chore(deps-dev): bump @types/bluebird from 3.5.34 to 3.5.35 [`#1918`](https://github.com/opengovsg/FormSG/pull/1918)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#1911`](https://github.com/opengovsg/FormSG/pull/1911)
- chore(deps-dev): bump @typescript-eslint/parser from 4.23.0 to 4.24.0 [`#1910`](https://github.com/opengovsg/FormSG/pull/1910)
- chore(deps-dev): bump @types/convict from 6.0.1 to 6.0.2 [`#1893`](https://github.com/opengovsg/FormSG/pull/1893)
- chore(deps-dev): bump eslint-plugin-import from 2.22.1 to 2.23.2 [`#1891`](https://github.com/opengovsg/FormSG/pull/1891)
- chore(deps-dev): bump @babel/core from 7.14.0 to 7.14.2 [`#1882`](https://github.com/opengovsg/FormSG/pull/1882)
- chore(deps-dev): bump @types/node from 14.14.44 to 14.14.45 [`#1884`](https://github.com/opengovsg/FormSG/pull/1884)
- chore(deps-dev): bump @babel/preset-env from 7.14.1 to 7.14.2 [`#1881`](https://github.com/opengovsg/FormSG/pull/1881)
- chore(deps-dev): bump testcafe from 1.14.1 to 1.14.2 [`#1880`](https://github.com/opengovsg/FormSG/pull/1880)
- chore(deps-dev): bump @babel/plugin-transform-runtime [`#1879`](https://github.com/opengovsg/FormSG/pull/1879)
- chore(deps-dev): bump @opengovsg/mockpass from 2.6.9 to 2.6.10 [`#1878`](https://github.com/opengovsg/FormSG/pull/1878)
- chore(deps-dev): bump testcafe from 1.14.0 to 1.14.1 [`#1876`](https://github.com/opengovsg/FormSG/pull/1876)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#1868`](https://github.com/opengovsg/FormSG/pull/1868)

### CODE REVIEW

**Comment by mantariksh** [comment]
## Tests
**Captcha infobox**
- [ ] Captcha infobox (see https://github.com/opengovsg/FormSG/pull/1908) appears in both email and storage mode

**Comment by mantariksh** [comment]
## Tests
**Response ID in end page**
- [ ] Create email field and turn on email confirmation. Check that dummy response ID is present in email confirmation preview in edit field modal
- **Create email field in email mode and submit form**
- [ ] Check that correct response ID (submission ID, not form ID) is displayed above time of submission
- [ ] Check that response ID is present in email confirmation
- [ ] Enter preview mode and repeat above checks
- **Create email field in storage mode and submit form**
- [ ] Check that correct response ID (submission ID, not form ID) is displayed above time of submission
- [ ] Check that response ID is present in email confirmation
- [ ] Enter preview mode and repeat above checks

**Comment by mantariksh** [comment]
## Tests
**Submission API refactor**
- [ ] Submit an email mode form with verified email field, should receive submission as admin, and also submission as form filler
  - [ ] Submit with multiple attachments, should receive attachments successfully
- [ ] Submit an storage mode form with verified email field, should receive submission as form filler, should also decrypt successfully
  - [ ] Submit with multiple attachments, should decrypt and download successfully
- [ ] Preview email mode form submission, should also be successful
- [ ] Preview encrypt mode form, should also be successful

**Comment by mantariksh** [comment]
## Tests
**Rating service refactor**
- [ ] Create new rating field. Ensure that all ratings (1-10) and rating shapes (heart and star) are present and check that preview and subsequent form has the correct number of rating options.

**Comment by mantariksh** [comment]
## Tests
**Duplicate form field API refactor**
- [ ] Create random field in storage mode and duplicate it. Check that contents of field are duplicated correctly.
- [ ] Create random field in email mode and duplicate it. Check that contents of field are duplicated correctly.
- [ ] Create myinfo field (with dropdown options) and duplicate it. Check that duplicated field has the correct options and is also uneditable if it has a pre-filled value.

**Comment by mantariksh** [comment]
## Tests
**Start page API refactor**
- [ ] Create a new form. Go into the admin panel and click the start page. Edit without saving. This should be prohibited.
- [ ] Create a new form. Go into the admin panel and click the start page. Edit the instructions field and add text there. Click save - the changes should be persisted. Open the start page again and clear the instructions field. Click save - the changes should be persisted. 
- [ ] Create a new form and update the time taken **programmatically** to be 12345. This should return an error from the backend. 
- [ ] Create a new form and update the logo **programmatically** to have `state: NOT_A_STATE`. This should return an error from teh backend
- [ ] Create a new form and update the colour **programmatically** to have `colour: transparent`. This should return an error from teh backend
- [ ] Create a new form and update the logo to be an image and click save. this should work. thereafter, repeat this **programmatically** but change the `fileSizeInBtes` to be >2MB. This should be rejected

**Comment by mantariksh** [comment]
## Tests
**Color themes service refactor**
- [ ] Create a new form in storage mode and check that updating color theme works.
- [ ] Create a new form in email mode and check that updating color theme works.

**Comment by mantariksh** [comment]
## Tests
**Verified field API refactor**
- [ ] create a form with a verified email field. go to the public form view; enter a email and click on verify. there should be a pop-up for the otp to be entered
- [ ] create a form with a verified mobile number field. go to the public form view; enter a number and click on verify. there should be a pop-up for the otp to be entered

**Comment by mantariksh** [comment]
@karrui 

## Tests
**Logic API refactor**
**Create Logic Endpoint**
- [ ] Create a showFields logic. Check that logic is successfully added and build tab is successfully updated (hidden fields greyed out).
- [ ] Repeat the above with a second logic

Test using manual API calls
- [ ] Check that endpoint returns 404 when formId is incorrect

**$watchCollection Refactor**
- [ ] Create a form with multiple showFields logic. Delete one of them. Check that the Build tab is updated correctly (field should no longer be greyed out)
- [ ] Now change one of the logic to preventSubmit. Check that the Build tab is updated correctly (field should no longer be greyed out). Change it back to showFields. Check that the field is now greyed out on build tab

**Comment by mantariksh** [comment]
## Tests
@tshuli 
**Reset verified field API refactor**
- [x] Create a new form and set mobile field to require verification. Publish the form and navigate to it. Key in a valid ~email~ mobile number, then click verify. Click backspace (so that the dropdown to enter the otp disappears) then, reenter the ~email~ mobile number again. Verify the ~email~ mobile number with the **previous** otp. This should fail. Next, verify with the **new** otp. This should pass. Attempt to submit the form after verification. This should pass
- [x] Repeat the above with email field
- [ ] Create a form with >1 fields that require verification. Attempt to submit without 0 verifications. Attempt to submit with less than the required amount of verifications. Both should fail. Submitting with the required amount of verifications should pass

**Review by karrui — APPROVED** [review]

**Pull request merged**
