### PR TITLE
build: Release 4.36.0

### PR DESCRIPTION
**Pull request by shuli-ogp**
**Features**
- feat: automate critical bounce handling [`#318`](https://github.com/opengovsg/FormSG/pull/318)
- feat: form ownership transfer feature [`#111`](https://github.com/opengovsg/FormSG/pull/111)

**Improvements**
- feat: update copy for email fields, intranet, privacy [`#321`](https://github.com/opengovsg/FormSG/pull/321)
- feat: Using `neverthrow` to explicitly handle errors in AuthController [`#332`](https://github.com/opengovsg/FormSG/pull/332)
- refactor: remove unused key [`#325`](https://github.com/opengovsg/FormSG/pull/325)
- test: remove storage mode attachment tests [`#336`](https://github.com/opengovsg/FormSG/pull/336)

**Bug Fixes**
- fix(dev): fix hot reloading and Localstack port [`#324`](https://github.com/opengovsg/FormSG/pull/324)
- fix: set nodeEnv to assigned variable if in dev environment [`#335`](https://github.com/opengovsg/FormSG/pull/335)
- Fix more tests [`0c6c8ac`](https://github.com/opengovsg/FormSG/commit/0c6c8acfa95a591449e90dea229b50bc5b73a7c4)
- Fix tests [`6d0ffde`](https://github.com/opengovsg/FormSG/commit/6d0ffde17207589d34c760f1b0aa9825d0323d0b)

**New Dependencies**
- chore: update spcp-auth-client library [`#346`](https://github.com/opengovsg/FormSG/pull/346)
- chore: update travis.yml and pin localstack in docker-compose [`#337`](https://github.com/opengovsg/FormSG/pull/337)
- chore(deps-dev): bump concurrently from 3.6.1 to 5.3.0 [`#308`](https://github.com/opengovsg/FormSG/pull/308)
- chore(deps-dev): bump eslint from 7.8.1 to 7.9.0 [`#331`](https://github.com/opengovsg/FormSG/pull/331)
- chore(deps-dev): bump eslint-plugin-import from 2.21.2 to 2.22.0 [`#330`](https://github.com/opengovsg/FormSG/pull/330)
- chore(deps-dev): bump eslint-plugin-jest from 24.0.0 to 24.0.2 [`#341`](https://github.com/opengovsg/FormSG/pull/341)
- chore(deps-dev): bump lint-staged from 10.2.11 to 10.4.0 [`#328`](https://github.com/opengovsg/FormSG/pull/328)
- chore(deps-dev): bump ts-node from 8.10.2 to 9.0.0 [`#329`](https://github.com/opengovsg/FormSG/pull/329)
- fix(deps): bump celebrate from 12.2.0 to 13.0.3 [`#338`](https://github.com/opengovsg/FormSG/pull/338)
- fix(deps): bump csv-parse from 4.10.1 to 4.12.0 [`#340`](https://github.com/opengovsg/FormSG/pull/340)
- fix(deps): bump csv-string from 3.2.0 to 4.0.1 [`#344`](https://github.com/opengovsg/FormSG/pull/344)
- fix(deps): bump helmet from 3.23.1 to 4.1.0 [`#233`](https://github.com/opengovsg/FormSG/pull/233)
- fix(deps): bump whatwg-fetch from 3.0.0 to 3.4.1 [`#300`](https://github.com/opengovsg/FormSG/pull/300)
- fix(deps): bump winston from 3.2.1 to 3.3.3 [`#278`](https://github.com/opengovsg/FormSG/pull/278)
- fix(deps): fix npm audit issues [`#322`](https://github.com/opengovsg/FormSG/pull/322)
- fix(deps): uninstall async [`#309`](https://github.com/opengovsg/FormSG/pull/309)
- fix(deps): uninstall node-jose [`#339`](https://github.com/opengovsg/FormSG/pull/339)

- neverthrow^2.7.1 (from #332)

### CODE REVIEW

**Comment by shuli-ogp** [comment]
@karrui 
**Form transfer**

- [ ] Mobile view of collaborator modal works
- [ ] Able to transfer ownership to collaborator for encrypt forms (existing owner should become collaborator and only have edit access)
- [ ] Able to add a collaborator with read access to encrypt forms
- [ ] Able to add a collaborator with edit access to encrypt forms
- [ ] Able to add a collaborator with edit access to email forms

**Comment by shuli-ogp** [comment]
@arshadali172 
**Automate critical bounce handling**

- [ ] Create an email mode form where there are two email recipients, one valid and one invalid. Submit the form. The form should remain active and the valid admin should not receive any automated critical bounce emails. In the database, check that the document for this form in the Bounce collection has been updated correctly with `hasBounced: true` and `bounceType: Permanent` for the invalid email recipient.
- [ ] Change the recipients such that all recipients are invalid. Add a collaborator with a valid email. Submit the form. The form should be deactivated, and both the admin and collaborator should receive an email following the [permanent bounce template](https://docs.google.com/document/d/12bWYcxNh5fLmz1iNyC809rnVBsW1H2btiqIPdLbsa-0/edit#heading=h.2lyngvnqgs8e) notifying them of the critical bounce.
- [ ] In production, BOUNCE_LIFE_SPAN has been updated to 86400000 (24h in milliseconds).
- [ ] In production CloudWatch queries and dashboard widgets, `Critical bounce` has been changed to `Bounced submission`.

**Comment by shuli-ogp** [comment]
@shuli-ogp 
**Filter Storage Mode Responses by Submission Id**
- [ ] Create a storage mode form. Submit 5 responses. Input a valid submission ID. Check that only the correct submission is shown now
- [ ] Input a random submission ID. Check that no submissions are shown

**Comment by shuli-ogp** [comment]
@karrui 
**remove Localstack from end-to-end tests**
- [ ] Test that storage mode attachments work.

**Comment by shuli-ogp** [comment]
@mantariksh 
**Upgrade helmet to v4.1.0**

- [ ] Check that the following CSPs are present: defaultSrc, imgSrc, fontSrc, scriptSrc, connectSrc, frameSrc, objectSrc, styleSrc, formAction, upgradeInsecureRequests, reportUri
- [ ] imgSrc / connectSrc: check that image can be uploaded correctly for form
- [ ] fontSrc: check that SG government banner renders correctly
- [ ] scriptSrc / frameSrc / styleSrc: check that captcha works and is rendered correctly

**Comment by shuli-ogp** [comment]
@arshadali172 
- [ ] General run through on IE and Intranet

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
