### PR TITLE
build: release v4.38.0

### PR DESCRIPTION
**Pull request by arshadali172**
### New
- feat: add trace to logs [`#405`](https://github.com/opengovsg/formsg/pull/405)

### Improvements
- refactor: use validator's isEmail for validating email domains [`#386`](https://github.com/opengovsg/formsg/pull/386)
- refactor: migrate SmsFactory to Typescript [`#387`](https://github.com/opengovsg/formsg/pull/387)
- chore: add lint rule to prevent floating promises [`#404`](https://github.com/opengovsg/formsg/pull/404)

### Fixes
- fix: only show exclamation in navbar if sms feature is enabled [`#383`](https://github.com/opengovsg/formsg/pull/383)
- fix: transfer form toastr [`#379`](https://github.com/opengovsg/formsg/pull/379)
- style: fix squished styling when user emails are too long [`#382`](https://github.com/opengovsg/formsg/pull/382)
- fix: invalid key reference in retrieving form submissions [`#385`](https://github.com/opengovsg/formsg/pull/385)

### Dependency upgrades
- fix(deps): bump @sentry/browser from 5.22.3 to 5.24.2 [`#407`](https://github.com/opengovsg/formsg/pull/407)
- chore(deps-dev): bump @types/uuid from 8.0.0 to 8.3.0 [`#375`](https://github.com/opengovsg/formsg/pull/375)
- fix(deps): bump twilio from 3.46.0 to 3.49.3 [`#367`](https://github.com/opengovsg/formsg/pull/367)
- chore(deps-dev): bump @types/node from 14.0.13 to 14.11.2 [`#374`](https://github.com/opengovsg/formsg/pull/374)
- fix(deps): bump nodemailer from 6.4.11 to 6.4.12 [`#399`](https://github.com/opengovsg/formsg/pull/399)
- fix(deps): bump multiparty from 4.2.1 to 4.2.2 [`#406`](https://github.com/opengovsg/formsg/pull/406)
- chore(deps-dev): bump eslint from 7.9.0 to 7.10.0 [`#401`](https://github.com/opengovsg/formsg/pull/401)
- fix(deps): bump aws-sdk from 2.734.0 to 2.763.0 [`#393`](https://github.com/opengovsg/formsg/pull/393)
- chore(deps-dev): bump @types/express from 4.17.6 to 4.17.8 [`#392`](https://github.com/opengovsg/formsg/pull/392)
- fix(deps): bump helmet from 4.1.0 to 4.1.1 [`#390`](https://github.com/opengovsg/formsg/pull/390)

### CODE REVIEW

**Comment by arshadali172** [comment]
@karrui 
- [ ] At the login page, key in an invalid email address abc@abc.com. Check that the value of cf-ray header is logged under trace in the server logs error message.
- [ ] Access a public form. Check that the value of cf-ray header is logged under trace in the server logs for the get request.

**Comment by arshadali172** [comment]
@mantariksh 
- [ ] Check that exclamation is only shown in navbar if sms feature is enabled (On both staging and staging-alt)
- [ ] Check that user emails that are too long on avatar dropdown are shown properly
- [ ] Check that use-template page shows correct submission count and feedback count (On both staging and staging-alt)

**Comment by arshadali172** [comment]
@shuli-ogp 
- [ ] Errors during form transfer should appear as toastr (Adding a collaborator that already exists, Transferring ownership to a user who has not logged in etc.)

**Comment by arshadali172** [comment]
@arshadali172 
- [ ] General run through on IE/Intranet

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
