### PR TITLE
build: release v6.58.0

### PR DESCRIPTION
**Pull request by LinHuiqing**
## New

- fix: learn more link for what's new drawer [`#6422`](https://github.com/opengovsg/FormSG/pull/6422)
- feat: GoGov link shortener [`#6369`](https://github.com/opengovsg/FormSG/pull/6369)
- fix: add payment field to numVisibleFields [`#6414`](https://github.com/opengovsg/FormSG/pull/6414)
- chore: remove support for legacy stripe metadata [`#6415`](https://github.com/opengovsg/FormSG/pull/6415)
- chore: delete angular [`#6344`](https://github.com/opengovsg/FormSG/pull/6344)
- feat: restricting days date validation [`#5136`](https://github.com/opengovsg/FormSG/pull/5136)
- feat: add debit card to copy and dashboard banner for payments [`#6416`](https://github.com/opengovsg/FormSG/pull/6416)
- style: Use S$ instead of SGD [`#6417`](https://github.com/opengovsg/FormSG/pull/6417)
- build: merge v6.57.0 into develop [`#6413`](https://github.com/opengovsg/FormSG/pull/6413)
- build: release v6.57.0 [`#6412`](https://github.com/opengovsg/FormSG/pull/6412)

## Dependencies

- fix(deps): bump libphonenumber-js from 1.10.31 to 1.10.33 in /shared [`#6421`](https://github.com/opengovsg/FormSG/pull/6421)

### fix: learn more link for what's new drawer [`#6422`](https://github.com/opengovsg/FormSG/pull/6422)

@foochifa 

- [x] Check that What's New drawer has the "Learn more" copy linked to "https://go.gov.sg/formsg-payment-overview" as seen in screenshot.

### feat: GoGov link shortener [`#6369`](https://github.com/opengovsg/FormSG/pull/6369)

@mayying 

When `goLinks` feature is enabled:
- [x] Make sure that the `goLinks` feature flag is enabled. In the `featureflags` collection, ensure that the following document is present:
   ```json
   {
       "name": "goLinks",
       "enabled": true
   }
   ```
- [x] Go to the Share Form Modal of any form. There should be a section titled "Go link".
- [x] Successful claim flow:
   - [x] Key in a GoGov link to claim and click "Claim". If it says that the short link is taken, try another link.
   - [x] After successfully claiming the link, the "Claim" button should disappear and the icon to copy the link should appear.
   - [x] Copy the link with the icon. Open a new tab and paste the link. It should show the GoGov screen then redirect you to the public form.
- [x] Get claimed link flow:
   - [x] Go to the main form dashboard then select a form which you have claimed a link for.
   - [x] Open the Share Form Modal. You should see the section titled "Go link".
   - [x] There should be no "Claim" button and only the copy icon.
   - [x] Click the copy icon and paste the link in a new tab. You should be redirected to the public form.
- [x] Unsuccessful claim flow due to short link taken:
   - [x] Go to a form that has not claimed any GoGov link. Open the Share Form Modal.
   - [x] Key in a link that you have previously claimed on GoGov. An error should be shown indicating that the link is taken.
- [x] Unsuccessful claim flow due to other errors (aside from short link taken error):
   - [x] Go to a form that has not claimed any GoGov link. Open the Share Form Modal.
   - [x] Key in a very very long link, or link with space. An error should be shown indicating that that the link is taken. (expected output for this release)

Check that `goLinks` can be switched off with a simple DB update:
- [x] In the `featureflags` collection, remove any document with `name: goLinks` or ensure that the following document is present:
   ```json
   {
       "name": "goLinks",
       "enabled": false
   }
   ```
- [x] Refresh the existing page and opening any Share Form Modals for forms with no go link previously attached should show all fields except for the "Go links" section.
- [x] Opening any Share Form Modals for form with go links previously attached should show the attached go link.

(Can't be tested with live emails, only in dev) Check that only emails with `*.gov.sg` domain will see the go links feature.
- [x] Check that "goLinks" feature flag is enabled on DB.
- [x] Login with an email with domain that does not end with ".gov.sg".
- [x] "Go links" section should be missing from Share Form Modal.

#### Deploy Notes

**New environment variables**:

- `GOGOV_API_KEY`: GoGov API key of the form@open.gov.sg GoGov account.

**New feature flags**:

- `goLinks`: feature flag to enable go links feature on the frontend.

### fix: add payment field to numVisibleFields [`#6414`](https://github.com/opengovsg/FormSG/pull/6414)

@LinHuiqing 
- [x] make a payment on a form
- [x] check the payload of the form submission, the body should contain the correct number of visible fields including payments
- [x] check the db is updated with the correct number of visible fields
- [x] ensure that response time metrics are still visible in DD

### feat: add debit card to copy and dashboard banner for payments [`#6416`](https://github.com/opengovsg/FormSG/pull/6416)

@foochifa 

- [x] Check that the copy in the announcement rollout modal is correct (ie includes "debit / credit card").
- [x] Check that the copy in the what's new drawer is correct (ie includes "debit / credit card").
- [x] Check that there is a banner in the dashboard announcing payments.

### style: Use S$ instead of SGD [`#6417`](https://github.com/opengovsg/FormSG/pull/6417)
@LinHuiqing 
Ensure the 'S$' changes are reflected in:
- [x] Form builder payment preview
- [x] Form payment preview
- [x] Public form 
- [x] Public form payment page

### feat: restricting days date validation [`#5136`](https://github.com/opengovsg/FormSG/pull/5136)
@foochifa 
- [x] Make sure the date field validation is present
- [x] Enable date field validation on form
- [x] With all days of the week checked as valid days:
   - [x] Check that all previous date field features are still working as usual (ie no validation, past dates only, future dates only, custom date range)
- [x] With some days of the week unchecked and saved:
   - [x] For no validation:
      - [x] Check that opening the date picker will only show dates for valid days of the week and select them.
      - [x] Keying in a valid date in the date field directly should pass
      - [x] Keying in an invalid date in the date field directly should not pass
   - [x] For past only date validation:
      - [x] Check that opening the date picker will only show dates for valid days of the week and select them.
      - [x] Keying in a valid date in the date field directly should pass
      - [x] Keying in an invalid date in the date field directly should not pass
   - [x] For future only date validation:
      - [x] Check that opening the date picker will only show dates for valid days of the week and select them.
      - [x] Keying in a valid date in the date field directly should pass
      - [x] Keying in an invalid date in the date field directly should not pass
- [x] For custom date range validation:
   - [x] For date range of more than or equal to 7 days:
      - [x] Check that opening the date picker will only show dates for valid days of the week and select them.
      - [x] Keying in a valid date in the date field directly should pass
      - [x] Keying in an invalid date in the date field directly should not pass
   - [x] For date range of less than 7 days:
      - [x] If the custom date range does not include any of the valid days of the week selected, an error will be thrown.
      - [x] If the custom date range includes at least 1 of the valid days of the week selected, the date validation will be saved successfully.
         - [x] Check that opening the date picker will only show dates for valid days of the week and select them.
         - [x] Keying in a valid date in the date field directly should pass
         - [x] Keying in an invalid date in the date field directly should not pass

### CODE REVIEW

**Comment by LinHuiqing** [comment]
We should add regression tests for this release! Because there's the PR to remove angular

**Comment by mayying** [comment]
For golink, if the error is not about taken short link, the error right now will still be `Short link is already in use.` I tried with unexceptionally long strings, all strings with empty spaces, and I still got short link is already in use. Please confirm if this is an expected behaviour. @LinHuiqing Screenshot 2023-06-05 at 3 49 16 PM

**Comment by LinHuiqing** [comment]
> For golink, if the error is not about taken short link, the error right now will still be `Short link is already in use.` I tried with unexceptionally long strings, all strings with empty spaces, and I still got short link is already in use. Please confirm if this is an expected behaviour. @LinHuiqing Screenshot 2023-06-05 at 3 49 16 PM

Yep, it currently is :') I have decided to just leave error handling to another PR as I had some issues getting the error shape. Created an issue on linear: FRM-901

**Comment by LinHuiqing** [comment]
To be added in description
---
Tests for date field validation: 
- [ ] Make sure the date field validation is present
- [ ] Enable date field validation on form
- [ ] With all days of the week checked as valid days:
   - [ ] Check that all previous date field features are still working as usual (ie no validation, past dates only, future dates only, custom date range)
- [ ] With some days of the week unchecked and saved:
   - [ ] For no validation:
      - [ ] Check that opening the date picker will only show dates for valid days of the week and select them.
      - [ ] Keying in a valid date in the date field directly should pass
      - [ ] Keying in an invalid date in the date field directly should not pass
   - [ ] For past only date validation:
      - [ ] Check that opening the date picker will only show dates for valid days of the week and select them.
      - [ ] Keying in a valid date in the date field directly should pass
      - [ ] Keying in an invalid date in the date field directly should not pass
   - [ ] For future only date validation:
      - [ ] Check that opening the date picker will only show dates for valid days of the week and select them.
      - [ ] Keying in a valid date in the date field directly should pass
      - [ ] Keying in an invalid date in the date field directly should not pass
- [ ] For custom date range validation:
   - [ ] For date range of more than or equal to 7 days:
      - [ ] Check that opening the date picker will only show dates for valid days of the week and select them.
      - [ ] Keying in a valid date in the date field directly should pass
      - [ ] Keying in an invalid date in the date field directly should not pass
   - [ ] For date range of less than 7 days:
      - [ ] If the custom date range does not include any of the valid days of the week selected, an error will be thrown.
      - [ ] If the custom date range includes at least 1 of the valid days of the week selected, the date validation will be saved successfully.
         - [ ] Check that opening the date picker will only show dates for valid days of the week and select them.
         - [ ] Keying in a valid date in the date field directly should pass
         - [ ] Keying in an invalid date in the date field directly should not pass

**Comment by foochifa** [comment]
FRM-978 for date custom range issue

**Review by foochifa — APPROVED** [review]

**Comment by foochifa** [comment]
@staceytan1998 

image


Just wanna check, for this feature (Custom Available Days), if the day that is disallowed (Thursday in this case) is selected. Is this error message good enough? Was wondering if we wanna be explicit and something like `Thursday is not allowed by the form admin` or `This day is not allowed by the form admin`

**Pull request merged**
