### PR TITLE
fix: ogp logo svgr

### LINKED ISSUE #5748: Firefox: OGP logo in app footer gets cut off
In firefox, the 'T' in the OGP logo in the App footer is cut off. 

Screenshot 2023-02-13 at 10 23 27 AM

### PR DESCRIPTION
**Pull request by justynoh**
## Problem

Currently, the OGP logo svgr in the app footer gets cut off (the 'T' is dead). This PR fixes that.

Closes #5748 

## Solution
Remove masks from the path groups in the SVGR.

**Breaking Changes** 
- No - this PR is backwards compatible  

## Screenshots

Left: chrome, Right: firefox

Screenshot 2023-02-13 at 10 21 00 AM

### CODE REVIEW

**Review by wanlingt — APPROVED** [review]
:o

**Comment by karrui** [comment]
Oh i know why this happens. Using SVGR means they assign `id`s to the mask groups, starting from `a`, to `b`, ... etc. But when there are two SVGR components, the IDs may clash. We should take a look at all the SVG React components to name the mask ids something less likely to clash....

**Comment by justynoh** [comment]
what motivated you to look at this again LOL

**Comment by karrui** [comment]
> what motivated you to look at this again LOL

Reading working doc

**Pull request merged**
