### PR TITLE
build: Release 4.51.0

### PR DESCRIPTION
**Pull request by tshuli**
**New**

- feat: add   FIXED_LINE_OR_MOBILE numbers to pass homeno validation   [`#886`](https://github.com/opengovsg/FormSG/pull/886)
- feat: harden rate limits   [`#909`](https://github.com/opengovsg/FormSG/pull/909)

**Improvements**
- refactor: inline form permissions check for presigned POST URL endpoints   [`#863`](https://github.com/opengovsg/FormSG/pull/863)
- refactor:   prepareEncryptSubmission to typescript   [`#891`](https://github.com/opengovsg/FormSG/pull/891)
- refactor:   validateAndProcessEncryptSubmission to typescript   [`#887`](https://github.com/opengovsg/FormSG/pull/887)
- docs(public-form): add   warning comment to GET endpoint in case of API refactor   [`#897`](https://github.com/opengovsg/FormSG/pull/897)

**Fixes**
- fix: add request metadata   to email data error log   [`#915`](https://github.com/opengovsg/FormSG/pull/915)
- fix: backend validation   does not prevent responses on hidden fields   [`#809`](https://github.com/opengovsg/FormSG/pull/809)
- fix: include noopener,   noreferrer to &lt;a&gt; tags that open in a new page   [`#916`](https://github.com/opengovsg/FormSG/pull/916)

**Dependency updates**
- chore(deps-dev): bump   @babel/core from 7.12.3 to 7.12.10   [`#878`](https://github.com/opengovsg/FormSG/pull/878)
- chore(deps-dev): bump   @types/express-serve-static-core   [`#905`](https://github.com/opengovsg/FormSG/pull/905)
- chore(deps-dev): bump   @types/jest from 26.0.16 to 26.0.19   [`#906`](https://github.com/opengovsg/FormSG/pull/906)
- chore(deps-dev): bump   @types/node from 14.14.11 to 14.14.14   [`#900`](https://github.com/opengovsg/FormSG/pull/900)
- chore(deps-dev): bump   @typescript-eslint/parser from 4.9.0 to 4.10.0   [`#910`](https://github.com/opengovsg/FormSG/pull/910)
- chore(deps-dev): bump   core-js from 3.6.5 to 3.8.1   [`#907`](https://github.com/opengovsg/FormSG/pull/907)
- chore(deps-dev): bump   csv-parse from 4.14.1 to 4.14.2   [`#911`](https://github.com/opengovsg/FormSG/pull/911)
- chore(deps-dev): bump   husky from 4.3.5 to 4.3.6   [`#877`](https://github.com/opengovsg/FormSG/pull/877)
- chore(deps-dev): bump jest   from 26.6.2 to 26.6.3 [`#890`](https://github.com/opengovsg/FormSG/pull/890)
- chore(deps-dev): bump   lint-staged from 10.5.2 to 10.5.3   [`#893`](https://github.com/opengovsg/FormSG/pull/893)
- fix: upgrade   angular-moment from 1.2.0 to 1.3.0   [`#870`](https://github.com/opengovsg/FormSG/pull/870)
- fix: upgrade   angular-ui-router from 1.0.26 to 1.0.28   [`#868`](https://github.com/opengovsg/FormSG/pull/868)
- fix: upgrade fp-ts from   2.8.6 to 2.9.0 [`#896`](https://github.com/opengovsg/FormSG/pull/896)
- fix: upgrade   intl-tel-input from 12.1.16 to 12.4.0   [`#866`](https://github.com/opengovsg/FormSG/pull/866)
- fix: upgrade sortablejs   from 1.10.2 to 1.12.0 [`#865`](https://github.com/opengovsg/FormSG/pull/865)
- fix: upgrade to use latest   Node v12 [`#879`](https://github.com/opengovsg/FormSG/pull/879)
- fix: upgrade twilio from   3.51.0 to 3.52.0 [`#869`](https://github.com/opengovsg/FormSG/pull/869)
- fix(deps): bump   @sentry/browser from 5.29.0 to 5.29.1   [`#899`](https://github.com/opengovsg/FormSG/pull/899)
- fix(deps): bump   @sentry/integrations from 5.27.4 to 5.29.0   [`#888`](https://github.com/opengovsg/FormSG/pull/888)
- fix(deps): bump fp-ts from   2.9.0 to 2.9.1 [`#914`](https://github.com/opengovsg/FormSG/pull/914)
- fix(deps): bump mongoose   from 5.10.18 to 5.11.8 [`#889`](https://github.com/opengovsg/FormSG/pull/889)
- fix(deps): bump opossum   from 5.0.2 to 5.1.1 [`#898`](https://github.com/opengovsg/FormSG/pull/898)
- fix(deps): bump twilio   from 3.52.0 to 3.54.1 [`#913`](https://github.com/opengovsg/FormSG/pull/913)
- fix(deps): bump uuid from   8.3.1 to 8.3.2 [`#892`](https://github.com/opengovsg/FormSG/pull/892)
- fix(deps): bump   web-streams-polyfill from 2.1.1 to 3.0.1   [`#838`](https://github.com/opengovsg/FormSG/pull/838)
- fix(deps): run snyk wizard   [`#876`](https://github.com/opengovsg/FormSG/pull/876)

### CODE REVIEW

**Comment by tshuli** [comment]
## Tests
**feat: add FIXED_LINE_OR_MOBILE numbers to pass homeno validation**

- [ ] Create home number field and allow intl numbers. Check that the number +12025373100 passes validation.

**Comment by tshuli** [comment]
**feat: harden rate limits**

- [ ] Change the SUBMISSIONS_RATE_LIMIT and AUTH_OTP_RATE_LIMIT env vars to 3 each (choosing 3 instead of 0/1/2 so that hopefully it won't affect the other tests running concurrently)
- [ ] Attempt to make 4 email mode submissions across at least 2 different forms within 1 minute. The 4th submission should return 429 with a "please try again in one minute" error message. Cloudwatch should contain a `limitRate` log message with your IP address.
- [ ] Make 3 email mode submissions within 1 minute, then another one from a different IP address . The one from the different IP address should go through.
- [ ] Attempt to make 4 encrypt mode submissions across at least 2 different forms within 1 minute. The 4th submission should return 429 with a "please try again in one minute" error message. Cloudwatch should contain a `limitRate` log message with your IP address.
- [ ] Make 3 email encrypt submissions within 1 minute, then another one from a different IP address . The one from the different IP address should go through.
- [ ] Attempt to resend auth OTP 4 times within 1 minute. The 4th submission should return 429 with a "please try again in one minute" error message. Cloudwatch should contain a `limitRate` log message with your IP address.

**Comment by tshuli** [comment]
** fix: backend validation does not prevent responses on hidden fields**

- [ ] Create a email mode form with Yes/No field, and a Number Field hidden behind it. Attempt to submit a number response programatically with the number field still hidden. Submission should fail.
- [ ] Now unhide the Number Field. Attempt to submit a response on the number field normally. Submission should pass.
- [ ] Create email mode form with all field types (including Yes/No) hidden behind a Yes/No field. Submit while keeping the fields hidden. Submission should pass.
- [ ] Now unhide the fields and submit responses for all the hidden fields. Submission should pass.
- [ ] Create storage mode form with a mobile, email and short text field hidden behind a Yes/No field. Unhide the mobile and email fields and submit a response. Submission should pass.
- [ ] Create storage mode form with a mobile, email and short text field hidden behind a Yes/No field. Submit a response without unhiding the fields. Submission should pass.

**Comment by tshuli** [comment]
## Tests
**IE11 intranet tests for this week**
- [ ] Create home number field and allow intl numbers. Check that the number +12025373100 passes validation.


**IE11 intranet general run-through**
- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your GSIB inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Comment by karrui** [comment]
## Tests
### inline form permissions check for presigned POST URL endpoints
- [ ] Whilst logged in, should be able to upload new logo to a form you have write permissions for.
- [ ] Whilst logged in, should be able to upload images to an image field for a form you have write permissions for.

**Comment by tshuli** [comment]
**fix: include noopener, noreferrer to <a> tags that open in a new page**

@tshuli 

- [x] Check that links to external page (e.g. share link for form) include rel="noopener noreferrer"

**Review by mantariksh — APPROVED** [review]

**Review by mantariksh — APPROVED** [review]

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
