### PR TITLE
fix(deps-dev): run npm audit fix

### PR DESCRIPTION
**Pull request by mantariksh**
This PR upgrades MockPass to resolve a vulnerability with `node-forge`.

### CODE REVIEW

**Review by liangyuanruo — APPROVED** [review]
have u tried running singpass locally?

**Comment by mantariksh** [comment]
yup, but e2e tests for CorpPass are failing, I'll investigate that further

**Comment by mantariksh** [comment]
@LoneRifle hey quick qn - the mockpass corppass login page shows all undefined, but the UEN shows up when I click on one of them. any idea if this is a mockpass problem or a formsg problem?
Screenshot 2020-10-08 at 12 16 51 AM
fScreenshot 2020-10-08 at 12 18 35 AM

**Comment by mantariksh** [comment]
@LoneRifle I found the issue I think: the object declared [here](https://github.com/opengovsg/mockpass/blob/887f5a9410c42e38ecc7f49fd6028db1e077565c/lib/assertions.js#L70) should have lowercase keys. I can't open a PR though because I don't have access to the repo :/

**Comment by LoneRifle** [comment]
Kicked out mockpass 2.5.4 for you

**Pull request merged**
