### PR TITLE
feat: Release v4.32.0

### PR DESCRIPTION
**Pull request by karrui**
## New
- Create bounce collection and alarms (#131)
- Increase breaker window time and add minimum volume threshold (#165)
- Add mailto link for secret key when creating storage mode form (#150)
- Support &`;'" in form title (#156)
- Log form ID in GA event labels (#154)
- Add core `ApplicationError` for express app (#195)
- Remove beta field validations (#194)

## Improved
- Refactor `MailService` to a class based Typescript implementation (#76)
- Migrate date util to Typescript (#161)
- Migrate encryption util to Typescript (#167)
- Delete render promise util (#168)
- Move verification module to `modules/verification` and migrate to Typescript (#172)
- Move `util/response` to  `modules/submission` and migrate to Typescript (#176)

## Fixes
- Enable `forceDelivery` on Twilio message sending (#178)
- Shift `userEmail` retrieval to GA service (#192) 

## Misc
- Various dependabot dependency bumps:
  - bump font-awesome from 4.6.1 to 4.7.0 (#186) 
  - bump puppeteer-core from 4.0.0 to 5.2.1 (#188)
  - bump uid-generator from 1.0.0 to 2.0.0 (#187)

- Various dependabot dev dependency bumps:
  - bump typescript to 4.0.2 (#196)
  - bump env-cmd from 9.0.3 to 10.1.0 (#133)
  - bump jasmine from 3.5.0 to 3.6.1 (#158)
  - bump @typescript-eslint/eslint-plugin (#197)
  - bump @opengovsg/mockpass from 2.2.0 to 2.4.6 (#198)

### CODE REVIEW

**Comment by karrui** [comment]
## Post release checklist
- [ ] Create index on `expireAt` in Bounce collection in production.

**Comment by karrui** [comment]
## Tests

- [ ] Submit a form with all valid email recipients. Check that in the Bounces collection, all the email addresses are present for that form ID and `hasBounced` is false for all of them.
- [ ] Submit the same form as the previous test again. Check that the Bounces collection still only has 1 document for that form ID, i.e. a duplicate document is not created.
- [ ] Add an invalid email recipient to that form and submit it again. Check that the Bounces collection still only has 1 document for that form ID, and `hasBounced` is set to true only for the invalid recipient.
- [ ] For the same form, edit the recipient list such that it only has invalid emails. Check that the corresponding document in the Bounces collection is updated with the new recipient list, and `hasBounced` is set to true for all of them. Check CloudWatch alarms and ensure that the alarm called "Critical Bounces (Staging)" has triggered.
- [ ] Bounce document expires 30min after initial creation.
- [ ] `BOUNCE_LIFE_SPAN` env var has been added in production and set to 1800000 (number of ms in 30min).
- [ ] Alarm has been created for critical bounces in production.

**Comment by karrui** [comment]
## Tests
### Mailto link feature
- [ ] Clicking on "Email" link in secret key modal opens email with correct subject, form title and secret key

**Comment by karrui** [comment]
## Tests
### Log form ID in GA event labels
- [ ] Create and submit a form. Check that the formId is present in the GA logs.
- [ ] Create a storage mode form. Submit a response. Download responses. Check that the admin user email is present in the GA logs.

**Comment by karrui** [comment]
## Tests
### Backend fixes/improvements - MailService refactor
- [ ] Log in to application. You should receive an OTP mail and log in successfully
- [ ] Create an email form, and add an email field with email verification and confirmation (leave confirmation with default values).
  - [ ] Enter your email into the email form and verify your email. The email should be sent to the given email and the OTP should validate successfully.
  - [ ] Submit the form. You (as form admin) should receive the usual form submission email with the correct answers. You (as the form filler) should also receive an acknowledgement email. 

- [ ] Create an email form, and add an email field with email verification and confirmation (**change the defaults with your own values).**
  - [ ] Enter your email into the email form and verify your email. The email should be sent to the given email and the OTP should validate successfully.
  - [ ] Submit the form. You (as form admin) should receive the usual form submission email with the correct answers. You (as the form filler) should also receive an acknowledgement email **with the values you as admin entered**.

**Comment by karrui** [comment]
## Tests
### Backend fixes/improvements - DateUtil refactor
- [ ] Go to any storage mode form with responses (or create one and add a response). Go to response tab and filter by date. 
  - [ ] Select a date range with no responses. When attempting to download responses, it should successfully say no responses found.
  - [ ] Select a date range with responses. When attempting to download responses, it should decrypt and download the correct responses.

**Comment by karrui** [comment]
@arshadali172 

## Tests
### Final UAT
- [ ]  General run through on IE11 + Intranet

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
