### PR TITLE
build: release v5.17.0

### PR DESCRIPTION
**Pull request by karrui**
# Release v5.17.0

## Features
- build(ci): create   .env files in EB with Param Store   [`ac27242`](https://github.com/opengovsg/FormSG/commit/ac2724276bef8e4bd47211efa32b24a5a8cb1738)
- feat(config): support config via   dotenv, use EB to create file   [`#2194`](https://github.com/opengovsg/FormSG/pull/2194)
- feat(config): support env var config   via dotenv   [`9fc8c9e`](https://github.com/opengovsg/FormSG/commit/9fc8c9e6562fe55e7e13c593c2bb1a4c96cbfe96)
- feat(feature-manager): remove sms from   feature manager [`#2218`](https://github.com/opengovsg/FormSG/pull/2218)
- feat(feature-manager): remove   spcp-myinfo from feature manager   [`#2222`](https://github.com/opengovsg/FormSG/pull/2222)

## Improvements
- docs(deploy): add information  concerning SSM params   [`ef7d79f`](https://github.com/opengovsg/FormSG/commit/ef7d79fdfac7c482504aa2e2621b4b190479f070)
- refactor: convert   CsvMergedHeadersGenerator to typescript   [`#2080`](https://github.com/opengovsg/FormSG/pull/2080)
- refactor(feature-manager): delete   remaining unused code   [`#2223`](https://github.com/opengovsg/FormSG/pull/2223)
- test: fix flaky form feedback test   [`#2241`](https://github.com/opengovsg/FormSG/pull/2241)

## Dependency changes
- chore(deps-dev): bump @babel/preset-env   from 7.14.5 to 7.14.7   [`#2238`](https://github.com/opengovsg/FormSG/pull/2238)
- chore(deps-dev): bump @types/node from   14.17.3 to 14.17.4 [`#2245`](https://github.com/opengovsg/FormSG/pull/2245)
- chore(deps-dev): bump   @typescript-eslint/eslint-plugin   [`#2239`](https://github.com/opengovsg/FormSG/pull/2239)
- chore(deps-dev): bump   @typescript-eslint/parser from 4.27.0 to 4.28.0   [`#2226`](https://github.com/opengovsg/FormSG/pull/2226)
- chore(deps-dev): bump core-js from   3.14.0 to 3.15.0 [`#2225`](https://github.com/opengovsg/FormSG/pull/2225)
- chore(deps-dev): bump core-js from   3.15.0 to 3.15.1 [`#2243`](https://github.com/opengovsg/FormSG/pull/2243)
- fix(deps): bump aws-sdk from 2.931.0 to   2.932.0 [`#2237`](https://github.com/opengovsg/FormSG/pull/2237)
- fix(deps): bump nocache from 3.0.0 to   3.0.1 [`#2236`](https://github.com/opengovsg/FormSG/pull/2236)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
### Deleting feature manager
- [ ] Submit a form with a verified SMS field
- [ ] Create, activate and submit a Singpass form in email mode. Repeat for storage mode and decrypt the response.
- [ ] Create, activate and submit a Corppass form in email mode. Repeat for storage mode and decrypt the response.
- [ ] Create, activate and submit a MyInfo form in email mode

**Comment by karrui** [comment]
## Tests
### `parsedResponses` refactor
Copy this [email-mode form](https://staging.form.gov.sg/60d0086fcf8dc0001197b48d/use-template).

- [ ] Submit the form with valid inputs. Submission should go through.
- [ ] Copy the request as a CURL, and modify the responses to have invalid information (like invalid email, phone number). The error you get is `There is something wrong with your form submission. Please check your responses and try again.`
- [ ] Paste that same request you copied as CURL, this time deleting a compulsory field (like the decimal field). The error message is `The form has been updated. Please refresh and submit again.`

**Comment by karrui** [comment]
## Tests
### convert `CsvMergedHeadersGenerator` to TS
- [ ] Create a storage mode form with a table field (to check `TableResponse`), a checkbox field (to check `ArrayAnswerResponse`) and an email field (to check `SingleAnswerResponse`). Submit a few responses and download the csv. Ensure that all answers to each form field are present in the csv and the metadata headers are also present.

**Comment by karrui** [comment]
## Tests
### ELB, SSM, AWS, more acronyms
- [ ] App runs

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
