### PR TITLE
build: release v4.50.0

### PR DESCRIPTION
**Pull request by karrui**
## Release v4.50.0
_Halfway to the 4.100.0 mark!_ 

### Improvements
- chore: improve logging  when answer is undefined   [`#856`](https://github.com/opengovsg/FormSG/pull/856)
- fix: Put email domain restriction behind verified-fields feature toggle   [`#852`](https://github.com/opengovsg/FormSG/pull/852)
- refactor: migrate saveMetadataToDb to TypeScript   [`#778`](https://github.com/opengovsg/FormSG/pull/778)
- refactor: migrate sendAdminEmail to TypeScript   [`#781`](https://github.com/opengovsg/FormSG/pull/781)
- refactor: migrate isFormPublic middleware to TypeScript   [`#791`](https://github.com/opengovsg/FormSG/pull/791)

### Dependency upgrades
- fix: run npm audit fix [`#858`](https://github.com/opengovsg/FormSG/pull/858)
- fix(deps): bump angular-animate from 1.8.0 to 1.8.2   [`#860`](https://github.com/opengovsg/FormSG/pull/860)
- chore(deps-dev): bump @types/express from 4.17.8 to 4.17.9   [`#840`](https://github.com/opengovsg/FormSG/pull/840)
- chore(deps-dev): bump @types/express-serve-static-core   [`#841`](https://github.com/opengovsg/FormSG/pull/841)
- chore(deps-dev): bump @types/mongodb from 3.5.34 to 3.6.3   [`#839`](https://github.com/opengovsg/FormSG/pull/839)
- chore(deps-dev): bump babel-loader from 8.2.1 to 8.2.2   [`#859`](https://github.com/opengovsg/FormSG/pull/859)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
### Email domain restriction fixes
- [ ] On staging, email domain restriction toggle in email fields should show up and be able to be toggled on/off
- [ ] On staging-alt (without the verified fields feature enabled), email domain restriction toggle in email fields should not show up.

**Comment by mantariksh** [comment]
## Tests
### Email submissions
- [ ] Submit an email form with an attachment. Check that the submission is saved to the database with a response hash.
- [ ] Submit the form with a different attachment and check that the hash is different.

**Comment by karrui** [comment]
## Tests
### Typescript refactors
- [ ] Viewing an archived form as public form filler should return 410
- [ ] Viewing a private form as public form filler should return 404 with form's inactive message
- [ ] Viewing a public form as public form filler should resolve successfully

**Comment by karrui** [comment]
## Tests
**IE11 intranet tests for this week**
- [ ] Submit an email form with an attachment. Check that the submission is saved to the database with a response hash.
- [ ] Submit the form with a different attachment and check that the hash is different.

**IE11 intranet general run-through**
- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your GSIB inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Review by mantariksh — APPROVED** [review]

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
