### PR TITLE
chore(payments): remove payment flags checks from payment controller

### PR DESCRIPTION
**Pull request by KenLSM**
## Problem

We're no longer gating our payment features behind a flag as it has been released as general availability.

Closes FRM-1322

## Solution

Remove flags.

**Breaking Changes** 

- No - this PR is backwards compatible  

#### Regression
- [ ] Go to form settings payment page
- [ ] Click Connect Stripe
- [ ] Observe that stripe is connected successfully

### CODE REVIEW

**Review by g-tejas — COMMENTED** [review]
Do we need to remove these from `SettingsPage.tsx` as well?

https://github.com/opengovsg/FormSG/blob/620453d3a0017f42b657cc4ee3e714397ccd844e/frontend/src/features/admin-form/settings/SettingsPage.tsx#L52

**Review by g-tejas — COMMENTED** [review]
https://github.com/opengovsg/FormSG/blob/620453d3a0017f42b657cc4ee3e714397ccd844e/frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx#L37

There's a check for betaFlags.payments here as well

**Comment by KenLSM** [comment]
> https://github.com/opengovsg/FormSG/blob/620453d3a0017f42b657cc4ee3e714397ccd844e/frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx#L37
> 
> There's a check for betaFlags.payments here as well

801cf7a84

**Comment by KenLSM** [comment]
> https://github.com/opengovsg/FormSG/blob/620453d3a0017f42b657cc4ee3e714397ccd844e/frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx#L37
> 
> There's a check for betaFlags.payments here as well

f52521831

**Review by g-tejas — APPROVED** [review]
LGTM! I looked through other parts of the code but I don't think we missed anything

**Pull request merged**
