### PR TITLE
build: release v5.22.0

### PR DESCRIPTION
**Pull request by mantariksh**
## New
- feat(sms-limiting): db dependencies [`#2503`](https://github.com/opengovsg/FormSG/pull/2503)
- feat: add MYINFO_BANNER_CONTENT env var for bannering myinfo forms [`#2457`](https://github.com/opengovsg/FormSG/pull/2457)

## Fixes
- fix(login): show Joi validation error correctly [`#2499`](https://github.com/opengovsg/FormSG/pull/2499)
- fix(SGID): disallow SGID authentication in storage mode [`#2468`](https://github.com/opengovsg/FormSG/pull/2468)
- feat: remove validation when logging esrvcId to login collection [`90a0fb0`](https://github.com/opengovsg/FormSG/commit/90a0fb04c450607c5e246c153583844bfe6d42dc)

## Improved
- feat(client): add EncryptionService to validate encrypt submission responses [`#2436`](https://github.com/opengovsg/FormSG/pull/2436)
- fix(snyk): Fix vulnerability in Twilio [`#2469`](https://github.com/opengovsg/FormSG/pull/2469)

## Internal
- chore: add postinstall script to install /shared modules [`#2438`](https://github.com/opengovsg/FormSG/pull/2438)
- chore: remove express-device [`#2498`](https://github.com/opengovsg/FormSG/pull/2498)
- feat(shared-types): move billing related types to shared folder [`#2400`](https://github.com/opengovsg/FormSG/pull/2400)
- feat(shared-types): relocate (admin-related) Submission types to new shared folder [`#2399`](https://github.com/opengovsg/FormSG/pull/2399)
- fix(types): Fix express session types based on latest definitions [`#2463`](https://github.com/opengovsg/FormSG/pull/2463)
- feat(shared-types): move core, FormFeedback related types to root shared folder [`#2394`](https://github.com/opengovsg/FormSG/pull/2394)
- ref: remove backend package dependencies from Form (sub-)types and move to shared dir [`#2385`](https://github.com/opengovsg/FormSG/pull/2385)

### App dependencies
- fix(deps): bump zod from 3.6.1 to 3.7.1 [`#2506`](https://github.com/opengovsg/FormSG/pull/2506)
- fix(deps): bump libphonenumber-js from 1.9.22 to 1.9.23 [`#2505`](https://github.com/opengovsg/FormSG/pull/2505)
- fix(deps): bump aws-sdk from 2.956.0 to 2.958.0 [`#2497`](https://github.com/opengovsg/FormSG/pull/2497)
- fix(deps): bump zod from 3.5.1 to 3.6.1 [`#2490`](https://github.com/opengovsg/FormSG/pull/2490)
- fix: upgrade zod from 3.3.4 to 3.5.1 [`#2476`](https://github.com/opengovsg/FormSG/pull/2476)
- fix(deps): bump aws-sdk from 2.955.0 to 2.956.0 [`#2474`](https://github.com/opengovsg/FormSG/pull/2474)
- fix(deps): bump fp-ts from 2.11.0 to 2.11.1 [`#2458`](https://github.com/opengovsg/FormSG/pull/2458)
- fix: upgrade sortablejs from 1.13.0 to 1.14.0 [`#2456`](https://github.com/opengovsg/FormSG/pull/2456)
- fix(deps): bump aws-sdk from 2.954.0 to 2.955.0 [`#2461`](https://github.com/opengovsg/FormSG/pull/2461)
- fix(deps): bump aws-sdk from 2.953.0 to 2.954.0 [`#2451`](https://github.com/opengovsg/FormSG/pull/2451)

### Dev dependencies
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#2508`](https://github.com/opengovsg/FormSG/pull/2508)
- chore(deps-dev): bump @opengovsg/mockpass from 2.7.6 to 2.7.7 [`#2507`](https://github.com/opengovsg/FormSG/pull/2507)
- chore(deps-dev): bump core-js from 3.15.2 to 3.16.0 [`#2493`](https://github.com/opengovsg/FormSG/pull/2493)
- chore(deps-dev): bump type-fest from 1.2.3 to 1.3.0 [`#2496`](https://github.com/opengovsg/FormSG/pull/2496)
- chore(deps-dev): bump ts-essentials from 7.0.2 to 7.0.3 [`#2495`](https://github.com/opengovsg/FormSG/pull/2495)
- chore(deps-dev): bump eslint from 7.31.0 to 7.32.0 [`#2494`](https://github.com/opengovsg/FormSG/pull/2494)
- chore(deps-dev): bump @types/node from 14.17.6 to 14.17.7 [`#2492`](https://github.com/opengovsg/FormSG/pull/2492)
- chore(deps-dev): bump @babel/preset-env from 7.14.8 to 7.14.9 [`#2491`](https://github.com/opengovsg/FormSG/pull/2491)
- chore(deps-dev): bump type-fest from 1.2.2 to 1.2.3 [`#2473`](https://github.com/opengovsg/FormSG/pull/2473)
- chore(deps-dev): bump @opengovsg/mockpass from 2.7.4 to 2.7.6 [`#2460`](https://github.com/opengovsg/FormSG/pull/2460)
- chore(deps-dev): bump testcafe from 1.15.0 to 1.15.1 [`#2459`](https://github.com/opengovsg/FormSG/pull/2459)

### CODE REVIEW

**Comment by mantariksh** [comment]
## Tests
**MyInfo banner**
- [ ] Add a `MYINFO_BANNER_CONTENT` env var. Check that the banner is updated on MyInfo forms only, and not on any other auth type (SP, CP, NIL, SGID).

**Comment by mantariksh** [comment]
## Tests
**Sign-in page Joi validation error**
- [ ] Go to the login page and enter your email. In the OTP input, paste any non-digit text (has to be copy-pasted, cannot be typed). Click submit and check that you get a readable error message.

**Comment by mantariksh** [comment]
## Tests
**SGID form duplication**
- [ ] Duplicate an SGID email-mode form into storage mode. The authentication type of the new duplicated form should be NIL.

**Comment by mantariksh** [comment]
## Tests
**Encryption service (1)**
- [ ] Submit a storage mode form with all field types, should submit properly. The submission should also be decrypted properly.

**Comment by mantariksh** [comment]
## Tests
**Encryption service (2)**
- [ ] Submit an email mode form with all field types. Enable email copy. Should submit properly. Should receive submission with all the correct fields.

**Comment by mantariksh** [comment]
## Tests
**Encryption service (3)**
- [ ] Submit an email MyInfo form with all MyInfo fields. Same as above.

**Comment by mantariksh** [comment]
## Tests
**Encryption service (4)**
- [ ] Submit a storage mode form with all field types where all fields are optional. Leave all the fields blank and submit. Should be able to submit and decrypt.

**Comment by mantariksh** [comment]
## Tests
**Encryption service (5)**
- [ ] Submit a storage mode form with all field types where all field types are hidden by logic. Hide all the logicked fields and submit. Should be able to submit and decrypt.

**Review by karrui — APPROVED** [review]

**Pull request merged**
