### PR TITLE
chore(ci): conditionally run CI/CD pipeline only on changes in relevant paths

### PR DESCRIPTION
**Pull request by karrui**
no point running chromatic on unrelated files and burning through our snapshot quota

Uses a new github action workflow `dorny/paths-filter@v2` to conditionally run Chromatic.

also conditionally runs ci/cd on frontend/backend/whatever based on what files has changed

### CODE REVIEW

**Comment by karrui** [comment]
Waiting for dorny/paths-filter@v2 to be approved for use in this org. Should simplify the CI/CD and cut down some times

**Comment by karrui** [comment]
Reopening to retrigger

**Review by justynoh — APPROVED** [review]
cool

**Comment by timotheeg** [comment]
Looks good, but err, so how/where is the map `needs.changes.outputs` populated?

**Comment by karrui** [comment]
> Looks good, but err, so how/where is the map `needs.changes.outputs` populated?

github workflow: https://github.com/dorny/paths-filter

will crawl through commits and check if there are any file changes. can look at source code if you want

**Comment by timotheeg** [comment]
Roger that! Thanks @karrui

**Pull request merged**
