### PR TITLE
feat: refresh storage mode responses when navigating to data / responses tab

### LINKED ISSUE #182: Improve refresh trigger for storage mode responses
In storage mode, admins must refresh the page or exit the form to update the list of storage mode responses
It could be more intuitive and seamless if we refresh the list of storage mode responses when navigating to the Data tab / Responses subtab

### PR DESCRIPTION
**Pull request by shuli-ogp**
## Problem

Closes #182

## Tests

- [ ] Create a storage mode form. Activate the form. Go to the Data tab in the admin panel. The responses view should say "This form doesn't have any responses yet.".
- [ ] Submit a response. Click the feedback sub-tab and then back to responses. The response count should now be 1.
- [ ] Submit another responses. Click the Share tab and then back to Data. The response count 
should now be 2.
- [ ] Unlock responses. Submit another response. Click the feedback sub-tab and then back to responses. The response count should now be 3. Check that the responses are correctly reflected in the list of responses.
- [ ] Submit another responses. Click the Share tab and then back to Data. The response count should now be 4. Check that the responses are correctly reflected in the list of responses.
- [ ] Open a response in the list. Submit another response. Exit the response view. The response count should now be 5. Check that the responses are correctly reflected in the list of responses.

### CODE REVIEW

**Review by mantariksh — CHANGES_REQUESTED** [review]
Hmm, tbh I'm not sure if this is the right approach. Refreshing upon every single access of the tab might place a large load on the Submissions collection. A better approach might be to have a refresh button which allows admins to choose when to refresh the list, but that will require design input. @karrui thoughts?

**Comment by shuli-ogp** [comment]
as discussed at sync-up, @liangyuanruo to review before we decide what to do next

**Comment by syan-syan** [comment]
not sure if this has alr been discussed but perhaps we can put in a check to compare response count or on timestamp of latest response before triggering the refresh @shuli-ogp @liangyuanruo

**Comment by liangyuanruo** [comment]
De-prioritising this improvement in UX due to potential to introduce database performance problems, as discovered in #174.

**Pull request closed without merging**
