### PR TITLE
build: Release 4.30.3 - Typescript migrations, filter storage mode responses by submission id

### PR DESCRIPTION
**Pull request by arshadali172**
## New
- Remove `allowSms` beta flag
- Filter Storage Mode Responses by Submission Id
- Show error upon FileReader failure

## Fix
- Phone validation now only accepts 8 digit #s starting with 8 or 9
- Fix myInfoError typo

## Improved
- Setup jest for use with Typescript tests
- Updating contributing, readme, license for open source
- Several backend files migrated to TypeScript.

### CODE REVIEW

**Comment by arshadali172** [comment]
## Tests

@karrui 
- [ ] Email mode: check that you don't have the allowSms beta flag, and you can see the "Verified" option for mobile fields. Submit a form with a verified mobile number and check that the email response has the [verified] prefix.
- [ ] Storage mode: check that you don't have the allowSms beta flag, and you can see the "Verified" option for mobile fields. Submit a form with a verified mobile number and check that the response in the Data tab has the [verified] prefix. Download the responses CSV and make sure the answer appears correctly (there won't be a [verified] prefix in the column header).
- [ ] Upload an attachment from Google Drive on an Android phone. The error should show as per the screenshot.
- [ ] On both desktop and mobile, upload a valid attachment. The UI should behave correctly. Make sure that this works for .zip files.
- [ ] On both desktop and mobile, upload an attachment which exceeds the maximum allowed size. You should see the correct error message, and you should subsequently be able to upload a valid attachment and submit the form.
- [ ] On both desktop and mobile, upload an attachment of an invalid file type (e.g. .js). You should see the correct error message, and you should subsequently be able to upload a valid attachment and submit the form.

@mantariksh 
- [ ] Ensure that phone number field for Singapore numbers start with 8 and 9
- [ ] Submit a form with all fields. 
  - The responses sent to the admin/form-filler email for **email forms** should have the correct questions for all fields (table fields should be `${title} (${column titles separated by comma})`
  - The responses sent to the results tab for **storage mode forms** should also display the correct questions.

@arshadali172 
- [ ] Test filtering submissions by reference ID 
- [ ] General tests on IE/Intranet

**Comment by karrui** [comment]
## Tests

@mantariksh 
- [ ] Ensure that phone number field for Singapore numbers start with 8 and 9
- [ ] Submit a form with all fields. 
  - The responses sent to the admin/form-filler email for **email forms** should have the correct questions for all fields (table fields should be `${title} (${column titles separated by comma})`
  - The responses sent to the results tab for **storage mode forms** should also display the correct questions.

**Comment by karrui** [comment]
## Tests
@arshadali172 
- [ ] Test filtering submissions by reference ID 
- [ ] General tests on IE/Intranet

**Comment by arshadali172** [comment]
@liangyuanruo 
- [ ] General tests on IE/Intranet

**Comment by karrui** [comment]
Mobile fields do not show country flags. Probably due to #90.

**Pull request merged**
