### PR TITLE
chore: remove dependabot triggers for react /frontend directory

### PR DESCRIPTION
**Pull request by karrui**
Dependabot is creating new PRs to target form-v2/develop, which is pointless. Removing that.

### CODE REVIEW

**Review by justynoh — APPROVED** [review]
bye dependabot

**Comment by karrui** [comment]
Dependabot not going away, it's updating to correct main `develop` instead now LOL

**Comment by karrui** [comment]
ok bye dependabot we will upgrade all packages then reneable

**Comment by justynoh** [comment]
actually bye dependabot

**Comment by karrui** [comment]
OMG ITS TAKING 30 MINUTE A PR WTF

**Pull request merged**
