### PR TITLE
feat: Increase attachment size options

### LINKED ISSUE #662: Increase attachment size options
@tshuli not sure how much incremental effort it would be to allow 1-20mb, then remove 8-20mb for Email mode? we have some users wanting to have a 20mb attachment but they cant right now as our max individual attachment size is 7mb

### PR DESCRIPTION
**Pull request by tshuli**
## Problem
Closes #662

## Solution
- Allow attachments up to 20mb for storage mode
- Expand attachment size options to 1mb, 2mb, 3mb, 7mb, 10mb, 20mb. For email mode, the limit is 7mb
- Shift size guidance to tooltip

## Before & After Screenshots

**BEFORE**:
Screenshot 2020-11-19 at 4 17 29 PM
**AFTER**:

**(email mode)**
Screenshot 2020-11-23 at 3 25 20 PM

**(storage mode)**
Screenshot 2020-11-23 at 3 25 45 PM

## Tests
(tested on IE)
- [ ] Create storage mode form. Check that you can set max attachment size up to 20mb. Publish form. Upload file of ~15mb. Check that upload succeeds and you can retrieve it from admin data tab.
- [ ] Check that it is not possible to have total attachments across multiple fields exceeding 20mb.
- [ ] Create email mode form. Check that you can only set max attachment size up to 7mb. Upload file of ~6mb. Check that upload succeeds and you can receive it in your inbox.
- [ ] Check that it is not possible to have total attachments across multiple fields exceeding 7mb
.

### CODE REVIEW

**Comment by tshuli** [comment]
@syan-syan to review the copy pls

**Review by karrui — APPROVED** [review]
lgtm

**Comment by syan-syan** [comment]
Suggesting change for brevity and actionability (removing 6 and 9 MB since not actionable)

Guideline: Images / PDFs - 1-3 MB, Slides - 7 MB, Videos - 10-20 MB. Include up to 20 MB of attachments in a submission (Storage mode).

**Comment by tshuli** [comment]
@syan-syan Thanks! This is clearer. I've made the copy changes and will merge in.

**Pull request merged**
