### PR TITLE
build: Release 5.24.0

### PR DESCRIPTION
**Pull request by tshuli**
**Improvements**
- feat(sms-limiting): changes for mail/modal [`#2565`](https://github.com/opengovsg/FormSG/pull/2565)

**Fixes**
- fix: disable eserviceid check modal for sgid forms [`#2593`](https://github.com/opengovsg/FormSG/pull/2593)
- fix(verification): prevents otp request when limit exceeded [`#2586`](https://github.com/opengovsg/FormSG/pull/2586)
- fix: prevents otp request when limit exceeded [`#2630`](https://github.com/opengovsg/FormSG/pull/2630)
- fix(MailService): correct type, pass in original form admin as param [`#2629`](https://github.com/opengovsg/FormSG/pull/2629)

**Dependency Updates**
- chore: freeze test-cafe package version to 1.15.1 [`#2592`](https://github.com/opengovsg/FormSG/pull/2592)
- chore(deps-dev): bump @types/jest from 26.0.24 to 27.0.0 [`#2573`](https://github.com/opengovsg/FormSG/pull/2573)
- chore(deps-dev): bump @types/jest from 27.0.0 to 27.0.1 [`#2589`](https://github.com/opengovsg/FormSG/pull/2589)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#2597`](https://github.com/opengovsg/FormSG/pull/2597)
- chore(deps-dev): bump @typescript-eslint/parser from 4.29.1 to 4.29.2 [`#2595`](https://github.com/opengovsg/FormSG/pull/2595)
- chore(deps-dev): bump axios-mock-adapter from 1.19.0 to 1.20.0 [`#2591`](https://github.com/opengovsg/FormSG/pull/2591)
- chore(deps-dev): bump core-js from 3.16.1 to 3.16.2 [`#2625`](https://github.com/opengovsg/FormSG/pull/2625)
- chore(deps-dev): bump jest-localstorage-mock from 2.4.14 to 2.4.16 [`#2581`](https://github.com/opengovsg/FormSG/pull/2581)
- chore(deps-dev): bump supertest from 6.1.4 to 6.1.5 [`#2571`](https://github.com/opengovsg/FormSG/pull/2571)
- chore(deps-dev): bump testcafe from 1.15.1 to 1.15.2 [`#2572`](https://github.com/opengovsg/FormSG/pull/2572)
- chore(deps-dev): bump ts-essentials from 7.0.3 to 8.0.0 [`#2598`](https://github.com/opengovsg/FormSG/pull/2598)
- fix: upgrade date-fns from 2.22.1 to 2.23.0 [`#2587`](https://github.com/opengovsg/FormSG/pull/2587)
- fix(configure-mobile.client): updated counts to not be shown when form onboarded [`#2585`](https://github.com/opengovsg/FormSG/pull/2585)
- fix(deps): bump @babel/runtime from 7.14.8 to 7.15.3 [`#2569`](https://github.com/opengovsg/FormSG/pull/2569)
- fix(deps): bump aws-sdk from 2.964.0 to 2.965.0 [`#2570`](https://github.com/opengovsg/FormSG/pull/2570)
- fix(deps): bump aws-sdk from 2.965.0 to 2.966.0 [`#2580`](https://github.com/opengovsg/FormSG/pull/2580)
- fix(deps): bump aws-sdk from 2.966.0 to 2.968.0 [`#2590`](https://github.com/opengovsg/FormSG/pull/2590)
- fix(deps): bump aws-sdk from 2.968.0 to 2.969.0 [`#2624`](https://github.com/opengovsg/FormSG/pull/2624)
- fix(deps): bump twilio from 3.66.1 to 3.67.0 [`#2582`](https://github.com/opengovsg/FormSG/pull/2582)
- fix(deps): bump zod from 3.7.1 to 3.7.2 [`#2588`](https://github.com/opengovsg/FormSG/pull/2588)

### CODE REVIEW

**Comment by tshuli** [comment]
## Tests

**fix: disable eserviceid check modal for sgid forms**
- [ ] Create SGID form. Activate. check that eserviceid modal does not show up
- [ ] Check that sgid form can be submitted successfully
- [ ] Create SP form. Activate. check that eserviceid modal shows up
- [ ] Check that SP form can be submitted successfully

**Comment by tshuli** [comment]
**fix(verification): prevents otp request when limit exceeded**

- [ ] Create form with mobile verification. Open in public form view. Disable mobile verification. Attempt to verify and check that otp is not sent.

**Comment by karrui** [comment]
## Tests
### Verified sms quota emails copywriting
**Warning email tests - requires db population in staging**
- [ ] Create a form with a verifiable mobile field.  Insert enough smses so that the form has 2499 total smses (see the misc section down below). Insert a collaborator to also check for collaborator email
- [ ] Open the form and subsequently, the mobile field. Verify that the counts has been updated.
- [ ] request for otp verification. Should receive an email warning form admin about the limit. Attempt to toggle the mobile field on again - this should succeed and show the updated count.
- [ ] Verify that there is a warning email receieved.
  - [ ] Warning email has a replyto of form [AT] open [DOT] gov [DOT] sg
  - [ ] Admin Email contains the following pieces of information
    - The forms that may be affected
    - Your account can use <%= numAvailable %> more free verifications until free SMS verification is automatically disabled on all forms you own.
    - Forms with Twilio already set up will not be affected.
  - [ ] Collaborator email contains the following pieces of information
    - The owner of this form has used up <%= percentageUsed %> of their free tier limit for SMS verifications.
    - Only the form you are collaborator on is mentioned 
    - SMS verification will be disabled for this form when the owner’s account has reached <%= smsVerificationLimit %> verifications.

**Comment by karrui** [comment]
## Tests
### Verified sms quota emails copywriting
**Limit hit email tests - requires db population in staging**
- [ ] Create a form with a verifiable mobile field.  Insert enough smses so that the form has 9999 total smses (see the misc section down below). Insert a collaborator to also check for collaborator email
- [ ] request for otp verification. Should receive a limit hit email to form admin.
- [ ] Verify that there is a field disabled email received.
  - [ ] Email has a replyto of form [AT] open [DOT] gov [DOT] sg
  - [ ] Admin Email contains the following pieces of information
    - The forms that may be affected
    - As you have reached the free tier limit of <%= smsVerificationLimit %> per account, SMS OTP verification has been automatically disabled on **all** forms you own.
    - Forms with Twilio already set up will not be affected.
  - [ ] Collaborator email contains the following pieces of information:
    - Only the form you are collaborator on is mentioned 
    - As the form owner has reached the account limit of <%=smsVerificationLimit %> free verifications, SMS verification has been automatically disabled on this form.

**Review by karrui — APPROVED** [review]

**Pull request merged**
