### PR TITLE
fix: resolve eslint warnings on npm builds

### PR DESCRIPTION
**Pull request by g-tejas**
## Problem

This PR resolves the warnings that arise from eslint

**Breaking Changes** 
- [x] No - this PR is backwards compatible

### CODE REVIEW

**Comment by g-tejas** [comment]
* **#7446** <a href="https://app.graphite.dev/github/pr/opengovsg/FormSG/7446?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @g-tejas and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by KenLSM** [comment]
**Regarding `no-unsed-vars`**
👍 

**Regarding `explicit-module-boundary-types`**
My personal take: for React Components that are not explicitly returning `JSX.Element`, I feel that it doesn't really add much value to add types to them. 

Usually, for these components, we are already using it as a component that will be rendered, and TS is smart enough to know whether the untyped-function is renderable function.

No qualms on adding them, but also not advocating that we should enforce a return to them.

**Comment by g-tejas** [comment]
> **Regarding `no-unsed-vars`** 👍
> 
> **Regarding `explicit-module-boundary-types`** My personal take: for React Components that are not explicitly returning `JSX.Element`, I feel that it doesn't really add much value to add types to them.
> 
> Usually, for these components, we are already using it as a component that will be rendered, and TS is smart enough to know whether the untyped-function is renderable function.
> 
> No qualms on adding them, but also not advocating that we should enforce a return to them.



> **Regarding `no-unsed-vars`** 👍
> 
> **Regarding `explicit-module-boundary-types`** My personal take: for React Components that are not explicitly returning `JSX.Element`, I feel that it doesn't really add much value to add types to them.
> 
> Usually, for these components, we are already using it as a component that will be rendered, and TS is smart enough to know whether the untyped-function is renderable function.
> 
> No qualms on adding them, but also not advocating that we should enforce a return to them.

@KenLSM  In that case, should we disable `explicit-module-boundary-types` eslint rule for `.tsx` files (since these files mostly consist of frontend components? It seems like the majority of the eslint warnings emitted on builds are just this. Either that or we can disable it per file, but that feels weird. Or should we just keep the warnings?

**Comment by KenLSM** [comment]
Sounds good on excluding `.tsx` files

**Pull request closed without merging**
