### PR TITLE
build: release v6.61.0

### PR DESCRIPTION
**Pull request by timotheeg**
## New

- feat: Add getStartOfDay function [`#6467`](https://github.com/opengovsg/FormSG/pull/6467)
- feat: track webhook metrics in DataDog [`#6469`](https://github.com/opengovsg/FormSG/pull/6469)
- chore: Send issue reported notification email to admin [`#6468`](https://github.com/opengovsg/FormSG/pull/6468)
- feat: email onboarding and help center of payments landing page [`#6462`](https://github.com/opengovsg/FormSG/pull/6462)
- fix: payout webhooks not returning OK [`#6436`](https://github.com/opengovsg/FormSG/pull/6436)
- feat: (BE) create and update admin feedback  [`#6454`](https://github.com/opengovsg/FormSG/pull/6454)
- build: merge v6.60.0 into develop  [`#6461`](https://github.com/opengovsg/FormSG/pull/6461)
- build: release v6.60.0 [`#6460`](https://github.com/opengovsg/FormSG/pull/6460)
- test: add payout cases [`d0eb2d4`](https://github.com/opengovsg/FormSG/commit/d0eb2d4f5ec741ffa9faa2742a713c9e2e7100b1)
- test: add tests for getMetadataPaymentId, cleanup test cases [`a5a06be`](https://github.com/opengovsg/FormSG/commit/a5a06bebe35d2f9c9d819997fa172baeb0c26190)
- refactor: use mapErr to handle errors in neverthrow chain [`ef18774`](https://github.com/opengovsg/FormSG/commit/ef18774805de9e2f0cd879440d29b9a6e57ea402)

## Dependencies

- fix(deps): bump libphonenumber-js from 1.10.34 to 1.10.36 in /shared [`#6466`](https://github.com/opengovsg/FormSG/pull/6466)
- fix(deps): bump type-fest from 3.11.1 to 3.12.0 in /shared [`#6464`](https://github.com/opengovsg/FormSG/pull/6464)

## Dev-Dependencies

- chore(deps-dev): bump @typescript-eslint/parser from 5.59.11 to 5.60.0 in /shared [`#6470`](https://github.com/opengovsg/FormSG/pull/6470)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.59.11 to 5.60.0 in /shared [`#6471`](https://github.com/opengovsg/FormSG/pull/6471)

### feat: track webhook metrics in DataDog [`#6469`](https://github.com/opengovsg/FormSG/pull/6469)
@LinHuiqing 

- [x] Create a storage-mode form. Set the webhook URL as a [Zapier](https://zapier.com/) URL (follow this [guide](https://guide.form.gov.sg/user-guides/advanced-guide/webhooks/zapier-integration) to set up a Zapier integration with your FormSG form to get that URL). Submit a response. A count of the response should be reflected in this [DD-graph](https://app.datadoghq.com/dashboard/f29-urp-an7/wan-lings-dashboard-test?fullscreen_end_ts=1687175566578&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1687171966578&fullscreen_widget=4704661163853978&tpl_var_env%5B0%5D=staging&from_ts=1684583088053&to_ts=1687175088053&live=false) with the tag 'zapier'
- [x] Repeat the same test, but with a URL from [Plumber](https://plumber.gov.sg/) - you will have to create a new pipe in Plumber with your FormSG form to get this URL. The associated tag should be 'plumber'
- [x] Repeat the same test, but with a non-zapier and non-plumber URL. The associated tag should be 'generic'
- [x] Access form definition in Studio3T and change url to something dummy (`http://foobarbaz123.ogp.com`), submit to trigger a submission and check behaviour: formSG should not throw a 500

### chore: Send issue reported notification email to admin [`#6468`](https://github.com/opengovsg/FormSG/pull/6468)
@LinHuiqing 
- [x] Verify that email content and aesthetic (spacing, casing) sent matches the one on [Figma](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=18487-191297&t=W1rhKXSHXfaNhoKG-4)

### feat: email onboarding and help center of payments landing page [`#6462`](https://github.com/opengovsg/FormSG/pull/6462)

@KenLSM 
- [x] Go to `/payments`.
- [x] Before any input / click interaction, payments landing page should look like the [design](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17464-182424&t=oUfFBKhxIFV65fFS-0) (minus the payment stats section).
- [x] First section (top CTA)
   - [x] Should look like top section with the email input as designed.
   - [x] Email validation:
      - [x] Entering a string that is not an email should show an error asking users to input a valid email.
      - [x] Entering an email that is not whitelisted should show an error asking users to input a whitelisted email.
      - [x] Entering an email that is whitelisted should show a success message (and disable submissions).
   - [x] An email should be sent to your entered email. Check the copy of the email against the [design](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17516-191210&t=NRWPjcEWt6ujplgg-0).
- [x] Bottom CTA
   - [x] If you have previously sent an email through the top CTA, refresh the page.
   - [x] Should look like bottom section with the email input as designed.
   - [x] Email validation:
      - [x] Entering a string that is not an email should show an error asking users to input a valid email.
      - [x] Entering an email that is not whitelisted should show an error asking users to input a whitelisted email.
      - [x] Entering an email that is whitelisted should show a success message (and disable submissions).
   - [x] An email should be sent to your entered email. Check the copy of the email against the [design](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17516-191210&t=NRWPjcEWt6ujplgg-0).
- [x] Help Center
   - [x] Should look like help center section with the collapsible content as designed.
   - [x] On click, links in content should scroll to the bottom CTA.
   - [x] On click, the "Visit our Payments Help Center" link should direct users to the public payment guide in a new tab.

#### Deploy Notes

**New environment variables**:

- `PAYMENT_LANDING_GUIDE_LINK`: guide link given to users onboarded from landing page.

### fix: payout webhooks not returning OK [`#6436`](https://github.com/opengovsg/FormSG/pull/6436)

@foochifa 

Payout event from stripe should now return a 200 OK
- [x] Find a trigger a webhook from stripe dashboard

### feat: (BE) create and update admin feedback [`#6454`](https://github.com/opengovsg/FormSG/pull/6454)

@timotheeg 

Happy path
- [x] Log in, and capture the auth cookie
- [x] Use a tool to set up api calls (like postman)
- [x] Send a post request to `/api/v3/admin/forms/feedback` with a req.body containing {rating: 0|1}
- [x] The request should be successful and you should receive a success message + the admin feedback dto in the response
- [x] Send a patch request to `/api/v3/admin/forms/feedback/:feedbackId` with a req.body containing {comment: '{something}'} and feedbackId of the feedback document from above
- [x] The request should be successful and you should receive a success message

### CODE REVIEW

**Comment by KenLSM** [comment]
Non blocking issues of differences in figma @LinHuiqing 

Seems like there's a `Coming soon!`  badge on the right side of `Flexible Payments` item that's missing in the actual.

| Figma | Actual |
|--------|--------|
| Screenshot 2023-06-22 at 9 30 34 AM | Screenshot 2023-06-22 at 9 30 36 AM |

**Comment by LinHuiqing** [comment]
> Non blocking issues of differences in figma @LinHuiqing
> 
> Seems like there's a `Coming soon!` badge on the right side of `Flexible Payments` item that's missing in the actual.
> 
> Figma	Actual
> Screenshot 2023-06-22 at 9 30 34 AM	Screenshot 2023-06-22 at 9 30 36 AM

Ah dammit, thanks for catching it! But I guess you'll make the badge no longer required soon? 👀

**Comment by LinHuiqing** [comment]
I can't really do the manual test for 'chore: Send issue reported notification email to admin [`#6468`](https://github.com/opengovsg/FormSG/pull/6468)' (@mayying's PR) because the endpoint is not exposed haha

Checked the HTML and looks about right though (tho I have some nits)! So gonna check it off 👍 

Based on the HTML and I have some comments:
1. The inverted commas for `'Request an Issue' button` seem like they're not the normal inverted commas we type. Is this intentional?
2. The line break should be `<br/>` instead of `</br>`.

**Comment by mayying** [comment]
> I can't really do the manual test for 'chore: Send issue reported notification email to admin [`#6468`](https://github.com/opengovsg/FormSG/pull/6468)' (@mayying's PR) because the endpoint is not exposed haha
> 
> Checked the HTML and looks about right though (tho I have some nits)! So gonna check it off 👍
> 
> Based on the HTML and I have some comments:
> 
> 1. The inverted commas for `'Request an Issue' button` seem like they're not the normal inverted commas we type. Is this intentional?
> 2. The line break should be `<br/>` instead of `</br>`.

Yeah, the PR is tagged with chore, as a way to indicate it's not gonna be active in production. So we can let it through now.
1. I was just following the figma design actually, see [here](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=18487-191297&mode=design&t=qIL2f3erANhjAI3A-0).
2. Noted on the </br> will change on next PR (but somehow it works tho?)

**Review by KenLSM — APPROVED** [review]
Tests completed LGTM

**Comment by LinHuiqing** [comment]
@KenLSM hold off merging first in view of https://github.com/opengovsg/FormSG/pull/6475?

**Comment by timotheeg** [comment]
On #6475, I've been trying to trigger run time errors, but it seems things are actually OK. I think we can release this first and do another release asap with improvement from @wanlingt 🤞 

```
error.at.0 | stack 0 WebhookValidationError: Error encountered during DNS resolution for webhook URL: https://foobarbaz123.ogp.foobar.bladiblou987654321.com/foo/bar/123. Check that the URL is correct or delete the webhook before proceeding.
error.at.1 | stack 1 at /opt/formsg/src/app/modules/webhook/webhook.validation.js:42:27
error.message | Error encountered during DNS resolution for webhook URL: https://foobarbaz123.ogp.foobar.bladiblou987654321.com/foo/bar/123. Check that the URL is correct or delete the webhook before proceeding.
error.name | WebhookValidationError
```

**Comment by timotheeg** [comment]
Though I didn't test a valid domain with connection refused, let me see if I can try that 🤔

**Comment by LinHuiqing** [comment]
> I was just following the figma design actually, see [here](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=18487-191297&mode=design&t=qIL2f3erANhjAI3A-0).

Ah yes, I think usually should be fine, just not sure if it might show up differently or something in the future for different mail clients since they're different characters. Not sure it really is better tho. Can leave it bah 🤔 

> Noted on the `</br>` will change on next PR (but somehow it works tho?)

as pm-ed, interesting read: https://www.quora.com/Why-does-both-br-and-br-works-the-same-way-Is-it-fine-to-use-both

**Comment by timotheeg** [comment]
> (but somehow it works tho?)

This is the reason there was (is?) so much crap on the web 😢 Browsers were trying to be resilient to invalid markup, but they implemented corrections differently.

That is an unfortunate drawback of the [Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle) ("be conservative in what you do, be liberal in what you accept from others"): when multiple vendors implement resilience differently (instead of having everyone sticking to standard), we get inconsistent behaviours. Not sure if any of you remember the days of "This site is tested with and optimized for Internet Explorer" 😑 

Nonetheless **WE** should always strictly produce valid content! So let's make sure we fix the markup before this gets used in prod!

**Pull request merged**
