### PR TITLE
build: release v5.12.0

### PR DESCRIPTION
**Pull request by yong-jie**
## New
- feat: Deduplicate Mongodb Error Messages [`#1996`](https://github.com/opengovsg/FormSG/pull/1996)
- feat: display different e-service placeholder text for singpass and corpass [`#1968`](https://github.com/opengovsg/FormSG/pull/1968)

## Improved
- fix(verification): loosen OTP waiting time by 2 seconds [`#1957`](https://github.com/opengovsg/FormSG/pull/1957)
- fix: add types to RequestHandler in submitEncryptModeForm [`#1889`](https://github.com/opengovsg/FormSG/pull/1889)
- refactor(verification): migrate otp verification to new v3 routes [`#1926`](https://github.com/opengovsg/FormSG/pull/1926)
- refactor(verification): migrate otp generation to new api endpoint [`#1916`](https://github.com/opengovsg/FormSG/pull/1916)
- refactor: Convert form-feedback.client.factory.js, CsvGenerator.js to TypeScript [`#1899`](https://github.com/opengovsg/FormSG/pull/1899)

## Dev changes
- build: upgrade application node version to v14 (by updating Docker image) [`#2038`](https://github.com/opengovsg/FormSG/pull/2038)
- ref: remove usage of express-serve-static-core types (ParamsDictionary, Query) [`#1848`](https://github.com/opengovsg/FormSG/pull/1848)

## Dependency upgrades
- fix(deps): bump aws-sdk from 2.913.0 to 2.914.0 [`#1980`](https://github.com/opengovsg/FormSG/pull/1980)
- fix(deps): bump libphonenumber-js from 1.9.18 to 1.9.19 [`#1979`](https://github.com/opengovsg/FormSG/pull/1979)
- fix(deps): bump opossum from 6.0.1 to 6.1.0 [`#1976`](https://github.com/opengovsg/FormSG/pull/1976)
- fix(deps): bump aws-sdk from 2.912.0 to 2.913.0 [`#1974`](https://github.com/opengovsg/FormSG/pull/1974)
- fix(deps): bump aws-sdk from 2.914.0 to 2.916.0 [`#1985`](https://github.com/opengovsg/FormSG/pull/1985)
- fix(deps): bump @sentry/browser from 6.4.1 to 6.5.0 [`#2033`](https://github.com/opengovsg/FormSG/pull/2033)
- fix(deps): bump aws-sdk from 2.916.0 to 2.918.0 [`#1993`](https://github.com/opengovsg/FormSG/pull/1993)
- fix(deps): bump @sentry/integrations from 6.4.1 to 6.5.0 [`#2036`](https://github.com/opengovsg/FormSG/pull/2036)
- fix: upgrade mongoose from 5.12.5 to 5.12.7 [`#1977`](https://github.com/opengovsg/FormSG/pull/1977)

## Dev dependencies
- chore(deps-dev): bump @types/express-serve-static-core [`#1973`](https://github.com/opengovsg/FormSG/pull/1973)
- chore(deps-dev): bump @types/node from 14.17.0 to 14.17.1 [`#1972`](https://github.com/opengovsg/FormSG/pull/1972)
- chore(deps-dev): bump core-js from 3.12.1 to 3.13.0 [`#1978`](https://github.com/opengovsg/FormSG/pull/1978)
- chore(deps-dev): bump typescript from 4.2.4 to 4.3.2 [`#1984`](https://github.com/opengovsg/FormSG/pull/1984)
- chore(deps-dev): bump @types/express from 4.17.11 to 4.17.12 [`#1975`](https://github.com/opengovsg/FormSG/pull/1975)
- chore(deps-dev): bump date-fns from 2.21.3 to 2.22.1 [`#1992`](https://github.com/opengovsg/FormSG/pull/1992)
- chore(deps-dev): bump @types/mongodb from 3.6.16 to 3.6.17 [`#1991`](https://github.com/opengovsg/FormSG/pull/1991)
- chore(deps-dev): bump core-js from 3.13.0 to 3.13.1 [`#1990`](https://github.com/opengovsg/FormSG/pull/1990)
- chore(deps-dev): bump @opengovsg/mockpass from 2.7.0 to 2.7.2 [`#2031`](https://github.com/opengovsg/FormSG/pull/2031)
- chore(deps-dev): bump eslint-plugin-import from 2.23.3 to 2.23.4 [`#1995`](https://github.com/opengovsg/FormSG/pull/1995)
- chore(deps-dev): bump @babel/preset-env from 7.14.2 to 7.14.4 [`#1994`](https://github.com/opengovsg/FormSG/pull/1994)
- chore(deps-dev): bump @typescript-eslint/parser from 4.25.0 to 4.26.0 [`#2035`](https://github.com/opengovsg/FormSG/pull/2035)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#2034`](https://github.com/opengovsg/FormSG/pull/2034)

### CODE REVIEW

**Comment by yong-jie** [comment]
## Tests
- [ ] Change authentication method to Singpass and Singpass(MyInfo). Placeholder text should show "Enter Singpass e-service ID".
- [ ] Change authentication method to Singpass(Corporate). Placeholder text should show "Enter Corppass e-service ID"

**Comment by yong-jie** [comment]
## Manual tests
- [ ] Request for an OTP for a verified field. When the 30 second timer on the UI elapses, _immediately_ request a new one. The request should be valid and you should receive the new OTP.

**Comment by yong-jie** [comment]
## Manual Tests 
- [ ] Create a form with a verifiable mobile field and publish it. Go to the form, and verify with a valid mobile number. There should be an OTP generated
- [ ] Follow the above, but on successful otp generation, go to the networks tab in the developer panel and `copy as fetch` for the request. Change the `fieldType` to something else. This should fail. Change the `answer` property to be an invalid number. this should also fail
- [ ] Create a form with a verifiable email field and publish it. Go to the form, and verify with a valid email. There should be an OTP generated
- [ ] Follow the above, but on successful otp generation, go to the networks tab in the developer panel and `copy as fetch` for the request. Change the `fieldType` to something else. This should fail. Change the `answer` property to be an invalid email. this should also fail.

**Comment by yong-jie** [comment]
## Tests

- [ ] Create email mode form. Check that feedback tab shows no feedback received.
- [ ] Check that form feedback can be submitted successfully. Do this several times.
- [ ] Check that submitted feedback and count appears correctly on feedback tab.
- [ ] Check that submitted feedback can be downloaded.
- [ ] Repeat above with storage mode form.

**Review by tshuli — APPROVED** [review]

**Pull request merged**
