### PR TITLE
build: release v4.48.0

### PR DESCRIPTION
**Pull request by karrui**
# Release v4.48.0

## New
- chore: add Go and Postman tips on Share tab [`#759`](https://github.com/opengovsg/FormSG/pull/759) 
- feat: remove .oa file from allowed file types [`#731`](https://github.com/opengovsg/FormSG/pull/731) 
- feat(utils): add exhaustive switch case typeguard [`#729`](https://github.com/opengovsg/FormSG/pull/729) 

## Improvements
- ref: migrate get feedback flow to TypeScript [`#735`](https://github.com/opengovsg/FormSG/pull/735) 
- ref: migrate stream feedback flow to TypeScript [`#733`](https://github.com/opengovsg/FormSG/pull/733) 
- refactor: migrate mobile number validator to ts [`#713`](https://github.com/opengovsg/FormSG/pull/713) 
- refactor: migrate radio button validator to ts [`#723`](https://github.com/opengovsg/FormSG/pull/723) 
- refactor: migrate rating validator to ts [`#724`](https://github.com/opengovsg/FormSG/pull/724) 
- refactor(field-validation): simplify [`#734`](https://github.com/opengovsg/FormSG/pull/734)
- feat: migrate get encrypt metadata endpoint controller to TypeScript [`#711`](https://github.com/opengovsg/FormSG/pull/711) 

## Bug fixes
- fix: backend validation does not prevent responses on hidden fields [`#736`](https://github.com/opengovsg/FormSG/pull/736) 
- fix(AdminFormRoutes): add Joi validation on /submission endpoint [`#712`](https://github.com/opengovsg/FormSG/pull/712) 

## Misc
- chore: update travis to have multiple ci stages [`#742`](https://github.com/opengovsg/FormSG/pull/742) 
- docs: add script for unlisting array of forms [`#714`](https://github.com/opengovsg/FormSG/pull/714)

## Dependency upgrades
- fix(deps): bump angular-messages from 1.8.1 to 1.8.2 [`#725`](https://github.com/opengovsg/FormSG/pull/725) 
- fix(deps): bump celebrate from 13.0.3 to 13.0.4 [`#756`](https://github.com/opengovsg/FormSG/pull/756) 
- fix(deps): bump express-rate-limit from 5.1.3 to 5.2.3 [`#726`](https://github.com/opengovsg/FormSG/pull/726) 
- fix(deps): bump mongoose from 5.10.15 to 5.10.18 [`#758`](https://github.com/opengovsg/FormSG/pull/758) 
- fix(deps): bump opossum from 5.0.1 to 5.0.2 [`#738`](https://github.com/opengovsg/FormSG/pull/738) 
- fix(deps): bump winston-cloudwatch from 2.3.2 to 2.4.0 [`#728`](https://github.com/opengovsg/FormSG/pull/728) 
- chore(deps-dev): bump @babel/preset-env from 7.12.1 to 7.12.7 [`#740`](https://github.com/opengovsg/FormSG/pull/740) 
- chore(deps-dev): bump @types/mongoose from 5.10.0 to 5.10.1 [`#746`](https://github.com/opengovsg/FormSG/pull/746) 
- chore(deps-dev): bump eslint from 7.13.0 to 7.14.0 [`#741`](https://github.com/opengovsg/FormSG/pull/741) 
- chore(deps-dev): bump lint-staged from 10.5.1 to 10.5.2 [`#722`](https://github.com/opengovsg/FormSG/pull/722) 
- chore(deps-dev): bump prettier from 2.1.2 to 2.2.0 [`#709`](https://github.com/opengovsg/FormSG/pull/709) 
- chore(deps-dev): bump stylelint from 13.6.1 to 13.8.0 [`#721`](https://github.com/opengovsg/FormSG/pull/721) 
- chore(deps-dev): bump ts-jest from 26.4.1 to 26.4.4 [`#720`](https://github.com/opengovsg/FormSG/pull/720) 
- chore(deps-dev): bump ts-mock-imports from 1.3.0 to 1.3.1 [`#747`](https://github.com/opengovsg/FormSG/pull/747)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
## Tips on Share Tab
- [ ] Tips show up
- [ ] Links work

**Comment by karrui** [comment]
# Tests
## TypeScript endpoint migrations
- [ ] Can retrieve feedback successfully (if feedback exists)
- [ ] Go to a form without feedback. Request should still succeed with 200 but empty page shown.
- [ ] Can download feedback successfully
- [ ] In storage mode, can view storage mode responses page successfully
- [ ] Can search for valid storage mode responses successfully
- [ ] Can search for invalid storage mode, just that no results are returned
- [ ] In empty responses, empty info is shown appropriately

**Comment by karrui** [comment]
## Tests
### Validator migrations
- [ ] Create two mobile phone number fields. Hide one of them behind logic.
- [ ] Check that validation on both visible and hidden phone number fields work when submitting programatically
 - Invalid phone number format is rejected
 - Valid phone number format is accepted
 - When international number are allowed, international phone number is accepted
 - When international number is not allowed, international phone number is rejected
- [ ] Create two radio button fields. Hide one of them behind logic.
- [ ] Check that validation on both visible and hidden radio button fields work, when submitting programatically
- Answer is accepted if it is one of the options or "other" if enabled
- Answer is rejected otherwise
- [ ] Create two rating fields. Hide one of them behind logic.
- [ ] Check that validation on both visible and hidden rating fields work by submitting programatically
- Rating is accepted if it is an integer between 1 and "steps", rejected otherwise
- Rating must not have trailing zero

**Comment by karrui** [comment]
## Tests
### General intranet run-through
- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your GSIB inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.
- [ ] Create form with MyInfo fields. Submit successfully

**Comment by karrui** [comment]
## Tests
### Specific IE11 run-through
- [ ] Share tips for Go/Postman renders correctly
- [ ] Can retrieve feedback successfully (if feedback exists)
- [ ] Go to a form without feedback. Request should still succeed with 200 but empty page shown.
- [ ] Can download feedback successfully
- [ ] In storage mode, can view storage mode responses page successfully
- [ ] Can search for valid storage mode responses successfully
- [ ] Can search for invalid storage mode, just that no results are returned
- [ ] In empty responses, empty info is shown appropriately

**Comment by mantariksh** [comment]
@mantariksh 
## Tests
### Logic edge cases
- [ ] Hide a table field using logic and check that the form can be submitted
- [ ] Hide a table field using logic, then unhide it and hide it again, and check that the form can be submitted
- [ ] Hide a table field using logic, then unhide it and fill it in, and check that the form can be submitted
- [ ] Hide a checkbox field using logic and check that the form can be submitted
- [ ] Hide a checkbox field using logic, then unhide it and hide it again, and check that the form can be submitted
- [ ] Hide a checkbox field using logic, then unhide it and fill it in, and check that the form can be submitted
- [ ] Hide an attachment field using logic and check that the form can be submitted
- [ ] Hide an attachment field using logic, then unhide it and hide it again, and check that the form can be submitted
- [ ] Hide an attachment field using logic, then unhide it and fill it in, and check that the form can be submitted

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
