### PR TITLE
build: release v5.4.0

### PR DESCRIPTION
**Pull request by mantariksh**
## New
- chore: take csv and attachments download out of beta [`#1466`](https://github.com/opengovsg/FormSG/pull/1466)

## Improved
- refactor: remove unnecessary field validator JS tests in favour of TS tests [`#1475`](https://github.com/opengovsg/FormSG/pull/1475)
- feat: revert custom code for CorpPass cloud migration [`#1476`](https://github.com/opengovsg/FormSG/pull/1476)
- refactor: migrate field validator tests to typescript [`#1444`](https://github.com/opengovsg/FormSG/pull/1444)
- refactor: remove deprecated analytics API endpoints [`#1427`](https://github.com/opengovsg/FormSG/pull/1427)
- feat: remove adminform passThroughFeedback [`#1298`](https://github.com/opengovsg/FormSG/pull/1298)
- refactor: Migrate 3 more filters to handleEncryptedSubmission [`#1420`](https://github.com/opengovsg/FormSG/pull/1420)
- refactor: move Verification files together (part 1) [`#1450`](https://github.com/opengovsg/FormSG/pull/1450)
- build: fix mergify config [`#1456`](https://github.com/opengovsg/FormSG/pull/1456)
- feat: add samesite GA cookie property to enable GA in iframe [`#1463`](https://github.com/opengovsg/FormSG/pull/1463)
- chore: copy changes [`#1408`](https://github.com/opengovsg/FormSG/pull/1408)
- fix: shortened sms otp copy for accessibility [`#1461`](https://github.com/opengovsg/FormSG/pull/1461)
- ref: collapse middlewares of /adminform/submissions/download [`#1442`](https://github.com/opengovsg/FormSG/pull/1442)
- refactor: display verification error message if present [`#1443`](https://github.com/opengovsg/FormSG/pull/1443)
- feat: remove isTemplate validation on duplicate template api [`#1432`](https://github.com/opengovsg/FormSG/pull/1432)
- refactor: migrate table validator to typescript [`#1316`](https://github.com/opengovsg/FormSG/pull/1316)

## Dependency upgrades
- chore(deps-dev): bump eslint from 7.22.0 to 7.23.0 [`#1473`](https://github.com/opengovsg/FormSG/pull/1473)
- chore(deps-dev): bump mockdate from 3.0.4 to 3.0.5 [`#1472`](https://github.com/opengovsg/FormSG/pull/1472)
- chore(deps-dev): bump @types/node from 14.14.35 to 14.14.37 [`#1471`](https://github.com/opengovsg/FormSG/pull/1471)
- chore(deps-dev): bump @types/jest from 26.0.21 to 26.0.22 [`#1470`](https://github.com/opengovsg/FormSG/pull/1470)
- fix(deps): bump aws-sdk from 2.871.0 to 2.874.0 [`#1468`](https://github.com/opengovsg/FormSG/pull/1468)
- chore(deps-dev): bump @babel/core from 7.13.10 to 7.13.13 [`#1467`](https://github.com/opengovsg/FormSG/pull/1467)
- fix(deps): bump twilio from 3.58.0 to 3.59.0 [`#1465`](https://github.com/opengovsg/FormSG/pull/1465)
- fix(deps): bump aws-sdk from 2.870.0 to 2.871.0 [`#1464`](https://github.com/opengovsg/FormSG/pull/1464)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#1448`](https://github.com/opengovsg/FormSG/pull/1448)
- chore(deps-dev): bump mockdate from 3.0.3 to 3.0.4 [`#1458`](https://github.com/opengovsg/FormSG/pull/1458)
- fix(deps): bump connect-mongo from 4.4.0 to 4.4.1 [`#1459`](https://github.com/opengovsg/FormSG/pull/1459)
- chore(deps-dev): bump testcafe from 1.12.0 to 1.13.0 [`#1460`](https://github.com/opengovsg/FormSG/pull/1460)
- chore(deps-dev): bump @babel/preset-env from 7.13.10 to 7.13.12 [`#1457`](https://github.com/opengovsg/FormSG/pull/1457)
- fix(deps): bump aws-sdk from 2.866.0 to 2.870.0 [`#1449`](https://github.com/opengovsg/FormSG/pull/1449)
- chore(deps-dev): bump husky from 5.1.3 to 5.2.0 [`#1447`](https://github.com/opengovsg/FormSG/pull/1447)
- chore(deps-dev): bump @typescript-eslint/parser from 4.18.0 to 4.19.0 [`#1433`](https://github.com/opengovsg/FormSG/pull/1433)
- fix(deps): bump @sentry/browser from 6.2.2 to 6.2.3 [`#1422`](https://github.com/opengovsg/FormSG/pull/1422)
- chore(deps-dev): bump sinon from 9.2.4 to 10.0.0 [`#1429`](https://github.com/opengovsg/FormSG/pull/1429)

### CODE REVIEW

**Comment by mantariksh** [comment]
## Tests
**CorpPass cloud**
- [ ] Create, activate and submit CorpPass form

**Comment by mantariksh** [comment]
## Tests
**Copy changes**
- [ ] Email confirmation tooltip in edit field modal shows "Customise an email acknowledgement to respondents"

**Comment by mantariksh** [comment]
## Tests
**Storage mode middleware refactors**
- [ ] Downloading CSV + attachments works as expected on Chrome

**Comment by mantariksh** [comment]
## Tests
**Table validator**
- [ ] Create two required table fields. Hide one of them behind logic. Check that normal submission using frontend succeeds for both visible and hidden field.
- [ ] Check that following validation works when submitting programatically
- Answer cannot be empty for required column
- For dropdown column, invalid answer (e.g. 'abc') is rejected
- Answer cannot have more than max rows if addMoreRows is true
- Answer cannot have fewer than min rows

**Comment by mantariksh** [comment]
## Tests
**Intranet IE11 runthrough**
- [ ] Create email mode form with all fields and custom start/end page. Activate and submit form. Check that you can receive responses in your intranet inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields and custom start/end page. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments for individual fields can be downloaded from Data tab in storage mode.
- [ ] Attachment ZIP for submission can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Review by karrui — APPROVED** [review]

**Pull request merged**
