### PR TITLE
build: release v6.64.0

### PR DESCRIPTION
**Pull request by tshuli**
## New

- build: merge v6.63.0 into develop  [`#6508`](https://github.com/opengovsg/FormSG/pull/6508)
- feat: payment variable [`#6463`](https://github.com/opengovsg/FormSG/pull/6463)
- fix: separated captcha and turnstile error tracking [`#6494`](https://github.com/opengovsg/FormSG/pull/6494)
- build: release v6.63.0 [`#6493`](https://github.com/opengovsg/FormSG/pull/6493)

## Dependencies

- fix(deps): bump libphonenumber-js from 1.10.36 to 1.10.37 in /shared [`#6496`](https://github.com/opengovsg/FormSG/pull/6496)

## Dev-Dependencies

- chore(deps-dev): bump @typescript-eslint/parser from 5.60.1 to 5.61.0 in /shared [`#6506`](https://github.com/opengovsg/FormSG/pull/6506)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.60.1 to 5.61.0 in /shared [`#6505`](https://github.com/opengovsg/FormSG/pull/6505)

### feat: payment variable [`#6463`](https://github.com/opengovsg/FormSG/pull/6463)

**Regression Flow for original payments**
@justynoh 
Responders able to make payment, admin response still functions
- [x] As a responder
  - [x] using an old / existing payment form
  - [x] able to successfully make payment on form
- [x] As an admin
  - [x] able to see submission response on admin response result page

Admin able to save on old forms
@mayying 
- [x] As an admin
  - [x] login using an old / existing payment form as an admin
  - [x] able to successfully add/edit/remove non-payment fields
  - [x] able to successfully edit/remove payment fields
- [x] As a responder
  - [x] able to successfully make payment on form
- [x] As an admin
  - [x] able to see submission response on admin response result page

**New feature flow**
@foochifa 
Fixed Payments
- [x] create a fixed payment form
- [x] able to successfully make payment on form
- [x] able to see submission response on admin response result page

Variable Payments
@KenLSM 
- [x] As an admin
  - [x] create a variable payment form
  - [x] set a min and max value
- [x] As a responder
  - [x] able to successfully make payment on form
- [x] As an admin
  - [x] able to see submission response on admin response result page
  - [x] result should reflect the dynamic amount paid

Switching Payment Types
@tshuli 
- [x] As an admin
  - [x] create a variable payment form
  - [x] set a min and max value, description, name, and save the form
  - [x] refresh the page, and switch payment type to Fixed
  - [x] observe that amount field is reset, and description, name are still set.
  - [x] able to save form
  - [x] refresh the page, and switch payment type to Variable
  - [x] observe that min and max value fields are reset, and description, name are still set.
  - [x] able to save form
 

#### Deploy Notes

Backwards compatibility is supported, but we should proactively run the DB migration to update the entries on DB.
Script to run `scripts/202306xx_populate_paymenttype_default/add_fixed_payment_type_default.js`

### CODE REVIEW

**Comment by foochifa** [comment]
A lil note for the db script following the discussion in #6463, we might just want to run it after hours. Due to potential load from multiple collection scans.

**Comment by foochifa** [comment]
A separate note but the invoice date is in GMT, is this only for test mode? 

image

**Comment by mayying** [comment]
1. Tested on staging.form.gov.sg, get the following error while updating payments:
image
It seems to happen on just this form: https://staging.form.gov.sg/admin/form/647d7c4b640b5b00122b7a88. It works with another form: https://staging.form.gov.sg/admin/form/6412ccd0ebce100012b8dc37 

1. Also tested with a variable payment, setting 1 as min and 2 as max, but the API query is calling with max amount =0, and min amount =100 
image
image

1. Also, when accessing the results page, it seems that the payment status and pending status is a button (clickable and has an editable icon), is that intentional?

https://github.com/opengovsg/FormSG/assets/10881671/75415c7a-3b99-4f87-93b1-6f26afef4c40


[](url)

**Comment by mayying** [comment]
Also, this prompt doesn't make sense. I think the minimum amount should be min(maxConfiguredAmount, maxInputAmount)
image

**Comment by tshuli** [comment]
Typo on variable payment error copy
Screenshot 2023-07-04 at 2 23 22 PM

**Comment by tshuli** [comment]
> Also, this prompt doesn't make sense. I think the minimum amount should be min(maxConfiguredAmount, maxInputAmount) image

I think this is meant to set limits on the values allowed in the payment amount limit (hence the error triggered)

How about copy like
'Minimum amount cannot be more than $1,000,000.00'
'Maximum amount cannot be more than $1,000,000.00' 
'Minimum amount cannot be more than maximum amount'

**Comment by mayying** [comment]
LGTM! Below listed the summary of discussions between @KenLSM and I:
1. Right now, FE is updating the whole payments object based on what is given when retrieving the form. Since the form is created when payment by product is deployed for testing, the DB entry for the form has some fields that are not ready for this production. Removal of the field manually on DB resolved the issues. There are concerns where we are updating fields that are not modified by users, specifically when it comes to multi read/write and conflict resolve. We can optionally look into forcing a fresh update on admin end when conflict is detected, if we want to, but it doesn't block the release.
1.  Unable to reproduce after some refreshes, will just let this slip for now.
1. https://linear.app/ogp/issue/FRM-1109/payment-status-badges-should-not-have-an-active-hover-on-admin-result created.
1. Typo and amount validation errors is brought into attention, I believe resolution will be on the way.

**Comment by KenLSM** [comment]
@tshuli for the copy, i'll create a ticket for it so that we can get some input from design as well (the current copy was deliberated with design).

**Comment by mayying** [comment]
image
It seems like 2 maximum amounts error prompt is shown

**Review by KenLSM — APPROVED** [review]

**Pull request merged**
