### PR TITLE
build: release v5.64.0

### PR DESCRIPTION
**Pull request by justynoh**
*New dependencies*

- chore(deps-dev): bump ts-node-dev from 1.1.8 to 2.0.0 [`#4123`](https://github.com/opengovsg/FormSG/pull/4123)
- chore(deps-dev): bump @types/validator from 13.7.3 to 13.7.4 [`#4126`](https://github.com/opengovsg/FormSG/pull/4126)
- chore(deps-dev): bump lint-staged from 13.0.1 to 13.0.3 [`#4127`](https://github.com/opengovsg/FormSG/pull/4127)
- chore(deps-dev): bump csv-parse from 5.0.4 to 5.2.2 [`#4122`](https://github.com/opengovsg/FormSG/pull/4122)
- chore(deps-dev): bump ts-essentials from 9.1.2 to 9.2.0 [`#4124`](https://github.com/opengovsg/FormSG/pull/4124)
- fix(deps): bump nodemailer from 6.7.5 to 6.7.7 [`#4113`](https://github.com/opengovsg/FormSG/pull/4113)
- fix(deps): bump @sentry/browser from 7.4.1 to 7.5.1 [`#4115`](https://github.com/opengovsg/FormSG/pull/4115)
- fix(deps): bump moment from 2.29.2 to 2.29.4 [`#4116`](https://github.com/opengovsg/FormSG/pull/4116)
- chore(deps-dev): bump maildev from 2.0.4 to 2.0.5 [`#4114`](https://github.com/opengovsg/FormSG/pull/4114)
- chore(deps-dev): bump concurrently from 7.1.0 to 7.2.2 [`#4100`](https://github.com/opengovsg/FormSG/pull/4100)
- chore(deps-dev): bump @types/node from 18.0.0 to 18.0.1 [`#4099`](https://github.com/opengovsg/FormSG/pull/4099)
- fix(deps): bump aws-sdk from 2.1136.0 to 2.1167.0 [`#4101`](https://github.com/opengovsg/FormSG/pull/4101)
- chore(deps-dev): bump @babel/preset-env from 7.17.12 to 7.18.6 [`#4086`](https://github.com/opengovsg/FormSG/pull/4086)
- fix(deps): bump openid-client from 5.1.7 to 5.1.8 [`#4088`](https://github.com/opengovsg/FormSG/pull/4088)
- fix(deps): bump type-fest from 2.15.1 to 2.16.0 in /shared [`#4091`](https://github.com/opengovsg/FormSG/pull/4091)
- fix(deps): bump twilio from 3.77.0 to 3.78.0 [`#4078`](https://github.com/opengovsg/FormSG/pull/4078)
- chore(deps-dev): bump @babel/core from 7.18.5 to 7.18.6 [`#4079`](https://github.com/opengovsg/FormSG/pull/4079)
- fix(deps): bump @sentry/browser from 7.2.0 to 7.4.1 [`#4080`](https://github.com/opengovsg/FormSG/pull/4080)

*Features*

- fix: bounce notification [`#4107`](https://github.com/opengovsg/FormSG/pull/4107)
- fix: update sgid client to v1.0.3 (again) [`#4090`](https://github.com/opengovsg/FormSG/pull/4090)
- feat: add backend validation for form feedback submission [`#3941`](https://github.com/opengovsg/FormSG/pull/3941)
- update: number of bcrypt salt rounds for otp and myinfo hashing [`#4075`](https://github.com/opengovsg/FormSG/pull/4075)

### CODE REVIEW

**Comment by justynoh** [comment]
## Tests

*fix: bounce notification* https://github.com/opengovsg/FormSG/pull/4107

@justynoh 

- [x] Create an email mode form. Add a valid collaborator with a registered contact number, and add a non-existent email as one of the email recipients. Submit the form. The form should NOT be deactivated, and the valid email recipient should not receive any emails/SMSes. Check the document in the Bounces collection corresponding to the form ID. The bounces array should contain the correct hasBounced key for each email address.
- [x] Remove all valid email recipients and leave only non-existent emails. Submit the form. The form should be deactivated, and the form admin + collaborators should each receive only ONE email and TWO smses, informing them of the bounce and form deactivation.

**Comment by justynoh** [comment]
*fix: update sgid client to v1.0.3 (again)* https://github.com/opengovsg/FormSG/pull/4090
@tshuli 

- [x] test sgid flow on staging

**Comment by justynoh** [comment]
*feat: add backend validation for form feedback submission* https://github.com/opengovsg/FormSG/pull/3941

@karrui

- [x] Test that submitting a feedback with `submissionId` for a form without a prior form submission with the same `submissionId` returns `404`
- [x] Test that submitting feedback twice for the same `submissionId` and `formId` returns `422`
- [x] Test that feedback using only endpoint of `/api/v3/forms/{formId}/feedback` still works
- [x] Test that old client works with new server both locally and on staging (load the submit feedback page on the old client, deploy the new version of the code, then submit feedback to see that feedback submission still works)

**Comment by justynoh** [comment]
*update: number of bcrypt salt rounds for otp and myinfo hashing* https://github.com/opengovsg/FormSG/pull/4075


@justynoh 
- [x] Test that we can request OTP and successfully verify the OTP on the new server
- [x] Test that we can request OTP on the old server, switch to the new server (with `salt rounds` reduced to 1), and verify the requested OTP on the new server

**Review by tshuli — APPROVED** [review]

**Pull request merged**
