### PR TITLE
feat: navigation prompt for unsaved logic

### PR DESCRIPTION
**Pull request by tohhengxing**
## Problem
extends navigation prompt from #4670 to logic builder. apologies for the slow progress I was unable to work on this as I fell sick and had exams :(

Closes [#4799 ]

## Solution
reused dirty store for logic form.

**Breaking Changes** 

- [ ] Yes - this PR contains breaking changes
    - Details ...
- [x] No - this PR is backwards compatible  

## Before & After Screenshots

**AFTER**:
<details>

https://user-images.githubusercontent.com/102740235/198898034-c8bf090b-cda7-4988-bb14-da421a3123ae.mp4

</details>

## Found potential bug ##

Unfortunately, seems like there's an unintended bug that was already present before I started working on this. 

It relates to the edit thank you page feature. I don't think the navigation prompt is supposed to trigger the moment you try to leave the edit thank you page feature.

It doesn't seem to be part of the flow mentioned in #4670 so I am raising this to whoever has more knowledge on the actual intended outcome. 

This issue is not present in the issues page.

<details>

https://user-images.githubusercontent.com/102740235/198898101-5d67288c-ae1b-49bf-a561-7eb6e84209dc.mp4

</details>

### CODE REVIEW

**Comment by justynoh** [comment]
hi @tohhengxing , thanks for the contribution! the bug you pointed out is indeed a bug, it was identified and fixed in #5235. if you merge or rebase you should get the latest changes from develop now. 😄

**Comment by justynoh** [comment]
hi @tohhengxing ! just took a look at your PR, but the behavior needs to change a little. if the user did not change anything in the logic block, the modal should not show up. (You can take a look at the behavior of add/edit form fields in the builder to see what the flow should be like)

You might have to make some changes to access the `formMethods.isDirty` prop from `useEditLogicBlock` to get this to work. Feel free to reach out again if you need clarification!

**Comment by tohhengxing** [comment]
> hi @tohhengxing ! just took a look at your PR, but the behavior needs to change a little. if the user did not change anything in the logic block, the modal should not show up. (You can take a look at the behavior of add/edit form fields in the builder to see what the flow should be like)
> 
> You might have to make some changes to access the `formMethods.isDirty` prop from `useEditLogicBlock` to get this to work. Feel free to reach out again if you need clarification!

Hi @justynoh . Thanks for the clarifications. I will be working towards the requested requirements. However, I might need some help. Unfortunately, I am no longer able to run the backend server anymore for some reason. 

I am able to run `npm install` and `npm run dev`. Although all containers built successfully, the backend server raises an error ` Error: ENOENT: no such file or directory, open '/opt/formsg/dist/frontend/index.html' ` and then terminates in a SIGTERM.

[error 2.txt](https://github.com/opengovsg/FormSG/files/9997414/error.2.txt)

I spent a few hours narrowing down the specific commit which caused the issue. 
https://github.com/opengovsg/FormSG/commit/7b03ed80519a92e967e52c9c5e0274ed45a36470

And this seems to be the change causing the issue
https://github.com/opengovsg/FormSG/commit/7b03ed80519a92e967e52c9c5e0274ed45a36470#diff-ee507496faf3fb23b7c9dbd501d04ad86ac84858c0991db1d09a5955dbf6c4dc

In particular, this exact line
`const reactHtml = readFileSync(path.join(reactFrontendPath, 'index.html'), {
  encoding: 'utf8',
})`

I started from commit f87e0cc and basically did binary search between that commit and the latest commit 0b1cc67. The commits after the culprit commit were throwing different errors than the one I listed above.


The steps I took when testing each commit was to remove node_modules, clear the npm cache and follow the steps outlined in the README for a fresh installation. In addition, I already tried restarting docker desktop, my PC, WSL, deleting and re-cloning the repo, uninstalling node, npm, nvm and reinstalling. Nothing seems to work.

I am currently using nvm version 0.39.2, npm version 6.14.13, node version 14.17.3 and i am running wsl2, ubuntu 20.04.5 LTS

Would like any guidance or any pointers if possible to try to resolve this issue. Thank you!

**Comment by justynoh** [comment]
Hey @tohhengxing! We upgraded to node 18 recently, you'll probably have to upgrade your node version as well. You might also need to add some flags at your install step and build step (see #5344 for more details). we're working on fixing these flags away (#5361, #5362). let us know if you still can't run and we can see if we can repro!

**Comment by tohhengxing** [comment]
> Hey @tohhengxing! We upgraded to node 18 recently, you'll probably have to upgrade your node version as well. You might also need to add some flags at your install step and build step (see #5344 for more details). we're working on fixing these flags away (#5361, #5362). let us know if you still can't run and we can see if we can repro!

thanks for taking time to give me pointers. I will experiment tomorrow and report back. Thank you very much!

**Comment by wanlingt** [comment]
> 

Hi @tohhengxing ! you might need to run `npm run build:frontend` as well before `npm run dev` to get it working

**Comment by tohhengxing** [comment]
> npm run build:frontend

@wanlingt wow...thanks it finally works...can i ask why this command wasn't needed previously? The error messages i encountered make more sense now

**Comment by foochifa** [comment]
Hi @tohhengxing! Will be closing this draft PR for now. If you would still like to work on issue #4799 please do update it and re-open a new PR as needed thank you!

**Pull request closed without merging**
