### PR TITLE
feat(twilio): remove twilio from fe

### PR DESCRIPTION
**Pull request by KenLSM**
## Problem

Twilio is no longer used as we've switched completely over to utilise Postman APIs. This PR removes the frontend components on the repo. 

We have had the Twilio deprecation banner up since July and it is time to decommission the settings page to reduce visual clutter for the admins.

The removal from the backend is in #7870.

Closes FRM-1745

## Solution

Remove the frontend visual components as we no longer require it.

**Breaking Changes** 

- No - this PR is backwards compatible  

## Before & After Screenshots
| Component | Before | After |
|--------|--------|--------|
| `<SettingsPage />` | image | image | 

## Tests

**Regression**
##### Admins can create and save forms
- [ ] Create an email mode form
- [ ] Add mobile number field with OTP verification
- [ ] Ensure that field can be saved

##### Respondents can submit forms
- [ ] Ensure that the form created above can be visited
- [ ] Ensure that mobile number verification works
- [ ] Ensure that form can be submitted

### CODE REVIEW

**Comment by kevin9foong** [comment]
Hi @KenLSM, just in case, there still seems to be

```
freeSmsCount: (id: string) =>
    [...adminFormKeys.id(id), 'freeSmsCount'] as const,
 ```
 in `frontend/src/features/admin-form/common/queries.ts` 
 
Should this also be removed?

**Review by kevin9foong — COMMENTED** [review]
Apart from the above comment, lgtm!

**Comment by KenLSM** [comment]
> Hi @KenLSM, just in case, there still seems to be
> 
> ```
> freeSmsCount: (id: string) =>
>     [...adminFormKeys.id(id), 'freeSmsCount'] as const,
> ```
> 
> in `frontend/src/features/admin-form/common/queries.ts`
> 
> Should this also be removed?

Good catch. Removed in e56425e03b5c76a95252d972b79fdbc32842da55

**Comment by kevin9foong** [comment]
lgtm!

**Review by kevin9foong — APPROVED** [review]

**Pull request merged**
