### PR TITLE
fix: add frontend logging for network error

### PR DESCRIPTION
**Pull request by justynoh**
## Problem
We have unknown Network Errors... this PR implements console logging so we can see some data from DD :)

## Solution

**Breaking Changes** 
- No - this PR is backwards compatible

### CODE REVIEW

**Review by timotheeg — APPROVED** [review]

**Comment by justynoh** [comment]
force push to rebase onto develop

**Comment by timotheeg** [comment]
Just asking, is there anything we can log about the rest of the app or the environment that could further help in troubleshooting?

**Comment by justynoh** [comment]
Are you thinking of anything specific? I'm not really sure what else we can log because in the body of the function, we log the entire error `e` already ahah

**Review by timotheeg — APPROVED** [review]
LGTM

**Pull request merged**
