### PR TITLE
build: release 4.49.0

### PR DESCRIPTION
**Pull request by mantariksh**
## Improved
- chore: enhance jest   test reliability [`#800`](https://github.com/opengovsg/FormSG/pull/800)
- chore: improve default submission error   message [`#796`](https://github.com/opengovsg/FormSG/pull/796)
- chore: log errors from concatResponse   [`#817`](https://github.com/opengovsg/FormSG/pull/817)
- docs: remove dangling commas from mongo   scripts [`#794`](https://github.com/opengovsg/FormSG/pull/794)
- feat: add ie11 specific styling for new   template forms [`#834`](https://github.com/opengovsg/FormSG/pull/834)
- feat: improve email mode messaging   [`#825`](https://github.com/opengovsg/FormSG/pull/825)
- feat: misc UX fixes   [`#833`](https://github.com/opengovsg/FormSG/pull/833)
- feat: tighten submission validation   [`#751`](https://github.com/opengovsg/FormSG/pull/751)
- fix: Travis Jest test not downloading   mongo binary fast enough   [`#826`](https://github.com/opengovsg/FormSG/pull/826)
- ref: migrate copy template form flow to   TypeScript    [`#793`](https://github.com/opengovsg/FormSG/pull/793)
- ref: migrate create new form api flow   to TypeScript [`#806`](https://github.com/opengovsg/FormSG/pull/806)
- ref: migrate DELETE /{formId}/adminform   endpoint flow to TypeScript   [`#753`](https://github.com/opengovsg/FormSG/pull/753)
- ref: migrate duplicate admin form   endpoint to TypeScript [`#789`](https://github.com/opengovsg/FormSG/pull/789)
- ref: migrate endpoint for getting admin   form to TypeScript    [`#807`](https://github.com/opengovsg/FormSG/pull/807)
- ref: migrate GET adminform/template   endpoint to TypeScript [`#823`](https://github.com/opengovsg/FormSG/pull/823)
- ref: migrate transfer ownership flow to   TypeScript [`#718`](https://github.com/opengovsg/FormSG/pull/718)
- refactor: convert Captcha to service   [`#827`](https://github.com/opengovsg/FormSG/pull/827)
- refactor: migrate date validator to ts   [`#749`](https://github.com/opengovsg/FormSG/pull/749)
- refactor: migrate decimal validator to   ts [`#750`](https://github.com/opengovsg/FormSG/pull/750)
- refactor: migrate   prepareEmailSubmission to TypeScript   [`#752`](https://github.com/opengovsg/FormSG/pull/752)
- refactor: migrate validate- and   receiveEmailSubmission to TypeScript   [`#755`](https://github.com/opengovsg/FormSG/pull/755)
- refactor/core: migrate & rename   core controller to HomeController in TypeScript   [`#788`](https://github.com/opengovsg/FormSG/pull/788)
- test: raise global statement threshold   [`#795`](https://github.com/opengovsg/FormSG/pull/795)

## Bug fixes
- fix: tear out response hash [`#837`](https://github.com/opengovsg/FormSG/pull/837)
- fix: wrap initDate in a new Date object to avoid reference to minDate [`#816`](https://github.com/opengovsg/FormSG/pull/816)
- fix: close create form modal when create form fails [`#824`](https://github.com/opengovsg/FormSG/pull/824)

## Dependency upgrades
- chore(deps-dev):   bump @opengovsg/mockpass from 2.5.6 to 2.6.0   [`#821`](https://github.com/opengovsg/FormSG/pull/821)
- chore(deps-dev): bump   @types/express-serve-static-core   [`#801`](https://github.com/opengovsg/FormSG/pull/801)
- chore(deps-dev): bump @types/helmet   from 0.0.48 to 4.0.0 [`#697`](https://github.com/opengovsg/FormSG/pull/697)
- chore(deps-dev): bump @types/jest from   26.0.15 to 26.0.16 [`#812`](https://github.com/opengovsg/FormSG/pull/812)
- chore(deps-dev): bump @types/node from   14.14.10 to 14.14.11 [`#829`](https://github.com/opengovsg/FormSG/pull/829)
- chore(deps-dev): bump @types/node from   14.14.7 to 14.14.10 [`#813`](https://github.com/opengovsg/FormSG/pull/813)
- chore(deps-dev): bump   @typescript-eslint/parser from 4.7.0 to 4.9.0   [`#803`](https://github.com/opengovsg/FormSG/pull/803)
- chore(deps-dev): bump csv-parse from   4.12.0 to 4.14.1 [`#745`](https://github.com/opengovsg/FormSG/pull/745)
- chore(deps-dev): bump   eslint-config-prettier from 6.15.0 to 7.0.0   [`#810`](https://github.com/opengovsg/FormSG/pull/810)
- chore(deps-dev): bump   eslint-plugin-simple-import-sort   [`#820`](https://github.com/opengovsg/FormSG/pull/820)
- chore(deps-dev): bump husky from 4.3.0   to 4.3.5 [`#819`](https://github.com/opengovsg/FormSG/pull/819)
- chore(deps-dev): bump prettier from   2.2.0 to 2.2.1 [`#785`](https://github.com/opengovsg/FormSG/pull/785)
- chore(deps-dev): bump type-fest from   0.18.0 to 0.20.2 [`#782`](https://github.com/opengovsg/FormSG/pull/782)
- fix(deps): bump @sentry/browser from   5.27.3 to 5.28.0 [`#774`](https://github.com/opengovsg/FormSG/pull/774)
- fix(deps): bump @sentry/browser from   5.28.0 to 5.29.0 [`#831`](https://github.com/opengovsg/FormSG/pull/831)
- fix(deps): bump aws-sdk from 2.783.0 to   2.802.0 [`#783`](https://github.com/opengovsg/FormSG/pull/783)
- fix(deps): bump aws-sdk from 2.802.0 to   2.805.0 [`#818`](https://github.com/opengovsg/FormSG/pull/818)
- fix(deps): bump file-saver from 2.0.2   to 2.0.5 [`#784`](https://github.com/opengovsg/FormSG/pull/784)
- fix(deps): bump libphonenumber-js from   1.7.55 to 1.9.5 [`#798`](https://github.com/opengovsg/FormSG/pull/798)
- fix(deps): bump libphonenumber-js from   1.9.5 to 1.9.6 [`#832`](https://github.com/opengovsg/FormSG/pull/832)
- fix(deps): bump neverthrow from 2.7.1   to 3.0.0 [`#797`](https://github.com/opengovsg/FormSG/pull/797)
- fix(deps): bump validator from 13.1.17   to 13.5.1 [`#811`](https://github.com/opengovsg/FormSG/pull/811)
- fix(deps): bump whatwg-fetch from 3.4.1   to 3.5.0 [`#804`](https://github.com/opengovsg/FormSG/pull/804)

### CODE REVIEW

**Comment by mantariksh** [comment]
## Tests
**IE11 intranet tests for this week**
- [ ] COVID-19 templates in create form modal are aligned in wide layout (when all templates are in a row) and narrow layout (when templates are in 2 rows)


**IE11 intranet general run-through
- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your GSIB inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.
- [ ] Create form with MyInfo fields. Submit successfully

**Comment by mantariksh** [comment]
## Tests

**Captcha**
- [ ] Submit a form with captcha
- [ ] Submit a form without captcha
- [ ] Submit a form on staging-alt

**Comment by mantariksh** [comment]
## Tests
@karrui 
**Admin form**
https://github.com/opengovsg/FormSG/pull/823
https://github.com/opengovsg/FormSG/pull/718
https://github.com/opengovsg/FormSG/pull/806
https://github.com/opengovsg/FormSG/pull/793
https://github.com/opengovsg/FormSG/pull/807
https://github.com/opengovsg/FormSG/pull/753

**Comment by mantariksh** [comment]
## Tests
**Email submissions**
- [ ] Submit an email mode form with an email field with autoreply, as well as multiple attachments with the same filename. Check that the attachment filenames are de-duplicated in both the admin response and the email confirmation.

**Comment by mantariksh** [comment]
## Tests
**Field validators**
- [ ] Create two decimal fields. Hide one of them behind logic.
- [ ] Check that validation on both visible and hidden decimal fields work when submitting programatically
- Decimal input is rejected if it is not within the validation range
- Decimal input is rejected if it has leading zeroes
- [ ] Create two date fields. Hide one of them behind logic.
- [ ] Check that validation on both visible and hidden date fields work when submitting programatically
 - Date input is rejected if it is not in the format 'DD MMM YYYY'
 - Date input is rejected if it is not within the validation range (isFutureOnly, isPastOnly, Custom Min / Max)

**Comment by mantariksh** [comment]
## Tests
**Form duplication**
### Storage mode duplication
- [ ] Duplicate **your own** storage mode form to email mode should succeed with all fields and logic retained. The new form 
admin should be you.
- [ ] Duplicate **your own** storage mode form to storage mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a storage mode form that **you are editor of** to email mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a storage mode form that **you are editor of** to storage mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a storage mode form that **you are viewer of** to email mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a storage mode form that **you are viewer of** to storage mode should succeed with all fields and logic retained. The new form admin should be you.
### Email mode duplication
- [ ] Duplicate **your own** email mode form to email mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate **your own** email mode form to storage mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a email mode form that **you are editor of** to email mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a email mode form that **you are editor of** to storage mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a email mode form that **you are viewer of** to email mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a email mode form that **you are viewer of** to storage mode should succeed with all fields and logic retained. The new form admin should be you.

**Comment by karrui** [comment]
## Tests
### GET adminform/template endpoint
- [ ] Go to examples tab and click on the example forms at random. The form should load and the logo should be of the agency opened.

**Comment by mantariksh** [comment]
## Tests
**Date field bug**
- [ ] Create date field. Set custom date range with minimum date in the distant past (e.g. 2015). Open the form in public view. Check that the datepicker opens to the month of the minimum date by default. 
- [ ] Select a date on the date picker 1 year in the future. Check that there is no change to the minimum date.
- [ ] Repeat the above with disallow past dates.
- [ ] Create date field with no date validation. Open in public view. Check that the datepicker opens to the current month by default.

**Comment by karrui** [comment]
## Tests
### Create new form
- [ ] Create new email form. Should be created successfully.
- [ ] Create new email mode template form. Should be created successfully.
- [ ] Create new email form with different email list input. Should be created successfully
- [ ] Create new storage mode form. Should be created successfully.
- [ ] Create new storage mode template form. Should be created successfully.

**Comment by karrui** [comment]
## Tests
### Storage mode duplication
- [ ] Duplicate **your own** storage mode form to email mode should succeed with all fields and logic retained. The new form 
admin should be you.
- [ ] Duplicate **your own** storage mode form to storage mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a storage mode form that **you are editor of** to email mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a storage mode form that **you are editor of** to storage mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a storage mode form that **you are viewer of** to email mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a storage mode form that **you are viewer of** to storage mode should succeed with all fields and logic retained. The new form admin should be you.
### Email mode duplication
- [ ] Duplicate **your own** email mode form to email mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate **your own** email mode form to storage mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a email mode form that **you are editor of** to email mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a email mode form that **you are editor of** to storage mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a email mode form that **you are viewer of** to email mode should succeed with all fields and logic retained. The new form admin should be you.
- [ ] Duplicate a email mode form that **you are viewer of** to storage mode should succeed with all fields and logic retained. The new form admin should be you.

**Comment by karrui** [comment]
## Tests
### Delete admin form
- [ ] Should be able to delete form successfully if you are admin.
- [ ] Programatically attempt to delete form that you do not have permissions to. Should be rejected by calling `DELETE /{formId}/adminform`

**Comment by mantariksh** [comment]
@karrui 
## Tests
**Tighten submission validation**
- [ ] Submit an email mode form with all form fields in preview mode.
- [ ] Submit a storage mode form with all form fields in preview mode.
- [ ] Create a Singpass email mode form with an autoreply email field. Submit the form and check that the NRIC is rendered correctly in both the admin response email and the autoreply email.
- [ ] Create a Corppass email mode form with an autoreply email field. Submit the form and check that the UEN and UID are rendered correctly in both the admin response email and the autoreply email.
- [ ] Create a Singpass storage mode form. Submit the form and check that the NRIC is rendered correctly in the data tab and the exported CSV. Add a form field and submit the form again. Check that the exported CSV has all the NRICs in the same column.
- [ ] Programmatically submit a table field with no `answerArray`, but with `answer` as an empty string. Check that you get a 400 and not a 500 response.
- [ ] Programmatically submit a table field with no `answerArray`, but with `answer` as a non-empty string. Check that you get a 400 and not a 500 response.
- [ ] Programmatically submit a short text field with no `answer`, but with `answerArray` as an empty array. Check that you get a 400 and not a 500 response.
- [ ] Programmatically submit a short text field with no `answer`, but with `answerArray` as a non-empty array. Check that you get a 400 and not a 500 response.

**Review by karrui — APPROVED** [review]

**Pull request merged**
