### PR TITLE
fix(settings): reorder and reword auth options

### PR DESCRIPTION
**Pull request by LoneRifle**
## Context

Reword and reorder the form auth options as indicated below:

*Desktop*
image

*Mobile*
image

### CODE REVIEW

**Comment by mantariksh** [comment]
@LoneRifle could you post a screenshot of the mobile view too pls?

**Comment by LoneRifle** [comment]
> @LoneRifle could you post a screenshot of the mobile view too pls?

done

**Comment by LoneRifle** [comment]
Note that the screenshots were taken when Singpass was incorrectly put after sgID. This has been corrected in the codebase

**Review by mantariksh — COMMENTED** [review]
padding btw the tooltip and "Contact us" seems a bit small, is it possible to increase that without breaking mobile view?

**Comment by LoneRifle** [comment]
> padding btw the tooltip and "Contact us" seems a bit small, is it possible to increase that without breaking mobile view?

I don't see a CSS class that I can latch onto, to introduce padding between the two elements. Given that they are related, and that we will not have this permanently, I'm inclined to leave it for now.

**Comment by mantariksh** [comment]
from @pearlyong:
>could you help add an underline to the link, and give it 15px left padding please? it looks a bit tight now, and not obvious it’s a link

**Comment by LoneRifle** [comment]
> could you help add an underline to the link, and give it 15px left padding please? it looks a bit tight now, and not obvious it’s a link

Done

**Comment by mantariksh** [comment]
spacing is a bit weird on mobile but I don't think it's critical plus We Are Moving To React <sup>TM</sup>

Screenshot 2021-07-06 at 3 46 37 PM

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
