### PR TITLE
build: release v6.78.0

### PR DESCRIPTION
**Pull request by foochifa**
## New

- fix(payments): payments response page frontend ui issues [`#6730`](https://github.com/opengovsg/FormSG/pull/6730)
- fix: add check for childname when populating field value [`#6715`](https://github.com/opengovsg/FormSG/pull/6715)
- fix: remove focus from myinfo child field when form is opened [`#6729`](https://github.com/opengovsg/FormSG/pull/6729)
- fix: gogov error handling [`#6714`](https://github.com/opengovsg/FormSG/pull/6714)
- feat: BE endpoint to retrieve presigned URLs [`#6685`](https://github.com/opengovsg/FormSG/pull/6685)
- fix: inconsistent modal close buttons [`#6713`](https://github.com/opengovsg/FormSG/pull/6713)
- fix: admin payment builder design [`#6699`](https://github.com/opengovsg/FormSG/pull/6699)
- feat: improve payment confirmation mailers [`#6704`](https://github.com/opengovsg/FormSG/pull/6704)
- fix: mobile view of unsaved modal [`#6712`](https://github.com/opengovsg/FormSG/pull/6712)
- feat: add logging to check for missing Myinfo field values [`#6694`](https://github.com/opengovsg/FormSG/pull/6694)
- build: merge v6.77.0 into develop [`#6711`](https://github.com/opengovsg/FormSG/pull/6711)
- build: release v6.77.0 [`#6710`](https://github.com/opengovsg/FormSG/pull/6710)

### fix(payments): payments response page frontend ui issues [`#6730`](https://github.com/opengovsg/FormSG/pull/6730)
@wanlingt 

**Regression**
Admin CSV Header change
- [x] Ensure that download csv of a payment form should still have proof of payment populated in the results
- [x] Ensure that header should now be label `proof of payment` instead of `invoice`

**New features**
Admin Response Table (with Payments)
- [x] Find a form with multiple completed payments
- [x] Ensure that `#` column can sufficiently render at least 4 digits without spilling to the next line. (edit HTML text to simulate a large number)
- [x] Ensure that the table scrolls when the screen width is smaller than ~600px
- [x] ensure payout date does not wrap (edit html: Tue, 19 Sep 2023)

Admin Response Table (without Payments)
- [x] Find a form without payments
- [x] Ensure that `#` column can sufficiently render at least 4 digits without spilling to the next line. (edit HTML text to simulate a large number)
- [x] Ensure that the table scrolls when the screen width is smaller than ~600px

### fix: add check for childname when populating field value [`#6715`](https://github.com/opengovsg/FormSG/pull/6715)

@LinHuiqing 
Regression test
- [x] On a MyInfo child form with the property `Birth Certification Number`, log in as a user with at least 1 child below the age of 21. 
- [x] Select that child, and submit the form.
- [x] The form should be submitted successfully
- [x] The form response should submit that single child

Unfortunately we're not able to test this on staging as the existing Mockpass profiles do not have children above 21yo. 
Hence, **please perform this test once it has been deployed to production**:
- [ ] On a MyInfo child form with the property `Birth Certification Number`, log in as a user with at least 1 child above the age of 21. 
- [ ] Click around the MyInfo child fields. Nothing should appear in the Birth Cert Number field.

### fix: remove focus from myinfo child field when form is opened [`#6729`](https://github.com/opengovsg/FormSG/pull/6729)
@LinHuiqing 

1. MyInfo child field - 1 child only
- [x] Open up a MyInfo child form with 1 child field
- [x] The focus should not be on the child field, unless the field is clicked
- [x] Select a child
- [x] Submit the form
- [x] Check that the email response contains the child's info

2. MyInfo child field - 2 children only (same test as above)
- [x] Open up a MyInfo child form with 2 children fields
- [x] The focus should not be on the child field, unless the field is clicked
- [x] Select a child
- [x] Submit the form
- [x] Check that the email response contains the children's info

3. MyInfo child field - 1 child only with option to add children
- [x] Enable the option "Allow respondent to add multiple children" on a MyInfo child form
- [x] Open up a MyInfo child form with 1 child field
- [x] The focus should not be on the child field, unless the field is clicked
- [x] Select a child
- [x] Add another child
- [ ] Select the 2nd child
- [ ] Submit the form
- [ ] Check that the email response contains the children's info

### fix: gogov error handling [`#6714`](https://github.com/opengovsg/FormSG/pull/6714)
@wanlingt 

- [x] Try to create a GoGov link with an existing short link
- [x] It should fail and return 400
- [x] FE modal should show short link is taken
- [x] Try to create a GoGov link with invalid characters like underscore or capital letters
- [x] It should fail and return 400
- [x] FE modal should show validation error
- [x] Go to Param store and delete GoGov API key
- [x] Try to create a GoGov link with a unique string
- [x] It should fail and return 500
- [x] FE modal should show an unexpected error
- [x] Restore the API key

Regression
- [x] Try to create a GoGov link with a unique string
- [x] The link should be successfully created

### feat: BE endpoint to retrieve presigned URLs [`#6685`](https://github.com/opengovsg/FormSG/pull/6685)

@KenLSM 

_Pssst... Required requests can be found in Insomnia > FormSG (Collection) > Form (Folder) > Virus Scanner (Folder)_

- [x] In `featureflags` collection in the DB, set `encryption-boundary-shift-virus-scanner` to `true`.

##### Make sure retrieving of presigned post data works as expected:

- [x] Send a `POST` request to `/api/v3/forms/<formId>/submissions/storage/get-s3-presigned-post-data` with the following payload:
  ```
  [ { "id": "<fieldId>", "size": <attachmentSize> }, ... ]
  ```
- [x] You should receive a response similar to this:
    ```
    [
	    {
		    "id": "<field_id>",
		    "presignedPostData": {
			    "url": "http://localhost:4566/local-virus-scanner-quarantine-bucket",
			    "fields": {
				    "key": "c837b040-06c2-40df-9b55-db82c84aa64d",
				    "bucket": "local-virus-scanner-quarantine-bucket",
				    "X-Amz-Algorithm": "AWS4-HMAC-SHA256",
				    "X-Amz-Credential": "fakeKey/20230904/ap-southeast-1/s3/aws4_request",
				    "X-Amz-Date": "20230904T052940Z",
				    "Policy": "eyJleHBpcmF0aW9uIjoiMjAyMy0wOS0wNFQwNTozMDo0MFoiLCJjb25kaXRpb25zIjpbWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwyMDAwMDAwXSx7ImtleSI6ImM4MzdiMDQwLTA2YzItNDBkZi05YjU1LWRiODJjODRhYTY0ZCJ9LHsiYnVja2V0IjoibG9jYWwtdmlydXMtc2Nhbm5lci1xdWFyYW50aW5lLWJ1Y2tldCJ9LHsiWC1BbXotQWxnb3JpdGhtIjoiQVdTNC1ITUFDLVNIQTI1NiJ9LHsiWC1BbXotQ3JlZGVudGlhbCI6ImZha2VLZXkvMjAyMzA5MDQvYXAtc291dGhlYXN0LTEvczMvYXdzNF9yZXF1ZXN0In0seyJYLUFtei1EYXRlIjoiMjAyMzA5MDRUMDUyOTQwWiJ9XX0=",
				    "X-Amz-Signature": "f24342cce26e50162083486f771b27271909f92898d64cbdd7ec680e5068683a"
			    }
		    }
	    }, ...
    ]
    ```
- [x] Send a `POST` request to `/api/v3/forms/<formId>/submissions/storage/get-s3-presigned-post-data` with at least 1 of the sizes >20000000. The joi validator should throw an error.
- [x] Send a `POST` request to `/api/v3/forms/<formId>/submissions/storage/get-s3-presigned-post-data` with none of the sizes >20000000, but total attachment size >20MB. A `400 BAD REQUEST` with message "Total file size exceeds 20MB" should be thrown.
- [x] Send a `POST` request to `/api/v3/forms/<formId>/submissions/storage/get-s3-presigned-post-data` with duplicate `id`s. A `400 BAD REQUEST` with message "Duplicate id(s) found" should be thrown.

##### Make sure attachments should be uploaded before expiry but blocked from uploading after expiry:

- [x] Send a valid `POST` request to `/api/v3/forms/<formId>/submissions/storage/get-s3-presigned-post-data` as described above.
- [x] Using the output from the request above, create a HTTP multipart form request: 
  - [x] Use `presignedPostData.url` as the request URL.
  - [x] Use the values in `presignedPostData.fields` as the key value pairs in the multipart form. Make sure that the pairs are _in order_.
- [x] If the request is made within _1 minute_ of the presigned post data generation (ie before expiry), the request should succeed with `204 No Content` and the file should be uploaded in the bucket with the key `presignedPostData.fields.key`.

    Screenshot 2023-09-13 at 10 25 02 AM

- [x] If the request is made more than _1 minute_ of the presigned post data generation (ie after expiry), the request should fail with `403 Forbidden` with the message saying the policy has expired.
    Screenshot 2023-09-13 at 12 13 47 PM

##### Make sure feature flagging works:

- [x] In `featureflags` collection in the DB, set `encryption-boundary-shift-virus-scanner` to `false` or unset it.
- [x] Send a `POST` request to `/api/v3/forms/<formId>/submissions/storage/get-s3-presigned-post-data` with a valid payload. `403 Forbidden` should be returned.

Note: Add file's MD5 hash and type to presigned url specifications when working on FE orchestration (FRM-1303). 

##### Regression tests:

- [x] Make sure refactored code works for previous flows with `createPresignedPost`:
  - [x] Login as an admin and go to the builder view a form.
  - [x] Add / update a custom logo. This should work as expected.
  - [x] Add / update an image. This should work as expected.

#### Deploy Notes

To enable endpoint: in the db `featureflags` collection, set `encryption-boundary-shift-virus-scanner` to `true`.

The following permissions have been added to the `formsg-[production|staging|uat]-s3-writeOnly` policies:
```json
{
    "Sid": "PutFileInQuarantine",
    "Effect": "Allow",
    "Action": [
        "s3:PutObject"
    ],
    "Resource": [
        "arn:aws:s3:::staging.virus.scanner.quarantine/*"
    ]
},
{
    "Sid": "GetFileFromClean",
    "Effect": "Allow",
    "Action": [
        "s3:GetObject"
    ],
    "Resource": [
        "arn:aws:s3:::staging.virus.scanner.clean/*"
    ]
}
```
This is to allow the following:
1. Putting files into the quarantine bucket.
2. Downloading clean files from the clean bucket.

### fix: inconsistent modal close buttons [`#6713`](https://github.com/opengovsg/FormSG/pull/6713)

@LinHuiqing 

For each below check that:
1. Modal close button has the correct styling, i.e. subtle color + 2rem sized 'X'
2. Modal close button successfully closes the modal

- [x] Payment by product item modal
- [x] Dirty (Unsaved changes) modal
- [x] Rollout announcement modal
- [x] Proceed to pay modal (desktop)
- [x] Duplicate payment modal (desktop)
- [x] Payment resume modal (desktop)
- [ ] Proceed to pay modal (mobile)
- [x] Duplicate payment modal (mobile)
- [x] Payment resume modal (mobile)

### fix: admin payment builder design [`#6699`](https://github.com/opengovsg/FormSG/pull/6699)

@LinHuiqing 
Regression
- [x] Create a payment field on a storage mode form
- [x] Select payment with products
- [x] Add new products without multi quantity
- [x] Add new products with multi quantity
- [x] Ensure the payment view looks the same as the screenshots/design figma in the linear ticket
- [x] Save field
- [x] Make a payment
- [x] Edit payment field to variable payment, ensure that the preview shows $0.5 instead of $0
- [x] Save variable payment with any amount
- [x] Make a payment

### feat: improve payment confirmation mailers [`#6704`](https://github.com/opengovsg/FormSG/pull/6704)

@LinHuiqing 
Products
- [x] Create a payment by products form
- [x] Submit the form and pay
- [x] Check your email
- [x] You should see the confirmation email design as stipulated in the linear issue
- [x] Check the information in the confirmation email is correct
- [x] Download the pdf from the email

Variable
- [x] Create a variable payment form
- [x] Submit and pay
- [x] Check your email
- [x] You should see the confirmation email design as stipulated in the linear issue
- [x] Check the information in the confirmation email is correct
- [x] Download the pdf from the email

### fix: mobile view of unsaved modal [`#6712`](https://github.com/opengovsg/FormSG/pull/6712)

@LinHuiqing 
On mobile mode
- [x] build a form
- [x] make some changes to a field
- [x] try to navigate away without saving or canceling
- [x] the modal should fill the entire window
- [x] return to edit and save
- [x] form field should be updated

On desktop mode (regression)
- [x] build a form
- [x] make some changes to a field
- [x] try to navigate away without saving or canceling
- [x] dirty modal should pop up
- [x] do not make the changes
- [x] form should be as before

### feat: add logging to check for missing Myinfo field values [`#6694`](https://github.com/opengovsg/FormSG/pull/6694)

@foochifa 
- [x] Missing Myinfo value is captured in logs. This has already been done on staging, can search for the message "Myinfo field value not found in existing list" on Cloudwatch, under `/aws/elasticbeanstalk/formsg-staging/var/log/eb-docker/containers/eb-current-app/stdouterr.log`

Steps that were taken:
- Delete constants from the current myinfo constants files (`NATIONALITIES`, `OCCUPATIONS`, `RACES`, `HOUSING_TYPES`, `HDB_TYPES`)
- Fill in a form with a profile that has the values of the deleted constants in the previous step
- The myinfo fields should show up as blank, and you should see a "Myinfo field value not found in existing list" message for each missing value in Cloudwatch

Regression test
- [x] Create a Myinfo form with the fields: Race, Nationality, Occupation, Dialect, Birth country, Housing type, HDB type
- [x] Fill in the form, submit
- [x] You should be able to submit the form successfully. The fields should be reflected in the email response

### CODE REVIEW

**Comment by LinHuiqing** [comment]
[Non-blocking] For fix: remove focus from myinfo child field when form is opened https://github.com/opengovsg/FormSG/pull/6729, mockpass doesn't have profiles with multiple children so I can't complete the last test. The current tests should be sufficient though, because the fix was just the auto-focus on the child field.

**Comment by foochifa** [comment]
For anyone testing #6704, gmail will strip the custom font away, from inter to your browser's default sans-serif font 🥲

**Comment by LinHuiqing** [comment]
For fix: inconsistent modal close buttons https://github.com/opengovsg/FormSG/pull/6713, as mentioned to @foochifa, there's a regression for the x:
image

**Comment by LinHuiqing** [comment]
As @KenLSM pointed out while testing, the create presigned url endpoint accepts negative sizes, which should not be the case. We should stop this at the joi level. Ticket here: FRM-1417.

**Review by LinHuiqing — APPROVED** [review]
Tests are all done! 👍

**Pull request merged**
