### PR TITLE
feat: use auth middleware to protect routes

### PR DESCRIPTION
**Pull request by karrui**
## Problem

Instead of inlining authentication checks, protect on the route level instead. 

This allows controller tests to not need to test for 401s, as those should be handled by integration tests.

### CODE REVIEW

**Comment by karrui** [comment]
Not ready, forgot to add middleware tests

**Review by tshuli — APPROVED** [review]
lgtm!

**Review by mantariksh — APPROVED** [review]
could you explain why you named the function `withUserAuthentication` instead of using a verb such as the original `authenticateUser`?

**Comment by karrui** [comment]
> could you explain why you named the function `withUserAuthentication` instead of using a verb such as the original `authenticateUser`?

Trying to make middlewares functions more obvious

**Comment by mantariksh** [comment]
as in, obvious that it's a middleware function rather than a controller function? is it a convention Express middleware functions start with `with`?

**Comment by karrui** [comment]
> as in, obvious that it's a middleware function rather than a controller function? is it a convention Express middleware functions start with `with`?

There's no real express naming conventions for middlewares, no. I stole it from React-style hook utilities lol

**Pull request merged**
