### PR TITLE
build: Release v5.10.0

### PR DESCRIPTION
**Pull request by karrui**
### Features
- feat: add  \<sg-govt-banner-component\> to top of public forms   [`#1439`](https://github.com/opengovsg/FormSG/pull/1439)
- feat: move server.ts into src/app   [`#1785`](https://github.com/opengovsg/FormSG/pull/1785)
- feat(admin-form): individual form field   api    [`#1799`](https://github.com/opengovsg/FormSG/pull/1799)
- feat(api-refactor): add specific update   end page endpoint in server   [`#1760`](https://github.com/opengovsg/FormSG/pull/1760)
- feat(email-submission): separate error   logging for db and state checks   [`#1813`](https://github.com/opengovsg/FormSG/pull/1813)
- feat: extract update logic endpoint   [`#1695`](https://github.com/opengovsg/FormSG/pull/1695)
- feat(adminform): update form collab endpoint  [`#1744`](https://github.com/opengovsg/FormSG/pull/1744)

### Fixes 
- fix: align joi validation types to   schema [`#1800`](https://github.com/opengovsg/FormSG/pull/1800)
- fix: remove Learn More link for MyInfo   field limit [`#1802`](https://github.com/opengovsg/FormSG/pull/1802)
- fix: speed up precommit hooks   [`#1820`](https://github.com/opengovsg/FormSG/pull/1820)

### Misc
- chore: gitignore   intellij files [`#1798`](https://github.com/opengovsg/FormSG/pull/1798)

### Dependencies updates
- fix(deps): bump @sentry/browser from   6.3.5 to 6.3.6 [`#1851`](https://github.com/opengovsg/FormSG/pull/1851)
- fix(deps): bump   abortcontroller-polyfill from 1.7.1 to 1.7.3   [`#1823`](https://github.com/opengovsg/FormSG/pull/1823)
- fix(deps): bump aws-sdk from 2.897.0 to   2.899.0 [`#1793`](https://github.com/opengovsg/FormSG/pull/1793)
- fix(deps): bump aws-sdk from 2.899.0 to   2.900.0 [`#1809`](https://github.com/opengovsg/FormSG/pull/1809)
- fix(deps): bump aws-sdk from 2.900.0 to   2.901.0 [`#1816`](https://github.com/opengovsg/FormSG/pull/1816)
- fix(deps): bump aws-sdk from 2.901.0 to   2.903.0 [`#1826`](https://github.com/opengovsg/FormSG/pull/1826)
- fix(deps): bump convict from 6.0.1 to   6.1.0 [`#1792`](https://github.com/opengovsg/FormSG/pull/1792)
- fix(deps): bump libphonenumber-js from   1.9.16 to 1.9.17 [`#1791`](https://github.com/opengovsg/FormSG/pull/1791)
- fix(deps): bump twilio from 3.61.0 to   3.62.0 [`#1818`](https://github.com/opengovsg/FormSG/pull/1818)

#### Devdeps
- chore(deps-dev): bump @babel/preset-env   from 7.14.0 to 7.14.1   [`#1795`](https://github.com/opengovsg/FormSG/pull/1795)
- chore(deps-dev): bump @types/bcrypt   from 3.0.1 to 5.0.0 [`#1830`](https://github.com/opengovsg/FormSG/pull/1830)
- chore(deps-dev): bump @types/bluebird   from 3.5.33 to 3.5.34   [`#1807`](https://github.com/opengovsg/FormSG/pull/1807)
- chore(deps-dev): bump @types/node from   14.14.43 to 14.14.44 [`#1805`](https://github.com/opengovsg/FormSG/pull/1805)
- chore(deps-dev): bump   @typescript-eslint/eslint-plugin   [`#1790`](https://github.com/opengovsg/FormSG/pull/1790)
- chore(deps-dev): bump   @typescript-eslint/parser from 4.22.0 to 4.22.1   [`#1794`](https://github.com/opengovsg/FormSG/pull/1794)
- chore(deps-dev): bump   @typescript-eslint/parser from 4.22.1 to 4.23.0   [`#1852`](https://github.com/opengovsg/FormSG/pull/1852)
- chore(deps-dev): bump concurrently from   6.0.2 to 6.1.0 [`#1832`](https://github.com/opengovsg/FormSG/pull/1832)
- chore(deps-dev): bump core-js from   3.11.2 to 3.11.3 [`#1808`](https://github.com/opengovsg/FormSG/pull/1808)
- chore(deps-dev): bump core-js from   3.11.3 to 3.12.0 [`#1817`](https://github.com/opengovsg/FormSG/pull/1817)
- chore(deps-dev): bump core-js from   3.12.0 to 3.12.1 [`#1829`](https://github.com/opengovsg/FormSG/pull/1829)
- chore(deps-dev): bump date-fns from   2.21.1 to 2.21.2 [`#1806`](https://github.com/opengovsg/FormSG/pull/1806)
- chore(deps-dev): bump date-fns from   2.21.2 to 2.21.3 [`#1824`](https://github.com/opengovsg/FormSG/pull/1824)
- chore(deps-dev): bump eslint from   7.25.0 to 7.26.0 [`#1828`](https://github.com/opengovsg/FormSG/pull/1828)
- chore(deps-dev): bump lint-staged from   10.5.4 to 11.0.0 [`#1827`](https://github.com/opengovsg/FormSG/pull/1827)
- chore(deps-dev): bump ts-jest from   26.5.5 to 26.5.6 [`#1804`](https://github.com/opengovsg/FormSG/pull/1804)

### CODE REVIEW

**Comment by karrui** [comment]
## Tests
### add <sg-govt-banner-component> to top of public forms
- [ ] Go to public forms, the SG Govt masthead should appear above the banner message
- [ ] Scrolling should work as per normal, with only the banner message remaining sticky

**Comment by karrui** [comment]
## Tests
### Update end page API
- [ ] Create a new form. Go into the admin panel and click the start page. Add a random button link without `http://` prefix. Save end page and reopen end page. The URL should have been prefixed with `http://`.
- [ ] Edit the end page button link to a URL with `https://`. Also edit the button text. Should save successfully. 
- [ ] Go to the form and submit the form. The button text should be the custom button text, and clicking the button should redirect you to the button link you used when editing end page.

**Comment by karrui** [comment]
## Tests
### Update logic specific endpoint
- [ ] Create field with one logic field. Edit logic - both from show field to prevent submit and vice versa. Check that logic is successfully edited.
- [ ] Check that build tab is updated correctly (hidden fields should be greyed out based on logic)
- [ ] Repeat the above with more than one logic field.

**Test using manual API calls**
- [ ] Check that endpoint returns 404 when formId or logicId are incorrect

**Comment by karrui** [comment]
## Tests
### Edit form collaborators specific API
- [ ] Add a collaborator with a valid `.gov.sg` email as `editor` to the form. After doing so, attempt to change their role to `read-only`. Thereafter, delete the collaborator. This should all succeed. 
- [ ] Add a collaborator with a valid `.gov.sg` email as `read-only` to the form. After doing so, attempt to change their role to `editor`. Thereafter, delete the collaborator. This should all succeed. 
- [ ] Attempt to add a collaborator with an invalid email to the form. This should fail with an error message.
    - [ ] try using `.gov.sga` 
    - [ ] try using invalid email domains `@imamonster.com` 
    - [ ] try using personal emails 
    - [ ] please feel free to add more

**Comment by karrui** [comment]
@mantariksh 
## Tests
### GSIB IE11 Tests

**Intranet IE11 runthrough**
- [ ] Create email mode form with all fields and custom start/end page. Activate and submit form. Check that you can receive responses in your intranet inbox.
- [ ] Collaborators can be added in email mode.
- [x] Create storage mode form with all fields and custom start/end page. Activate and submit form.
- [x] Response CSV can be downloaded for storage mode.
- [x] Responses can be viewed in Data tab in storage mode.
- [x] Attachments for individual fields can be downloaded from Data tab in storage mode.
- [x] Attachment ZIP for submission can be downloaded from Data tab in storage mode.
- [x] Submission IDs can be filtered in storage mode.
- [x] Collaborators can be added and their collaborating rights edited in storage mode. 


**New features/fixes**
- [ ] Editing form collaborators should work properly
- [ ] Updating logic should work properly
- [ ] Updating form's end page should work properly
- [ ] SG Govt masthead should show up properly

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
