### PR TITLE
build: release 5.16.0

### PR DESCRIPTION
**Pull request by tshuli**
**NEW**
- feat: add and call v3 API   for retrieving individual admin form (#2113)   [`#2201`](https://github.com/opengovsg/FormSG/pull/2201)
- feat: restore UEN field   [`#2199`](https://github.com/opengovsg/FormSG/pull/2199)
- chore: improve logging for   webhook retries [`#2186`](https://github.com/opengovsg/FormSG/pull/2186)

**IMPROVED** 
- chore: remove redundant   ValidationOption object properties for short text, long text and number   fields (#2040) [`#2200`](https://github.com/opengovsg/FormSG/pull/2200)
- docs(script): add script   to remove permissionList.read key from the db   [`#2190`](https://github.com/opengovsg/FormSG/pull/2190)
- fix: Clean-up and   right-align home page statistics   [`#2219`](https://github.com/opengovsg/FormSG/pull/2219)
- feat: update landing spcp   image, minify app images   [`#2173`](https://github.com/opengovsg/FormSG/pull/2173)
- feat(AdminFormCtl): remove   read permissionList.read key from Joi   [`#2197`](https://github.com/opengovsg/FormSG/pull/2197)
- feat(feature-manager):   remove Captcha from feature manager   [`#2157`](https://github.com/opengovsg/FormSG/pull/2157)
- feat(feature-manager):   remove verified fields from feature manager   [`#2158`](https://github.com/opengovsg/FormSG/pull/2158)
- feat(feature-manager):   remove webhooks, verified content   [`#2159`](https://github.com/opengovsg/FormSG/pull/2159)
-   feat(incoming-encrypt-submission): add more tests   [`#2211`](https://github.com/opengovsg/FormSG/pull/2211)

**FIXES**
- test: fix flaky form   feedback test [`#2217`](https://github.com/opengovsg/FormSG/pull/2217)

**DEPENDENCY   UPDATES**
- chore(deps-dev): bump   @babel/core from 7.14.5 to 7.14.6   [`#2185`](https://github.com/opengovsg/FormSG/pull/2185)
- chore(deps-dev): bump   @opengovsg/mockpass from 2.7.3 to 2.7.4   [`#2192`](https://github.com/opengovsg/FormSG/pull/2192)
- chore(deps-dev): bump   eslint from 7.28.0 to 7.29.0   [`#2216`](https://github.com/opengovsg/FormSG/pull/2216)
- chore(deps-dev): bump   type-fest from 1.2.0 to 1.2.1   [`#2202`](https://github.com/opengovsg/FormSG/pull/2202)
- fix(deps): bump   @babel/runtime from 7.14.5 to 7.14.6   [`#2183`](https://github.com/opengovsg/FormSG/pull/2183)
- fix(deps): bump   @opengovsg/formsg-sdk from 0.8.4-beta.0 to 0.9.0   [`#2204`](https://github.com/opengovsg/FormSG/pull/2204)
- fix(deps): bump   @sentry/browser from 6.7.0 to 6.7.1   [`#2184`](https://github.com/opengovsg/FormSG/pull/2184)
- fix(deps): bump   @sentry/browser from 6.7.1 to 6.7.2   [`#2228`](https://github.com/opengovsg/FormSG/pull/2228)
- fix(deps): bump   @sentry/integrations from 6.7.0 to 6.7.1   [`#2181`](https://github.com/opengovsg/FormSG/pull/2181)
- fix(deps): bump   @sentry/integrations from 6.7.1 to 6.7.2   [`#2227`](https://github.com/opengovsg/FormSG/pull/2227)
- fix(deps): bump aws-sdk   from 2.927.0 to 2.928.0   [`#2182`](https://github.com/opengovsg/FormSG/pull/2182)
- fix(deps): bump aws-sdk   from 2.928.0 to 2.929.0   [`#2191`](https://github.com/opengovsg/FormSG/pull/2191)
- fix(deps): bump aws-sdk   from 2.929.0 to 2.930.0   [`#2203`](https://github.com/opengovsg/FormSG/pull/2203)
- fix(deps): bump aws-sdk   from 2.930.0 to 2.931.0   [`#2214`](https://github.com/opengovsg/FormSG/pull/2214)
- fix(deps): bump   libphonenumber-js from 1.9.19 to 1.9.20   [`#2224`](https://github.com/opengovsg/FormSG/pull/2224)
- fix(deps): bump nodemailer   from 6.6.1 to 6.6.2 [`#2215`](https://github.com/opengovsg/FormSG/pull/2215)
- fix(deps): bump twilio   from 3.63.1 to 3.64.0   [`#2205`](https://github.com/opengovsg/FormSG/pull/2205)

### CODE REVIEW

**Comment by tshuli** [comment]
## Tests

**feat: add and call v3 API for retrieving individual admin form**
- [ ] Access admin form. In chrome network tab, should call new /api/v3 endpoint.

**feat: add UEN field**
Create a UEN field and check that the following UENs are **valid**:
- [ ] 01234567A
- [ ] 012345678A
- [ ] T01LP1234Z
- [ ] S01LP1234Z
- [ ] R01LP1234Z

Check that the following UENs are **invalid**:
- [ ] B1234567A
- [ ] 012345678
- [ ] 0123456789
- [ ] A01LP1234Z
- [ ] S01AA1234Z
- [ ] RS1LP1234Z
- [ ] R010P1234Z
- [ ] R01LPL234Z
- [ ] R01LP12345

Submit the following UEN **by API** and check that the backend invalidates it:
- [ ] R01LP12345

**Comment by tshuli** [comment]
## Tests

**chore: remove redundant ValidationOption object properties for short text, long text and number fields**

- [ ] Create a form with the following fields
  - Short text, with minimum 3 chars
  - Short text, with exactly 3 chars
  - Long text, with minimum 3 chars
  - Long text, with exactly 3 chars
  - Number, with minimum 3 chars
  - Number, with exactly 3 chars
- [ ] Test that the validation works correctly and the form can be submitted
- [ ] Edit the validation by replacing minimum with maximum. Check that the validation works correctly and form can be submitted.

**Backward compatibility checks**
- [ ] Repeat the above tests but using an old client for the public form user. Check that the validation works correctly and form can be submitted.
- [ ] Repeat the above tests but using an old client for the admin. Check that the form can be modified correctly and that the modified changes persist.

**Comment by tshuli** [comment]
## Tests

**fix: Clean-up and right-align home page statistics**

- [ ] Verify that the home page loads and looks as expected as per #2219

**feat: update landing spcp image, minify app images**

- [ ] Verify that landing page has updated image as per #2173

**feat(feature-manager): remove Captcha from feature manager**

- [ ] Create form with captcha. Check that form can be submitted.

**feat(feature-manager): remove verified fields from feature manager**

- [ ] Submit an email mode form with verified email and mobile
- [ ] Submit a storage mode form with verified email and mobile

**Comment by tshuli** [comment]
## Tests

**feat(feature-manager): remove webhooks, verified content**

- [ ] Create a storage mode form with verified fields. Submit and check that decrypted responses works, with the "[verified]" prefix for verified fields.
- [ ] Create a SP-authenticated storage mode form. Submit and check that the NRIC can be decrypted.
- [ ] Create a webhook server. Set the server to return a non-200 status the first time, then subsequently return 200. Enable retries and check that the webhook is received and decrypted correctly for both the initial attempt (which returns non-200) and the retry (which returns 200).

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
