### PR TITLE
build: merge release-al2 branch back into develop

### PR DESCRIPTION
**Pull request by karrui**
This branch merges `release-al2` back into `develop`.

In the future, a PR will be opened so we release from the `release` branch instead. This is tracked by #3528

### CODE REVIEW

**Comment by karrui** [comment]
@mantariksh not sure if we want to keep the hotfix in

**Comment by mantariksh** [comment]
@karrui I think it might be better to revert the hotfix in `release-al2` then merge the whole thing back into `develop` so the logging doesn't get persisted but there's a record of it, wdyt?

**Comment by karrui** [comment]
Will do that now.

**Comment by karrui** [comment]
As discussed, will merge this into develop, then revert on develop for next release.

**Review by timotheeg — APPROVED** [review]

**Comment by karrui** [comment]
also discussed with @timotheeg, no need to revert ba; the check is cheap and this prevents us from having to do this same thing in the future

**Pull request merged**
