### PR TITLE
feat: change end page default button copy to 'Submit another response'

### LINKED ISSUE #5064: End page default button copy
Change from "Submit another form" to "Submit another response"

### PR DESCRIPTION
**Pull request by developerdenesh**
## Problem

End page default button copy
Closes #5064

## Solution
Change from "Submit another form" to "Submit another response" in 2 files

**Breaking Changes** 

- [x] No - this PR is backwards compatible

### CODE REVIEW

**Review by karrui — COMMENTED** [review]
thanks for your contribution! we should update the defaults on the database schema (and related tests) too.

**Review by timotheeg — APPROVED** [review]

**Comment by karrui** [comment]
Sorry, some merge conflicts. May I trouble you to merge/rebase?

**Comment by justynoh** [comment]
Due to some other changes, the first commit is not needed anymore! Mind just keeping the second commit modifying the form model and spec? thanks!

**Comment by developerdenesh** [comment]
Seems like the PR has been shifted to: https://github.com/opengovsg/FormSG/pull/5117

**Pull request closed without merging**
