### PR TITLE
build: Release 5.19.0

### PR DESCRIPTION
**Pull request by tshuli**
**New**
- feat(auth): support sgID for form submissions [`#1986`](https://github.com/opengovsg/FormSG/pull/1986)

**Improvements**
- feat: Set SP/CP JWT cookie to HttpOnly [`#2193`](https://github.com/opengovsg/FormSG/pull/2193)
- refactor: revert the revert of encapsulate parsedResponses [`#2278`](https://github.com/opengovsg/FormSG/pull/2278)

**Fixes**
- feat: Remove self from collaborator list [`#2212`](https://github.com/opengovsg/FormSG/pull/2212)
- fix: allow duplicating email field with PDF to storage mode [`#2303`](https://github.com/opengovsg/FormSG/pull/2303)

**Dependency Changes**
- fix(deps): bump aws-sdk from 2.936.0 to 2.937.0 [`#2287`](https://github.com/opengovsg/FormSG/pull/2287)
- fix(deps): bump aws-sdk from 2.937.0 to 2.939.0 [`#2293`](https://github.com/opengovsg/FormSG/pull/2293)
- fix(deps): bump express-rate-limit from 5.2.6 to 5.3.0 [`#2288`](https://github.com/opengovsg/FormSG/pull/2288)
- fix(deps): bump libphonenumber-js from 1.9.20 to 1.9.21 [`#2291`](https://github.com/opengovsg/FormSG/pull/2291)
- fix(deps): bump neverthrow from 4.2.1 to 4.2.2 [`#2297`](https://github.com/opengovsg/FormSG/pull/2297)
- fix(deps): bump twilio from 3.64.0 to 3.65.0 [`#2284`](https://github.com/opengovsg/FormSG/pull/2284)
- fix(deps): bump zod from 3.2.0 to 3.3.3 [`#2296`](https://github.com/opengovsg/FormSG/pull/2296)
- fix(deps): bump zod from 3.3.3 to 3.3.4 [`#2299`](https://github.com/opengovsg/FormSG/pull/2299)
- fix(deps): unpin typescript [`#2305`](https://github.com/opengovsg/FormSG/pull/2305)
- chore(deps-dev): bump @types/mongodb from 3.6.18 to 3.6.19 [`#2286`](https://github.com/opengovsg/FormSG/pull/2286)
- chore(deps-dev): bump @types/uuid from 8.3.0 to 8.3.1 [`#2294`](https://github.com/opengovsg/FormSG/pull/2294)
- chore(deps-dev): bump @types/validator from 13.1.4 to 13.6.2 [`#2298`](https://github.com/opengovsg/FormSG/pull/2298)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#2307`](https://github.com/opengovsg/FormSG/pull/2307)
- chore(deps-dev): bump @typescript-eslint/parser from 4.28.1 to 4.28.2 [`#2306`](https://github.com/opengovsg/FormSG/pull/2306)
- chore(deps-dev): bump eslint from 7.29.0 to 7.30.0 [`#2295`](https://github.com/opengovsg/FormSG/pull/2295)
- chore(deps-dev): bump ts-node-dev from 1.1.7 to 1.1.8 [`#2285`](https://github.com/opengovsg/FormSG/pull/2285)

### CODE REVIEW

**Comment by tshuli** [comment]
## Tests

**feat: Set SP/CP JWT cookie to HttpOnly**

- [ ] Create form with singpass. Log in without selecting 'remember me'. Check that form can be submitted and logout works, with jwtSp cookie deleted upon logout
  - [ ] Repeat the above with 'remember me' checked
- [ ] Create form with corppass. Log in. Check that form can be submitted and logout works, with jwtCp cookie deleted upon logout
- [ ] Create form with myinfo and check that myinfo form submission works normally

**Comment by tshuli** [comment]
**refactor(email-submission): encapsulate parsedResponses**

Copy this [email-mode form](https://staging.form.gov.sg/60d0086fcf8dc0001197b48d/use-template).

- [ ] Submit the form with valid inputs. Submission should go through.
- [ ] Copy the request as a CURL, and modify the responses to have invalid information (like invalid email, phone number). The error you get is `There is something wrong with your form submission. Please check your responses and try again.`
- [ ] Paste that same request you copied as CURL, this time deleting a compulsory field (like the decimal field). The error message is `The form has been updated. Please refresh and submit again.`

**Comment by tshuli** [comment]
**feat: Remove self from collaborator list**

- [ ] Create a new form with collaborators, then login as the collaborators and manually remove themselves. It should succeed.

**Comment by tshuli** [comment]
**fix: allow duplicating email field with PDF to storage mode**

- [ ] Create an email mode form, with email field that has the include PDF summary option toggled on. 
  - [ ] Duplicate that form to a storage mode form. Should duplicate successfully, but with the include PDF summary option in the email form toggled off.
  - [ ] Duplicate that form to another email mode form. Should duplicate successfully and the include PDF summary option should still be toggled on.

**Comment by tshuli** [comment]
**feat(auth): support sgID for form submissions**

- [ ] Find an sgID developer who has access to a special build of the Singpass App that talks to sgID staging
- [ ] Create a betaFlag - `sgid` - for a user
- [ ] With this user, create a form with auth type set to Singpass (Lite)
- [ ] Make the form public and attempt to log into the form

**Review by mantariksh — APPROVED** [review]

**Comment by tshuli** [comment]
Rolled back due to bug with cookie domain, hence preventing users from logging out from sp/cp on prod after #2193

**Pull request merged**
