### PR TITLE
feat: Filter Storage Mode Responses by Submission Id

### PR DESCRIPTION
**Pull request by frankchn**
## Problem

Users have trouble finding specific responses and trying to download attachments for these responses.

## Solution

This introduces a new textbox which filters submissions by reference ID so users can jump to a certain response immediately.

## Screenshots

image

image

image

## Notes

This is a resubmission of #71 as the earlier PR was reverted due to performance issues.

### CODE REVIEW

**Comment by liangyuanruo** [comment]
Note - do not merge until read from primary is verified, and internal processes are complete.

**Comment by liangyuanruo** [comment]
I think we have an issue - every time the search box is cleared, the database has to perform an expensive scan to paginate and serve the first page. This is probably the root cause of CPU saturation on secondaries.

image

**Comment by frankchn** [comment]
@liangyuanruo Ah OK I didn't know the scan and serve can be so expensive on Mongo. I thought it would be more like the equivalent of a `SELECT ORDER BY submission_time DESC LIMIT 10` kind of thing. Is there any way to add an index to the store to make it faster.

One thing we can do is to just add a button to trigger the filter instead of doing debouncing and triggering on keydowns.

**Comment by liangyuanruo** [comment]
> Is there any way to add an index to the store to make it faster.

We already have an index on the `created` column today.

> One thing we can do is to just add a button to trigger the filter instead of doing debouncing and triggering on keydowns.

Something like that could work, although we should probably introduce both a "search" and a "clear" button.

I'll create a new issue for awareness since the potential fixes would involve engineering as well as design.

**Review by liangyuanruo — CHANGES_REQUESTED** [review]
Blocked by #276.

**Comment by frankchn** [comment]
image

I have added a "Filter" button so the expensive pagination queries won't happen unless explicitly requested by the user.

**Review by liangyuanruo — CHANGES_REQUESTED** [review]
Can we put in a Reset button too? The current UI will confuse users because it doesn't quite make sense to filter when the search box is empty. Could we also disable the filter button if the input doesn't match the regex for a MongoDB ObjectID (`/^[0-9a-fA-F]{24}$/`)? This could save on network calls to the backend.

**Comment by frankchn** [comment]
image

I just decided to use the standard buttons instead. Probably OK for now?

**Comment by frankchn** [comment]
@liangyuanruo I suspect introducing a "Clear" button that sends a request to the backend to paginate will cause the # of requests to increase. 

Instead of clearing the textbox manually and pasting in the next ID, users may decide to just click the Clear button to clear the textbox. This brings us back to the same issue that we had with the original design.

**Comment by frankchn** [comment]
@liangyuanruo Updated per discussion.

**Comment by frankchn** [comment]
@liangyuanruo I updated this based on the design in #276 -- main change being that I let the text box appear on a second row instead as it is a bit of a squeeze in the zeplin mockup if the user's screen is too narrow.

image

image

Let me know what you think!

**Review by liangyuanruo — CHANGES_REQUESTED** [review]
thanks @frankchn . i tested the new behavior and it's great. can we do up the UI before merging:

1. Get the search icon to look as per the design, instead of being a blue button
2. Address layout issues for the tablet view
image

**Comment by syan-syan** [comment]
@frankchn adding on

1. replace 'Reset' with 'Refresh'
2. placeholder for search box 'Search by submission ID'

**Comment by frankchn** [comment]
Hi @syan-syan, made the second change, but the `Reset` link is actually for going back to the un-filtered view I think.

**Comment by frankchn** [comment]
@liangyuanruo PTAL again, thanks!

**Comment by syan-syan** [comment]
> Hi @syan-syan, made the second change, but the `Reset` link is actually for going back to the un-filtered view I think.

I know, I'm thinking it may be scary to users since 'Reset' is often associated with drastic changes (could be wiping out all the data?), while what people generally expect with 'Refresh' is what we have planned for showing the unfiltered results

**Comment by frankchn** [comment]
@syan-syan No problem, updated! cc @liangyuanruo

**Review by liangyuanruo — APPROVED** [review]
lgtm @frankchn , except for a last-bit layout issue for the iPad Pro. could i trouble you to fine-tune the CSS?

image

**Comment by frankchn** [comment]
image

Well, this is better but still not perfect, partly because the iPad Pro has enough horizontal resolution to be treated as a desktop browser for bootstrap purposes, so things spill out. At least all the fields are visible? :p

**Comment by frankchn** [comment]
I am thinking of merging this and getting some feedback, and also changed the text for going back to looking at all responses to "View All". I think users might just end up clicking "Refresh" if they want to reload the particular filtered item.

**Pull request merged**
