### PR TITLE
feat: improve to drag and drop experience

### PR DESCRIPTION
**Pull request by darrelhong**
## Problem
This PR should improve the drag and drop experience ever so slightly by fulfilling points 1 & 2 of #5533.

## Caveats
Drag and drop while form has unsaved changes is not allowed as implementation was not as straightforward as expected. The useForm hook seems to be called again with unsaved field data, thereby breaking `isDirty` behaviour. (likely cause by key change in [` <MemoFieldDrawerContent
        field={fieldToEdit}
        key={`${fieldIndex}-${numFields}`}
      />`](https://github.com/opengovsg/FormSG/blob/cd9087dfc893db5df61173457fcc65a576f12aaa/frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/EditFieldDrawer.tsx#L89)
 
Also, drag and drop is disabled on create as there currently isn't a google docs-like constant saving mechanism, so its probably not possible to reorder an unsaved form field.

As such a tooltip was added to hint to users if they hover over the drag handle when drag is not allowed.

https://user-images.githubusercontent.com/39296145/209441657-b32eb673-6354-4243-8894-0be8941385a4.mov

### CODE REVIEW

**Comment by timotheeg** [comment]
Thanks for the contribution @darrelhong !

@pearlyong could you check if the tooltip behaviour works for you? 
@amitogp fyi

**Comment by darrelhong** [comment]
removing the key prop in [`<MemoFieldDrawerContent />`](https://github.com/opengovsg/FormSG/blob/cd9087dfc893db5df61173457fcc65a576f12aaa/frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/EditFieldDrawer.tsx#L89) seems to allow re-ordering while current field has unsaved edits. Also does not seem to affect the updating of the EditFieldDrawer as commented, but not sure if every case is covered.


https://user-images.githubusercontent.com/39296145/210050443-f80c800b-67d1-472e-9c1d-2797f3735811.mov

**Comment by darrelhong** [comment]
@timotheeg @pearlyong @amitogp still looking into this? will close this PR if not

**Comment by pearlyong** [comment]
@darrelhong thank you for your contribution and improvements! ideally a user should be able to re-order a field even when it has not been created, for consistency with the flow where they can re-order when it's an existing field with unsaved edits. Would that be possible?

If not, could we change the tooltip copy to 'Create your field before reordering it' to make it slightly clearer?

**Comment by darrelhong** [comment]
@pearlyong option 1 is definitely possible but not straightforward to implement

**Comment by darrelhong** [comment]
https://user-images.githubusercontent.com/39296145/216378175-0d17600a-6642-4efd-aaba-299afae81e27.mov

https://user-images.githubusercontent.com/39296145/216378862-d78c9297-161f-4196-a70c-fe650ed699b2.mov

@pearlyong updated to allow drag and drop when creating new field and when field is being edited. 

@timotheeg @karrui would be good this can be deployed to staging for testing

**Comment by darrelhong** [comment]
this should also help with #5517

**Comment by darrelhong** [comment]
@pearlyong @amitogp @timotheeg any update on this? would like to merge this if possible

**Comment by foochifa** [comment]
Hi @darrelhong! Thanks for working on this, and so sorry we took so long to follow-up on this (wanted to kill angular first which is done now!)

Was wondering if you could rebase your branch to the latest version? If you are too busy to iterate on this, I could help take over it. Thank you!

**Comment by darrelhong** [comment]
feel free to take over, thanks!

**Comment by darrelhong** [comment]
any update on this? i could get back on it if it's still in the pipeline

**Comment by foochifa** [comment]
Hey @darrelhong! Yes, feel free to take it back, the change is still welcomed. If you have the time to rebase and verify the improvements again that will be great!

**Comment by darrelhong** [comment]
Hi Chi Fa, rebased and verified

**Pull request closed without merging**
