### PR TITLE
build: release 4.58.0

### PR DESCRIPTION
**Pull request by mantariksh**
## New
- feat: deprecate MyInfo fields for V3 (step 3 - drop support) [`#1073`](https://github.com/opengovsg/FormSG/pull/1073)
- feat: update SMS OTP message [`#1085`](https://github.com/opengovsg/FormSG/pull/1085)

## Improved
- refactor: remove SPCP_COOKIE_MAX_AGE [`#1134`](https://github.com/opengovsg/FormSG/pull/1134)
- build: docker-compose to use mongo:4.0 image [`#1114`](https://github.com/opengovsg/FormSG/pull/1114)
- ref: migrate encrypt SP/CP verified content flow into separate module [`#934`](https://github.com/opengovsg/FormSG/pull/934)

## Dependency upgrades
- chore(deps-dev): bump typescript from 4.1.4 to 4.1.5 [`#1137`](https://github.com/opengovsg/FormSG/pull/1137)
- chore(deps-dev): bump @babel/core from 7.12.13 to 7.12.16 [`#1136`](https://github.com/opengovsg/FormSG/pull/1136)
- fix(deps): bump moment-timezone from 0.5.32 to 0.5.33 [`#1130`](https://github.com/opengovsg/FormSG/pull/1130)
- fix(deps): bump jszip from 3.5.0 to 3.6.0 [`#1131`](https://github.com/opengovsg/FormSG/pull/1131)
- chore(deps-dev): bump lint-staged from 10.5.3 to 10.5.4 [`#1132`](https://github.com/opengovsg/FormSG/pull/1132)
- chore(deps-dev): bump stylelint from 13.8.0 to 13.10.0 [`#1135`](https://github.com/opengovsg/FormSG/pull/1135)
- chore(deps-dev): bump @typescript-eslint/parser from 4.12.0 to 4.15.0 [`#1106`](https://github.com/opengovsg/FormSG/pull/1106)
- chore(deps-dev): bump ts-mock-imports from 1.3.1 to 1.3.3 [`#1122`](https://github.com/opengovsg/FormSG/pull/1122)
- fix(deps): bump fp-ts from 2.9.4 to 2.9.5 [`#1124`](https://github.com/opengovsg/FormSG/pull/1124)
- chore(deps-dev): bump @types/express-rate-limit from 5.1.0 to 5.1.1 [`#1123`](https://github.com/opengovsg/FormSG/pull/1123)
- fix(deps): bump web-streams-polyfill from 3.0.1 to 3.0.2 [`#1121`](https://github.com/opengovsg/FormSG/pull/1121)
- chore(deps-dev): bump typescript from 4.1.3 to 4.1.4 [`#1120`](https://github.com/opengovsg/FormSG/pull/1120)
- chore(deps-dev): bump @typescript-eslint/eslint-plugin [`#1107`](https://github.com/opengovsg/FormSG/pull/1107)
- chore(deps-dev): bump eslint from 7.17.0 to 7.19.0 [`#1108`](https://github.com/opengovsg/FormSG/pull/1108)

### CODE REVIEW

**Comment by mantariksh** [comment]
## Tests
**IE11 intranet general run-through**

- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your intranet inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments for individual fields can be downloaded from Data tab in storage mode.
- [ ] Attachment ZIP for submission can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Comment by mantariksh** [comment]
## Tests
**MyInfo field deprecation**
- [ ] Run the following query in production and ensure that you get 0 results: `db.getCollection('forms').find({ 'form_fields.myInfo.attr': { $in: ['homeno', 'mailadd', 'billadd', 'gradyear', 'edulevel', 'schoolname']} })`
- [ ] Submit a form with all MyInfo fields

**Comment by mantariksh** [comment]
## Tests
**Verification OTP copy**
- [ ] Verification OTP copy has been changed as per #1068

**Comment by mantariksh** [comment]
## Tests
**Verified content**
- [ ] Submit a SingPass form in storage mode and check that the NRIC is properly decrypted in the data tab and CSV
- [ ] Submit a CorpPass form in storage mode and check that the UEN and UID are properly decrypted in the data tab and CSV

**Comment by tshuli** [comment]
**Mobile signature validation**
- [ ] Create verified mobile field. Check that submission of verified mobile number works normally
- [ ] Clone network request and modify the signature. Submit programatically. Check that submission fails

**Review by tshuli — APPROVED** [review]

**Pull request merged**
