### PR TITLE
build: Release 4.41.0

### PR DESCRIPTION
**Pull request by shuli-ogp**
**New**

- feat: add billing module to handle /billing endpoints [`#398`](https://github.com/opengovsg/FormSG/pull/398)
- feat: allow form transfer for email mode forms [`#488`](https://github.com/opengovsg/FormSG/pull/488)

**Improvements**

- chore: increase node memory limit to 2GB [`#482`](https://github.com/opengovsg/FormSG/pull/482)
- chore(examples-search): log failures from database [`#467`](https://github.com/opengovsg/FormSG/pull/467)
- refactor: convert remaining res.send to res.json [`#455`](https://github.com/opengovsg/FormSG/pull/455)
- refactor: use celebrate error handler [`#458`](https://github.com/opengovsg/FormSG/pull/458)
- feat: return HTTP 200 OK for Bounce collection VersionError [`#472`](https://github.com/opengovsg/FormSG/pull/472)
- feat: validate that webhook does not point back to app [`#475`](https://github.com/opengovsg/FormSG/pull/475)

**Bug Fixes**

- fix: add additional startsWith('@') check when validating domain [`#487`](https://github.com/opengovsg/FormSG/pull/487)
- fix: show decrypt progress modal after 3 seconds [`#476`](https://github.com/opengovsg/FormSG/pull/476)
- style: increase min-width of .response-stats [`#490`](https://github.com/opengovsg/FormSG/pull/490)

**Dependency Updates**

- chore(deps-dev): bump husky from 4.2.5 to 4.3.0 [`#480`](https://github.com/opengovsg/FormSG/pull/480)
- chore(deps-dev): bump jasmine-spec-reporter from 5.0.2 to 6.0.0 [`#469`](https://github.com/opengovsg/FormSG/pull/469)
- chore(deps-dev): bump jest from 26.4.2 to 26.5.3 [`#474`](https://github.com/opengovsg/FormSG/pull/474)
- chore(deps-dev): bump supertest from 3.4.2 to 5.0.0 [`#473`](https://github.com/opengovsg/FormSG/pull/473)
- fix: upgrade myinfo-gov-client to v2.0.0 [`#461`](https://github.com/opengovsg/FormSG/pull/461)
- fix(deps): bump angular-messages from 1.8.0 to 1.8.1 [`#468`](https://github.com/opengovsg/FormSG/pull/468)
- fix(deps): bump angular-resource from 1.8.0 to 1.8.1 [`#464`](https://github.com/opengovsg/FormSG/pull/464)
- fix(deps): bump bson-ext from 2.0.3 to 2.0.5 [`#478`](https://github.com/opengovsg/FormSG/pull/478)
- fix(deps): bump validator from 13.1.1 to 13.1.17 [`#463`](https://github.com/opengovsg/FormSG/pull/463)

### CODE REVIEW

**Comment by shuli-ogp** [comment]
**feat: allow form transfer for email mode forms**

- [ ]  Mobile view of collaborator modal works

_Encrypt Forms_
- [ ]  Able to transfer ownership to collaborator (existing owner should become collaborator and only have edit access)
- [ ]  Able to add a collaborator with read access
- [ ]  Able to add a collaborator with edit access

_Email Forms_
- [ ]  Able to transfer ownership to collaborator (existing owner should become collaborator and only have edit access)
- [ ]  Able to add a collaborator with read access
- [ ]  Able to add a collaborator with edit access

**Comment by shuli-ogp** [comment]
**feat: validate that webhook does not point back to app**

- [ ] Create form. Under settings tab in admin view, attempt to set form.gov.sg as webhook url. You should see an error message "you cannot send responses back to https://form.gov.sg"

**Comment by shuli-ogp** [comment]
**add additional startsWith('@') check when validating domain**

- [ ] Create form with email field. In domains allowed, type a full email address e.g. "jenny@tech.gov.sg". You should not be able to save and you should see an error message that the email domain is invalid.

**Comment by shuli-ogp** [comment]
**correctly show decrypt progress modal after 3 seconds when downloading storage mode responses**
@shuli-ogp 

- [ ] Decrypt modal should show up after 3 seconds if downloading storage mode responses has not completed in that timeframe.

**Comment by shuli-ogp** [comment]
**unclickable submissionId search button**

- [ ] Create storage mode form. Submit response. Go to admin view data tab. Check that submissionId search button in clickable in various screen sizes.

**Comment by mantariksh** [comment]
@mantariksh
**refactor: convert remaining res.send to res.json**
- [ ] Load the OTP login page on the old client. Deploy the new server. Request an OTP and check that the "OTP sent to (email)!" message shows up correctly, without any JSON formatting.
- [ ] Load an image field editing modal on the old client. Deploy the new server. Upload an image with an invalid extension and check that the "Your filetype is not supported" message shows up correctly, without JSON formatting.

**Comment by shuli-ogp** [comment]
**use celebrate error handler**

- [ ] Attempt to access /frontend/redirect endpoint. The error message shown on client should include details of the error (statuscode, error, message, etc)

**Comment by shuli-ogp** [comment]
**Run through on IE / Intranet**


_General run through_
- [ ] Create email mode form with all fields. Activate and submit form. Check that submission and responses work
- [ ] Create storage mode form with all fields. Activate and submit form. Check that submission and responses work
- [ ] Flag out any styling errors which you see

_decrypt progress modal_
- [ ] Decrypt modal should show up after 3 seconds if downloading storage mode responses has not completed in that timeframe.

_unclickable submissionId search button_
- [ ] Create storage mode form. Submit response. Go to admin view data tab. Check that submissionId search button in clickable in various screen sizes.

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
