### PR TITLE
build: release 5.7.0

### PR DESCRIPTION
**Pull request by tshuli**
**_Release cannot be rolled back due to API endpoint changes_**

**Improvements**

- refactor: duplicate   adminform submissions to /api/v3 endpoint   [`#1641`](https://github.com/opengovsg/FormSG/pull/1641)
- refactor: migrate GET   /submission to new endpt   [`#1645`](https://github.com/opengovsg/FormSG/pull/1645)
- refactor(admin-form-api):   duplicate adminform form endpoints for /api/v3i   [`#1635`](https://github.com/opengovsg/FormSG/pull/1635)
-   refactor(email-submission/controller): refactored email submission   [`#1594`](https://github.com/opengovsg/FormSG/pull/1594)
- refactor(feedback-api):   duplicate adminform feedback endpoints for /api/v3   [`#1589`](https://github.com/opengovsg/FormSG/pull/1589)
- refactor(frontend-api):   duplicate frontend client endpoints to new /api/v3 router   [`#1574`](https://github.com/opengovsg/FormSG/pull/1574)
-   refactor(PublicFormRoutes): duplicate /publicform to /api/v3 endpoints   [`#1588`](https://github.com/opengovsg/FormSG/pull/1588)
- test: fix possibly flaky   test by assigning constant to date   [`#1668`](https://github.com/opengovsg/FormSG/pull/1668)

**Fixes**

- fix: jest memory leak   [`#1659`](https://github.com/opengovsg/FormSG/pull/1659)
- fix: loosen validation for   sg home numbers [`#1663`](https://github.com/opengovsg/FormSG/pull/1663)
- fix: merge conflict from   merging with develop   [`9f0930e`](https://github.com/opengovsg/FormSG/commit/9f0930e6665a5e635fe6187e031c3c5ea50dfc41)

**Dependency Updates**

- fix(deps): bump aws-sdk   from 2.884.0 to 2.885.0   [`#1636`](https://github.com/opengovsg/FormSG/pull/1636)
- fix(deps): bump aws-sdk   from 2.885.0 to 2.886.0   [`#1648`](https://github.com/opengovsg/FormSG/pull/1648)
- fix(deps): bump aws-sdk   from 2.886.0 to 2.888.0   [`#1656`](https://github.com/opengovsg/FormSG/pull/1656)
- fix(deps): bump fp-ts from   2.10.0 to 2.10.2 [`#1653`](https://github.com/opengovsg/FormSG/pull/1653)
- fix(deps): bump fp-ts from   2.10.2 to 2.10.3 [`#1677`](https://github.com/opengovsg/FormSG/pull/1677)
- fix(deps): bump fp-ts from   2.9.5 to 2.10.0 [`#1646`](https://github.com/opengovsg/FormSG/pull/1646)
- fix(deps): bump helmet   from 4.4.1 to 4.5.0 [`#1665`](https://github.com/opengovsg/FormSG/pull/1665)
- fix(deps): bump opossum   from 6.0.0 to 6.0.1 [`#1658`](https://github.com/opengovsg/FormSG/pull/1658)
- chore(deps-dev): bump   @types/node from 14.14.37 to 14.14.41   [`#1657`](https://github.com/opengovsg/FormSG/pull/1657)
- chore(deps-dev): bump   concurrently from 6.0.1 to 6.0.2   [`#1638`](https://github.com/opengovsg/FormSG/pull/1638)
- chore(deps-dev): bump   core-js from 3.10.1 to 3.10.2   [`#1678`](https://github.com/opengovsg/FormSG/pull/1678)
- chore(deps-dev): bump   csv-parse from 4.15.3 to 4.15.4   [`#1660`](https://github.com/opengovsg/FormSG/pull/1660)
- chore(deps-dev): bump   date-fns from 2.20.2 to 2.20.3   [`#1637`](https://github.com/opengovsg/FormSG/pull/1637)
- chore(deps-dev): bump   date-fns from 2.20.3 to 2.21.0   [`#1649`](https://github.com/opengovsg/FormSG/pull/1649)
- chore(deps-dev): bump   date-fns from 2.21.0 to 2.21.1   [`#1662`](https://github.com/opengovsg/FormSG/pull/1662)
- chore(deps-dev): bump   eslint-config-prettier from 8.1.0 to 8.2.0   [`#1639`](https://github.com/opengovsg/FormSG/pull/1639)
- chore(deps-dev): bump   eslint-plugin-prettier from 3.3.1 to 3.4.0   [`#1661`](https://github.com/opengovsg/FormSG/pull/1661)
- chore(deps-dev): bump   jest-mock-axios from 4.3.0 to 4.4.0   [`#1667`](https://github.com/opengovsg/FormSG/pull/1667)
- chore(deps-dev): bump   ts-jest from 26.5.4 to 26.5.5   [`#1654`](https://github.com/opengovsg/FormSG/pull/1654)

### CODE REVIEW

**Comment by tshuli** [comment]
## Tests

### Intranet IE11 runthrough
- [ ] Create email mode form with all fields and custom start/end page. Activate and submit form. Check that you can receive responses in your intranet inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields and custom start/end page. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments for individual fields can be downloaded from Data tab in storage mode.
- [ ] Attachment ZIP for submission can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Comment by tshuli** [comment]
**duplicate adminform submissions to /api/v3 endpoint**

- Create a storage mode form with attachment fields. Publish the form, go to it and submit a few times with attachments.
    - [ ] Go to the admin panel and click on data. There should be `x responses to date`. Click on export and perform both actions. The files should be downloaded successfully. 
    - [ ] Change the date range to a date in the past without submissions. Verify that you are unable to export csv (both with/without attachments) 
    - [ ] Change the date change to a valid date range and try to export csv again (with and without). The files should be downloaded successfully

**Comment by tshuli** [comment]
**migrate GET /submission to new endpt**

- [ ] Create a new storage mode form and make it public. Go to the form and submit a few responses. Go to the admin panel and click on data and click on any response. The panel should be populated with the information of the responses

**duplicate adminform form endpoints for /api/v3i**

- [ ] Check that the current logged in user can see the list of their forms in their dashboard (GET /api/v3/admin/forms/)
- [ ] Check that you can create a new form (POST /api/v3/admin/forms)
- [ ] Check that you can duplicate a form (POST /api/v3/admin/forms/:formId/duplicate)
- [ ] Check that you can delete a form (DELETE /api/v3/admin/forms/:formId)
- [ ] Check that you can transfer ownership of a form (POST /api/v3/admin/forms/:formId/collaborators/transfer-owner)

**Comment by tshuli** [comment]
**refactored email submission**

- [ ] 1. Create a single field form without authentication and set its mode to email. Submitting the form should have the field data
- [ ]  2. Create a single field SP form and set its mode to email. Submitting the form should have the field data
- [ ]  3. Create a single field CP form and set its mode to email. Submitting the form should have the field data
- [ ]  4. Create a single field MyInfo form and set its mode to email. Submitting the form should have the field data
- [ ]  5. Submit storage mode form to email mode endpoint
- [ ]  6. Submit form which has been made private
- [ ]  7. Submit form which has been archived
- [ ]  8. Submit captcha-enabled form without captcha
- [ ]  9. Submit captcha-disabled form
- [ ]  10. Submit form which has exceeded submission limit
- [ ]  11. Submit form with invalid responses
- [ ]  12. Create multiple email fields with email confirmation, check that the correct confirmation email is sent for each one
- [ ]  13. Submit form with invalid attachments

**Comment by tshuli** [comment]
**duplicate adminform feedback endpoints for /api/v3**

- [ ] Create a new form, submit a new response, then submit feedback for the form
 Return to the form admin feedback section
- [ ]  Check that the feedback can be successfully retrieved (GET /api/v3/admin/forms/:formId/feedback returns 200)
- [ ]  Check that the form feedback count is correct (GET /api/v3/admin/forms/:formId/feedback/count returns 200)
- [ ]  Check that the feedback export function works (GET /api/v3/admin/forms/:formId/feedback/download returns 200)
- [ ]  Check that calling GET /api/v3/admin/forms/:formId/feedback without logging in results in a 401 Unauthorized error
- [ ]  Check that calling PATCH /api/v3/admin/forms/:formId/settings without logging in results in a 401 Unauthorized error

**Comment by tshuli** [comment]
**duplicate frontend client endpoints to new /api/v3 router**

- [ ] Check that feature requests return 200 on the /api/v3/client/features on landing page
- [ ] Check that form redirects work by accessing a form from a form share link (/api/v3/client/redirect)
- [ ] Test /api/v3/client/analytics/google
- [ ] Test /api/v3/client/environment

**Comment by tshuli** [comment]
**duplicate /publicform to /api/v3 endpoints**

NOTE: Attempt the below tests in all auth types

- [ ] Create a normal (NIL Auth) email mode form with a few fields and publish it. Open the form and fill in the form together with feedback. The responses should show up in email while the feedback should show up in the admin panel
- [ ] Create a SP email mode form with a few fields and publish it. Open the form and fill in the form together with feedback. The responses should show up in email while the feedback should show up in the admin panel
- [ ] Create a CP email mode form with a few fields and publish it. Open the form and fill in the form together with feedback. The responses should show up in email while the feedback should show up in the admin panel
- [ ] Create a MyInfo email mode form with a few fields and publish it. Open the form and fill in the form together with feedback. The responses should show up in email while the feedback should show up in the admin panel
- [ ] Create a normal (NIL Auth) storage mode form with a few fields and publish it. Open the form and fill in the form together with feedback. The responses should show up in email while the feedback should show up in the admin panel
- [ ] Create a SP storage mode form with a few fields and publish it. Open the form and fill in the form together with feedback. The responses should show up in email while the feedback should show up in the admin panel
- [ ] Create a CP storage mode form with a few fields and publish it. Open the form and fill in the form together with feedback. The responses should show up in email while the feedback should show up in the admin panel
- [ ] Create a MyInfo storage mode form with a few fields and publish it. Open the form and fill in the form together with feedback. The responses should show up in email while the feedback should show up in the admin panel
MyInfo-specific

- [ ] Create an email mode form and publish it. When signing in using MockPass, deny authentication. The form should not have been signed in and there should be an error message with MyInfo error displayed

**Comment by tshuli** [comment]
**loosen validation for sg home numbers**

- [ ] Create form with home number field. Check that the number 66665555 can be successfully submitted.

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
