### PR TITLE
feat: Backend implementation for bulk attachment downloading

### PR DESCRIPTION
**Pull request by frankchn**
Backend implementation for bulk attachment downloading using existing CSV decryption workers.

### CODE REVIEW

**Review by liangyuanruo — COMMENTED** [review]
I suspect the `Transform` will cause issues because of a lack of [backpressure](https://nodejs.org/en/docs/guides/backpressuring-in-streams/) management. 

We might be able to resolve this by using [pipeline](https://nodejs.org/api/stream.html#stream_stream_pipeline_source_transforms_destination_callback), but let me test the implementation with a form with sizeable submission.

**Comment by frankchn** [comment]
I am not sure if it will create significant backpressure because signing URLs doesn't require additional network calls when you have a valid IAM key. We can test this out in staging though.

**Review by liangyuanruo — COMMENTED** [review]
As discussed, the implementation looks good. Immediate follow-up is to memory profile the implementation using the node inspector so that we know it's safe, then put in the frontend.

**Comment by frankchn** [comment]
@liangyuanruo, just tested. For signing and downloading 10,000 submissions, the heap usage went from 96 MB up to ~115 MB according to the profiler. The entire download took 15 seconds. I think this means that there are no significant memory pressure issues.

**Review by liangyuanruo — APPROVED** [review]

**Pull request merged**
