### PR TITLE
build: Release 4.52.0

### PR DESCRIPTION
**Pull request by tshuli**
**New**

- Bulk Attachment Download   Frontend [`#640`](https://github.com/opengovsg/FormSG/pull/640)
- feat: send SMS   notification when submissions bounce   [`#961`](https://github.com/opengovsg/FormSG/pull/961)
- feat/type-safe: Encourage   type-safe coding practices with eslint-plugin-typesafe   [`#943`](https://github.com/opengovsg/FormSG/pull/943)
- Show OTP delay   notification [`#748`](https://github.com/opengovsg/FormSG/pull/748)

**Improvements**

- refactor: migrate   submissions controller to TypeScript   [`#881`](https://github.com/opengovsg/FormSG/pull/881)
- test: add Joi validation   integration tests [`#933`](https://github.com/opengovsg/FormSG/pull/933)
- test: add SPCP   authentication integration tests   [`#921`](https://github.com/opengovsg/FormSG/pull/921)

**Fixes**

- fix(AuthClientCtl): cancel   timeout promise on page change   [`#971`](https://github.com/opengovsg/FormSG/pull/971)

**Dependency Updates**

- fix: upgrade neverthrow   from 3.0.0 to 3.1.2 [`#968`](https://github.com/opengovsg/FormSG/pull/968)
- fix(deps): bump   @opengovsg/myinfo-gov-client from 2.1.2 to 2.1.3   [`#924`](https://github.com/opengovsg/FormSG/pull/924)
- fix(deps): bump   @opengovsg/ng-file-upload from 12.2.14 to 12.2.15   [`#965`](https://github.com/opengovsg/FormSG/pull/965)
- fix(deps): bump   @sentry/browser from 5.29.1 to 5.29.2   [`#951`](https://github.com/opengovsg/FormSG/pull/951)
- fix(deps): bump   @sentry/integrations from 5.29.0 to 5.29.2   [`#946`](https://github.com/opengovsg/FormSG/pull/946)
- fix(deps): bump   angular-ui-router from 1.0.28 to 1.0.29   [`#936`](https://github.com/opengovsg/FormSG/pull/936)
- fix(deps): bump aws-sdk   from 2.805.0 to 2.817.0   [`#953`](https://github.com/opengovsg/FormSG/pull/953)
- fix(deps): bump aws-sdk   from 2.817.0 to 2.818.0   [`#956`](https://github.com/opengovsg/FormSG/pull/956)
- fix(deps): bump axios from   0.21.0 to 0.21.1 [`#947`](https://github.com/opengovsg/FormSG/pull/947)
- fix(deps): bump boxicons   from 1.8.0 to 1.8.1 [`#926`](https://github.com/opengovsg/FormSG/pull/926)
- fix(deps): bump mongoose   from 5.11.8 to 5.11.9 [`#958`](https://github.com/opengovsg/FormSG/pull/958)
- fix(deps): bump nodemailer   from 6.4.16 to 6.4.17 [`#954`](https://github.com/opengovsg/FormSG/pull/954)
- fix(deps): bump   winston-cloudwatch from 2.4.0 to 2.5.0   [`#945`](https://github.com/opengovsg/FormSG/pull/945)
- chore(deps-dev): bump   @babel/plugin-transform-runtime   [`#952`](https://github.com/opengovsg/FormSG/pull/952)
- chore(deps-dev): bump   @babel/preset-env from 7.12.7 to 7.12.11   [`#925`](https://github.com/opengovsg/FormSG/pull/925)
- chore(deps-dev): bump   @opengovsg/mockpass from 2.6.0 to 2.6.1   [`#960`](https://github.com/opengovsg/FormSG/pull/960)
- chore(deps-dev): bump   @typescript-eslint/eslint-plugin from 4.0.1 to 4.11.0   [`#927`](https://github.com/opengovsg/FormSG/pull/927)
- chore(deps-dev): bump   @typescript-eslint/parser from 4.10.0 to 4.11.0   [`#944`](https://github.com/opengovsg/FormSG/pull/944)
- chore(deps-dev): bump   eslint from 7.14.0 to 7.16.0   [`#955`](https://github.com/opengovsg/FormSG/pull/955)
- chore(deps-dev): bump   eslint-plugin-prettier from 3.1.4 to 3.3.0   [`#923`](https://github.com/opengovsg/FormSG/pull/923)
- chore(deps-dev): bump   eslint-plugin-simple-import-sort   [`#966`](https://github.com/opengovsg/FormSG/pull/966)
- chore(deps-dev): bump   ngrok from 3.3.0 to 3.4.0   [`#939`](https://github.com/opengovsg/FormSG/pull/939)
- chore(deps-dev): bump   sinon from 9.2.1 to 9.2.2   [`#959`](https://github.com/opengovsg/FormSG/pull/959)
- chore(deps-dev): bump   testcafe from 1.9.4 to 1.10.1   [`#942`](https://github.com/opengovsg/FormSG/pull/942)
- chore(deps-dev): bump   ts-node from 9.0.0 to 9.1.1   [`#937`](https://github.com/opengovsg/FormSG/pull/937)
- chore(deps-dev): bump   ts-node-dev from 1.0.0 to 1.1.1   [`#957`](https://github.com/opengovsg/FormSG/pull/957)

### CODE REVIEW

**Comment by tshuli** [comment]
**Bulk attachment download**

- [ ] Create storage mode form with attachment field. Submit many responses (e.g. 100 responses). Test that bulk attachment download works.

**Comment by tshuli** [comment]
**send SMS notification when submissions bounce**

- [ ] Create an email mode form and add one valid and one invalid (e.g. non-existent email address) email recipient. Add an editor as well as a read-only collaborator.
- [ ] Submit the form and ensure that you do NOT receive any texts.
- [ ] Replace the valid recipient with another invalid one. Submit the form and check that you AND the collaborator with write permissions receive two texts: one saying that a response has bounced, and another saying that your form was deactivated. ALL collaborators (including the read-only collaborator) should also receive an automated email. Check that each text has a corresponding document in the `smscounts` collection, with smsType as either `BOUNCED_SUBMISSION` or `FORM_DEACTIVATED`.
- [ ] Reactivate the form and submit again. You and the collaborator with write permissions should receive only one text saying that the form was deactivated, and no emails.

**Comment by tshuli** [comment]
**Show OTP delay notification**

- [ ] Send login OTP multiple times. After 45 seconds you should see "OTP might be delayed due to government email traffic. If you are unable to sign in, please try again later, or contact us"

**Comment by tshuli** [comment]
**IE11 intranet general run-through**

- [ ] Create email mode form with all fields. Activate and submit form. Check that you can receive responses in your GSIB inbox.
- [ ] Collaborators can be added in email mode.
- [ ] Create storage mode form with all fields. Activate and submit form.
- [ ] Response CSV can be downloaded for storage mode.
- [ ] Responses can be viewed in Data tab in storage mode.
- [ ] Attachments can be downloaded from Data tab in storage mode.
- [ ] Submission IDs can be filtered in storage mode.
- [ ] Collaborators can be added and their collaborating rights edited in storage mode.

**Comment by tshuli** [comment]
**Migrate submissions controller to typescript**


- [ ] Create an email mode form with 3 email fields: one with email confirmation but no PDF, one with email confirmation and PDF, one without email confirmation. Also add an attachment. Check that the correct email confirmation is sent to each email address, with the attachments.
- [ ] Create a storage mode form with 2 email fields: one with email confirmation, one without. Check that the email confirmation is sent to the correct email.

**Review by mantariksh — APPROVED** [review]

**Pull request merged**
